// packages/angular/src/app/pages/analytics-dashboard/analytics-dashboard.component.ts
import {
  Component, OnInit, NgModule, OnDestroy,
} from '@angular/core';

import { DxPieChartModule } from 'devextreme-angular/ui/pie-chart';
import { DxChartModule } from 'devextreme-angular/ui/chart';
import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';
import { DxFunnelModule } from 'devextreme-angular/ui/funnel';
import { DxBulletModule } from 'devextreme-angular/ui/bullet';

import { CommonModule } from '@angular/common';
import { RwaService } from 'src/app/shared/services';
import { forkJoin, map, Subscription } from 'rxjs';

import { CardAnalyticsModule } from 'src/app/shared/components/card-analytics/card-analytics.component';
import { ToolbarAnalyticsModule } from 'src/app/shared/components/toolbar-analytics/toolbar-analytics.component';

import { analyticsPanelItems, Dates } from 'src/app/shared/types/resource';
import {
  Sales, SalesByState, SalesOrOpportunitiesByCategory,
} from 'src/app/shared/types/analytics';

@Component({
  templateUrl: './analytics-dashboard.component.html',
  styleUrls: ['./analytics-dashboard.component.scss'],
  providers: [RwaService],
})
export class AnalyticsDashboardComponent implements OnInit, OnDestroy {
  analyticsPanelItems = analyticsPanelItems;

  opportunities: SalesOrOpportunitiesByCategory;

  sales: Sales;

  salesByState: SalesByState;

  salesByCategory: SalesOrOpportunitiesByCategory;

  subscriptions: Subscription[] = [];

  constructor(private service: RwaService) {
  }

  selectionChange(dates: Dates) {
    this.loadData(dates.startDate, dates.endDate);
  }

  customizeOppText(arg: { valueText: string }) {
    return `$${arg.valueText}`;
  }

  customizeSaleText(arg: { percentText: string }) {
    return arg.percentText;
  }

  getTotal(data: Array<any>) {
    if (!data) return;
    return data.reduce((total, item) => total + (item.value || item.total), 0);
  }

  loadData = (startDate: string, endDate: string) => {
    const observable$ = forkJoin([
      this.service.getOpportunitiesByCategory(startDate, endDate),
      this.service.getSalesByCategory(startDate, endDate),
      this.service.getSales(startDate, endDate),
    ]).pipe(
      map(([opportunities, salesByCategory, sales]) => ({ opportunities, salesByCategory, sales }))
    );

    this.subscriptions.push(this.service.getSalesByStateAndCity(startDate, endDate).subscribe((data) => {
      this.salesByState = this.service.getSalesByState(data);
    }));

    this.subscriptions.push(observable$.subscribe((data) => {
      Object.keys(data).forEach((key) => this[key] = data[key]);
    }));
  };

  ngOnInit(): void {
    const dates = analyticsPanelItems[4].value.split('/');

    this.loadData(dates[0], dates[1]);
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach((sub) => sub.unsubscribe());
  }
}

@NgModule({
  imports: [
    DxDataGridModule,
    DxBulletModule,
    DxFunnelModule,
    DxPieChartModule,
    DxChartModule,
    CardAnalyticsModule,
    ToolbarAnalyticsModule,

    CommonModule,
  ],
  providers: [],
  exports: [],
  declarations: [AnalyticsDashboardComponent],
})
export class AnalyticsDashboardModule { }

<div class="view-wrapper">
  <dx-toolbar>
    <dxi-item location="before">
      <span class="toolbar-header">Dashboard</span>
    </dxi-item>

    <dxi-item 
      location="before"
      locateInMenu="auto">
      <dx-tabs
        [selectedItemKeys]="[5]"
        keyExpr="key"
        [items]="analyticsPanelItems"
        (onItemClick)="selectionChange($event)"
      ></dx-tabs>
    </dxi-item>

    <dxi-item 
      location="after" 
      locateInMenu="auto"
      cssclass="add-card"
      >
      <dx-button
        icon="plus"
        text="Add Card"
        type="default"
        stylingMode="contained"
      ></dx-button>
    </dxi-item>

    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxButton"
      showText="inMenu"
      [options]="{
        text: 'Refresh',
        icon: 'refresh'
      }"
    ></dxi-item>

    <dxi-item location="after" locateInMenu="auto">
      <div class="separator"></div>
    </dxi-item>

    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxButton"
      showText="inMenu"
      [options]="{
        icon: 'export'
      }"
    ></dxi-item>
  </dx-toolbar>

  <div class="cards grey">
    <card-analytics
      class="grey"
      titleText="Opportunities"
      [showData]="getTotal(opportunities)"
      contentClass="opportunities-total"
    >
      <div *ngIf="getTotal(opportunities)">
        <div class="total">
          {{ getTotal(opportunities) | currency: "USD":"$":"1.0-0" }}
        </div>
        <div class="percentage">
          <i class="dx-icon-spinup"></i>
          <span>20.3%</span>
        </div>
      </div>
    </card-analytics>
    <card-analytics
      class="grey"
      titleText="Revenue Total"
      [showData]="getTotal(sales)"
      contentClass="revenue-total" 
    >
    <div *ngIf="getTotal(sales)">
      <div class="total">
        {{ getTotal(sales) | currency: "USD":"$":"1.0-0" }}
      </div>
      <div class="percentage">
        <i class="dx-icon-spinup"></i>
        <span>14.7%</span>
      </div>
    </div>
    </card-analytics>
    <card-analytics
      class="grey"
      titleText="Conversion"
      [showData]="true"
      contentClass="revenue-total"
    >
      <div class="total">16%</div>
      <div class="percentage">
        <i class="dx-icon-spindown"></i>
        <span>2.3%</span>
      </div>
    </card-analytics>
    <card-analytics
      class="grey"
      titleText="Leads"
      [showData]="true"
      contentClass="revenue-total"
    >
      <div class="total">51</div>
      <div class="percentage">
        <i class="dx-icon-spinup"></i>
        <span>8.5%</span>
      </div>
    </card-analytics>
  </div>

  <div class="cards">
    <card-analytics titleText="Revenue" contentClass="sales" [showData]="!!sales" [component]="chart">
      <dx-chart #chart [dataSource]="sales">
        <dxi-series valueField="total"></dxi-series>
        <dxo-common-series-settings argumentField="date" type="splinearea">
          <dxo-border [visible]="true"></dxo-border>
        </dxo-common-series-settings>
        <dxo-argument-axis argumentType="datetime"></dxo-argument-axis>
        <dxi-value-axis>
            <dxo-label>
              <dxo-format type="currency" currency="USD"></dxo-format>
            </dxo-label>
        </dxi-value-axis>
        <dxo-legend [visible]="false"> </dxo-legend>
        <dxo-size [height]="270"></dxo-size>
      </dx-chart>
    </card-analytics>
    <card-analytics
      titleText="Conversion Funnel (All Products)"
      contentClass="opportunities"
      [showData]="!!opportunities"
      [component]="funnel"
    >
      <dx-funnel
        #funnel
        [dataSource]="opportunities"
        argumentField="name"
        valueField="value"
      >
        <dxo-label
          [visible]="true"
          position="inside"
          backgroundColor="none"
          [customizeText]="customizeOppText"
        >
          <dxo-format type="largeNumber" [precision]="1"> </dxo-format>
        </dxo-label>

        <dxo-legend [visible]="true">
          <dxo-margin [top]="70"></dxo-margin>
        </dxo-legend>

        <dxo-size [height]="270"></dxo-size>
      </dx-funnel>
    </card-analytics>
    <card-analytics
      titleText="Revenue Analysis"
      contentClass="sales-by-state"
      [showData]="!!salesByState"
    >
      <dx-data-grid [dataSource]="salesByState" [height]="270">
        <dxi-column 
          caption="State" 
          dataField="stateName"
        >
        </dxi-column>

        <dxi-column
          alignment="left"
          caption="Sales"
          dataField="total"
          dataType="number"
          format="currency"
          sortOrder="desc"
          [hidingPriority]="2"
        >
        </dxi-column>

        <dxi-column
          alignment="left"
          caption="% Sold"
          dataField="percentage"
          name="percentN"
          format="percent"
          [hidingPriority]="1"
        >
        </dxi-column>

        <dxi-column
          alignment="left"
          caption="Percentage"
          dataField="percentage"
          name="percentB"
          cellTemplate="salesBullet"
          [width]="200"
        >
        </dxi-column>

        <div *dxTemplate="let cellInfo of 'salesBullet'">
          <dx-bullet
            [showTarget]="false"
            [showZeroLevel]="false"
            [value]="cellInfo.data.percentage * 100"
            [startScaleValue]="0"
            [endScaleValue]="100"
          >
            <dxo-tooltip enabled="false"></dxo-tooltip>
            <dxo-size [width]="200" [height]="20"></dxo-size>
          </dx-bullet>
        </div>
      </dx-data-grid>
    </card-analytics>
    <card-analytics
      titleText="Revenue Snapshot (All Products)"
      contentClass="sales-by-category"
      [showData]="!!salesByCategory"
      [component]="pie"
    >
      <dx-pie-chart
        #pie
        [dataSource]="salesByCategory"
        type="doughnut"
        [diameter]="0.8"
        [innerRadius]="0.6"
      >
        <dxi-series argumentField="name" valueField="value">
          <dxo-label
            backgroundColor="none"
            [radialOffset]="-20"
            [visible]="true"
            [customizeText]="customizeSaleText"
          >
            <dxo-font color="#757575" [size]="15"></dxo-font>
          </dxo-label>
        </dxi-series>

        <dxo-legend>
          <dxo-margin [top]="70"></dxo-margin>
        </dxo-legend>

        <dxo-size [height]="270"> </dxo-size>
      </dx-pie-chart>
    </card-analytics>
  </div>
</div>

// packages/vue/src/pages/analytics/analytics-dashboard/analytics-dashboard.vue
<template>
  <div class="view-wrapper">
    <analytics-toolbar
      :show-tabs="true"
      @tab-change="tabChange($event)"
    >
      Dashboard
    </analytics-toolbar>

    <div class="tiles">
      <card-analytics
        class="grey"
        title="Opportunities"
        :show-data="getTotal(opportunities) >= 0"
        content-class="opportunities-total"
      >
        <div class="total">
          {{ formatPrice(getTotal(opportunities)) }}
        </div>
        <div class="percentage">
          <i class="dx-icon-spinup" />
          <span>20.3%</span>
        </div>
      </card-analytics>
      <card-analytics
        class="grey"
        title="Revenue Total"
        :show-data="!!getTotal(sales)"
        content-class="revenue-total"
      >
        <div class="total">
          {{ formatPrice(getTotal(sales)) }}
        </div>
        <div class="percentage">
          <i class="dx-icon-spinup" />
          <span>14.7%</span>
        </div>
      </card-analytics>
      <card-analytics
        class="grey"
        title="Conversion"
        :show-data="true"
        content-class="revenue-total"
      >
        <div class="total">
          16%
        </div>
        <div class="percentage">
          <i class="dx-icon-spindown" />
          <span>2.3%</span>
        </div>
      </card-analytics>
      <card-analytics
        class="grey"
        title="Leads"
        :show-data="true"
        content-class="revenue-total"
      >
        <div class="total">
          51
        </div>
        <div class="percentage">
          <i class="dx-icon-spinup" />
          <span>8.5%</span>
        </div>
      </card-analytics>
    </div>

    <div class="cards">
      <card-analytics
        title="Revenue"
        content-class="sales"
        :show-data="!!sales"
      >
        <dx-chart :data-source="sales">
          <dx-series value-field="total" />
          <dx-common-series-settings
            argument-field="date"
            type="splinearea"
          >
            <dx-border :visible="true" />
          </dx-common-series-settings>
          <dx-argument-axis argument-type="datetime" />
          <dx-value-axis>
            <dx-chart-label>
              <dx-chart-format
                type="currency"
                currency="USD"
              />
            </dx-chart-label>
          </dx-value-axis>
          <dx-legend :visible="false" />
          <dx-size :height="270" />
        </dx-chart>
      </card-analytics>

      <card-analytics
        title="Conversion Funnel (All Products)"
        content-class="opportunities"
        :show-data="!!opportunities"
      >
        <dx-funnel
          :data-source="opportunities"
          argument-field="name"
          value-field="value"
        >
          <dx-label
            :visible="true"
            position="inside"
            background-color="none"
            :customize-text="arg => `$${arg.valueText}`"
          >
            <dx-format
              type="largeNumber"
              :precision="1"
            />
          </dx-label>

          <dx-funnel-legend :visible="true">
            <dx-margin :top="70" />
          </dx-funnel-legend>

          <dx-size :height="270" />
        </dx-funnel>
      </card-analytics>

      <card-analytics
        title="Revenue Analysis"
        content-class="sales-by-state"
        :show-data="!!salesByState"
      >
        <dx-data-grid
          :data-source="salesByState"
          :height="270"
        >
          <dx-column
            caption="State"
            data-field="stateName"
          />
          <dx-column
            alignment="left"
            caption="Sales"
            data-field="total"
            data-type="number"
            format="currency"
            sort-order="desc"
            :hiding-priority="2"
          />
          <dx-column
            alignment="left"
            caption="% Sold"
            data-field="percentage"
            name="percentN"
            format="percent"
            :hiding-priority="1"
          />
          <dx-column
            alignment="left"
            caption="Percentage"
            data-field="percentage"
            name="percentB"
            cell-template="salesBullet"
            :width="200"
          />

          <template #salesBullet="{ data }">
            <dx-bullet
              :show-target="false"
              :show-zero-level="false"
              :value="data.data?.percentage * 100"
              :start-scale-value="0"
              :end-scale-value="100"
            >
              <dx-bullet-tooltip :enabled="false" />
              <dx-bullet-size
                :width="200"
                :height="20"
              />
            </dx-bullet>
          </template>
        </dx-data-grid>
      </card-analytics>

      <card-analytics
        title="Revenue Snapshot (All Products)"
        content-class="sales-by-category"
        :show-data="!!salesByCategory"
      >
        <dx-pie-chart
          :data-source="salesByCategory"
          type="doughnut"
          :diameter="0.8"
          :inner-radius="0.6"
        >
          <dx-pie-series
            argument-field="name"
            value-field="value"
          >
            <dx-pie-label
              background-color="none"
              :radial-offset="-20"
              :visible="true"
              :customize-text="(arg) => arg.percentText"
            >
              <dx-pie-font
                color="#757575"
                :size="15"
              />
            </dx-pie-label>
          </dx-pie-series>

          <dx-pie-legend>
            <dx-pie-margin :top="70" />
          </dx-pie-legend>

          <dx-pie-size :height="270" />
        </dx-pie-chart>
      </card-analytics>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { DxDataGrid, DxColumn } from 'devextreme-vue/data-grid';
import { DxBullet, DxTooltip as DxBulletTooltip, DxSize as DxBulletSize } from 'devextreme-vue/bullet';
import {
  DxChart,
  DxSeries,
  DxCommonSeriesSettings,
  DxBorder,
  DxSize,
  DxLegend,
  DxArgumentAxis,
  DxValueAxis,
  DxLabel as DxChartLabel,
  DxFormat as DxChartFormat,
} from 'devextreme-vue/chart';

import {
  DxPieChart,
  DxLabel as DxPieLabel,
  DxSeries as DxPieSeries,
  DxFont as DxPieFont,
  DxMargin as DxPieMargin,
  DxLegend as DxPieLegend,
  DxSize as DxPieSize,
} from 'devextreme-vue/pie-chart';

import {
  DxFunnel,
  DxMargin,
  DxLabel,
  DxFormat,
  DxLegend as DxFunnelLegend,
} from 'devextreme-vue/funnel';

import { formatPrice } from '@/utils/formatters';
import {
  Sales,
  SalesByState,
  SalesOrOpportunitiesByCategory,
} from '@/types/analytics';

// eslint-disable-next-line import/no-unresolved
import {
  getOpportunitiesByCategory,
  getSalesByCategory,
  getSales,
  getSalesByStateAndCity,
  getSalesByState,
} from 'dx-rwa-data';

import CardAnalytics from '../components/card-analytics.vue';
import AnalyticsToolbar from '../components/analytics-toolbar.vue';

const salesByState = ref<SalesByState>();
const salesByCategory = ref<SalesOrOpportunitiesByCategory>();
const opportunities = ref<SalesOrOpportunitiesByCategory>();
const sales = ref<Sales>();

const loadData = async (startDate: string, endDate: string) => {
  [opportunities.value, salesByCategory.value, sales.value] = await Promise.allSettled(
    [
      getOpportunitiesByCategory(startDate, endDate),
      getSalesByCategory(startDate, endDate),
      getSales(startDate, endDate),
    ],
  ).then((results) => results.map((r) => (r.status === 'fulfilled' ? r.value : [])));

  const salesByStateAndCity = await getSalesByStateAndCity(startDate, endDate);

  salesByState.value = await getSalesByState(salesByStateAndCity);
};

const tabChange = ([startDate, endDate]: string[]) => {
  loadData(startDate, endDate);
};

// eslint-disable-next-line max-len
const getTotal = (data: any[]) => data?.reduce((total, item) => total + (item.value || item.total || 0), 0);
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;
@use "sass:math";
@use "../analytics";

.tiles {
  margin: 20px 0;
  grid-template-columns: repeat(4, calc(25% - 15px));

}
</style>
