// packages/angular/src/app/components/utils/opportunity-tile/opportunity-tile.component.ts
import { Component, Input } from '@angular/core';
import { Opportunity } from 'src/app/types/opportunities';
import { CommonModule } from "@angular/common";
import notify from 'devextreme/ui/notify';

@Component({
    selector: 'opportunity-tile',
    templateUrl: 'opportunity-tile.component.html',
    styleUrls: ['./opportunity-tile.component.scss'],
    imports: [ CommonModule ],
})

export class OpportunityTileComponent {
  @Input() data: Opportunity;

  opportunityClick() {
    notify('Click opportunity event');
  }
}

<div (click)="opportunityClick()" class="opportunity">
  <div class="name">{{ data.name }}</div>
  <div class="product-info"
    >Products: {{ data.products }}, total:
    <span class="total">{{ data.total | currency }}</span>
  </div>
  <div class="owner">
    Owner: <span class="owner-name">{{ data.manager }}</span>
  </div>
</div>

// packages/react/src/components/utils/opportunity-tile/OpportunityTile.tsx
import React from 'react';

import notify from 'devextreme/ui/notify';
import { formatNumber } from 'devextreme/localization';

import './OpportunityTile.scss';

export const OpportunityTile = ({ name, products, total, manager }) => {
  const opportunityClick = () => {
    notify('Click opportunity event');
  };

  const format = (item: number) => {
    return formatNumber(item, { type: 'currency', precision: 2 });
  };

  return (
    <div className='opportunities'>
      <div onClick={opportunityClick} className='opportunity'>
        <div className='name'>{name}</div>
        <div className='product-info'>
          Products: {products}, total: <span className='total'>{format(total)}</span>
        </div>
        <div className='owner'>
          Owner: <span className='owner-name'>{manager}</span>
        </div>
      </div>
    </div>
  );
};
