// packages/angular/src/app/shared/components/card-menu/card-menu.component.ts
import { Component, Input, NgModule } from '@angular/core';
import { DxDropDownButtonModule } from 'devextreme-angular/ui/drop-down-button';

@Component({
  selector: 'card-menu',
  templateUrl: './card-menu.component.html',
  styleUrls: ['./card-menu.component.scss']
})
export class CardMenuComponent {
  @Input() items: Array<{ text: string }>;
  @Input() visible = true;

  constructor() { }

}

@NgModule({
  imports: [DxDropDownButtonModule],
  declarations: [CardMenuComponent],
  exports: [CardMenuComponent],
})
export class CardMenuModule { }

<dx-drop-down-button
  icon="overflow"
  class="overflow-menu"
  [showArrowIcon]="false"
  stylingMode="text"
  [dropDownOptions]="{ width: 'auto' }"
  [items]="items"
  [visible]="visible"
>
</dx-drop-down-button>

// packages/react/src/components/library/card-menu/CardMenu.tsx
import React from 'react';
import { DropDownButton } from 'devextreme-react/ui/drop-down-button';

import './CardMenu.scss';

export const CardMenu = ({ items, visible = true }) => {
  return (
    <DropDownButton
      className='overflow-menu'
      items={items}
      visible={visible}
      icon='overflow'
      stylingMode='text'
      showArrowIcon={false}
      dropDownOptions={{ width: 'auto' }}
    />
  );
};
