// packages/angular/src/app/pages/analytics-dashboard/analytics-dashboard.component.ts
import {Component, inject, OnInit} from '@angular/core';
import { CommonModule } from '@angular/common';
import { map, share } from 'rxjs/operators';
import { Observable, forkJoin } from 'rxjs';

import { DxPieChartModule } from 'devextreme-angular/ui/pie-chart';
import { DxChartModule } from 'devextreme-angular/ui/chart';
import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';
import { DxFunnelModule } from 'devextreme-angular/ui/funnel';
import { DxBulletModule } from 'devextreme-angular/ui/bullet';
import { DxLoadPanelModule } from 'devextreme-angular/ui/load-panel';
import { DxScrollViewModule } from 'devextreme-angular/ui/scroll-view';

import { DataService } from 'src/app/services';
import { ToolbarAnalyticsComponent } from 'src/app/components/utils/toolbar-analytics/toolbar-analytics.component';
import { ConversionCardComponent } from 'src/app/components/utils/conversion-card/conversion-card.component';
import { RevenueCardComponent } from 'src/app/components/utils/revenue-card/revenue-card.component';
import { RevenueAnalysisCardComponent } from 'src/app/components/utils/revenue-analysis-card/revenue-analysis-card.component';
import { RevenueSnapshotCardComponent } from 'src/app/components/utils/revenue-snapshot-card/revenue-snapshot-card.component';
import { OpportunitiesTickerComponent } from 'src/app/components/utils/opportunities-ticker/opportunities-ticker.component';
import { RevenueTotalTickerComponent } from 'src/app/components/utils/revenue-total-ticker/revenue-total-ticker.component';
import { ConversionTickerComponent } from 'src/app/components/utils/conversion-ticker/conversion-ticker.component';
import { LeadsTickerComponent } from 'src/app/components/utils/leads-ticker/leads-ticker.component';
import { analyticsPanelItems, Dates } from 'src/app/types/resource';
import {
  Sales, SalesByState, SalesByStateAndCity, SalesOrOpportunitiesByCategory,
} from 'src/app/types/analytics';

type DashboardData = SalesOrOpportunitiesByCategory | Sales | SalesByState | SalesByStateAndCity | null;
type DataLoader = (startDate: string, endDate: string) => Observable<Object>;

@Component({
    templateUrl: './analytics-dashboard.component.html',
    styleUrls: ['./analytics-dashboard.component.scss'],
    providers: [ DataService ],
    imports: [
      DxScrollViewModule,
      DxDataGridModule,
      DxBulletModule,
      DxFunnelModule,
      DxPieChartModule,
      DxChartModule,
      ToolbarAnalyticsComponent,
      DxLoadPanelModule,
      ConversionCardComponent,
      RevenueAnalysisCardComponent,
      RevenueCardComponent,
      RevenueSnapshotCardComponent,
      OpportunitiesTickerComponent,
      RevenueTotalTickerComponent,
      ConversionTickerComponent,
      LeadsTickerComponent,
      CommonModule,
    ],
})
export class AnalyticsDashboardComponent implements OnInit {
  private service = inject(DataService);

  analyticsPanelItems = analyticsPanelItems;
  opportunities: SalesOrOpportunitiesByCategory = null;
  sales: Sales = null;
  salesByState: SalesByState = null;
  salesByCategory: SalesByStateAndCity = null;

  isLoading: boolean = true;

  selectionChange(dates: Dates) {
    this.loadData(dates.startDate, dates.endDate);
  }

  loadData = (startDate: string, endDate: string) => {
    this.isLoading = true;
    const tasks: Observable<object>[] = [
      ['opportunities', this.service.getOpportunitiesByCategory],
      ['sales', this.service.getSales],
      ['salesByCategory', this.service.getSalesByCategory],
      ['salesByState', (startDate: string, endDate: string) => this.service.getSalesByStateAndCity(startDate, endDate).pipe(
        map((data) => this.service.getSalesByState(data))
      )
      ]
    ].map(([dataName, loader]: [string, DataLoader]) => {
      const loaderObservable = loader(startDate, endDate).pipe(share());

      loaderObservable.subscribe((result: DashboardData) => {
        this[dataName] = result;
      });

      return loaderObservable;
    });

    forkJoin(tasks).subscribe(() => {
      this.isLoading = false;
    });
  };

  ngOnInit(): void {
    const [startDate, endDate] = analyticsPanelItems[4].value.split('/');

    this.loadData(startDate, endDate);
  }
}

<div class="view-wrapper">
  <dx-toolbar>
    <dxi-item location="before">
      <span class="toolbar-header">Dashboard</span>
    </dxi-item>

    <dxi-item 
      location="before"
      locateInMenu="auto">
      <dx-tabs
        [selectedItemKeys]="[5]"
        keyExpr="key"
        [items]="analyticsPanelItems"
        (onItemClick)="selectionChange($event)"
      ></dx-tabs>
    </dxi-item>

    <dxi-item 
      location="after" 
      locateInMenu="auto"
      cssclass="add-card"
      >
      <dx-button
        icon="plus"
        text="Add Card"
        type="default"
        stylingMode="contained"
      ></dx-button>
    </dxi-item>

    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxButton"
      showText="inMenu"
      [options]="{
        text: 'Refresh',
        icon: 'refresh'
      }"
    ></dxi-item>

    <dxi-item location="after" locateInMenu="auto">
      <div class="separator"></div>
    </dxi-item>

    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxButton"
      showText="inMenu"
      [options]="{
        icon: 'export'
      }"
    ></dxi-item>
  </dx-toolbar>

  <div class="cards grey">
    <card-analytics
      class="grey"
      titleText="Opportunities"
      [showData]="getTotal(opportunities)"
      contentClass="opportunities-total"
    >
      <div *ngIf="getTotal(opportunities)">
        <div class="total">
          {{ getTotal(opportunities) | currency: "USD":"$":"1.0-0" }}
        </div>
        <div class="percentage">
          <i class="dx-icon-spinup"></i>
          <span>20.3%</span>
        </div>
      </div>
    </card-analytics>
    <card-analytics
      class="grey"
      titleText="Revenue Total"
      [showData]="getTotal(sales)"
      contentClass="revenue-total" 
    >
    <div *ngIf="getTotal(sales)">
      <div class="total">
        {{ getTotal(sales) | currency: "USD":"$":"1.0-0" }}
      </div>
      <div class="percentage">
        <i class="dx-icon-spinup"></i>
        <span>14.7%</span>
      </div>
    </div>
    </card-analytics>
    <card-analytics
      class="grey"
      titleText="Conversion"
      [showData]="true"
      contentClass="revenue-total"
    >
      <div class="total">16%</div>
      <div class="percentage">
        <i class="dx-icon-spindown"></i>
        <span>2.3%</span>
      </div>
    </card-analytics>
    <card-analytics
      class="grey"
      titleText="Leads"
      [showData]="true"
      contentClass="revenue-total"
    >
      <div class="total">51</div>
      <div class="percentage">
        <i class="dx-icon-spinup"></i>
        <span>8.5%</span>
      </div>
    </card-analytics>
  </div>

  <div class="cards">
    <card-analytics titleText="Revenue" contentClass="sales" [showData]="!!sales" [component]="chart">
      <dx-chart #chart [dataSource]="sales">
        <dxi-series valueField="total"></dxi-series>
        <dxo-common-series-settings argumentField="date" type="splinearea">
          <dxo-border [visible]="true"></dxo-border>
        </dxo-common-series-settings>
        <dxo-argument-axis argumentType="datetime"></dxo-argument-axis>
        <dxi-value-axis>
            <dxo-label>
              <dxo-format type="currency" currency="USD"></dxo-format>
            </dxo-label>
        </dxi-value-axis>
        <dxo-legend [visible]="false"> </dxo-legend>
        <dxo-size [height]="270"></dxo-size>
      </dx-chart>
    </card-analytics>
    <card-analytics
      titleText="Conversion Funnel (All Products)"
      contentClass="opportunities"
      [showData]="!!opportunities"
      [component]="funnel"
    >
      <dx-funnel
        #funnel
        [dataSource]="opportunities"
        argumentField="name"
        valueField="value"
      >
        <dxo-label
          [visible]="true"
          position="inside"
          backgroundColor="none"
          [customizeText]="customizeOppText"
        >
          <dxo-format type="largeNumber" [precision]="1"> </dxo-format>
        </dxo-label>

        <dxo-legend [visible]="true">
          <dxo-margin [top]="70"></dxo-margin>
        </dxo-legend>

        <dxo-size [height]="270"></dxo-size>
      </dx-funnel>
    </card-analytics>
    <card-analytics
      titleText="Revenue Analysis"
      contentClass="sales-by-state"
      [showData]="!!salesByState"
    >
      <dx-data-grid [dataSource]="salesByState" [height]="270">
        <dxi-column 
          caption="State" 
          dataField="stateName"
        >
        </dxi-column>

        <dxi-column
          alignment="left"
          caption="Sales"
          dataField="total"
          dataType="number"
          format="currency"
          sortOrder="desc"
          [hidingPriority]="2"
        >
        </dxi-column>

        <dxi-column
          alignment="left"
          caption="% Sold"
          dataField="percentage"
          name="percentN"
          format="percent"
          [hidingPriority]="1"
        >
        </dxi-column>

        <dxi-column
          alignment="left"
          caption="Percentage"
          dataField="percentage"
          name="percentB"
          cellTemplate="salesBullet"
          [width]="200"
        >
        </dxi-column>

        <div *dxTemplate="let cellInfo of 'salesBullet'">
          <dx-bullet
            [showTarget]="false"
            [showZeroLevel]="false"
            [value]="cellInfo.data.percentage * 100"
            [startScaleValue]="0"
            [endScaleValue]="100"
          >
            <dxo-tooltip enabled="false"></dxo-tooltip>
            <dxo-size [width]="200" [height]="20"></dxo-size>
          </dx-bullet>
        </div>
      </dx-data-grid>
    </card-analytics>
    <card-analytics
      titleText="Revenue Snapshot (All Products)"
      contentClass="sales-by-category"
      [showData]="!!salesByCategory"
      [component]="pie"
    >
      <dx-pie-chart
        #pie
        [dataSource]="salesByCategory"
        type="doughnut"
        [diameter]="0.8"
        [innerRadius]="0.6"
      >
        <dxi-series argumentField="name" valueField="value">
          <dxo-label
            backgroundColor="none"
            [radialOffset]="-20"
            [visible]="true"
            [customizeText]="customizeSaleText"
          >
            <dxo-font color="#757575" [size]="15"></dxo-font>
          </dxo-label>
        </dxi-series>

        <dxo-legend>
          <dxo-margin [top]="70"></dxo-margin>
        </dxo-legend>

        <dxo-size [height]="270"> </dxo-size>
      </dx-pie-chart>
    </card-analytics>
  </div>
</div>

// packages/vue/src/pages/analytics/analytics-dashboard.vue
<template>
  <div class="view-wrapper">
    <analytics-toolbar
      ref="tabs"
      :show-tabs="true"
      @tab-change="tabChange($event)"
    >
      Dashboard
    </analytics-toolbar>
    <div class="tiles">
      <card-analytics
        class="grey"
        title="Opportunities"
        :show-data="data.opportunities !== null"
        content-class="opportunities-total"
      >
        <div class="total">
          {{ formatPrice(getTotal(data.opportunities)) }}
        </div>
        <div class="percentage">
          <i class="dx-icon-spinup" />
          <span>20.3%</span>
        </div>
      </card-analytics>
      <card-analytics
        class="grey"
        title="Revenue Total"
        :show-data="data.sales !== null"
        content-class="revenue-total"
      >
        <div class="total">
          {{ formatPrice(getTotal(data.sales)) }}
        </div>
        <div class="percentage">
          <i class="dx-icon-spinup" />
          <span>14.7%</span>
        </div>
      </card-analytics>
      <card-analytics
        class="grey"
        title="Conversion"
        :show-data="true"
        content-class="revenue-total"
      >
        <div class="total">
          16%
        </div>
        <div class="percentage">
          <i class="dx-icon-spindown" />
          <span>2.3%</span>
        </div>
      </card-analytics>
      <card-analytics
        class="grey"
        title="Leads"
        :show-data="true"
        content-class="revenue-total"
      >
        <div class="total">
          51
        </div>
        <div class="percentage">
          <i class="dx-icon-spinup" />
          <span>8.5%</span>
        </div>
      </card-analytics>
    </div>

    <div class="cards">
      <card-analytics
        title="Revenue"
        content-class="sales"
      >
        <dx-chart
          v-if="data.sales"
          :data-source="data.sales"
        >
          <dx-series value-field="total" />
          <dx-common-series-settings
            argument-field="date"
            type="splinearea"
          >
            <dx-border :visible="true" />
          </dx-common-series-settings>
          <dx-argument-axis argument-type="datetime" />
          <dx-value-axis>
            <dx-chart-label>
              <dx-chart-format
                type="currency"
                currency="USD"
              />
            </dx-chart-label>
          </dx-value-axis>
          <dx-legend :visible="false" />
          <dx-size :height="270" />
        </dx-chart>
      </card-analytics>

      <card-analytics
        title="Conversion Funnel (All Products)"
        content-class="opportunities"
      >
        <dx-funnel
          v-if="data.opportunities"
          :data-source="data.opportunities"
          argument-field="name"
          value-field="value"
        >
          <dx-label
            :visible="true"
            position="inside"
            background-color="none"
            :customize-text="arg => `$${arg.valueText}`"
          >
            <dx-format
              type="largeNumber"
              :precision="1"
            />
          </dx-label>

          <dx-funnel-legend :visible="true">
            <dx-margin :top="70" />
          </dx-funnel-legend>

          <dx-size :height="270" />
        </dx-funnel>
      </card-analytics>

      <card-analytics
        title="Revenue Analysis"
        content-class="sales-by-state"
      >
        <dx-data-grid
          :data-source="data.salesByState"
          :height="270"
        >
          <dx-column
            caption="State"
            data-field="stateName"
          />
          <dx-column
            alignment="left"
            caption="Sales"
            data-field="total"
            data-type="number"
            format="currency"
            sort-order="desc"
            :hiding-priority="2"
          />
          <dx-column
            alignment="left"
            caption="% Sold"
            data-field="percentage"
            name="percentN"
            format="percent"
            :hiding-priority="1"
          />
          <dx-column
            alignment="left"
            caption="Percentage"
            data-field="percentage"
            name="percentB"
            cell-template="salesBullet"
            :width="200"
          />

          <template #salesBullet="{ data }">
            <dx-bullet
              :show-target="false"
              :show-zero-level="false"
              :value="data.data?.percentage * 100"
              :start-scale-value="0"
              :end-scale-value="100"
            >
              <dx-bullet-tooltip :enabled="false" />
              <dx-bullet-size
                :width="200"
                :height="20"
              />
            </dx-bullet>
          </template>
        </dx-data-grid>
      </card-analytics>

      <card-analytics
        title="Revenue Snapshot (All Products)"
        content-class="sales-by-category"
      >
        <dx-pie-chart
          v-if="data.salesByCategory"
          :data-source="data.salesByCategory"
          type="doughnut"
          :diameter="0.8"
          :inner-radius="0.6"
        >
          <dx-pie-series
            argument-field="name"
            value-field="value"
          >
            <dx-pie-label
              background-color="none"
              :radial-offset="-20"
              :visible="true"
              :customize-text="(arg) => arg.percentText"
            >
              <dx-pie-font
                color="#757575"
                :size="15"
              />
            </dx-pie-label>
          </dx-pie-series>

          <dx-pie-legend>
            <dx-pie-margin :top="70" />
          </dx-pie-legend>

          <dx-pie-size :height="270" />
        </dx-pie-chart>
      </card-analytics>
    </div>
  </div>
  <dx-load-panel
    container=".view-wrapper"
    :visible="isLoading(data)"
    :show-pane="true"
    width="100%"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { DxDataGrid, DxColumn } from 'devextreme-vue/data-grid';
import { DxBullet, DxTooltip as DxBulletTooltip, DxSize as DxBulletSize } from 'devextreme-vue/bullet';
import { DxLoadPanel } from 'devextreme-vue/load-panel';
import {
  DxChart,
  DxSeries,
  DxCommonSeriesSettings,
  DxBorder,
  DxSize,
  DxLegend,
  DxArgumentAxis,
  DxValueAxis,
  DxLabel as DxChartLabel,
  DxFormat as DxChartFormat,
} from 'devextreme-vue/chart';

import {
  DxPieChart,
  DxLabel as DxPieLabel,
  DxSeries as DxPieSeries,
  DxFont as DxPieFont,
  DxMargin as DxPieMargin,
  DxLegend as DxPieLegend,
  DxSize as DxPieSize,
} from 'devextreme-vue/pie-chart';

import {
  DxFunnel,
  DxMargin,
  DxLabel,
  DxFormat,
  DxLegend as DxFunnelLegend,
} from 'devextreme-vue/funnel';

import { formatPrice } from '@/utils/formatters';
import {
  Sales,
  SalesByState, SalesByStateAndCity,
  SalesOrOpportunitiesByCategory,
} from '@/types/analytics';

// eslint-disable-next-line import/no-unresolved
import {
  getOpportunitiesByCategory,
  getSalesByCategory,
  getSales,
  getSalesByStateAndCity,
  getSalesByState,
} from 'dx-rwa-data';

import CardAnalytics from './components/card-analytics.vue';
import AnalyticsToolbar from './components/analytics-toolbar.vue';

type DashboardData = {
  opportunities: SalesOrOpportunitiesByCategory | null,
  sales: Sales | null,
  salesByState: SalesByState | null,
  salesByCategory: SalesByStateAndCity | null,
};

type DashboardDataName = keyof DashboardData;
type DashboardDataType = DashboardData[keyof DashboardData];
type DataLoader = (startDate: string, endDate: string) => Promise<any[]>;

const loaders: { [key in DashboardDataName]: DataLoader } = {
  opportunities: getOpportunitiesByCategory,
  salesByCategory: getSalesByCategory,
  sales: getSales,
  salesByState: (startDate: string, endDate: string) => getSalesByStateAndCity(startDate, endDate)
    .then((result: SalesByStateAndCity) => getSalesByState(result)),
};

const data = ref({} as DashboardData);

const getTotal = (value: Array<{value?: number, total?: number}>) => (value || [])
  .reduce((total, item) => total + (item.value || item.total || 0), 0);

const updateData = (propName: DashboardDataName, value: DashboardDataType = null) => {
  data.value = { ...data.value, [propName]: value };
};

const loadData = (startDate: string, endDate: string) => {
  (Object.entries(loaders) as [[DashboardDataName, DataLoader]]).forEach(([dataName, loader]) => {
    updateData(dataName);

    loader(startDate, endDate).then((result: DashboardDataType) => updateData(dataName, result));
  });
};

const isLoading = (dashboardData: DashboardData) => Object.values(dashboardData).includes(null);

const tabChange = ([startDate, endDate]: string[]) => {
  loadData(startDate, endDate);
};
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;
@use "sass:math";
@use "./analytics";

.view-wrapper {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
  padding: 20px 16px 0 16px;
}

.tiles {
  margin: 20px 0;
  grid-template-columns: repeat(4, calc(25% - 15px));
}

@media only screen and (max-width: 900px) {
  .tiles {
    grid-template-columns: repeat(2, calc(50% - 10px));
  }
}

@media only screen and (max-width: 400px) {
  .tiles {
    grid-template-columns: repeat(1, 100%);
  }
}
</style>
