// packages/angular/src/app/pages/crm-contact-list/user-new-form/user-new-form.component.ts
import {
  Component,
  NgModule,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxTextBoxModule,
  DxFormModule,
  DxValidatorModule,
} from 'devextreme-angular';
import {
  FormTextboxModule,
  FormPhotoUploaderModule,
} from 'src/app/shared/components';
import { newContact } from 'src/app/shared/types/contact';

@Component({
  selector: 'user-new-form',
  templateUrl: './user-new-form.component.html',
  providers: [],
})

export class UserNewFormComponent {
  newUser = newContact;

  constructor() { }
}

@NgModule({
  imports: [
    DxTextBoxModule,
    DxFormModule,
    DxValidatorModule,

    FormTextboxModule,
    FormPhotoUploaderModule,

    CommonModule,
  ],
  declarations: [UserNewFormComponent],
  exports: [UserNewFormComponent],
})
export class UserNewFormModule { }

<dx-form 
        class="plain-styled-form" 
        labelMode="floating" 
        [class.view-mode]="!isEditing"
>
  <dxi-item itemType="group">
    <dxo-col-count-by-screen [xs]="1" [sm]="1" [md]="1" [lg]="1"></dxo-col-count-by-screen>
    <dxi-item class="uploader">
      <div *dxTemplate>
        <form-item-uploader></form-item-uploader>
      </div>
    </dxi-item>
  </dxi-item>

  <dxi-item itemType="group">
    <dxo-col-count-by-screen [xs]="1" [sm]="1" [md]="2" [lg]="2"></dxo-col-count-by-screen>
    <dxi-item cssClass="accent">
      <div *dxTemplate>
        <form-textbox 
                label="First Name"
                [(value)]="newUser.firstName" 
                [isEditing]="isEditing">
          </form-textbox>
      </div>
    </dxi-item>
    <dxi-item cssClass="accent">
      <div *dxTemplate>
        <form-textbox 
                label="Last Name" 
                [(value)]="newUser.lastName" 
                [isEditing]="isEditing">
        </form-textbox>
      </div>
    </dxi-item>
    <dxi-item cssClass="accent">
      <div *dxTemplate>
        <form-textbox 
                label="Company" 
                [(value)]="newUser.company" 
                [isEditing]="isEditing">
        </form-textbox>
      </div>
    </dxi-item>
    <dxi-item>
      <div *dxTemplate>
        <form-textbox 
                label="Position" 
                [(value)]="newUser.position" 
                [isEditing]="isEditing">
        </form-textbox>
      </div>
    </dxi-item>
  </dxi-item>

  <dxi-item itemType="group" cssClass="contact-fields-group">
    <dxo-col-count-by-screen [xs]="1" [sm]="1" [md]="2" [lg]="2"></dxo-col-count-by-screen>

    <dxi-item cssClass="accent">
      <div *dxTemplate>
        <form-textbox 
                label="Assigned to" 
                [(value)]="newUser.manager" 
                [isEditing]="isEditing">
        </form-textbox>
      </div>
    </dxi-item>
    <dxi-item>
      <div *dxTemplate>
        <form-textbox 
                [(value)]="newUser.phone" 
                [isEditing]="isEditing" 
                icon="tel" 
                mask="+1(000)000-0000"
        >
        </form-textbox>
      </div>
    </dxi-item>
    <dxi-item>
      <div *dxTemplate>
        <form-textbox 
                [(value)]="newUser.email" 
                [isEditing]="isEditing" 
                icon="email" 
                [validators]="[{type: 'email'}]"
        >
        </form-textbox>
      </div>
    </dxi-item>
      <dxi-item>
        <div *dxTemplate>
          <form-textbox 
                  [(value)]="newUser.address" 
                  [isEditing]="isEditing" 
                  icon="home" 
                  [validators]="[]"
          >
          </form-textbox>
        </div>
      </dxi-item>
  </dxi-item>
</dx-form>

// packages/vue/src/pages/crm-contact-list/components/user-new-form.vue
<template>
  <dx-form
    class="plain-styled-form"
    label-mode="floating"
    :validation-group="props.validationGroup"
  >
    <dx-form-item item-type="group">
      <dx-col-count-by-screen
        :xs="1"
        :sm="1"
        :md="1"
        :lg="1"
      />
      <dx-form-item class="uploader">
        <form-photo-uploader/>
      </dx-form-item>
    </dx-form-item>

    <dx-form-item item-type="group">
      <dx-col-count-by-screen
        :xs="1"
        :sm="1"
        :md="2"
        :lg="2"
      />
      <dx-form-item>
        <form-textbox
          label="First Name"
          v-model.value="newUser.firstName"
          :is-editing="true"
          :validation-group="props.validationGroup"
        />
      </dx-form-item>
      <dx-form-item css-class="accent">
        <form-textbox
          label="Last Name"
          v-model="newUser.lastName"
          :is-editing="true"
          :validation-group="props.validationGroup"
        />
      </dx-form-item>
      <dx-form-item css-class="accent">
        <form-textbox
          label="Company"
          v-model.value="newUser.company"
          :is-editing="true"
          :validators="[]"
          :validation-group="props.validationGroup"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          label="Position"
          v-model.value="newUser.position"
          :is-editing="true"
          :validators="[]"
          :validation-group="props.validationGroup"
        />
      </dx-form-item>
    </dx-form-item>

    <dx-form-item
      item-type="group"
      css-class="contact-fields-group"
    >
      <dx-col-count-by-screen
        :xs="1"
        :sm="1"
        :md="2"
        :lg="2"
      />

      <dx-form-item css-class="accent">
        <form-textbox
          label="Assigned to"
          v-model.value="newUser.manager"
          :is-editing="true"
          :validators="[]"
          :validation-group="props.validationGroup"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model.value="newUser.phone"
          :is-editing="true"
          icon="tel"
          mask="+1(000)000-0000"
          :validators="[]"
          :validation-group="props.validationGroup"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model.value="newUser.email"
          :is-editing="true"
          icon="email"
          :validators="[{type: 'email'}]"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model.value="newUser.address"
          :is-editing="true"
          icon="home"
          :validators="[]"
          :validation-group="props.validationGroup"
        />
      </dx-form-item>
    </dx-form-item>
  </dx-form>
</template>

<script setup lang="ts">
import {
  DxForm,
  DxItem as DxFormItem,
  DxColCountByScreen,
} from 'devextreme-vue/form';
import { ref } from 'vue';
import { newContact } from '@/types/contact';
import FormPhotoUploader from '@/components/form-photo-uploader.vue';
import FormTextbox from '@/components/form-textbox.vue';

const props = defineProps<{
  validationGroup: string
}>();

const newUser = ref(newContact);
</script>
