// packages/vue/src/components/library/card-tasks.vue
<template>
  <div id="card-tasks">
    <dx-load-panel
      :visible="props.isLoading"
      :show-pane="false"
      width="auto"
      container="#card-tasks"
      :position="{ of: '#card-tasks' }"
    />
    <dx-data-grid
      class="grid-tasks"
      :data-source="filteredTasks"
      :column-auto-width="true"
      v-if="!props.isLoading"
    >
      <dx-selection
        show-check-boxes-mode="always"
        mode="multiple"
      />
      <dx-row-dragging
        :allow-reordering="true"
        :on-reorder="onReorder"
        :show-drag-icons="true"
      />

      <!--  Grid Columns    -->
      <dx-column
        data-field="text"
        caption="Subject"
        :hiding-priority="3"
      />
      <dx-column
        data-field="date"
        data-type="date"
        caption="Due Date"
        :hiding-priority="1"
      />
      <dx-column
        caption="Assigned To"
        data-field="manager"
        :hiding-priority="0"
      />
    </dx-data-grid>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import {
  DxDataGrid,
  DxColumn,
  DxSelection,
  DxRowDragging,
} from 'devextreme-vue/data-grid';
import type {
  DxDataGridTypes,
} from 'devextreme-vue/data-grid';
import DxLoadPanel from 'devextreme-vue/load-panel';
import { Task } from '@/types/task';

const props = withDefaults(defineProps<{
  isLoading: boolean,
  manager: string,
  tasks: Task[]
}>(), {
  tasks: () => [],
  isLoading: true,
  manager: '',
});

const tasksRef = ref<Task[]>([]);

watch(
  () => props.tasks,
  (newTasks) => {
    tasksRef.value = newTasks;
  },
);

const filteredTasks = computed(
  () => tasksRef.value.filter((item) => !!item.status && !!item.priority),
);

const onReorder = (e: DxDataGridTypes.RowDraggingReorderEvent) => {
  const visibleRows = e.component.getVisibleRows();
  const toIndex = tasksRef.value.indexOf(visibleRows[e.toIndex].data);
  const fromIndex = tasksRef.value.indexOf(e.itemData);

  tasksRef.value.splice(fromIndex, 1);
  tasksRef.value.splice(toIndex, 0, e.itemData);
};
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

#card-tasks {
  min-height: 300px;
  padding: 20px 0 0;
}

.grid-tasks {
  border-top: 1px solid var(--border-color);
}
</style>

// packages/angular/src/app/components/library/card-tasks/card-tasks.component.ts
import {
  Component, Input,OnChanges, SimpleChanges, ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxDataGridComponent,
  DxDataGridModule,
  DxLoadPanelModule,
} from 'devextreme-angular';
import { DxDataGridTypes } from 'devextreme-angular/ui/data-grid';
import { Task } from '../../../types/task';

@Component({
  selector: 'card-tasks',
  templateUrl: './card-tasks.component.html',
  styleUrls: ['./card-tasks.component.scss'],
  imports: [
    DxDataGridModule,
    DxLoadPanelModule,
    CommonModule,
  ]
})
export class CardTasksComponent implements OnChanges {
  @ViewChild('dataGrid', { static: false }) component!: DxDataGridComponent;

  @Input() tasks?: Task[];

  @Input() isLoading: boolean = false;

  currentTasks: Task[] = [];

  ngOnChanges(changes: SimpleChanges) {
    if (changes.tasks) {
      const tasks = changes.tasks.currentValue as Task[] | undefined;
      this.currentTasks = tasks?.filter((item: Task) => !!item.status && !!item.priority) ?? [];
    }
  }

  onReorder = (e: DxDataGridTypes.RowDraggingReorderEvent) => {
    const visibleRows = e.component.getVisibleRows();
    const toIndex = this.currentTasks.indexOf(visibleRows[e.toIndex].data);
    const fromIndex = this.currentTasks.indexOf(e.itemData);

    this.currentTasks.splice(fromIndex, 1);
    this.currentTasks.splice(toIndex, 0, e.itemData);

    e.component.refresh();
  }
}

<div id="card-tasks">
  @if (!isLoading && tasks) {
    <dx-data-grid
      #dataGrid
      [dataSource]="currentTasks"
      [columnAutoWidth]="true"
    >
      <dxo-data-grid-selection mode="multiple" showCheckBoxesMode="always"></dxo-data-grid-selection>

      <dxo-data-grid-row-dragging
        [allowReordering]="true"
        [onReorder]="$any(onReorder)"
        [showDragIcons]="true"
      ></dxo-data-grid-row-dragging>

      <dxi-data-grid-column
        dataField="text"
        caption="Subject"
        [hidingPriority]="3"
      ></dxi-data-grid-column>
      <dxi-data-grid-column
        dataField="date"
        dataType="date"
        caption="Due Date"
        [hidingPriority]="1"
      ></dxi-data-grid-column>
      <dxi-data-grid-column
        caption="Assigned To"
        dataField="manager"
        [hidingPriority]="0"
      ></dxi-data-grid-column>
    </dx-data-grid>
  }

  <dx-load-panel
    [visible]="isLoading || !tasks"
    [showPane]="false"
    container="#card-tasks"
    [position]="{ of: '#card-tasks' }"
  ></dx-load-panel>
</div>
