// packages/react/src/pages/crm-contact-list/crm-contact-list.js
import React, { useState } from 'react';
import DataGrid, {
  Column,
  Selection,
  Export,
  Toolbar as GridToolbar,
  Item as GridToolbarItem,
  SearchPanel
} from 'devextreme-react/data-grid';
import Toolbar, { Item } from 'devextreme-react/toolbar';
import ScrollView from 'devextreme-react/scroll-view';
import Accordion, { Item as AccordionItem } from 'devextreme-react/accordion';
import './crm-contact-list.scss';

const CrmContactList = () => {
  const gridData = [{
    name: 'Robert Reaga',
    status: 1,
    id: 120545,
    products: [
      { productId: 1, productStatus: 1 },
      { productId: 2, productStatus: 2 }
    ],
    manager: 'Sarah Davix',
    organization: 'SV Consult',
    address: '69 Ruthven St #24, Boston, MA 02121, United States of America',
    email: '1@2',
  }, {
    name: 'Samuel Browick',
    status: 2,
    id: 120545,
    products: [
      { productId: 1, productStatus: 2 },
      { productId: 2, productStatus: 1 }
    ],
    manager: 'Brett Johnson',
    organization: 'SV Consult',
    address: '69 Ruthven St #24, Boston, MA 02121, United States of America',
    email: '2@2',
  }];

  const statuses = {
    1: 'New',
    2: 'Active',
  };

  const products = {
    1: 'CRM System',
    2: 'Task Management',
  };

  const productStatuses = {
    1: 'Lead',
    2: 'Trial sent'
  };

  const [isPanelOpen, setPanelOpen] = useState(false);
  const [isPanelPin, setPanelPin] = useState(false);
  const [panelData, setPanelData] = useState(gridData[0]);

  function console(message) {
    console.log(message);
  }

  function rowClick(e) {
    setPanelData(e.data);
    setPanelOpen(true);
  }

  function closePanel() {
    setPanelOpen(false);
  }

  function pinClick() {
    setPanelPin(!isPanelPin);
  };

  function renderStatus(data) {
    return <span className={'status status-' + data.data.status}>{statuses[data.data.status]}</span>;
  }

  function renderProducts(data) {
    return <span>
      {data.data.products.map((product, i) =>
        <span key={i}>
          <span>{products[product.productId]} </span>
          <span className={'cloud cloud-' + product.productStatus}>
            {productStatuses[product.productStatus]}
          </span>
        </span>)}
    </span>
  }
  return (<React.Fragment>
    <div className="view-wrapper">
      <DataGrid
        dataSource={gridData}
        height="100%"
        onRowClick={rowClick}
      >
        <SearchPanel visible={true}
          width={240}
          placeholder="Contact Search" />
        <Export
          enabled={true}
          allowExportSelectedData={true} />
        <GridToolbar>
          <GridToolbarItem location="before">
            <div className="grid-header">Contact List</div>
          </GridToolbarItem>
          <GridToolbarItem
            location="after"
            locateInMenu="auto"
            widget="dxButton"
            options={{ text: 'Add Contact', icon: 'plus', type: 'default', stylingMode: 'contained' }}
          ></GridToolbarItem>
          <GridToolbarItem
            location="after"
            locateInMenu="auto"
            showText="inMenu"
            widget="dxButton"
            options={{ text: 'Refresh', icon: 'refresh' }}
          ></GridToolbarItem>
          <GridToolbarItem
            location="after"
            locateInMenu="auto">
            <div className="separator"></div>
          </GridToolbarItem>
          <GridToolbarItem name="exportButton"></GridToolbarItem>
          <GridToolbarItem
            location="after"
            locateInMenu="auto">
            <div className="separator"></div>
          </GridToolbarItem>
          <GridToolbarItem
            location="after"
            locateInMenu="auto"
            showText="inMenu"
            widget="dxButton"
            options={{ text: 'Remove', icon: 'trash' }}
          ></GridToolbarItem>
          <GridToolbarItem name="searchPanel"></GridToolbarItem>
        </GridToolbar>
        <Selection
          selectAllMode="allPages"
          showCheckBoxesMode="always"
          mode="multiple"
        />
        <Column dataField="name" caption="Name" hidingPriority={5} minWidth={150} />
        <Column dataField="status" caption="Status" dataType="string" cellRender={renderStatus} hidingPriority={3} minWidth={100} />
        <Column dataField="id" caption="ID" hidingPriority={1} />
        <Column dataField="Products" caption="Products" hidingPriority={0} minWidth={400} cellRender={renderProducts} />
        <Column dataField="manager" caption="Manager" hidingPriority={4} />
        <Column dataField="organization" caption="Organization" hidingPriority={2} />
      </DataGrid>

      <div className={'panel ' + (isPanelPin ? 'pin ' : '') + (isPanelOpen ? 'open' : '')}>
        {panelData &&
          <div className="data-wrapper">
            <Toolbar>
              <Item location="before">
                <div className="contact-name">{panelData.name}</div>
              </Item>
              <Item location="before">
                <span className={'status status-' + panelData.status}>{statuses[panelData.status]}</span>
              </Item>
              <Item
                location="after"
                widget="dxButton"
                options={{ icon: isPanelPin ? 'unpin' : 'pin', onClick: pinClick }}
              ></Item>
              <Item
                location="after"
                widget="dxButton"
                options={{ icon: 'close', onClick: closePanel }}
              ></Item>
            </Toolbar>
            <ScrollView>
              <div className="user-info">
                <div className="photo"></div>
                <div className="info">
                  <div>{panelData.id}</div>
                  <div><i className="dx-icon-user"></i> <span>{panelData.manager}</span></div>
                  <div><i className="dx-icon-product"></i> <span>{panelData.organization}</span></div>
                  <div><i className="dx-icon-email"></i> <span>{panelData.email}</span></div>
                </div>
              </div>
              <div>{panelData.address}</div>
              <Toolbar>
                <Item
                  location="before"
                  widget="dxButton"
                  options={{ icon: 'edit', stylingMode: 'outlined', text: 'Edit' }}
                ></Item>
                <Item
                  location="center"
                  widget="dxButton"
                  options={{ stylingMode: 'text', text: 'Send email' }}
                ></Item>
                <Item
                  location="after"
                  widget="dxDropDownButton"
                  options={{ text: 'Action' }}
                ></Item>
              </Toolbar>
              <Accordion
                multiple={true}
                collapsible={true}
              >
                <AccordionItem
                  title="Licenses"
                >
                  <div className="licenses">
                    <div>
                      <div className="caption">Income</div>
                      <div className="value">$1,650,00</div>
                    </div>
                    <div>
                      <div className="caption">Licences</div>
                      <div className="value">1</div>
                    </div>
                    <div>
                      <div className="caption">Active Licences</div>
                      <div className="value">1</div>
                    </div>
                  </div>
                </AccordionItem>
                <AccordionItem
                  title="Opportunities"
                >
                    {panelData.products.map((product, i) =>
                      <span className="oportunities" key={i}>
                        <span className="item">{products[product.productId]} </span>
                        <span className={'cloud cloud-' + product.productStatus}>{productStatuses[product.productStatus]}</span>
                        <br/>
                      </span>
                    )}
                </AccordionItem>
                <AccordionItem
                  title="Activities"
                >
                  c
                </AccordionItem>
              </Accordion>
            </ScrollView>
          </div>
        }
      </div>
    </div>
  </React.Fragment>
  )
};

export default CrmContactList;

// packages/angular/src/app/pages/crm-contact-list/crm-contact-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ScreenService } from '../../shared/services';

@Component({
  //selector: 'app-crm-contact-list',
  templateUrl: './crm-contact-list.component.html',
  styleUrls: ['./crm-contact-list.component.scss']
})
export class CrmContactListComponent implements OnInit {

  constructor(private screen: ScreenService) {
    this.pinClick = this.pinClick.bind(this);
    this.closePanel = this.closePanel.bind(this);
    this.calculatePin();
    this.screen.changed.subscribe(this.calculatePin.bind(this));
  }

  isPanelOpen: boolean = false;
  isPanelPin: boolean = false;
  isPinEnabled: boolean = false;

  gridData: any[] = [{
    name: 'Robert Reaga',
    status: 1,
    id: 120545,
    products: [
      { productId: 1, productStatus: 1 },
      { productId: 2, productStatus: 2 }
    ],
    manager: 'Sarah Davix',
    organization: 'SV Consult',
    address: '69 Ruthven St #24, Boston, MA 02121, United States of America',
    email: '1@2',
  },{
    name: 'Samuel Browick',
    status: 2,
    id: 120545,
    products: [
      { productId: 1, productStatus: 2 },
      { productId: 2, productStatus: 1 }
    ],
    manager: 'Brett Johnson',
    organization: 'SV Consult',
    address: '69 Ruthven St #24, Boston, MA 02121, United States of America',
    email: '2@2',
  }];

  statuses: any = {
    1: 'New',
    2: 'Active',
  };

  products: any = {
    1: 'CRM System',
    2: 'Task Management',
  };

  productStatuses: any = {
    1: 'Lead',
    2: 'Trial sent'
  };

  panelData: any = this.gridData[0];

  console(message: string) {
    console.log(message);
  }

  rowClick(e) {
      this.panelData = e.data;
      this.isPanelOpen = true;
  }

  closePanel() {
    this.isPanelOpen = false;
  }

  pinClick() {
    this.isPanelPin = !this.isPanelPin;
  };

  calculatePin() {
    this.isPinEnabled = this.screen.sizes['screen-large'] || this.screen.sizes['screen-medium'];
    if(this.isPanelPin && !this.isPinEnabled) {
      this.isPanelPin = false;
    }
  }

  ngOnInit(): void {
  }

}


<div class="view-wrapper">
    <dx-data-grid [dataSource]="dataSource" (onRowClick)="rowClick($event)" class="grid" noDataText="">
        <dxo-search-panel [visible]="true" placeholder="Contact Search">
        </dxo-search-panel>
        <dxo-export [enabled]="true" [allowExportSelectedData]="true"></dxo-export>
        <dxo-toolbar>
            <dxi-item location="before">
                <div class="grid-header">Contact List</div>
            </dxi-item>
            <dxi-item location="before" locateInMenu="auto">
                <dx-drop-down-button
                    [dataSource]="statuses"
                    stylingMode="text"
                    displayExpr="text"
                    keyExpr="status"
                    [width]="160"
                    selectedItemKey=""
                    [useSelectMode]="true"
                    (onSelectionChanged)="filterStatus($event)"
                ></dx-drop-down-button>
            </dxi-item>
            <dxi-item location="after" locateInMenu="auto" widget="dxButton"
                [options]="{ icon: 'plus', text: 'Add Contact', type: 'default', stylingMode: 'outlined'}">
            </dxi-item>
            <dxi-item location="after" locateInMenu="auto" showText="inMenu" widget="dxButton"
                [options]="{text: 'Refresh', icon: 'refresh'}">
            </dxi-item>
            <dxi-item location="after" locateInMenu="auto">
                <div class="separator"></div>
            </dxi-item>
            <dxi-item name="exportButton"></dxi-item>
            <dxi-item location="after" locateInMenu="auto">
                <div class="separator"></div>
            </dxi-item>
            <dxi-item name="columnChooserButton" locateInMenu="auto"></dxi-item>
            <dxi-item name="searchPanel" locateInMenu="auto"></dxi-item>
        </dxo-toolbar>
        <dxo-selection selectAllMode="allPages" showCheckBoxesMode="always" mode="multiple"></dxo-selection>
        <dxo-header-filter [visible]="true"></dxo-header-filter>
        <dxo-column-chooser [enabled]="true"></dxo-column-chooser>
        <dxo-sorting mode="multiple"></dxo-sorting>
        <dxi-column dataField="name" caption="Name" sortOrder="asc" [hidingPriority]="5" [minWidth]="150" cellTemplate="nameTemplate">
            <div *dxTemplate="let s of 'nameTemplate'" class="name-template">
                <div>{{s.data.name}}</div>
                <div class="position">{{s.data.position}}</div>
            </div>
        </dxi-column>
        <dxi-column dataField="company" caption="Company" [hidingPriority]="5" [minWidth]="150"></dxi-column>
        <dxi-column dataField="status" caption="Status" dataType="string" cellTemplate="statusTemplate"
            [hidingPriority]="3" [minWidth]="100">
            <div *dxTemplate="let s of 'statusTemplate'">
                <span class="status status-{{s.data.status.toLowerCase()}}">{{s.data.status}}</span>
            </div>
        </dxi-column>
        <dxi-column dataField="assignedTo" caption="Assigned to" [hidingPriority]="4"></dxi-column>
        <dxi-column dataField="phone" caption="Phone" [customizeText]="customizePhoneCell" [hidingPriority]="2">
        </dxi-column>
        <dxi-column dataField="email" caption="Email" [hidingPriority]="1"></dxi-column>
    </dx-data-grid>

    <div class="panel" [ngClass]="{ 'pin': isPanelPin, 'open': isPanelOpen }">
        <div class="data-wrapper">
            <ng-template [ngIf]="!panelLoading" [ngIfElse]="loading">
                <dx-toolbar>
                    <dxi-item location="before">
                        <div *dxTemplate>
                            <div class="contact-name value">{{panelData.name}}</div>
                        </div>
                    </dxi-item>
                    <dxi-item location="before">
                        <div *dxTemplate>
                            <span class="status status-{{panelData.status | lowercase}}">{{panelData.status}}</span>
                        </div>
                    </dxi-item>
                    <dxi-item location="after" widget="dxButton" [visible]="isPinEnabled"
                        [options]="{ icon: isPanelPin ? 'unpin' : 'pin', onClick: pinClick }">
                    </dxi-item>
                    <dxi-item location="after" widget="dxButton" [options]="{ icon: 'close', onClick: closePanel }">
                    </dxi-item>
                </dx-toolbar>
                <dx-scroll-view class="panel-scroll">
                    <div class="user-info">
                        <div class="photo"
                            [style.backgroundImage]="'url(\'data:image/png;base64,' + panelData.image +'\')'"></div>
                        <div>
                            <div class="title">Company</div>
                            <div class="value">{{panelData.company}}</div>
                            <div class="title">Position</div>
                            <div class="value black">{{panelData.position}}</div>
                            <div class="title">Assigned to</div>
                            <div class="value">{{panelData.manager}}</div>
                        </div>
                    </div>
    
                    <div class="value black">
                        <div><i class="dx-icon dx-icon-tel"></i> <span>{{formatPhone(panelData.phone)}}</span></div>
                        <div><i class="dx-icon dx-icon-email"></i> <span>{{panelData.email}}</span></div>
                        <div><i class="dx-icon dx-icon-home"></i> <span>{{panelData.address}}</span></div>
                    </div>
    
                    <dx-toolbar class="panel-toolbar">
                        <dxi-item location="before" widget="dxButton"
                            [options]="{ icon: 'edit', stylingMode: 'outlined', text: 'Edit', type: 'default' }">
                        </dxi-item>
                        <dxi-item location="after" widget="dxDropDownButton" [options]="{ text: 'Actions', stylingMode: 'contained' }">
                        </dxi-item>
                    </dx-toolbar>
                    <dx-accordion [multiple]="true" [collapsible]="true">
                        <dxi-item title="Opportunities">
                            <div *dxTemplate="let i of 'item'">
                                <div *ngFor="let opportunity of panelData.opportunities" class="opportunities">
                                    <span class="value">{{ opportunity.name }} </span>
                                    <span class="value black">{{ opportunity.price | currency:'USD':'$':'1.0-0' }}</span>
                                    <br>
                                </div>
                            </div>
                        </dxi-item>
                        <dxi-item title="Activities">
                            <app-activities [activities]="panelData.activities"></app-activities>
                        </dxi-item>
                    </dx-accordion>
                </dx-scroll-view>
            </ng-template>
            <ng-template #loading>
                <dx-load-panel [visible]="panelLoading" container=".panel"
                    [position]="{of: '.panel', my: 'center', at: 'center'}"></dx-load-panel>
            </ng-template>
           
        </div>
    </div>
</div>
