// packages/vue/src/pages/analytics-sales-analysis.vue
<template>
  <dx-scroll-view class="view-wrapper-scroll">
    <div class="view-wrapper">
      <toolbar-analytics>Sales Analysis</toolbar-analytics>

      <div class="cards">
        <sales-range-card
          :data="sales"
          :value="visualRange"
          class="sales-range-card"
          @range-changed="onRangeChanged"
        />
        <sales-by-range-card :data="salesByCategory" />
        <sales-performance-card
          :data="salesByDateAndCategory"
          :group-by-periods="groupByPeriods"
          :visual-range="visualRange"
          @performance-period-changed="performancePeriodChange"
        />
      </div>
    </div>
  </dx-scroll-view>
  <dx-load-panel
    container=".view-wrapper"
    :position="{ of: '.dx-drawer-content' }"
    :visible="loading"
    :show-pane="true"
  />
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue';

import { DxDropDownButtonTypes } from 'devextreme-vue/drop-down-button';
import { DxScrollView } from 'devextreme-vue/scroll-view';
import { DxLoadPanel } from 'devextreme-vue/load-panel';
import { formatDate } from 'devextreme/localization';

import {
  getSalesByOrderDate,
  getSalesByCategory,
  getSales,
} from 'dx-template-gallery-data';
import {
  Sales,
  SalesByStateAndCity,
} from '@/types/analytics';
import { analyticsPanelItems } from '@/types/resource';
import ToolbarAnalytics from '@/components/utils/toolbar-analytics.vue';
import SalesRangeCard from '@/components/utils/sales-range-card.vue';
import SalesByRangeCard from '@/components/utils/sales-by-range-card.vue';
import SalesPerformanceCard from '@/components/utils/sales-performance-card.vue';

const sales = ref<Sales | null>(null);
const salesByDateAndCategory = ref<Sales | null>(null);
const salesByCategory = ref<SalesByStateAndCity | null>(null);

const visualRange = ref<[Date, Date]>([]);

const customRange = analyticsPanelItems[5].value.split('/').map((d) => new Date(d)) as [Date, Date];

const groupByPeriods = ['Day', 'Month'];

const loading = ref<boolean>(true);

const performancePeriodChange = async (e: DxDropDownButtonTypes.SelectionChangedEvent) => {
  loading.value = true;
  salesByDateAndCategory.value = await getSalesByOrderDate(e.item.toLowerCase());
  loading.value = false;
};

const onRangeChanged = async (e: { value: [Date, Date] } | [Date, Date]) => {
  const dates = Array.isArray(e) ? e : e.value;
  visualRange.value = dates as [Date, Date];
  loading.value = true;
  salesByCategory.value = await getSalesByCategory(
    ...dates.map((date) => formatDate(date, 'yyyy-MM-dd')),
  );
  loading.value = false;
};

const loadData = async (groupBy: string) => {
  loading.value = true;
  const [startDate, endDate] = analyticsPanelItems[4].value.split('/');

  await Promise.all([
    getSales(startDate, endDate)
      .then((result: Sales) => { sales.value = result; }),
    getSalesByOrderDate(groupBy)
      .then((result: Sales) => { salesByDateAndCategory.value = result; }),
  ]).then(() => { loading.value = false; });
};

onMounted(() => {
  visualRange.value = customRange;
  onRangeChanged(customRange);
  loadData(groupByPeriods[1].toLowerCase());
});
</script>

<style scoped lang="scss">
@use "@/variables" as *;
.view-wrapper {
  padding-top: var(--content-padding);
  padding-bottom: var(--content-padding);
}

.cards  {
  display: grid;
  width: 100%;
  grid-gap: 20px;
  gap: 20px;
  grid-template-columns: repeat(1,100%);

  .sales-range-card :deep(.content) {
    height: auto;
  }
}

@media only screen and (max-width: 900px) {
  .view-wrapper .cards {
    grid-template-columns: repeat(1, 100%);
  }
}

@media only screen and (max-width: 400px) {
  .cards :deep(.card) {
    flex: 1 320px;
  }
}
</style>

// packages/angular/src/app/pages/analytics-sales-analysis/analytics-sales-analysis.component.ts
import { Component, inject, model, OnInit, signal } from '@angular/core';
import { CommonModule, formatDate } from '@angular/common';

import { forkJoin } from 'rxjs';

import { DxScrollViewModule } from 'devextreme-angular/ui/scroll-view';
import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';
import { DxPieChartModule } from 'devextreme-angular/ui/pie-chart';
import { DxChartModule } from 'devextreme-angular/ui/chart';
import { DxRangeSelectorModule } from 'devextreme-angular/ui/range-selector';
import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxDropDownButtonModule } from 'devextreme-angular/ui/drop-down-button';
import { DxLoadPanelModule } from 'devextreme-angular/ui/load-panel';
import { DxDropDownButtonTypes } from 'devextreme-angular/ui/drop-down-button';

import { DataService } from 'src/app/services';
import { ToolbarAnalyticsComponent } from 'src/app/components/utils/toolbar-analytics/toolbar-analytics.component';
import { SalesByRangeCardComponent } from 'src/app/components/utils/sales-by-range-card/sales-by-range-card.component';
import { SalesPerformanceCardComponent } from 'src/app/components/utils/sales-performance-card/sales-performance-card.component';
import { SalesRangeCardComponent } from 'src/app/components/utils/sales-range-card/sales-range-card.component';
import { analyticsPanelItems } from 'src/app/types/resource';
import { Sale, SalesOrOpportunitiesByCategory } from 'src/app/types/analytics';
import { ChartVisualRange } from 'src/app/types/chart-visual-range';

@Component({
  templateUrl: './analytics-sales-analysis.component.html',
  styleUrls: ['./analytics-sales-analysis.component.scss'],
  providers: [DataService],
  imports: [
    DxScrollViewModule,
    DxLoadPanelModule,
    DxButtonModule,
    DxToolbarModule,
    DxPieChartModule,
    DxChartModule,
    DxDropDownButtonModule,
    DxRangeSelectorModule,
    ToolbarAnalyticsComponent,
    CommonModule,
    SalesByRangeCardComponent,
    SalesPerformanceCardComponent,
    SalesRangeCardComponent,
  ],
})
export class AnalyticsSalesAnalysisComponent implements OnInit {
  private service = inject(DataService);

  groupByPeriods = ['Day', 'Month'];

  visualRange = model<ChartVisualRange>({});

  isLoading = signal(true);

  sales = signal<Sale[] | null>(null);

  salesByCategory = signal<SalesOrOpportunitiesByCategory | null>(null);

  salesByDateAndCategory = signal<Sale[] | null>(null);

  customRange = analyticsPanelItems[5].value.split('/').map((d) => new Date(d));

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  onRangeChanged = ({ value: dates }: any) => {
    const [startDate, endDate] = dates.map((date: Date) =>
      formatDate(date, 'yyyy-MM-dd', 'en')
    );

    this.isLoading.set(true);

    this.service.getSalesByCategory(startDate, endDate).subscribe((result) => {
      this.salesByCategory.set(result);
      this.isLoading.set(false);
    });
  };

  selectionChange({ item: period }: DxDropDownButtonTypes.SelectionChangedEvent) {
    this.isLoading.set(true);

    this.service.getSalesByOrderDate(period.toLowerCase()).subscribe((result) => {
      this.salesByDateAndCategory.set(result as Sale[]);
      this.isLoading.set(false);
    });
  }

  loadData = (groupBy: string) => {
    const [startDate, endDate] = analyticsPanelItems[4].value.split('/');

    this.isLoading.set(true);

    forkJoin({
      sales: this.service.getSales(startDate, endDate),
      salesByDateAndCategory: this.service.getSalesByOrderDate(groupBy),
    }).subscribe((data) => {
      this.sales.set(data.sales as Sale[]);
      this.salesByDateAndCategory.set(data.salesByDateAndCategory as Sale[]);
      this.isLoading.set(false);
    });
  };

  ngOnInit(): void {
    this.visualRange.set(this.customRange);
    this.onRangeChanged({ value: this.customRange });
    this.loadData(this.groupByPeriods[1].toLowerCase());
  }
}

<dx-scroll-view class="view-wrapper-scroll">
  <div class="view-wrapper view-wrapper-dashboard">
    <toolbar-analytics titleText="Sales Analysis"> </toolbar-analytics>

    <div class="cards wide">
      <sales-range-card
        [data]="sales()"
        [(visualRange)]="visualRange"
        (salesRangeChanged)="onRangeChanged($event)"
      ></sales-range-card>

      <sales-by-range-card [data]="salesByCategory()"></sales-by-range-card>

      <sales-performance-card
        [groupByPeriods]="groupByPeriods"
        [salesByDateAndCategory]="salesByDateAndCategory()"
        [visualRange]="visualRange()"
        (performancePeriodChanged)="selectionChange($event)"
      ></sales-performance-card>
    </div>
  </div>
</dx-scroll-view>
<dx-load-panel
  container=".view-wrapper"
  [position]="{ of: '.content' }"
  [visible]="isLoading()"
  [showPane]="true"
></dx-load-panel>
