// packages/react/src/components/agenda/agenda-list-item.tsx
import './agenda-list-item.scss';
import React from 'react';
import { Duration } from 'luxon';

const getFormattedDuration = ({ startDate, endDate }) => {
  return Duration.fromMillis(endDate - startDate)
    .rescale()
    .toFormat("h'h' m'm'");
};

const TimeContent = ({ appointment }) => {
  const start = appointment.startDate.toLocaleTimeString(undefined, {
    hour: 'numeric',
    minute: 'numeric',
    hour12: false
  });
  return <div className='time'>
    <div className='start'>{start}</div>
    <div className='duration'>{getFormattedDuration(appointment)}</div>
  </div>;
};

export const AgendaListItem = ({ item, resources }) => {
  return <div className='agenda-list-item'>
    <div className='time'>
      <TimeContent appointment={item} />
    </div>
    <div className='description'>
      <div className='description-title'>
        {item.text}
      </div>
      <div className='description-resource'>
        {resources[item.calendarId]?.text}
      </div>
    </div>
  </div>;
};

// packages/angular/src/app/components/library/agenda-list-item/agenda-list-item.component.ts
import {
  Component, Input, NgModule, OnInit,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxListModule } from 'devextreme-angular/ui/list';
import { Duration } from 'luxon';
import { ApplyPipeModule } from "../../../pipes/apply.pipe";

@Component({
  selector: 'agenda-list-item',
  template: `
    <div class='agenda-list-item'>
      <div class='time'>
        <div class='start'>{{getStart| apply: appointment}}</div>
        <div class='duration'>{{ getFormattedDuration | apply: appointment}}</div>
      </div>
      <div class='description'>
        <div class='description-title'>
          {{appointment.text}}
        </div>
        <div class='description-resource'>
          {{resources[appointment.calendarId]?.text}}
        </div>
      </div>
    </div>
`,
  styleUrls: ['./agenda-list-item.component.scss'],
})
export class AgendaListItemComponent implements OnInit {
  @Input() appointment: Record<string, any> = {};

  @Input() resources: Record<string, any> = [];

  ngOnInit(): void {
    console.log('----appointment------>', this.appointment)
  }

  getFormattedDuration = ({ startDate, endDate }) => {
    return Duration.fromMillis(endDate - startDate)
      .rescale()
      .toFormat("h'h' m'm'");
  };

  getStart = (appointment) => {
    return appointment.startDate.toLocaleTimeString(undefined, {
      hour: 'numeric',
      minute: 'numeric',
      hour12: false
    });
  };
}

@NgModule({
  imports: [
    CommonModule,
    DxListModule,
    ApplyPipeModule,
  ],
  declarations: [AgendaListItemComponent],
  exports: [AgendaListItemComponent],
})
export class AgendaListItemModule {}
