// packages/react/src/components/library/task-list-gantt/TaskListGantt.tsx
import React from 'react';

import Gantt, { Tasks, Column, Toolbar, Item, Validation, Editing } from 'devextreme-react/gantt';

import { PlanningProps } from '../../../types/task';

import './TaskListGantt.scss';

export const TaskListGantt = React.forwardRef<Gantt, PlanningProps>(({ dataSource }, ref) => {
  return (
    <div className='gantt'>
      <Gantt ref={ref} taskListWidth={500} scaleType='weeks' height={700}>
        <Tasks dataSource={dataSource} startExpr='startDate' endExpr='dueDate' titleExpr='text' />
        <Column dataField='text' caption='Subject' width={300} />
        <Column dataField='startDate' caption='Start Date' dataType='date' sortOrder='asc' />
        <Column dataField='dueDate' caption='Due Date' dataType='date' />

        <Toolbar>
          <Item name='undo' />
          <Item name='redo' />
          <Item name={'separator' as any} />
          <Item name='collapseAll' />
          <Item name='expandAll' />
          <Item name={'separator' as any} />
          <Item name='addTask' />
          <Item name='deleteTask' />
          <Item name={'separator' as any} />
          <Item name='zoomIn' />
          <Item name='zoomOut' />
        </Toolbar>

        <Validation autoUpdateParentTasks />
        <Editing enabled />
      </Gantt>
    </div>
  );
});

// packages/angular/src/app/pages/planning-task-list/task-list-gantt/task-list-gantt.component.ts
import {
  Component, NgModule, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { DxGanttModule } from 'devextreme-angular/ui/gantt';
import { Task } from 'src/app/shared/types/task';

@Component({
  selector: 'task-list-gantt',
  templateUrl: './task-list-gantt.component.html',
  styleUrls: ['./task-list-gantt.component.scss'],
})
export class TaskListGanttComponent {
  @Input() dataSource: Task[];

  constructor(private router: Router) {
  }

  navigateToDetails = () => {
    this.router.navigate(['/planning-task-details']);
  };
}

@NgModule({
  imports: [
    DxGanttModule,

    CommonModule,
  ],
  providers: [],
  exports: [TaskListGanttComponent],
  declarations: [TaskListGanttComponent],
})
export class TaskListGanttModule { }

<dx-gantt
  *ngIf="!isLoading"
  [taskListWidth]="500"
  scaleType="weeks"
  (onTaskClick)="navigateToDetails()"
  [height]="700"
>
  <dxo-tasks
    [dataSource]="dataSource"
    startExpr="startDate"
    endExpr="dueDate"
    titleExpr="text"
  >
  </dxo-tasks>

  <dxi-column dataField="text" caption="Subject" [width]="300"></dxi-column>
  <dxi-column
    dataField="startDate"
    caption="Start Date"
    dataType="date"
    sortOrder="asc"
  ></dxi-column>
  <dxi-column
    dataField="dueDate"
    caption="Due Date"
    dataType="date"
  ></dxi-column>

  <dxo-toolbar>
    <dxi-item name="undo"></dxi-item>
    <dxi-item name="redo"></dxi-item>
    <dxi-item name="separator"></dxi-item>
    <dxi-item name="collapseAll"></dxi-item>
    <dxi-item name="expandAll"></dxi-item>
    <dxi-item name="separator"></dxi-item>
    <dxi-item name="addTask"></dxi-item>
    <dxi-item name="deleteTask"></dxi-item>
    <dxi-item name="separator"></dxi-item>
    <dxi-item name="zoomIn"></dxi-item>
    <dxi-item name="zoomOut"></dxi-item>
  </dxo-toolbar>

  <dxo-validation [autoUpdateParentTasks]="true"></dxo-validation>
  <dxo-editing [enabled]="true"></dxo-editing>
</dx-gantt>

<dx-load-panel
  [visible]="isLoading"
  [showPane]="false"
  container=".content"
  [position]="{ of: '.content' }"
></dx-load-panel>
