// packages/angular/src/app/components/library/app-header/app-header.component.ts
import {
  Component, Input, Output, EventEmitter, OnInit, inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';

import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';

import { UserPanelComponent } from '../user-panel/user-panel.component';
import { AuthService, IUser } from 'src/app/services';
import { ThemeSwitcherComponent } from 'src/app/components/library/theme-switcher/theme-switcher.component';

@Component({
  selector: 'app-header',
  templateUrl: 'app-header.component.html',
  styleUrls: ['./app-header.component.scss'],
  imports: [
      CommonModule,
      DxButtonModule,
      DxToolbarModule,
      ThemeSwitcherComponent,
      UserPanelComponent,
  ]
})

export class AppHeaderComponent implements OnInit {
  @Output()
  menuToggle = new EventEmitter<boolean>();

  @Input()
  menuToggleEnabled = false;

  @Input()
  title!: string;

  private authService = inject(AuthService);

  user: IUser | null = { email: '' };

  userMenuItems = [
  {
    text: 'Logout',
    icon: 'runner',
    onClick: () => {
      this.authService.logOut();
    },
  }];

  ngOnInit() {
    this.authService.getUser().then((e) => this.user = e.data);
  }

  toggleMenu = () => {
    this.menuToggle.emit();
  };
}

<header>
  <dx-toolbar class="header-toolbar">
    @if (menuToggleEnabled) {
      <dxi-toolbar-item
        location="before"
        widget="dxButton"
        cssClass="menu-button"
        [options]="{
        icon: 'menu',
        stylingMode: 'text',
        onClick: toggleMenu
      }"
      >
      </dxi-toolbar-item>
    }
    @if (title) {
      <dxi-toolbar-item
        location="before"
        cssClass="header-title"
        [text]="title"
      >
      </dxi-toolbar-item>
    }

    <dxi-toolbar-item
      location="after"
      widget="dxTextBox"
      locateInMenu="auto"
      cssClass="global-search-box"
      [options]="{
        stylingMode: 'filled',
        mode: 'search',
        placeholder: 'Search',
        width: 180
      }"
    >
    </dxi-toolbar-item>
    <dxi-toolbar-item location="after" locateInMenu="never">
      <div *dxTemplate>
        <theme-switcher></theme-switcher>
      </div>
    </dxi-toolbar-item>

    <dxi-toolbar-item location="after">
      <div *dxTemplate>
        <div class="messages">
          <dx-button icon="belloutline" stylingMode="text"> </dx-button>
          <div class="dx-badge"> 4 </div>
        </div>
      </div>
    </dxi-toolbar-item>

    <dxi-toolbar-item location="after" locateInMenu="auto" menuItemTemplate="menuItem">
      <div *dxTemplate>
        <user-panel
          [user]="user"
          [menuItems]="userMenuItems"
          menuMode="context"
        ></user-panel>
      </div>
    </dxi-toolbar-item>
    <div *dxTemplate="let data of 'menuItem'">
      <user-panel
        [user]="user"
        [menuItems]="userMenuItems"
        menuMode="list"
      ></user-panel>
    </div>
  </dx-toolbar>
</header>

// packages/react/src/components/library/app-header/AppHeader.tsx
import React from 'react';
import Toolbar, { Item } from 'devextreme-react/toolbar';
import TextBox from 'devextreme-react/text-box';
import Button from 'devextreme-react/button';

import { Template } from 'devextreme-react/core/template';

import { UserPanel } from '../user-panel/UserPanel';
import { ThemeSwitcher } from '../theme-switcher/ThemeSwitcher';

import type { AppHeaderProps } from '../../../types';

import './AppHeader.scss';

export const AppHeader = ({ menuToggleEnabled, title, toggleMenu, className }: AppHeaderProps) => {
  return (
    <header className={`header-component ${className}`}>
      <Toolbar className='header-toolbar'>
        <Item visible={menuToggleEnabled} location='before' widget='dxButton' cssClass='menu-button'>
          <Button icon='menu' stylingMode='text' onClick={toggleMenu} />
        </Item>
        <Item location='before' cssClass='header-title' text={title} visible={!!title} />
        <Item location='after' locateInMenu='auto' cssClass='global-search-box'>
          <TextBox placeholder='Search' width={180} mode='search' stylingMode='filled' />
        </Item>
        <Item location='after' locateInMenu='never'>
          <ThemeSwitcher />
        </Item>
        <Item location='after'>
          <div className='messages'>
            <Button icon='belloutline' stylingMode='text' />
            <div className='dx-badge'>
              4
            </div>
          </div>
        </Item>
        <Item location='after' locateInMenu='auto' menuItemTemplate='userPanelTemplate'>
          <UserPanel menuMode='context' />
        </Item>
        <Template name='userPanelTemplate'>
          <UserPanel menuMode='list' />
        </Template>
      </Toolbar>
    </header>
  );
};
