// packages/angular/src/app/components/utils/leads-ticker/leads-ticker.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TickerCardComponent } from 'src/app/components/library/ticker-card/ticker-card.component';

@Component({
    selector: 'leads-ticker',
    templateUrl: 'leads-ticker.component.html',
    imports: [
      CommonModule,
      TickerCardComponent,
    ],
})
export class LeadsTickerComponent {
}

<ticker-card
  titleText="Leads"
  total="51"
  [percentage]="8.5"
  tone="info"
  icon="datapie"
></ticker-card>

// packages/react/src/components/utils/leads-ticker/LeadsTicker.tsx
import React from 'react';

import { TickerCard } from '../../library/ticker-card/TickerCard';
import { TickerProps } from '../../../types/analytics';

export const LeadsTicker = ({ value }: TickerProps) =>
  <TickerCard
    icon='datapie'
    tone='info'
    title='Leads'
    value={value}
    percentage={8.5}
  />;
