// packages/vue/src/components/utils/toolbar-form.vue
<template>
  <dx-toolbar>
    <dx-toolbar-item location="before">
      <span class="dx-form-group-caption">Details</span>
    </dx-toolbar-item>
    <dx-toolbar-item
      location="after"
      locate-in-menu="after"
      :visible="!props.isEditing"
    >
      <dx-button
        text="Edit"
        icon="edit"
        styling-mode="outlined"
        type="default"
        @click="emit('editToggled')"
      />
    </dx-toolbar-item>
    <dx-toolbar-item
      location="after"
      locate-in-menu="after"
      :visible="props.isEditing"
    >
      <dx-button
        text="Save"
        styling-mode="outlined"
        type="default"
        @click="emit('saveClicked', $event)"
      />
    </dx-toolbar-item>
    <dx-toolbar-item
      location="after"
      locate-in-menu="after"
      :visible="props.isEditing"
    >
      <dx-button
        text="Cancel"
        @click="emit('editCanceled')"
        styling-mode="text"
      />
    </dx-toolbar-item>
  </dx-toolbar>
</template>

<script setup lang="ts">
import {
  DxToolbar,
  DxItem as DxToolbarItem,
} from 'devextreme-vue/toolbar';
import { DxButton } from 'devextreme-vue/button';

const props = withDefaults(defineProps<{
  isEditing: boolean,
}>(), {
  isEditing: false,
});

const emit = defineEmits(['editCanceled', 'saveClicked', 'editToggled']);
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

.dx-toolbar {
  margin-bottom: $toolbar-margin-bottom;
}
</style>

// packages/react/src/components/toolbar-form/ToolbarForm.tsx
import React from 'react';

import Toolbar, { Item } from 'devextreme-react/toolbar';
import Button from 'devextreme-react/button';

import './ToolbarForm.scss';

export const ToolbarForm = ({ editing, toggleEditing }) => {
  return (
    <Toolbar className='toolbar-form'>
      <Item location='before'>
        <span className='dx-form-group-caption'>Details</span>
      </Item>
      <Item location='after' locateInMenu='after' visible={!editing}>
        <Button text='Edit' icon='edit' stylingMode='outlined' type='default' onClick={toggleEditing} />
      </Item>
      <Item location='after' locateInMenu='after' visible={editing}>
        <Button text='Save' stylingMode='outlined' type='default' onClick={toggleEditing} />
      </Item>
      <Item location='after' locateInMenu='after' visible={editing}>
        <Button text='Cancel' stylingMode='text' onClick={toggleEditing} />
      </Item>
    </Toolbar>
  );
};
