// packages/vue/src/components/library/task-kanban-card.vue
<template>
  <div
    class="card dx-theme-text-color dx-theme-background-color"
    @click="navigateToDetails()"
  >
    <div
      class="card-wrapper"
      :class="`priority-${ task.priority.toLowerCase() }`"
    >
      <div class="card-priority" />
      <dx-button
        icon="edit"
        @click="notifyByCard"
      />
      <div class="card-content">
        <div class="card-subject dx-theme-text-color">
          {{ task.text }}
        </div>
        <div class="card-data">
          <span class="priority">{{ task.priority }}</span>
          <span class="date dx-theme-text-color">{{
            formatDate(task.dueDate)
          }}</span>
        </div>
        <div class="card-assignee">
          <span class="company dx-theme-text-color">{{ task.company }}</span>
          <avatar :data-letters="getAvatarText(task.owner)" />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Task } from '@/types/task';
import notify from 'devextreme/ui/notify';
import { DxButton } from 'devextreme-vue/button';
import { formatDate } from '@/utils/formatters';
import { router } from '@/router';
import Avatar from '@/components/library/user-avatar.vue';

const props = withDefaults(defineProps<{
  task: Task | null
}>(), {
  task: () => null,
});

const getAvatarText = (name: string) => name.split(' ').map((namePart) => namePart[0]).join('');

const notifyByCard = (event: {event: Event}) => {
  event.event.stopPropagation();
  notify(`Edit '${props.task?.text}' card event`);
};

const navigateToDetails = () => {
  router.push('/planning-task-details');
};
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

$low-priorety-color: #dfb32f;
$normal-priorety-color: #6fbaca;
$high-priorety-color: #d9534f;

@mixin priority($priorety-color) {
  .card-priority {
    background: $priorety-color;
  }

  span.priority {
    color: $priorety-color;
  }
}

.card {
  position: relative;
  box-sizing: border-box;
  cursor: pointer;
  display: block;
}

:deep(.card-wrapper) {
  padding: 10px;

  .dx-button {
    position: absolute;
    right: 10px;
    font-size: 18px;
    opacity: 0.87;
  }

  &.priority-low {
    @include priority($low-priorety-color);
  }

  &.priority-normal {
    @include priority($normal-priorety-color);
  }

  &.priority-high {
    @include priority($high-priorety-color);
  }

  .card-content {
    padding-left: 14px;

    span.priority {
      font-weight: 500;
      font-size: 12px;
      line-height: 14px;
    }

    span.date {
      padding-left: 8px;
      font-size: 12px;
      line-height: 14px;
      opacity: 0.87;
    }
  }

  .card-subject {
    font-weight: 500;
    font-size: 14px;
    line-height: 16px;
    padding-right: 40px;
  }

  .card-assignee {
    padding-top: 14px;
    font-size: 12px;
    line-height: 14px;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .card-priority {
    position: absolute;
    top: 10px;
    bottom: 10px;
    left: 10px;
    width: 4px;
  }
}
</style>

// packages/angular/src/app/components/library/task-kanban-card/task-kanban-card.component.ts
import {Component, inject, Input} from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { DxButtonModule, DxToastModule } from 'devextreme-angular';
import notify from 'devextreme/ui/notify';

import { Task } from 'src/app/types/task';
import { UserAvatarComponent } from 'src/app/components/library/user-avatar/user-avatar.component';

@Component({
    selector: 'task-kanban-card',
    templateUrl: './task-kanban-card.component.html',
    styleUrls: ['./task-kanban-card.component.scss'],
    imports: [
      DxButtonModule,
      DxToastModule,
      CommonModule,
      UserAvatarComponent,
    ],
})
export class TaskKanbanCardComponent {
  private router = inject(Router);

  @Input() task: Task;

  getAvatarText = (name: string) => name.split(' ').map((name) => name[0]).join('');

  notify = (e) => {
    e.event.stopPropagation();
    notify(`Edit '${this.task.text}' card event`);
  };

  navigateToDetails = () => {
    this.router.navigate(['/planning-task-details']);
  };
}


<div
  class="card dx-theme-text-color dx-theme-background-color"
  (click)="navigateToDetails()"
>
  <div class="card-wrapper" class="priority-{{ task.priority | lowercase }}">
    <div class="card-priority"></div>
    <dx-button
      icon="edit"
      stylingMode="text"
      (onClick)="notify($event)"
    ></dx-button>
    <div class="card-content">
      <div class="card-subject dx-theme-text-color">{{ task.text }}</div>
      <div class="card-data">
        <span class="priority">{{ task.priority }}</span>
        <span class="date dx-theme-text-color">{{
          task.dueDate | date: 'MM/dd/yyyy'
        }}</span>
      </div>
      <div class="card-assignee">
        <span class="company dx-theme-text-color">{{ task.company }}</span>
        <user-avatar [dataLetters]="getAvatarText(task.owner)"></user-avatar>
      </div>
    </div>
  </div>
</div>
