// packages/angular/src/app/components/library/pictured-item-select-box/pictured-item-select-box.component.ts
import {
  Component, EventEmitter, Input, Output,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxSelectBoxModule, DxTextBoxModule } from 'devextreme-angular';

@Component({
    selector: 'pictured-item-select-box',
    templateUrl: 'pictured-item-select-box.component.html',
    styleUrls: ['./pictured-item-select-box.component.scss'],
    imports: [
      DxSelectBoxModule,
      DxTextBoxModule,
      CommonModule,
    ],
})
export class PicturedItemSelectBoxComponent {
  @Input() value: Record<string, unknown>;

  @Input() label = '';

  @Input() items: Record<string, unknown>[] = [];

  @Output() valueChange = new EventEmitter<string>();
}

<dx-select-box
  class="pictured-item-select-box"
  [label]="label"
  [value]="value"
  (onValueChanged)="valueChange.emit($event.value)"
  [items]="items"
  valueExpr="name"
  stylingMode="filled"
  labelMode="hidden"
  width="100%"
  fieldTemplate="field"
  [dropDownOptions]="{
    wrapperAttr: { class: 'pictured-item-select-box-dropdown' }
  }"
>
  <div *dxTemplate="let data of 'field'" class="pictured-item-select-field">
    <img
      [alt]="data.name"
      class="pictured-item-image"
      src="data:image/png;base64,{{ data.image }}"
    />
    <dx-text-box
      [hoverStateEnabled]="false"
      [inputAttr]="{ class: 'pictured-item-editor-input' }"
      [readOnly]="true"
      [value]="data.name"
    >
    </dx-text-box>
  </div>
  <div *dxTemplate="let data of 'item'">
    <img
      [alt]="data.name"
      class="pictured-item-image"
      height="20px"
      src="data:image/png;base64,{{ data.image }}"
    />
    {{ data.name }}
  </div>
</dx-select-box>

// packages/react/src/components/pictured-item-select-box/PicturedItemSelectBox.tsx
import './PicturedItemSelectBox.scss';
import React from 'react';
import SelectBox from 'devextreme-react/select-box';
import TextBox from 'devextreme-react/text-box';

const fieldRender = (data) => {
  return <div
    className='pictured-item-select-field'>
    <img alt={data.name}
      className='pictured-item-image'
      src='data:image/png;base64,{{data.image}}'
    />
    <TextBox
      hoverStateEnabled={false}
      inputAttr={{ class: 'pictured-item-editor-input' }}
      readOnly
      value={data.name}
    />
  </div>;
};

const ItemRender = (data) => {
  return <div>
    <img alt='data.name'
      className='pictured-item-image'
      height='20px'
      src='data:image/png;base64,{{data.image}}' />
    {data.name}
  </div>;
};

export const PicturedItemSelectBox = ({ value, label = '', items = [], onValueChange }) => {
  return <SelectBox
    className='pictured-item-select-box'
    value={value}
    onValueChange={onValueChange}
    label={label}
    items={items}
    itemRender={ItemRender}
    valueExpr='name'
    stylingMode='outlined'
    labelMode='hidden'
    width='100%'
    fieldTemplate={fieldRender}
    dropDownOptions={{ wrapperAttr: { class: 'pictured-item-select-box-dropdown' } }}
  />;
};
