// packages/react/src/components/card-activities/CardActivities.tsx
import React from 'react';

import List from 'devextreme-react/list';
import Menu from 'devextreme-react/menu';

import { formatDate } from 'devextreme/localization';

import classNames from 'classnames';

import { Activities, Activity } from '../../shared/types/card-activities';
import { withLoadPanel } from '../../shared/utils/withLoadPanel';

import './CardActivities.scss';

const activityMenuItems = [{
  icon: 'overflow',
  items: [
    { text: 'View details' },
    { text: 'Delete' },
  ],
}];

const listItemRender = (item: Activity) => {
  return (
    <div className='activity'>
      <div className='name'>{item.name}</div>
      <div className='date by'>
        <span>{formatDate(new Date(item.date), 'MM/dd/yyyy')}</span>
        <span className='by-span'>by</span>
        <span>{item.manager}</span>
      </div>
      <Menu className='overflow-menu' items={activityMenuItems} />
    </div>
  );
};

const ActivitiesList = ({ activities }) => {
  return (
    <List className='activities-list' dataSource={activities} scrollingEnabled={false} itemRender={listItemRender} />
  );
};

const ActivitiesWithLoadPanel = withLoadPanel(ActivitiesList);

export const CardActivities = ({ activities }: { activities?: Activities }) => (
  <div className={classNames({ 'card-activities': true, load: !activities })}>
    <ActivitiesWithLoadPanel
      activities={activities}
      loading={!activities}
      panelProps={{
        container: '.card-activities',
        position: { of: '.card-activities' }
      }}
    />
  </div>
);

// packages/angular/src/app/shared/components/card-activities/card-activities.component.ts
import { CommonModule } from '@angular/common';
import {
  Component, NgModule, Input, SimpleChanges, OnInit, OnChanges,
} from '@angular/core';
import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxListModule } from 'devextreme-angular/ui/list';
import { DxLoadPanelModule } from 'devextreme-angular/ui/load-panel';
import { DxMenuModule } from 'devextreme-angular/ui/menu';
import { Activities } from 'src/app/shared/types/activities';

@Component({
  selector: 'card-activities',
  templateUrl: './card-activities.component.html',
  styleUrls: ['./card-activities.component.scss'],
})
export class CardActivitiesComponent implements OnInit, OnChanges {
  @Input() activities: Activities;

  @Input() showBy? = false;

  isLoading = true;

  activityMenuItems: Array<{ icon: string, items: Array<{ text: string }> }> = [{ 
    icon: 'overflow',
    items: [
      { text: 'View details' },
      { text: 'Delete' },
    ]}
  ];

  ngOnInit() {
    this.isLoading = !this.activities;
  }

  ngOnChanges(changes: SimpleChanges) {
    this.isLoading = !changes.activities.currentValue;
  }
}

@NgModule({
  imports: [
    DxListModule,
    DxButtonModule,
    DxLoadPanelModule,
    DxMenuModule,

    CommonModule,
  ],
  declarations: [CardActivitiesComponent],
  exports: [CardActivitiesComponent],
})
export class CardActivitiesModule { }

<div id="activities-list" [ngClass]="!isLoading ? 'load' : null">
  <div *ngIf="isLoading; then displayLoadPanel; else displayActivities"></div>

  <ng-template #displayActivities>
    <dx-list
      class="activities-list"
      [items]="activities"
      [scrollingEnabled]="false"
    >
      <div *dxTemplate="let item of 'item'">
        <div class="activity">
          <div class="name">{{ item.name }}</div>
          <div class="date" [ngClass]="{ by: showBy }">
            <span>{{ item.date | date: "MM/dd/yyyy" }}</span>
            <span *ngIf="showBy">by</span>
            <span>{{ item.manager }}</span>
          </div>
          <dx-button icon="overflow"></dx-button>
        </div>
      </div>
    </dx-list>
  </ng-template>

  <ng-template #displayLoadPanel>
    <dx-load-panel
      container="#activities-list"
      [position]="{ of: '#activities-list' }"
      [visible]="isLoading"
    ></dx-load-panel>
  </ng-template>
</div>
