// packages/vue/src/components/task-form.vue
<template>
  <div id="task-form">
    <dx-toolbar v-if="!isCreateMode">
      <dx-toolbar-item location="before">
        <span class="dx-form-group-caption">Details</span>
      </dx-toolbar-item>
      <dx-toolbar-item
        location="after"
        locate-in-menu="after"
        :visible="!isEditing"
      >
        <dx-button
          text="Edit"
          icon="edit"
          styling-mode="outlined"
          type="default"
          @click="handleEditClick"
        />
      </dx-toolbar-item>
      <dx-toolbar-item
        location="after"
        locate-in-menu="after"
        :visible="isEditing"
      >
        <dx-button
          text="Save"
          styling-mode="outlined"
          type="default"
          @click="handleSaveClick"
        />
      </dx-toolbar-item>
      <dx-toolbar-item
        location="after"
        locate-in-menu="after"
        :visible="isEditing"
      >
        <dx-button
          text="Cancel"
          @click="handleCancelClick"
          styling-mode="text"
        />
      </dx-toolbar-item>
    </dx-toolbar>
    <load-component
      :is-loading="isLoading"
      :container-selector="'#task-form'"
      :show-content="!!props.data"
    >
      <dx-form
        :form-data="data"
        class="plain-styled-form"
        :class="{'view-mode': !isEditing}"
      >
        <dx-form-item
          v-if="isCreateMode"
          :col-span="2"
        >
          <form-textbox
            label="Subject"
            v-model="data.text"
            :is-editing="isEditing"
          />
        </dx-form-item>
        <dx-form-group-item
          :col-count="2"
          :col-count-by-screen="colCountByScreen"
        >
          <dx-form-item css-class="accent">
            <form-textbox
              label="Company"
              v-model="data.company"
              :is-editing="isEditing"
            />
          </dx-form-item>

          <dx-form-item css-class="accent">
            <form-textbox
              label="Assigned to"
              v-model="data.owner"
              :is-editing="isEditing"
            />
          </dx-form-item>

          <dx-form-item>
            <dx-select-box
              label="Priority"
              v-model="data.priority"
              :items="taskPriorityList"
              :read-only="!isEditing"
              field-template="field"
              item-template="item"
              v-bind="formSelectBoxProps"
            >
              <template #field>
                <div class="task-editor-field">
                  <status-indicator
                    :is-field="true"
                    :show-bar="true"
                    :value="data.priority"
                  />
                </div>
              </template>
              <template #item="item">
                <status-indicator
                  :show-bar="true"
                  :value="item.data"
                />
              </template>
            </dx-select-box>
          </dx-form-item>

          <dx-form-item>
            <dx-select-box
              label="Status"
              v-model="data.status"
              :items="taskStatusList"
              :read-only="!isEditing"
              field-template="field"
              item-template="item"
              v-bind="formSelectBoxProps"
            >
              <template #field>
                <div class="task-editor-field">
                  <status-indicator
                    :is-field="true"
                    :value="data.status"
                  />
                </div>
              </template>
              <template #item="item">
                <status-indicator
                  :value="item.data"
                />
              </template>
            </dx-select-box>
          </dx-form-item>

          <dx-form-item>
            <form-datebox
              label="Start Date"
              v-model="data.startDate"
              :is-editing="isEditing"
            />
          </dx-form-item>

          <dx-form-item>
            <form-datebox
              label="Due Date"
              v-model="data.dueDate"
              :is-editing="isEditing"
            />
          </dx-form-item>
        </dx-form-group-item>
        <dx-form-item>
          <dx-text-area
            label="Details"
            styling-mode="filled"
            v-model="data.description"
          />
        </dx-form-item>
      </dx-form>
    </load-component>
  </div>
</template>
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import StatusIndicator from '@/components/status-indicator.vue';
import { DxButton } from 'devextreme-vue/button';
import { DxTextArea } from 'devextreme-vue/text-area';
import {
  taskPriorityList, Task, taskStatusList,
} from '@/types/task';
import {
  DxToolbar,
  DxItem as DxToolbarItem,
} from 'devextreme-vue/toolbar';
import {
  DxForm,
  DxItem as DxFormItem,
  DxGroupItem as DxFormGroupItem,
} from 'devextreme-vue/form';
import { DxSelectBox } from 'devextreme-vue/select-box';
import { ClickEvent } from 'devextreme/ui/button';
import LoadComponent from '@/components/load-component.vue';
import FormTextbox from '@/components/form-textbox.vue';
import FormDatebox from '@/components/form-datebox.vue';
import { formSelectBoxProps } from '@/shared/form-editor-config';

const props = withDefaults(defineProps<{
  isCreateMode?: boolean,
  isLoading?: boolean,
  data?: Task,
  contentByScreen: { xs: number, sm: number },
  validationGroup?: string,
}>(), {
  data: undefined,
  isLoading: false,
  isCreateMode: false,
  validationGroup: undefined,
});

const isEditing = ref(props.isCreateMode);
const data = ref(props.data);
const colCountByScreen = computed(() => ({
  xs: props.contentByScreen.xs,
  sm: props.contentByScreen.sm,
  md: 2,
  lg: 2,
}));

watch(
  () => props.data,
  (newValue) => {
    data.value = newValue;
  },
);

let dataSaved: Task;

function handleEditClick() {
  dataSaved = { ...data.value };
  isEditing.value = true;
}

function handleSaveClick({ validationGroup }: ClickEvent) {
  if (validationGroup.validate().isValid) {
    isEditing.value = false;
  }
}

function handleCancelClick() {
  if (dataSaved) {
    data.value = dataSaved;
  }

  isEditing.value = false;
}
</script>
<style scoped lang="scss">
@use "@/variables.scss" as *;

#task-form {
  min-height: 250px;

  .dx-toolbar {
    margin-bottom: $toolbar-margin-bottom;
  }
}
</style>

// packages/angular/src/app/pages/planning-task-details/task-form/task-form.component.ts
import {
  Component, NgModule, Input, SimpleChanges, OnChanges,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxFormModule,
  DxLoadPanelModule,
  DxSelectBoxModule,
  DxTextBoxModule,
  DxTextAreaModule,
  DxToolbarModule,
  DxValidatorModule,
  DxValidationGroupModule,
} from 'devextreme-angular';
import {
  StatusIndicatorModule,
  FormItemDateModule,
  FormTextboxModule,
} from 'src/app/shared/components';
import { taskPriorityList, taskStatusList } from 'src/app/shared/types/task';
import { Task } from 'src/app/shared/types/task';

@Component({
  selector: 'task-form',
  templateUrl: './task-form.component.html',
  styleUrls: ['./task-form.component.scss'],
})
export class TaskFormComponent implements OnChanges {
  @Input() task: Task;

  @Input() contentByScreen: { xs: number, sm: number }

  isEditing = false;

  statusList = taskStatusList;

  priorityList = taskPriorityList;

  isLoading = true;

  ngOnChanges(changes: SimpleChanges) {
    this.isLoading = !changes.task.currentValue;

    if (!this.isLoading) {
      this.isEditing = !this.task?.text;
    }
  }

  handleEditClick = () => {
    this.isEditing = true;
  };

  handleSaveClick = (e) => {
    if(!e.validationGroup.validate().isValid) return;
    this.isEditing = false;
  };

  handleCancelClick = () => {
    this.isEditing = false;
  };
}

@NgModule({
  imports: [
    DxButtonModule,
    DxFormModule,
    DxLoadPanelModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    DxTextAreaModule,
    DxToolbarModule,
    DxValidatorModule,
    DxValidationGroupModule,

    FormTextboxModule,
    StatusIndicatorModule,
    FormItemDateModule,
    CommonModule,
  ],
  providers: [],
  exports: [TaskFormComponent],
  declarations: [TaskFormComponent],
})
export class TaskFormModule { }

<div id="task-form">
  <dx-validation-group>
    <dx-toolbar [visible]="!!task?.text">
      <dxi-item location="before"
        ><span class="dx-form-group-caption">Details</span>
      </dxi-item>
      <dxi-item location="after" locateInMenu="after" [visible]="!isEditing">
        <dx-button
          text="Edit"
          icon="edit"
          stylingMode="outlined"
          type="default"
          (onClick)="handleEditClick()"
        ></dx-button>
      </dxi-item>
      <dxi-item location="after" locateInMenu="after" [visible]="isEditing">
        <dx-button
          text="Save"
          stylingMode="outlined"
          type="default"
          (onClick)="handleSaveClick($event)"
        ></dx-button>
      </dxi-item>
      <dxi-item location="after" locateInMenu="after" [visible]="isEditing">
        <dx-button
          text="Cancel"
          (onClick)="handleCancelClick()"
          stylingMode="text"
        ></dx-button>
      </dxi-item>
    </dx-toolbar>

    <dx-form *ngIf="!isLoading"
            class="plain-styled-form"
            [class.view-mode]="!isEditing"
            labelMode="floating"
    >
      <dxi-item [visible]="!task.text">
        <div *dxTemplate>
          <form-textbox label="Subject"
              [(value)]="task.text"
              [isEditing]="isEditing"
          ></form-textbox>
        </div>
      </dxi-item>
      <dxi-item itemType="group">
        <dxo-col-count-by-screen [xs]="contentByScreen.xs" [sm]="contentByScreen.sm" [md]="2" [lg]="2"></dxo-col-count-by-screen>
        <dxi-item cssClass="accent">
          <div *dxTemplate>
            <form-textbox label="Company"
                        [(value)]="task.company"
                        [isEditing]="isEditing"
            ></form-textbox>
        </div>
        </dxi-item>

        <dxi-item cssClass="accent">
          <div *dxTemplate>
            <form-textbox label="Assigned to"
                        [(value)]="task.owner"
                        [isEditing]="isEditing"
            ></form-textbox>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <dx-select-box label="Priority"
                          [(value)]="task.priority"
                          [items]="priorityList"
                          [readOnly]="!isEditing"
                          [elementAttr]="{class: 'form-editor'}"
                          stylingMode="filled"
                          fieldTemplate="field"
            >
              <div *dxTemplate="let data of 'field'">
                <div>
                  <status-indicator
                    [showBar]="true"
                    [value]="task.priority"
                  ></status-indicator>
                </div>
              </div>

              <div *dxTemplate="let data of 'item'">
                <status-indicator
                  [showBar]="true"
                  [isField]="false"
                  [value]="data"></status-indicator>
              </div>
            </dx-select-box>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <dx-select-box label="Status"
                          [(value)]="task.status"
                          [items]="statusList"
                          [readOnly]="!isEditing"
                          [elementAttr]="{class: 'form-editor'}"
                          stylingMode="filled"
                          fieldTemplate="field"
            >
              <div *dxTemplate="let data of 'field'">
                <div>
                  <status-indicator [value]="task.status"></status-indicator>
                </div>
              </div>

              <div *dxTemplate="let data of 'item'">
                <status-indicator [isField]="false" [value]="data"></status-indicator>
              </div>
            </dx-select-box>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <form-item-date
              label="Start Date"
              text="Set Start Date"
              [isEditing]="isEditing"
              [(value)]="task.startDate"
            ></form-item-date>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <form-item-date
              label="Due Date"
              text="Set Due Date"
              [isEditing]="isEditing"
              [(value)]="task.dueDate"
            ></form-item-date>
          </div>
        </dxi-item>
      </dxi-item>
      <dxi-item>
        <div *dxTemplate>
          <dx-text-area label="Details"
                        [readOnly]="!isEditing"
                        [(value)]="task.description"
                        [elementAttr]="{class: 'form-editor'}"
                        stylingMode="filled"
          ></dx-text-area>
        </div>
      </dxi-item>
    </dx-form>
  </dx-validation-group>

  <dx-load-panel
    [visible]="isLoading"
    [showPane]="false"
    content="#task-form"
    [position]="{ of: '#task-form' }"
  ></dx-load-panel>
</div>
