// packages/react/src/pages/auth-sign-in/auth-sign-in.tsx
import React from 'react';

import { CardAuth, LoginForm } from '../../components';

export const SignInPage = () => {
  return (
    <CardAuth title='Sign In'>
      <LoginForm
        resetLink='/reset-password-form-page'
        createAccountLink='/signup-form-page'
      />
    </CardAuth>
  );
};

// packages/angular/src/app/pages/auth-login/auth-signin.component.ts
import { Component, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { CardAuthModule, LoginFormModule } from 'src/app/components';

@Component({
  selector: 'app-auth-login',
  templateUrl: './auth-signin.component.html',
  styleUrls: ['./auth-signin.component.scss']
})
export class AuthSigninComponent {
  constructor() { }
}

@NgModule({
  imports: [
    CommonModule,
    LoginFormModule,
    CardAuthModule,
  ],
  providers: [],
  exports: [AuthSigninComponent],
  declarations: [AuthSigninComponent],
})
export class AuthLoginModule { }

<app-card-auth title="Sign In">
  <app-login-form
    resetLink="/reset-password-form-page"
    createAccountLink="/signup-form-page"
  ></app-login-form>
</app-card-auth>
