// packages/vue/src/components/library/task-form.vue
<template>
  <div id="task-form">
    <toolbar-form
      v-if="!isCreateMode"
      :is-editing="isEditing"
      @edit-canceled="handleCancelClick"
      @edit-toggled="handleEditClick"
      @save-clicked="handleSaveClick"
    />
    <dx-load-panel
      :visible="isLoading"
      :show-pane="false"
      width="auto"
      container="#task-form"
      :position="{ of: '#task-form' }"
    />
    <dx-form
      :form-data="data"
      class="plain-styled-form"
      :class="{'view-mode': !isEditing}"
      :screen-by-width="getSizeQualifier"
      v-if="!!props.data"
    >
      <dx-form-item
        v-if="isCreateMode"
        :col-span="2"
      >
        <form-textbox
          label="Subject"
          v-model="data.text"
          :is-editing="isEditing"
        />
      </dx-form-item>
      <dx-form-group-item :col-count="2">
        <dx-col-count-by-screen
          :xs="1"
          :sm="2"
          :md="2"
          :lg="2"
        />
        <dx-form-item css-class="accent">
          <form-textbox
            label="Company"
            v-model="data.company"
            :is-editing="isEditing"
          />
        </dx-form-item>

        <dx-form-item css-class="accent">
          <form-textbox
            label="Assigned to"
            v-model="data.owner"
            :is-editing="isEditing"
          />
        </dx-form-item>

        <dx-form-item>
          <dx-select-box
            label="Priority"
            v-model="data.priority"
            :items="taskPriorityList"
            :read-only="!isEditing"
            field-template="field"
            item-template="item"
            v-bind="formSelectBoxProps"
          >
            <template #field>
              <div class="task-editor-field">
                <status-indicator
                  :is-field="true"
                  :show-bar="true"
                  :value="data.priority"
                />
              </div>
            </template>
            <template #item="item">
              <status-indicator
                :show-bar="true"
                :value="item.data"
              />
            </template>
          </dx-select-box>
        </dx-form-item>

        <dx-form-item>
          <dx-select-box
            label="Status"
            v-model="data.status"
            :items="taskStatusList"
            :read-only="!isEditing"
            field-template="field"
            item-template="item"
            v-bind="formSelectBoxProps"
          >
            <template #field>
              <div class="task-editor-field">
                <status-indicator
                  :is-field="true"
                  :value="data.status"
                />
              </div>
            </template>
            <template #item="item">
              <status-indicator
                :value="item.data"
              />
            </template>
          </dx-select-box>
        </dx-form-item>

        <dx-form-item>
          <form-datebox
            label="Start Date"
            v-model="data.startDate"
            :is-editing="isEditing"
          />
        </dx-form-item>

        <dx-form-item>
          <form-datebox
            label="Due Date"
            v-model="data.dueDate"
            :is-editing="isEditing"
          />
        </dx-form-item>
      </dx-form-group-item>
      <dx-form-item>
        <dx-text-area
          label="Details"
          styling-mode="filled"
          v-model="data.description"
        />
      </dx-form-item>
    </dx-form>
  </div>
</template>
<script setup lang="ts">
import { ref, watch } from 'vue';
import { getSizeQualifier } from '@/utils/media-query';
import StatusIndicator from '@/components/library/status-indicator.vue';
import { DxTextArea } from 'devextreme-vue/text-area';
import {
  taskPriorityList, Task, taskStatusList,
} from '@/types/task';
import {
  DxForm,
  DxItem as DxFormItem,
  DxGroupItem as DxFormGroupItem,
  DxColCountByScreen,
} from 'devextreme-vue/form';
import { DxSelectBox } from 'devextreme-vue/select-box';
import { DxButtonTypes } from 'devextreme-vue/button';
import DxLoadPanel from 'devextreme-vue/load-panel';
import FormTextbox from '@/components/utils/form-textbox.vue';
import FormDatebox from '@/components/utils/form-datebox.vue';
import { formSelectBoxProps } from '@/shared/form-editor-config';
import ToolbarForm from '@/components/utils/toolbar-form.vue';

const props = withDefaults(defineProps<{
  isCreateMode?: boolean,
  isLoading?: boolean,
  data?: Task,
  contentByScreen: { xs: number, sm: number },
  validationGroup?: string,
}>(), {
  data: undefined,
  isLoading: false,
  isCreateMode: false,
  validationGroup: undefined,
});

const isEditing = ref(props.isCreateMode);
const data = ref(props.data);

watch(
  () => props.data,
  (newValue) => {
    data.value = newValue;
  },
);

let dataSaved: Task;

function handleEditClick() {
  dataSaved = { ...data.value };
  isEditing.value = true;
}

function handleSaveClick({ validationGroup }: DxButtonTypes.ClickEvent) {
  if (validationGroup.validate().isValid) {
    isEditing.value = false;
  }
}

function handleCancelClick() {
  if (dataSaved) {
    data.value = dataSaved;
  }

  isEditing.value = false;
}
</script>
<style scoped lang="scss">
@use "@/variables.scss" as *;

#task-form {
  min-height: 250px;
}
</style>

// packages/angular/src/app/components/library/task-form/task-form.component.ts
import { Component, Input, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxFormModule,
  DxLoadPanelModule,
  DxSelectBoxModule,
  DxTextBoxModule,
  DxTextAreaModule,
  DxToolbarModule,
  DxValidatorModule,
} from 'devextreme-angular';
import {
  StatusIndicatorComponent,
  FormDateboxComponent,
  FormTextboxComponent,
} from 'src/app/components';
import { taskPriorityList, taskStatusList } from 'src/app/types/task';
import { Task } from 'src/app/types/task';
import { getSizeQualifier } from 'src/app/services/screen.service';
import { DxButtonTypes } from 'devextreme-angular/ui/button';
import { ScreenService } from '../../../services';
import { ToolbarFormComponent } from 'src/app/components/utils/toolbar-form/toolbar-form.component';

@Component({
  selector: 'task-form',
  templateUrl: './task-form.component.html',
  styleUrls: ['./task-form.component.scss'],
  imports: [
    DxButtonModule,
    DxFormModule,
    DxLoadPanelModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    DxTextAreaModule,
    DxToolbarModule,
    DxValidatorModule,
    FormTextboxComponent,
    StatusIndicatorComponent,
    FormDateboxComponent,
    ToolbarFormComponent,
    CommonModule,
  ],
})
export class TaskFormComponent implements OnInit {
  @Input() task: Task;

  @Input() isLoading: boolean = false;

  @Input() isCreateMode: boolean = false;

  protected screen = inject(ScreenService);

  savedData: Task = null;

  isEditing = false;

  statusList = taskStatusList;

  priorityList = taskPriorityList;

  getSizeQualifier = getSizeQualifier;

  ngOnInit() {
    this.isEditing = this.isCreateMode;
  }
  handleEditClick = () => {
    this.savedData = { ...this.task }
    this.isEditing = true;
  };

  handleSaveClick = ({ validationGroup }: DxButtonTypes.ClickEvent) => {
    if(!validationGroup.validate().isValid) return;
    this.savedData = null;
    this.isEditing = false;
  };

  handleCancelClick = () => {
    this.task = { ...this.savedData };
    this.isEditing = false;
  };

  getNewTaskData = ()=> ({ ...this.task });
}

<div id="task-form">
  @if (!isCreateMode) {
    <toolbar-form
      [isEditing]="isEditing"
      titleClass="dx-form-group-caption"
      (editingCancelled)="handleCancelClick()"
      (editModeToggled)="handleEditClick()"
      (saveButtonClicked)="handleSaveClick($event)"
    >
    </toolbar-form>
  }

  @if (task) {
    <dx-form
      class="plain-styled-form"
      [class.view-mode]="!isEditing"
      [screenByWidth]="getSizeQualifier"
    >
      <dxi-item [visible]="isCreateMode">
        <div *dxTemplate>
          <form-textbox
            label="Subject"
            [(value)]="task.text"
            [isEditing]="isEditing"
          ></form-textbox>
        </div>
      </dxi-item>
      <dxi-item itemType="group">
        <dxo-col-count-by-screen
          [xs]="1"
          [sm]="2"
          [md]="2"
          [lg]="2"
        ></dxo-col-count-by-screen>
        <dxi-item cssClass="accent">
          <div *dxTemplate>
            <form-textbox
              label="Company"
              [(value)]="task.company"
              [isEditing]="isEditing"
            ></form-textbox>
          </div>
        </dxi-item>

        <dxi-item cssClass="accent">
          <div *dxTemplate>
            <form-textbox
              label="Assigned to"
              [(value)]="task.owner"
              [isEditing]="isEditing"
            ></form-textbox>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <dx-select-box
              class="task-details-select-box"
              label="Priority"
              stylingMode="filled"
              [(value)]="task.priority"
              [items]="priorityList"
              [readOnly]="!isEditing"
              [elementAttr]="{ class: 'form-editor' }"
              placeholder=""
              [displayExpr]="displayExprFn"
            >
              <dxo-select-box-field-addons beforeTemplate="before"></dxo-select-box-field-addons>
              <div *dxTemplate="let data of 'before'">
                <status-indicator
                  [showBar]="true"
                  [isField]="false"
                  [value]="task.priority"
                ></status-indicator>
              </div>
              <div *dxTemplate="let data of 'item'">
                <status-indicator
                  [showBar]="true"
                  [isField]="false"
                  [value]="data"
                ></status-indicator>
              </div>
            </dx-select-box>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <dx-select-box
              class="task-details-select-box"
              label="Status"
              stylingMode="filled"
              [(value)]="task.status"
              [items]="statusList"
              [readOnly]="!isEditing"
              [elementAttr]="{ class: 'form-editor' }"
              placeholder=""
              [displayExpr]="displayExprFn"
            >
              <dxo-select-box-field-addons beforeTemplate="before"></dxo-select-box-field-addons>
              <div *dxTemplate="let data of 'before'">
                <status-indicator [isField]="false" [value]="task.status"></status-indicator>
              </div>
              <div *dxTemplate="let data of 'item'">
                <status-indicator [isField]="false" [value]="data"></status-indicator>
              </div>
            </dx-select-box>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <form-item-date
              label="Start Date"
              text="Set Start Date"
              [isEditing]="isEditing"
              [(value)]="task.startDate"
            ></form-item-date>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <form-item-date
              label="Due Date"
              text="Set Due Date"
              [isEditing]="isEditing"
              [(value)]="task.dueDate"
            ></form-item-date>
          </div>
        </dxi-item>
      </dxi-item>
      <dxi-item>
        <div *dxTemplate>
          <dx-text-area
            label="Details"
            stylingMode="filled"
            [readOnly]="!isEditing"
            [(value)]="task.description"
            [elementAttr]="{ class: 'form-editor' }"
          ></dx-text-area>
        </div>
      </dxi-item>
    </dx-form>
  }

  <dx-load-panel
    content="#task-form"
    [visible]="!task || isLoading"
    [showPane]="false"
    [position]="{ of: '#task-form' }"
  ></dx-load-panel>
</div>
