// packages/angular/src/app/components/utils/right-side-panel/right-side-panel.component.ts
import {
  Component,
  Output,
  Input,
  EventEmitter, HostBinding, inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxButtonComponent } from 'devextreme-angular';
import {DataService, ScreenService} from 'src/app/services';

@Component({
    selector: 'right-side-panel',
    templateUrl: './right-side-panel.component.html',
    styleUrls: ['./right-side-panel.component.scss'],
    providers: [DataService],
    imports: [
      DxButtonComponent,
      CommonModule,
    ],
})
export class RightSidePanelComponent {
  @Input() isOpened = false;

  @Input() showOpenButton = true;

  @Input() title = '';

  @Output() openedChange = new EventEmitter<boolean>();

  @HostBinding('class.overlapping') get overlapping() { return !this.isLarge; };

  @HostBinding('class.closed-state-hidden') get closedStateHidden() { return !this.showOpenButton; };

  @HostBinding('class.open') get open() { return this.isOpened; };

  private screen = inject(ScreenService);

  isLarge = this.screen.sizes['screen-large'];

  constructor() {
    this.screen.screenChanged.subscribe(({isLarge, isXLarge}) => {
      this.isLarge = isLarge || isXLarge;
    });
  }

  toggleOpen = () => {
    this.isOpened = !this.isOpened;
    this.openedChange.emit(this.isOpened);
  };
}

<div class="right-side-panel">
  <div class="side-panel-container">
    <div class="side-panel-header">
      @if (title) {
        <div class="side-panel-title">
          <div class="side-panel-title-text">
            {{ title }}
          </div>
        </div>
      }
      <dx-button
        class="open-button"
        stylingMode="text"
        [icon]="isOpened ? (isLarge ? 'panelleft' : 'close') : 'panelright'"
        (onClick)="toggleOpen()"
      >
      </dx-button>
    </div>

    <div class="side-panel-content-wrapper">
      <ng-content></ng-content>
    </div>
  </div>
</div>

// packages/react/src/components/side-panel/right-side-panel.tsx
import React, { } from 'react';
import classNames from 'classnames';
import Button from 'devextreme-react/button';
import { useScreenSize } from '../../utils/media-query';
import './right-side-panel.scss';

export const RightSidePanel = ({ isOpened, title, toggleOpen, children }) => {

  const { isLarge } = useScreenSize();
  return <>
    <div id='right-panel'>
      <div
        className={classNames({
          'right-sight-panel': true,
          'overlapping': !isLarge,
          'open': isOpened
        })}
      >
        <div className='side-panel-container'>
          <div className='side-panel-header'>
            {title &&
              <div className='side-panel-title'>
                <div className='side-panel-title-text'>
                  {{ title }}
                </div>
              </div>
            }
          </div>

          <div className='side-panel-content-wrapper'>
            {children}
          </div>
        </div>
      </div>
    </div>
    {!isOpened && isLarge && <Button
      className='open-button'
      icon={isOpened ? 'showpanel' : 'hidepanel'}
      onClick={toggleOpen} />
    }
  </>;
};
