// packages/react/src/components/form-popup/FormPopup.tsx
import React, { useRef } from 'react';

import { Popup, ToolbarItem } from 'devextreme-react/popup';
import ValidationGroup from 'devextreme-react/validation-group';
import { useScreenSize } from './../../utils/media-query';

type PopupProps = {
  title: string,
  visible: boolean,
  changeVisibility: () => void,
}

export const FormPopup = ({ title, visible, changeVisibility, children }: React.PropsWithChildren<PopupProps>) => {
  const { isXSmall, isSmall } = useScreenSize();
  const validationGroup = useRef<ValidationGroup>(null);

  const onCancelClick = () => {
    validationGroup.current?.instance.reset();
    changeVisibility();
  };

  const onSaveClick = () => {
    if (!validationGroup.current?.instance.validate().isValid) return;
    validationGroup.current?.instance.reset();

    changeVisibility();
  };

  return (
    <Popup
      title={title}
      visible={visible}
      fullScreen={isXSmall || isSmall}
      width='auto'
      height='auto'
    >
      <ToolbarItem
        widget='dxButton'
        toolbar='bottom'
        location='after'
        options={{
          text: 'Save',
          stylingMode: 'outlined',
          type: 'default',
          onClick: onSaveClick,
        }}
      />
      <ToolbarItem
        widget='dxButton'
        toolbar='bottom'
        location='after'
        options={{
          text: 'Cancel',
          stylingMode: 'text',
          type: 'default',
          onClick: onCancelClick,
        }}
      />
      <ValidationGroup ref={validationGroup}>
        {children}
      </ValidationGroup>
    </Popup>
  );
};

// packages/angular/src/app/components/form-popup/form-popup.component.ts
import {
    Component,
    NgModule,
    Input,
    ViewChild,
  } from '@angular/core';
  import { CommonModule } from '@angular/common';
  import {
    DxButtonModule,
    DxToolbarModule,
    DxPopupModule,
    DxValidationGroupModule,
    DxValidationGroupComponent,
  } from 'devextreme-angular';
  import { ScreenService } from '../../services';

  @Component({
    selector: 'form-popup',
    templateUrl: './form-popup.component.html',
    providers: [],
  })

  export class FormPopupComponent {
    @ViewChild('validationGroup', { static: true }) validationGroup: DxValidationGroupComponent;

    @Input() titleText = '';

    popupVisible = false;

    constructor(protected screen: ScreenService) { }

    onCancelClick = () => {
      this.validationGroup.instance.reset();
      this.popupVisible = false;
    }

    onSaveClick = () => {
      if(!this.validationGroup.instance.validate().isValid) return;
      this.validationGroup.instance.reset();
      this.popupVisible = false;
    }
  }

  @NgModule({
    imports: [
      DxButtonModule,
      DxToolbarModule,
      DxPopupModule,
      DxValidationGroupModule,
      CommonModule,
    ],
    declarations: [FormPopupComponent],
    exports: [FormPopupComponent],
  })
  export class FormPopupModule { }


<dx-popup [title]="titleText"
          [(visible)]="popupVisible"
          [fullScreen]="(screen.xSmallScreenChanged | async)"
          width="480px"
          height="auto">
  <dxi-toolbar-item widget="dxButton" toolbar="bottom" location="after" [options]="{
                    text: 'Save',
                    stylingMode: 'outlined',
                    type: 'default',
                    onClick: onSaveClick
                }">
  </dxi-toolbar-item>

  <dxi-toolbar-item widget="dxButton" toolbar="bottom" location="after" [options]="{
                    text: 'Cancel',
                    stylingMode: 'text',
                    type: 'default',
                    onClick: onCancelClick
                }">
  </dxi-toolbar-item>
  <dx-validation-group #validationGroup>
    <ng-content></ng-content>
  </dx-validation-group>
</dx-popup>
