// packages/react/src/components/library/card-opportunities/CardOpportunities.tsx
import React from 'react';

import Button from 'devextreme-react/button';
import { OpportunityTile } from '../../utils/opportunity-tile/OpportunityTile';

import { Opportunities } from '../../../types/card-opportunities';

import { withLoadPanel } from '../../../utils/withLoadPanel';

import './CardOpportunities.scss';

const CardTemplate = ({ items, title }: { items: Opportunities, title: string}) => (
  <div className='opportunities-block'>
    <div className='dx-form-group-caption'>{title}</div>
    <div className='opportunities-container'>
      {items.map((item) => (
        <OpportunityTile
          key={item.name}
          name={item.name}
          products={item.products}
          total={item.total}
          manager={item.manager}
        />
      ))}
    </div>
  </div>
);

const Cards = ({ active, closed }: { active: Opportunities, closed: Opportunities }) => (
  <>
    <Button
      text='Add Opportunity'
      icon='add'
      width={300}
      height={115}
      stylingMode='outlined'
      type='default'
      className='add-tile'
    />

    <CardTemplate title='Active' items={active} />
    <CardTemplate title='Closed' items={closed} />
  </>
);

const CardsWithLoadPanel = withLoadPanel(Cards);

export const CardOpportunities = ({ active, closed }: { active?: Opportunities, closed?: Opportunities }) => {
  return (
    <div className='card-opportunies'>
      <CardsWithLoadPanel
        active={active}
        closed={closed}
        hasData={!!(active && closed)}
        panelProps={{
          container: '.card-opportunies',
          position: { of: '.card-opportunies' }
        }}
      />
    </div>
  );
};

// packages/angular/src/app/components/library/card-opportunities/card-opportunities.component.ts
import {
  Component, Input, OnChanges, SimpleChanges,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxLoadPanelModule,
} from 'devextreme-angular';
import { Opportunity } from 'src/app/types/opportunities';
import { OpportunityTileComponent } from 'src/app/components/utils/opportunity-tile/opportunity-tile.component';

@Component({
  selector: 'card-opportunities',
  templateUrl: './card-opportunities.component.html',
  styleUrls: ['./card-opportunities.component.scss'],
  imports: [
    DxButtonModule,
    DxLoadPanelModule,
    OpportunityTileComponent,
    CommonModule,
  ]
})
export class CardOpportunitiesComponent implements OnChanges {
  @Input() openedOpportunities: Opportunity[];

  @Input() closedOpportunities: Opportunity[];

  isLoading = true;

  ngOnChanges(changes: SimpleChanges) {
    const isLoadActive = !changes.openedOpportunities?.currentValue;
    const isLoadClosed = !changes.closedOpportunities?.currentValue;

    this.isLoading = isLoadActive || isLoadClosed;
  }
}

<div id="card-opportunies">
  @if (!isLoading) {
    <dx-button
      text="Add Opportunity"
      icon="add"
      width="300"
      height="115"
      stylingMode="outlined"
      type="default"
      class="add-tile"
    ></dx-button>

    <div class="opportunities-block">
      <div class="dx-form-group-caption">Active</div>
      <div class="opportunities-container">
        @for (data of openedOpportunities; track data.name) {
          <div class="opportunities">
            <opportunity-tile [data]="data"></opportunity-tile>
          </div>
        }
      </div>
    </div>

    <div class="opportunities-block">
      <div class="dx-form-group-caption">Closed</div>
      <div class="opportunities-container">
        @for (data of closedOpportunities; track data.name) {
          <div class="opportunities">
            <opportunity-tile [data]="data"></opportunity-tile>
          </div>
        }
      </div>
    </div>
  }

  <dx-load-panel
    [visible]="isLoading"
    [showPane]="false"
    container="#card-opportunies"
    [position]="{ of: '#card-opportunies' }"
  ></dx-load-panel>
</div>
