// packages/vue/src/pages/analytics-sales-analysis.vue
<template>
  <dx-scroll-view class="view-wrapper-scroll">
    <div class="view-wrapper">
      <toolbar-analytics>Sales Analysis</toolbar-analytics>

      <div class="cards">
        <sales-range-card
          :data="sales"
          class="sales-range-card"
          @range-changed="onRangeChanged"
        />
        <sales-by-range-card :data="salesByCategory" />
        <sales-performance-card
          :data="salesByDateAndCategory"
          :group-by-periods="groupByPeriods"
          :visual-range="visualRange"
          @performance-period-changed="performancePeriodChange"
        />
      </div>
    </div>
  </dx-scroll-view>
  <dx-load-panel
    container=".view-wrapper"
    :position="{ of: '.dx-drawer-content' }"
    :visible="loading"
    :show-pane="true"
  />
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue';

import { DxDropDownButtonTypes } from 'devextreme-vue/drop-down-button';
import { DxScrollView } from 'devextreme-vue/scroll-view';
import { DxLoadPanel } from 'devextreme-vue/load-panel';
import { formatDate } from 'devextreme/localization';

import {
  getSalesByOrderDate,
  getSalesByCategory,
  getSales,
} from 'dx-template-gallery-data';
import {
  Sales,
  SalesByStateAndCity,
} from '@/types/analytics';
import { analyticsPanelItems } from '@/types/resource';
import ToolbarAnalytics from '@/components/utils/toolbar-analytics.vue';
import SalesRangeCard from '@/components/utils/sales-range-card.vue';
import SalesByRangeCard from '@/components/utils/sales-by-range-card.vue';
import SalesPerformanceCard from '@/components/utils/sales-performance-card.vue';

const sales = ref<Sales | null>(null);
const salesByDateAndCategory = ref<Sales | null>(null);
const salesByCategory = ref<SalesByStateAndCity | null>(null);

const visualRange = ref<[Date, Date]>([]);

const groupByPeriods = ['Day', 'Month'];

const loading = ref<boolean>(true);

const performancePeriodChange = async (e: DxDropDownButtonTypes.SelectionChangedEvent) => {
  loading.value = true;
  salesByDateAndCategory.value = await getSalesByOrderDate(e.item.toLowerCase());
  loading.value = false;
};

const onRangeChanged = async (dates: [Date, Date]) => {
  visualRange.value = dates;
  loading.value = true;
  salesByCategory.value = await getSalesByCategory(
    ...dates.map((date) => formatDate(date, 'yyyy-MM-dd')),
  );
  loading.value = false;
};

const loadData = async (groupBy: string) => {
  loading.value = true;
  const [startDate, endDate] = analyticsPanelItems[4].value.split('/');

  await Promise.all([
    getSales(startDate, endDate)
      .then((result: Sales) => { sales.value = result; }),
    getSalesByOrderDate(groupBy)
      .then((result: Sales) => { salesByDateAndCategory.value = result; }),
  ]).then(() => { loading.value = false; });
};

onMounted(() => {
  loadData(groupByPeriods[1].toLowerCase());
});
</script>

<style scoped lang="scss">
@use "@/variables" as *;
.view-wrapper {
  padding-top: var(--content-padding);
  padding-bottom: var(--content-padding);
}

.cards  {
  display: grid;
  width: 100%;
  grid-gap: 20px;
  gap: 20px;
  grid-template-columns: repeat(1,100%);

  .sales-range-card :deep(.content) {
    height: auto;
  }
}

@media only screen and (max-width: 900px) {
  .view-wrapper .cards {
    grid-template-columns: repeat(1, 100%);
  }
}

@media only screen and (max-width: 400px) {
  .cards :deep(.card) {
    flex: 1 320px;
  }
}
</style>

// packages/react/src/pages/analytics-sales-analysis/analytics-sales-analysis.tsx
import React, { useState, useEffect, useCallback } from 'react';

import { ToolbarAnalytics, SalesRangeCard, SalesByRangeCard, SalesPerformanceCard } from '../../components';
import { Sale, SaleOrOpportunityByCategory } from '../../types/analytics';

import { getSalesByCategory, getSales, getSalesByOrderDate } from 'dx-template-gallery-data';

import { formatDate } from 'devextreme/localization';
import LoadPanel from 'devextreme-react/load-panel';
import { RangeSelectorTypes } from 'devextreme-react/range-selector';
import { DropDownButtonTypes } from 'devextreme-react/drop-down-button';
import ScrollView from 'devextreme-react/scroll-view';

import { ANALYTICS_PERIODS, DEFAULT_ANALYTICS_PERIOD_KEY } from '../../shared/constants';

import './analytics-sales-analysis.scss';

const formatDateRange = (dateRange: Date[]) => dateRange.map((date) => formatDate(date, 'yyyy-MM-dd'));

const defaultDateRange = ANALYTICS_PERIODS[DEFAULT_ANALYTICS_PERIOD_KEY].period.split('/').map((d) => new Date(d));

const groupByPeriods = ['Day', 'Month'];

export const AnalyticsSalesAnalysis = () => {
  const [sales, setSales] = useState<Sale[]>([]);
  const [salesByCategory, setSalesByCategory] = useState<SaleOrOpportunityByCategory[]>([]);
  const [salesByDateAndCategory, setSalesByDateAndCategory] = useState<Sale[]>([]);
  const [dateRange, setDateRange] = useState(defaultDateRange);
  const [groupByPeriod, setGroupByPeriod] = useState(groupByPeriods[1]);
  const [isLoading, setIsLoading] = useState(true);

  const onRangeChanged = useCallback((e: RangeSelectorTypes.ValueChangedEvent) => {
    const [startDate, endDate] = e.value;
    setDateRange([startDate, endDate] as Date[]);
    setIsLoading(true);
  }, []);

  const onPeriodChanged = useCallback((e: DropDownButtonTypes.SelectionChangedEvent) => {
    setGroupByPeriod(e.item);
    setIsLoading(true);
  }, []);

  useEffect(() => {
    getSales(...formatDateRange(defaultDateRange))
      .then((data) => setSales(data))
      .catch((error) => console.log(error));
  }, []);

  useEffect(() => {
    getSalesByCategory(...formatDateRange(dateRange))
      .then((data) => {
        setSalesByCategory(data);
        setIsLoading(false);
      })
      .catch((error) => console.log(error));
  }, [dateRange]);

  useEffect(() => {
    getSalesByOrderDate(groupByPeriod.toLowerCase())
      .then((data) => {
        setSalesByDateAndCategory(data);
        setIsLoading(false);
      })
      .catch((error) => console.log(error));
  }, [groupByPeriod]);

  return (
    <ScrollView className='view-wrapper-scroll'>
      <ToolbarAnalytics title='Sales Analysis'>
        <div className='cards wide'>
          <SalesRangeCard datasource={sales} range={dateRange} onRangeChanged={onRangeChanged} />
          <SalesByRangeCard datasource={salesByCategory} />
          <SalesPerformanceCard
            datasource={salesByDateAndCategory}
            periods={groupByPeriods}
            selectedPeriod={groupByPeriod}
            onPeriodChanged={onPeriodChanged}
            range={dateRange}
          />
        </div>
      </ToolbarAnalytics>
      <LoadPanel container='.content' visible={isLoading} position={{ of: '.layout-body' }} />
    </ScrollView>
  );
};
