// packages/angular/src/app/components/task-list-gantt/task-list-gantt.component.ts
import {
  Component, NgModule, Input, ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { DxGanttModule, DxGanttComponent } from 'devextreme-angular/ui/gantt';
import { exportGantt as exportGanttToPdf } from 'devextreme/pdf_exporter';
import { jsPDF } from 'jspdf';
import { Task } from 'src/app/types/task';

import 'jspdf-autotable';

@Component({
  selector: 'task-list-gantt',
  templateUrl: './task-list-gantt.component.html',
  styleUrls: ['./task-list-gantt.component.scss'],
})
export class TaskListGanttComponent {
  @ViewChild(DxGanttComponent, { static: false }) gantt: DxGanttComponent;

  @Input() dataSource: Task[];

  constructor(private router: Router) {
  }

  refresh() {
    this.gantt.instance.refresh();
  }

  onExporting() {
    exportGanttToPdf(
      {
        component: this.gantt.instance,
        createDocumentMethod: (args?: any) => new jsPDF(args),
      },
    ).then((doc) => doc.save('Tasks.pdf'));
  };

  navigateToDetails = () => {
    this.router.navigate(['/planning-task-details']);
  };
}

@NgModule({
  imports: [
    DxGanttModule,

    CommonModule,
  ],
  providers: [],
  exports: [TaskListGanttComponent],
  declarations: [TaskListGanttComponent],
})
export class TaskListGanttModule { }

<dx-gantt
  [taskListWidth]="500"
  scaleType="weeks"
  (onTaskClick)="navigateToDetails()"
  [height]="700"
>
  <dxo-tasks
    [dataSource]="dataSource"
    startExpr="startDate"
    endExpr="dueDate"
    titleExpr="text"
  >
  </dxo-tasks>

  <dxi-column dataField="text" caption="Subject" [width]="300"></dxi-column>
  <dxi-column
    dataField="startDate"
    caption="Start Date"
    dataType="date"
    sortOrder="asc"
  ></dxi-column>
  <dxi-column
    dataField="dueDate"
    caption="Due Date"
    dataType="date"
  ></dxi-column>

  <dxo-toolbar>
    <dxi-item name="undo"></dxi-item>
    <dxi-item name="redo"></dxi-item>
    <dxi-item name="separator"></dxi-item>
    <dxi-item name="collapseAll"></dxi-item>
    <dxi-item name="expandAll"></dxi-item>
    <dxi-item name="separator"></dxi-item>
    <dxi-item name="addTask"></dxi-item>
    <dxi-item name="deleteTask"></dxi-item>
    <dxi-item name="separator"></dxi-item>
    <dxi-item name="zoomIn"></dxi-item>
    <dxi-item name="zoomOut"></dxi-item>
  </dxo-toolbar>

  <dxo-validation [autoUpdateParentTasks]="true"></dxo-validation>
  <dxo-editing [enabled]="true"></dxo-editing>
</dx-gantt>

// packages/vue/src/pages/planning-task-list/components/task-list-gantt.vue
<template>
  <dx-gantt ref="dxGanttCmp"
            :task-list-width="500"
            :scale-type="'weeks'"
            @task-click="onTaskClick"
            :height="700">

    <dx-tasks :data-source="props.tasks"
              :start-expr="'startDate'"
              :end-expr="'dueDate'"
              title-expr="text"/>

    <dx-gantt-column data-field="text" caption="Subject" :width="300"/>
    <dx-gantt-column data-field="startDate"
                     caption="Start Date"
                     data-type="date"
                     sort-order="asc"/>
    <dx-gantt-column data-field="dueDate"
                     caption="Due Date"
                     data-type="date"/>

    <dx-gantt-toolbar>
      <dx-item name="undo"/>
      <dx-item name="redo"/>
      <dx-item name="separator"/>
      <dx-item name="collapseAll"/>
      <dx-item name="expandAll"/>
      <dx-item name="separator"/>
      <dx-item name="addTask"/>
      <dx-item name="deleteTask"/>
      <dx-item name="separator"/>
      <dx-item name="zoomIn"/>
      <dx-item name="zoomOut"/>
    </dx-gantt-toolbar>

    <dx-validation :auto-update-parent-tasks="true"/>
    <dx-editing :enabled="true"/>
  </dx-gantt>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { router } from '@/router';
import {
  DxGantt,
  DxTasks,
  DxEditing,
  DxValidation,
  DxColumn as DxGanttColumn,
  DxToolbar as DxGanttToolbar,
  DxItem,
} from 'devextreme-vue/gantt';
import { Task } from '@/types/task';
import { jsPDF as JsPDF } from 'jspdf';
import { exportGantt } from 'devextreme/pdf_exporter';
import { TaskClickEvent } from 'devextreme/ui/gantt';

const props = withDefaults(defineProps<{
  tasks: Task[]
}>(), {
  tasks: () => [],
});

const dxGanttCmp = ref<InstanceType<typeof DxGantt> | null>(null);

const onExporting = () => {
  const doc = new JsPDF();
  exportGantt({
    jsPDFDocument: doc,
    component: dxGanttCmp.value.instance,
  }).then(() => {
    doc.save('Tasks.pdf');
  });
};

const navigateToDetails = () => {
  router.push('/planning-task-details');
};

const onTaskClick = (e: TaskClickEvent) => {
  if (!e.event?.target?.closest('.dx-treelist-expanded, .dx-treelist-collapsed')) {
    navigateToDetails();
  }
};

defineExpose({
  onExporting,
});
</script>

<style scoped lang="scss">
</style>
