// packages/angular/src/app/pages/planning-scheduler/planning-scheduler.component.ts
import {
  Component, OnInit, NgModule, ViewChild
} from '@angular/core';
import DataSource from 'devextreme/data/data_source';
import { CommonModule } from '@angular/common';
import {
  DxCalendarModule,
  DxButtonModule,
  DxTooltipComponent,
  DxTooltipModule,
  DxSchedulerModule,
  DxSchedulerComponent,
  DxSpeedDialActionModule,
} from "devextreme-angular";
import { Task } from 'src/app/types/task';
import { DataService, ScreenService } from 'src/app/services';
import { CalendarListModule } from 'src/app/components/utils/calendar-list/calendar-list.component';
import { LeftSidePanelModule } from 'src/app/components/utils/left-side-panel/left-side-panel.component';
import { RightSidePanelModule } from 'src/app/components/utils/right-side-panel/right-side-panel.component';
import { AgendaItem, AgendaModule } from "../../components/utils/agenda/agenda.component";
import { ApplyPipeModule } from '../../pipes/apply.pipe';
import { SchedulerTooltipModule } from '../../components/library/scheduler-tooltip/scheduler-tooltip.component';
import { DxSchedulerTypes } from 'devextreme-angular/ui/scheduler'

type SelectedAppointment = { data: Record<string, any>, target: any };

@Component({
  templateUrl: './planning-scheduler.component.html',
  styleUrls: ['./planning-scheduler.component.scss'],
  providers: [DataService],
})
export class PlanningSchedulerComponent implements OnInit {
  @ViewChild('schedulerRef', { static: false }) schedulerRef: DxSchedulerComponent;

  @ViewChild('tooltipRef', { static: false }) tooltipRef: DxTooltipComponent;
  tasks: DataSource<Task> = new DataSource([]);

  currentDate = new Date();

  currentView = 'workWeek';

  isRightPanelOpen = false;

  listDataSource = [];

  resourcesList = [];

  selectedAppointment: SelectedAppointment = null;

  agendaItems: AgendaItem[] = [];

  isXSmall = this.screen.sizes['screen-small'];

  schedulerCurrentDate: Date = this.currentDate;

  constructor(private service: DataService, protected screen: ScreenService) {
    this.service.getDefaultListDS().subscribe(
   (data) => {
     this.listDataSource = data;
     this.resourcesList = data.reduce((res: Record<string,any>[], calendarList) => res.concat(calendarList.items), []);
      });

    screen.screenChanged.subscribe(({isXSmall}) => {
      this.isXSmall = isXSmall;
      this.repaintScheduler();
    });
  }

  ngOnInit(): void {
    this.service.getSchedulerTasks().subscribe((data) => {
      this.tasks = new DataSource(data);
      this.repaintScheduler();
    })
  }

  openRightPanelOpen() {
    this.isRightPanelOpen = true;
    this.repaintScheduler();
  }

  onCalendarDateChange = (date) => {
    this.currentDate = date;
    this.updateAgenda({ startDate: this.currentDate });
    this.repaintScheduler();
  };

  getSchedulerCurrentDate = (currentDate) => {
    const schedulerInstance = this.schedulerRef?.instance;
    const startViewDate = schedulerInstance?.getStartViewDate();
    const endViewDate = schedulerInstance?.getEndViewDate();

    if (this.schedulerCurrentDate.getMonth() !== currentDate.getMonth() ||
      startViewDate && startViewDate > currentDate ||
      endViewDate && endViewDate < currentDate
    ) {
      this.schedulerCurrentDate = currentDate;
    }

    return this.schedulerCurrentDate;
  }

  onSchedulerOptionChanged(e: DxSchedulerTypes.OptionChangedEvent) {
    if (e.name === 'currentView') {
      this.onCurrentViewChange(e.value);
    }
  }
  onCurrentViewChange = (view: string) => {
    this.currentView = view;

    if (this.currentView === 'month' && !this.screen.sizes['screen-x-small']) {
      this.isRightPanelOpen = true;
      this.updateAgenda({ startDate: this.currentDate });
    }

    this.repaintScheduler();
  }

  onSelectedDateChange = (e?: Date) => {
    const date = e instanceof Date ? e : new Date();
    this.currentDate = date;
    this.selectedAppointment = { data: { startDate: date }, target: undefined };
    this.updateAgenda({ startDate: date });
  }

  onCellClick = ({cellData}) => {
    this.onSelectedDateChange(cellData.startDate);

    if (this.currentView === 'month' && cellData) {
      const cellAppointments = this.findAllAppointmentsForDay(cellData);

      if (cellAppointments.length > 1) {
        this.selectedAppointment = { data: cellData, target: null };
        this.agendaItems = cellAppointments;
        this.toggleRightPanelOpen(true);
      }
    }
  };

  calendarListChanged(selectedCalendars) {
    const filters = selectedCalendars
      .flatMap((calendar) => [['calendarId', '=', calendar.id], 'or']).slice(0, -1);

    this.tasks?.filter(filters.length > 0 ? filters : null);

    this.tasks?.load();
    this.updateAgenda({ startDate: this.currentDate });
  }

  repaintScheduler() {
    setTimeout(() => this.schedulerRef?.instance.repaint(), 0);
  }

  getTooltipPosition = (selectedAppointment: SelectedAppointment, rightPanelOpen: boolean, isXSmall: boolean) => {
    if (isXSmall) {
      return 'bottom';
    }
    const classList = selectedAppointment?.target?.classList || selectedAppointment?.target?.[0]?.classList;
    return classList?.contains('dx-list') && rightPanelOpen ? 'left' : 'top';
  }

  toggleRightPanelOpen(isOpen?) {
    this.isRightPanelOpen = isOpen || !this.isRightPanelOpen;
    this.repaintScheduler();
  }

  showAppointmentCreationForm(appointment?) {
    this.schedulerRef?.instance.showAppointmentPopup(appointment?.data, !appointment);
  }

  findAllAppointmentsForDay = (selectedAppointment) => {
    if (!this.tasks) {
      return [];
    }
    const appointments = this.tasks.items();
    if (appointments.length === 0 || !selectedAppointment) {
      return [];
    }
    return appointments
      .filter((appointment) => {
        return appointment.startDate.getDate() === selectedAppointment.startDate.getDate()
          && appointment.startDate.getMonth() === selectedAppointment.startDate.getMonth();
      });
  }

  updateAgenda = (appointmentData?) => {
    this.agendaItems = this.findAllAppointmentsForDay(appointmentData);
  }

  onAppointmentClick(e) {
    const appointmentData = e.appointmentData;
    this.selectedAppointment = { data: appointmentData, target: e.targetElement };

    if (this.currentView === 'month') {
      this.updateAgenda(appointmentData);
      this.toggleRightPanelOpen(true);
    }
  }

  onAppointmentTooltipShowing = (e) => {
    e.cancel = true;
    const appointmentData = e.appointments[0].appointmentData;
    const isAppointmentCollectorClicked = (e) => {
      return e.targetElement?.[0]?.classList.contains('dx-scheduler-appointment-collector');
    };

    this.selectedAppointment = { data: appointmentData, target: e.targetElement };

    if (this.currentView === 'month' || isAppointmentCollectorClicked(e)) {
      this.updateAgenda(appointmentData);
    }

    if (this.currentView === 'month' && this.screen.sizes['screen-small'] ||
        isAppointmentCollectorClicked(e)) {
      this.toggleRightPanelOpen(true);
    }
    else {
      this.tooltipRef?.instance.show();
    }
  }

  showAppointmentTooltip = (e) => {
    this.schedulerRef?.instance.showAppointmentTooltip(e.itemData, e.element);
  };

  editSelectedAppointment() {
    this.showAppointmentCreationForm(this.selectedAppointment);
    this.tooltipRef?.instance.hide();
  }

  deleteSelectedAppointment(appointmentData) {
    this.schedulerRef?.instance.deleteAppointment(this.selectedAppointment?.data);
    this.tooltipRef?.instance.hide();
    this.agendaItems = this.findAllAppointmentsForDay(appointmentData)
  }


}

@NgModule({
  imports: [
    ApplyPipeModule,
    DxCalendarModule,
    DxButtonModule,
    DxSchedulerModule,
    DxSpeedDialActionModule,
    DxTooltipModule,
    CommonModule,
    CalendarListModule,
    LeftSidePanelModule,
    RightSidePanelModule,
    AgendaModule,
    SchedulerTooltipModule,
  ],
  providers: [],
  exports: [],
  declarations: [PlanningSchedulerComponent],
})
export class PlanningSchedulerModule { }

<div class="view-wrapper">
  <div class="panels">
    <left-side-panel class="left-side-panel">
      <div class="left-side-panel-content">
        <div class="buttons">
          <dx-button
            text="Today"
            (onClick)="onSelectedDateChange()"
          ></dx-button>
          <dx-button
            text="Create event"
            type="default"
            (onClick)="showAppointmentCreationForm()"
          ></dx-button>
        </div>
        <div class="calendar">
          <dx-calendar
            [value]="currentDate"
            (onValueChanged)="onCalendarDateChange($event.value)"
          ></dx-calendar>
        </div>
        <calendar-list
          [dataSource]="listDataSource"
          (listSelectionChanged)="calendarListChanged($event)"
        ></calendar-list>
      </div>
    </left-side-panel>

    <div class="scheduler-container">
      <dx-scheduler
        #schedulerRef
        height="inherit"
        [adaptivityEnabled]="!!(screen.screenChanged | async)?.isXSmall"
        [allDayPanelMode]="'allDay'"
        [dataSource]="tasks"
        [currentView]="currentView"
        [currentDate]="getSchedulerCurrentDate | apply: currentDate"
        [startDayHour]="4"
        [showCurrentTimeIndicator]="false"
        (onOptionChanged)="onSchedulerOptionChanged($event)"
        (onAppointmentClick)="onAppointmentClick($event)"
        (onAppointmentTooltipShowing)="onAppointmentTooltipShowing($event)"
        (onCellClick)="onCellClick($event)"
      >
        <dxi-resource
          fieldExpr="calendarId"
          label="Calendar"
          [dataSource]="resourcesList"
        >
        </dxi-resource>
        <dxi-view type="day"></dxi-view>
        <dxi-view type="workWeek"></dxi-view>
        <dxi-view type="month"></dxi-view>
        <dxi-view type="agenda"></dxi-view>
      </dx-scheduler>
      @if (selectedAppointment) {
        <dx-tooltip
          #tooltipRef
          showEvent="click"
          [target]="selectedAppointment?.target"
          [position]="
          getTooltipPosition
            | apply
              : selectedAppointment
              : isRightPanelOpen
              : (screen.screenChanged | async)?.isSmall
        "
        >
          <scheduler-tooltip
            [selectedAppointmentData]="selectedAppointment?.data"
            (clickEditAppointment)="editSelectedAppointment()"
            (clickDeleteAppointment)="deleteSelectedAppointment($event)"
          ></scheduler-tooltip>
        </dx-tooltip>
      }
      <dx-speed-dial-action
        icon="add"
        [visible]="!!(screen.screenChanged | async)?.isXSmall"
        (onClick)="showAppointmentCreationForm()"
      ></dx-speed-dial-action>
    </div>

    <right-side-panel
      class="right-side-panel"
      [isOpened]="isRightPanelOpen"
      [showOpenButton]="currentView === 'month'"
      [title]="
        ((selectedAppointment?.data?.startDate ?? currentDate) | date: 'EE, MMMM d') ?? ''
      "
      (openedChange)="toggleRightPanelOpen($event)"
    >
      <agenda
        [items]="agendaItems"
        [resources]="resourcesList"
        (clickAppointment)="showAppointmentTooltip($event)"
      ></agenda>
    </right-side-panel>
  </div>
</div>

// packages/vue/src/pages/planning-scheduler.vue
<template>
  <div class="planning-scheduler">
    <div class="view-wrapper">
      <div class="panels">
        <left-side-panel class="left-side-panel">
          <div class="left-side-panel-content">
            <div class="buttons">
              <dx-button
                text="Today"
                @click="onSelectedDateChange"
              />
              <dx-button
                text="Create event"
                type="default"
                @click="showAppointmentCreationForm"
              />
            </div>
            <div class="calendar">
              <dx-calendar
                :value="currentDate"
                @value-changed="onCalendarDateChange"
              />
            </div>
            <calendar-list
              :data-source="defaultCalendarListItems"
              @list-selection-changed="calendarListChanged"
            />
          </div>
        </left-side-panel>

        <div class="scheduler-container">
          <dx-scheduler
            ref="schedulerRef"
            height="inherit"
            :adaptivity-enabled="!!screenInfo.isXSmall"
            :all-day-panel-mode="'hidden'"
            :data-source="tasks"
            :current-view="currentView"
            :current-date="schedulerCurrentDate"
            :start-day-hour="4"
            :show-current-time-indicator="false"
            @option-changed="onSchedulerOptionChange"
            @appointment-click="onAppointmentClick"
            @appointment-tooltip-showing="onAppointmentTooltipShowing"
            @cell-click="onCellClick"
          >
            <dx-resource
              field-expr="calendarId"
              label="Calendar"
              :data-source="resourcesList"
            />
            <dx-view type="day" />
            <dx-view type="workWeek" />
            <dx-view type="month" />
            <dx-view type="agenda" />
          </dx-scheduler>
          <dx-tooltip
            ref="tooltipRef"
            show-event="click"
            :target="selectedAppointment?.target"
            :position="tooltipPosition"
          >
            <scheduler-tooltip
              :selected-appointment-data="selectedAppointment?.data"
              @click-edit-appointment="editSelectedAppointment"
              @click-delete-appointment="deleteSelectedAppointment"
            />
          </dx-tooltip>
          <dx-speed-dial-action
            icon="add"
            :visible="screenInfo.isXSmall"
            @click="showAppointmentCreationForm"
          />
        </div>

        <right-side-panel
          class="right-side-panel"
          :is-opened="isRightPanelOpen"
          :show-open-button="currentView === 'month'"
          :title="formatDate(selectedAppointment?.data.startDate || currentDate, 'EE, MMMM d')"
          @opened-change="toggleRightPanelOpen($event)"
        >
          <agenda-list
            :items="agendaItems"
            :resources="resourcesList"
            @click-appointment="showAppointmentTooltip"
          />
        </right-side-panel>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watchEffect } from 'vue';
import {
  DxButton,
  DxCalendar,
  DxScheduler,
  DxSpeedDialAction,
  DxTooltip,
} from 'devextreme-vue';
import { DxView, DxResource } from 'devextreme-vue/scheduler';
import { formatDate } from 'devextreme/localization';
import { screenInfo } from '@/utils/media-query';
import LeftSidePanel from '@/components/utils/left-side-panel.vue';
import CalendarList from '@/components/utils/calendar-list.vue';
import SchedulerTooltip from '@/components/utils/scheduler-tooltip.vue';
import RightSidePanel from '@/components/utils/right-side-panel.vue';

import { defaultCalendarListItems, getTasksForScheduler } from 'dx-template-gallery-data';
import DataSource from 'devextreme/data/data_source';
import { Task } from '@/types';
import AgendaList, { AgendaItem } from '@/components/utils/agenda-list.vue';

type AppointmentData = {startDate: Date};
type SelectedAppointment = {
  data: AppointmentData,
  target: HTMLElement | undefined };

const schedulerRef = ref<InstanceType<typeof DxScheduler>>();
const tooltipRef = ref<InstanceType<typeof DxTooltip>>();
const currentDate = ref(new Date());
const currentView = ref('workWeek');
const isRightPanelOpen = ref(false);

const tasks = ref<DataSource | null>(null);

const agendaItems = ref<AgendaItem[]>([]);

const schedulerCurrentDate = computed((): Date => {
  const schedulerInstance = schedulerRef?.value?.instance;
  const startViewDate = schedulerInstance?.getStartViewDate();
  const endViewDate = schedulerInstance?.getEndViewDate();

  return (schedulerCurrentDate.value?.getMonth() !== currentDate.value?.getMonth()
    || (startViewDate && startViewDate > currentDate.value)
    || (endViewDate && endViewDate < currentDate.value)
  )
    ? currentDate.value
    : schedulerCurrentDate.value;
});

const resourcesList: Record<string, unknown>[] = defaultCalendarListItems.reduce(
  (res: Record<string, unknown>[], calendarList: {items: []}) => res.concat(calendarList.items),
  [],
);

const selectedAppointment = ref<SelectedAppointment | null>(null);
const rightPanelOpen = ref(false);

const tooltipPosition = computed(() => {
  if (screenInfo.value.isSmall) {
    return 'bottom';
  }

  const appointmentTarget = selectedAppointment.value?.target;
  const classList = (appointmentTarget as unknown as HTMLElement[])?.[0]?.classList
    || appointmentTarget?.classList;

  return classList?.contains('dx-list') && rightPanelOpen ? 'left' : 'top';
});

watchEffect(() => {
  const deps = [tasks.value, currentView.value, currentDate.value, isRightPanelOpen.value];
  if (deps.length) {
    setTimeout(() => schedulerRef.value?.instance?.repaint());
  }
});

getTasksForScheduler().then((data: Task[]) => {
  tasks.value = new DataSource(data);
});

function toggleRightPanelOpen(isOpen?: boolean) {
  isRightPanelOpen.value = isOpen || !isRightPanelOpen.value;
  console.log('------toggleRightPanelOpen---->', isRightPanelOpen.value);
}

function findAllAppointmentsForDay(selectedAppointmentData?: AppointmentData) {
  if (!tasks.value) {
    return [];
  }
  const appointments = tasks.value.items();
  if (appointments.length === 0 || !selectedAppointmentData) {
    return [];
  }
  return appointments.filter(
    (appointment) => appointment.startDate.getDate() === selectedAppointmentData.startDate.getDate()
        && appointment.startDate.getMonth() === selectedAppointmentData.startDate.getMonth(),
  );
}

function updateAgenda(appointmentData?: AppointmentData) {
  agendaItems.value = findAllAppointmentsForDay(appointmentData);
}

function onCalendarDateChange({ value }: { value: Date }) {
  currentDate.value = value;
  updateAgenda({ startDate: currentDate.value });
}

function showAppointmentCreationForm(appointment: SelectedAppointment| null) {
  schedulerRef.value?.instance.showAppointmentPopup(appointment?.data, !appointment);
}

function onSelectedDateChange(e?: Date) {
  const date = e instanceof Date ? e : new Date();
  currentDate.value = date;
  selectedAppointment.value = { data: { startDate: date }, target: undefined };
  updateAgenda({ startDate: date });
}

function calendarListChanged(selectedCalendars: {id: string}[]) {
  const filters = selectedCalendars
    .flatMap((calendar: {id: string}) => [['calendarId', '=', calendar.id], 'or']).slice(0, -1);

  tasks.value?.filter(filters.length > 0 ? filters : null);
  tasks.value?.load();
  updateAgenda({ startDate: currentDate.value });
}

function onCurrentViewChange(view: string) {
  currentView.value = view;

  if (currentView.value === 'month' && !screenInfo.value.isSmall) {
    isRightPanelOpen.value = true;
    updateAgenda({ startDate: currentDate.value });
  }
}

function onSchedulerOptionChange({ name, value }: {name: string, value: string}) {
  if (name === 'currentView') {
    onCurrentViewChange(value);
  }
}

function onAppointmentClick(e: {appointmentData: AppointmentData, targetElement: HTMLElement}) {
  const { appointmentData } = e;
  selectedAppointment.value = { data: appointmentData, target: e.targetElement };

  if (currentView.value === 'month') {
    updateAgenda(appointmentData);
    toggleRightPanelOpen(true);
  }
}

function onAppointmentTooltipShowing(
  e: {appointments: {
      appointmentData: AppointmentData }[],
    targetElement: HTMLElement,
    cancel: boolean},
) {
  e.cancel = true;

  const { appointmentData } = e.appointments[0];
  const isAppointmentCollectorClicked = ({ targetElement }: {targetElement: HTMLElement}) => (targetElement as unknown as HTMLElement[])?.[0]?.classList.contains('dx-scheduler-appointment-collector');

  selectedAppointment.value = { data: appointmentData, target: e.targetElement };

  if (currentView.value === 'month' || isAppointmentCollectorClicked(e)) {
    updateAgenda(appointmentData);
  }

  if ((currentView.value === 'month' && screenInfo.value.isSmall)
    || isAppointmentCollectorClicked(e)) {
    toggleRightPanelOpen(true);
  } else {
    tooltipRef.value?.instance.show();
  }
}

function onCellClick({ cellData }: {cellData: AppointmentData}) {
  onSelectedDateChange(cellData.startDate);

  if (currentView.value === 'month' && cellData) {
    const cellAppointments = findAllAppointmentsForDay(cellData);

    if (cellAppointments.length > 1) {
      selectedAppointment.value = { data: cellData, target: undefined };
      agendaItems.value = cellAppointments;
      toggleRightPanelOpen(true);
    }
  }
}

function showAppointmentTooltip(e: {itemData: AppointmentData, element: HTMLElement}) {
  schedulerRef.value?.instance.showAppointmentTooltip(e.itemData, e.element);
}

function editSelectedAppointment() {
  showAppointmentCreationForm(selectedAppointment.value);
  tooltipRef.value?.instance.hide();
}

function deleteSelectedAppointment(appointmentData: AppointmentData) {
  schedulerRef.value?.instance.deleteAppointment(selectedAppointment.value?.data);
  tooltipRef.value?.instance.hide();
  agendaItems.value = findAllAppointmentsForDay(appointmentData);
}
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

@include separator();

.planning-scheduler {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
  height: 100%;

  .view-wrapper {
    position: relative;
    flex-direction: column;
    display: flex;
    height: inherit;

    .panels {
      display: flex;
      flex-wrap: wrap;
      height: inherit;
      gap: 16px;
      padding: var(--content-padding) var(--content-padding) var(--theme-padding);

      .left-side-panel-content {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        gap: var(--theme-padding);

        .buttons {
          display: flex;
          width: 100%;
          gap: 16px;
          margin-top: var(--theme-padding);
          padding: 0 var(--theme-padding);

          .dx-button {
            width: calc((100% - var(--theme-padding)) / 2);
            font-size: 13px;
            border-radius: 4px;
          }
        }

        .calendar {
          align-self: center;
          padding: var(--theme-padding);

          .dx-calendar {
            width: var(--calendar-width);
          }
        }
      }

      :deep(.scheduler-container) {
        flex: 1;
        height: inherit;
        border: 1px grey;
        border-radius: 8px;

        .dx-scheduler-header {
          border-radius: 8px 8px 0 0;
          height: var(--scheduler-toolbar-height);
        }

        .dx-scheduler-appointment-content {
          color: #333;
        }

        .dx-scheduler-work-space {
          border-radius: 0 0 8px 8px;
        }
      }
    }
  }
}
</style>
