// packages/react/src/pages/reset-password-form/reset-password-form.tsx
import React from 'react';

import { CardAuth, ResetPasswordForm } from '../../components';

export const ResetPasswordPage = () => {
  return (
    <CardAuth
      title='Reset Password'
      description='Please enter the email address that you used to register, and we will send you a link to reset your password via Email.'
    >
      <ResetPasswordForm
        signInLink='/sign-in-form'
        buttonLink='/reset-password-form'
      />
    </CardAuth>
  );
};

// packages/vue/src/pages/reset-password-form.vue
<template>
  <CardAuth
    title="Reset Password"
    :description="desc"
  >
    <ResetPasswordForm
      signInLink="/sign-in-form"
      buttonLink="/reset-password-form"
    ></ResetPasswordForm>
  </CardAuth>
</template>

<script setup lang="ts">
import CardAuth from '@/components/card-auth.vue';
import ResetPasswordForm from '@/components/reset-password-form.vue';

const desc = 'Please enter the email address that you used to register, and we will send you a link to reset your password via Email.';
</script>

<style scoped lang="scss">
@use "@/variables" as *;

</style>
