// packages/angular/src/app/pages/sign-up-form/sign-up-form.component.ts
import { Component } from '@angular/core';

import { CardAuthComponent, CreateAccountFormComponent } from 'src/app/components';

@Component({
    selector: 'app-sign-up-form',
    templateUrl: './sign-up-form.component.html',
    styleUrls: ['./sign-up-form.component.scss'],
    imports: [
      CreateAccountFormComponent,
      CardAuthComponent,
    ],
})
export class AppSignUpComponent {

  defaultLink = '/sign-in-form';

  buttonLink = '/sign-up-form';
}

<app-card-auth title="Register">
  <app-create-account-form
    [redirectLink]="defaultLink"
    [buttonLink]="buttonLink"
  ></app-create-account-form>
</app-card-auth>

// packages/vue/src/pages/sign-up-form.vue
<template>
  <CardAuth title="Sign Up">
    <CreateAccountForm
      redirectLink="/sign-in-form"
      buttonLink="/sign-up-form"
    ></CreateAccountForm>
  </CardAuth>
</template>

<script setup lang="ts">
import CardAuth from '@/components/card-auth.vue';
import CreateAccountForm from '@/components/create-account-form.vue';

</script>

<style scoped lang="scss">
@use "@/variables" as *;

</style>
