// packages/react/src/components/revenue-snapshot-card/RevenueSnapshotCard.tsx
import React from 'react';
import PieChart, { Font, Label, Legend, Margin, Series, Size } from 'devextreme-react/pie-chart';
import { CardAnalytics } from '../card-analytics/CardAnalytics';
import { SaleOrOpportunityByCategory } from '../../types/analytics';

export const RevenueSnapshotCard = ({ datasource }: { datasource: SaleOrOpportunityByCategory[] }) => (
  <CardAnalytics title='Revenue Snapshot (All Products)' contentClass='sales-by-category'>
    <PieChart dataSource={datasource} type='doughnut' diameter={0.8} innerRadius={0.6}>
      <Series argumentField='name' valueField='value'>
        <Label backgroundColor='none' radialOffset={-20} visible customizeText={({ percentText }) => percentText}>
          <Font color='#757575' size={15} />
        </Label>
      </Series>
      <Legend>
        <Margin top={70} />
      </Legend>
      <Size height={270} />
    </PieChart>
  </CardAnalytics>
);

// packages/angular/src/app/components/utils/revenue-snapshot-card/revenue-snapshot-card.component.ts
import { Component, Input } from '@angular/core';
import { CardAnalyticsComponent } from '../../library/card-analytics/card-analytics.component';
import { DxPieChartModule } from 'devextreme-angular/ui/pie-chart';
import { SalesOrOpportunitiesByCategory } from 'src/app/types/analytics';

@Component({
  selector: 'revenue-snapshot-card',
  templateUrl: './revenue-snapshot-card.component.html',
  imports: [
    CardAnalyticsComponent,
    DxPieChartModule,
  ],
})
export class RevenueSnapshotCardComponent {
  @Input() data: SalesOrOpportunitiesByCategory;

  customizeSaleText(arg: { percentText: string }) {
    return arg.percentText;
  }
}


<card-analytics
  titleText="Revenue Snapshot (All Products)"
  contentClass="sales-by-category"
>
  <dx-pie-chart
    [dataSource]="data"
    type="doughnut"
    [diameter]="0.8"
    [innerRadius]="0.6"
  >
    <dxi-pie-chart-series argumentField="name" valueField="value">
      <dxo-pie-chart-label
        backgroundColor="none"
        [radialOffset]="-20"
        [visible]="true"
        [customizeText]="customizeSaleText"
      >
        <dxo-pie-chart-font color="#757575" [size]="15"></dxo-pie-chart-font>
      </dxo-pie-chart-label>
    </dxi-pie-chart-series>

    <dxo-pie-chart-legend>
      <dxo-pie-chart-margin [top]="70"></dxo-pie-chart-margin>
    </dxo-pie-chart-legend>

    <dxo-pie-chart-size [height]="270"> </dxo-pie-chart-size>
  </dx-pie-chart>
</card-analytics>
