// packages/react/src/pages/auth-reset-password/auth-reset-password.tsx
import React from 'react';

import { CardAuth, ResetPasswordForm } from '../../components';

export const ResetPasswordPage = () => {
  return (
    <CardAuth
      title='Reset Password'
      description='Please enter the email address that you used to register, and we will send you a link to reset your password via Email.'
    >
      <ResetPasswordForm signInLink='/signin-form-page' buttonLink='/reset-password-form-page' />
    </CardAuth>
  );
};

// packages/angular/src/app/pages/auth-reset-password/auth-reset-password.component.ts
import { Component, NgModule } from '@angular/core';


import { CardAuthModule, ResetPasswordFormModule } from 'src/app/components';

@Component({
  selector: 'app-auth-reset-password',
  templateUrl: './auth-reset-password.component.html',
  styleUrls: ['./auth-reset-password.component.scss']
})
export class AuthResetPasswordComponent {

  defaultLink = '/signin-form-page';

  buttonLink = '/reset-password-form-page';

  constructor() { }

}

@NgModule({
  imports: [
    CardAuthModule,
    ResetPasswordFormModule,
  ],
  providers: [],
  exports: [AuthResetPasswordComponent],
  declarations: [AuthResetPasswordComponent],
})
export class AuthResetPasswordModule { }


<app-card-auth title="Reset Password" description="Please enter the email address that you used to register, and we will send you a link to reset your password via Email.">
  <app-reset-password-form [signInLink]="defaultLink" [buttonLink]="buttonLink"></app-reset-password-form >
</app-card-auth>
