// packages/react/src/components/utils/chat-card-component/ChatCardComponent.tsx
import './ChatCardComponent.scss';

import React, { useCallback } from 'react';

import Chat, { ChatTypes } from 'devextreme-react/chat';
import Button from 'devextreme-react/button';
import { ChatEmptyView, ChatEmptyViewTexts } from '../chat-empty-view/ChatEmptyView';

type ChatCardComponentProps = {
  messages: ChatTypes.Message[];
  currentUser: ChatTypes.User;
  typingUsers?: ChatTypes.User[];
  alerts?: ChatTypes.Alert[];
  isProcessing?: boolean;
  onMessageEntered: (event: ChatTypes.MessageEnteredEvent) => void;
  onPromptClick: (messageText: string) => void;
  onResetClick: () => void;
  onCloseClick: () => void;
  onUnpinClick: () => void;
};

export const ChatCardComponent = ({
  messages,
  currentUser,
  typingUsers = [],
  alerts = [],
  isProcessing = false,
  onMessageEntered,
  onPromptClick,
  onResetClick,
  onCloseClick,
  onUnpinClick,
}: ChatCardComponentProps) => {
  const renderEmptyView = useCallback(
    (texts: ChatEmptyViewTexts) => (
      <ChatEmptyView texts={texts} onPromptClick={onPromptClick} />
    ),
    [onPromptClick]
  );

  return (
    <section className='chat-card-component'>
      <div className='chat-card-component__header'>
        <div className='chat-card-component__title-section'>
          <span className='chat-card-icon dx-icon dx-icon-sparkle' aria-hidden />
          <div className='chat-card-component__title-content'>
            <div className='chat-card-component__title'>AI Data Insights</div>
          </div>
        </div>
        <div className='chat-card-component__actions'>
          <Button
            icon='clearformat'
            stylingMode='text'
            hint='Reset chat'
            onClick={onResetClick}
          />
          <Button
            icon='unpin'
            stylingMode='text'
            hint='Unpin'
            onClick={onUnpinClick}
          />
          <Button
            icon='close'
            stylingMode='text'
            hint='Close chat'
            onClick={onCloseClick}
          />
        </div>
      </div>

      <div className='chat-card-component__body'>
        <Chat
          className={`chat-card-component__chat${isProcessing ? ' chat-disabled' : ''}`}
          user={currentUser}
          items={messages}
          typingUsers={typingUsers}
          alerts={alerts}
          height='100%'
          emptyViewRender={renderEmptyView}
          showAvatar={false}
          showDayHeaders={false}
          onMessageEntered={onMessageEntered}
        />
      </div>
    </section>
  );
};

// packages/angular/src/app/components/utils/chat-card-component/chat-card-component.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxButtonModule, DxChatModule } from 'devextreme-angular';
import { DxChatTypes } from 'devextreme-angular/ui/chat';

type Message = DxChatTypes.Message;
type MessageEnteredEvent = DxChatTypes.MessageEnteredEvent;
type User = DxChatTypes.User;
type Alert = DxChatTypes.Alert;

import { ChatEmptyViewComponent } from '../chat-empty-view/chat-empty-view.component';
import { ChatMessageRenderComponent } from '../chat-message-render/chat-message-render.component';

@Component({
  selector: 'chat-card-component',
  templateUrl: './chat-card-component.component.html',
  styleUrls: ['./chat-card-component.component.scss'],
  imports: [
    CommonModule,
    DxButtonModule,
    DxChatModule,
    ChatEmptyViewComponent,
    ChatMessageRenderComponent,
  ],
})
export class ChatCardComponent {
  @Input() messages: Message[] = [];

  @Input() currentUser: User = {};

  @Input() typingUsers: User[] = [];

  @Input() alerts: Alert[] = [];

  @Input() isProcessing = false;

  @Output() messageEntered = new EventEmitter<MessageEnteredEvent>();

  @Output() promptClick = new EventEmitter<string>();

  @Output() resetClick = new EventEmitter<void>();

  @Output() closeClick = new EventEmitter<void>();

  @Output() unpinClick = new EventEmitter<void>();
}

<section class="chat-card-component">
  <div class="chat-card-component__header">
    <div class="chat-card-component__title-section">
      <span class="chat-card-icon dx-icon dx-icon-sparkle" aria-hidden="true"></span>
      <div class="chat-card-component__title-content">
        <div class="chat-card-component__title">AI Data Insights</div>
      </div>
    </div>

    <div class="chat-card-component__actions">
      <dx-button
        icon="clearformat"
        stylingMode="text"
        hint="Reset chat"
        (onClick)="resetClick.emit()"
      ></dx-button>
      <dx-button
        icon="unpin"
        stylingMode="text"
        hint="Unpin"
        (onClick)="unpinClick.emit()"
      ></dx-button>
      <dx-button
        icon="close"
        stylingMode="text"
        hint="Close chat"
        (onClick)="closeClick.emit()"
      ></dx-button>
    </div>
  </div>

  <div class="chat-card-component__body">
    <dx-chat
      [class]="'chat-card-component__chat' + (isProcessing ? ' chat-disabled' : '')"
      [user]="currentUser"
      [items]="messages"
      [typingUsers]="typingUsers"
      [alerts]="alerts"
      height="100%"
      emptyViewTemplate="emptyView"
      messageTemplate="messageTemplate"
      [showAvatar]="false"
      [showDayHeaders]="false"
      (onMessageEntered)="messageEntered.emit($event)"
    >
      <div *dxTemplate="let data of 'emptyView'" class="chat-card-component__empty-wrapper">
        <chat-empty-view
          [texts]="data.texts"
          (promptClick)="promptClick.emit($event)"
        ></chat-empty-view>
      </div>
      <div *dxTemplate="let data of 'messageTemplate'">
        <chat-message-render [text]="data.message?.text || ''"></chat-message-render>
      </div>
    </dx-chat>
  </div>
</section>
