// packages/vue/src/components/utils/revenue-total-ticker.vue
<template>
  <ticker-card
    title="Revenue Total"
    :data="props.data"
    :percentage="14.7"
  />
</template>

<script setup lang="ts">
import TickerCard from '@/components/library/ticker-card.vue';
import { Sales } from '../../types/analytics';

const props = withDefaults(defineProps<{
  data: Sales | null
}>(), {
  data: () => null,
});
</script>

// packages/angular/src/app/components/utils/revenue-total-ticker/revenue-total-ticker.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Sales } from 'src/app/types/analytics';
import { TickerCardComponent } from 'src/app/components/library/ticker-card/ticker-card.component';

@Component({
  selector: 'revenue-total-ticker',
  templateUrl: 'revenue-total-ticker.component.html',
  imports: [
    CommonModule,
    TickerCardComponent,
  ],
})

export class RevenueTotalTickerComponent {
  @Input() data: Sales | null = null;
}


<ticker-card
  titleText="Revenue Total"
  [data]="data"
  [percentage]="14.7"
  contentClass="revenue-total"
>
</ticker-card>
