// packages/react/src/components/library/user-panel/UserPanel.tsx
import React, { useRef, useCallback } from 'react';
import DropDownButton from 'devextreme-react/drop-down-button';
import { Template } from 'devextreme-react/core/template';
import { UserMenuSection } from '../user-menu-section/UserMenuSection';
import type { UserPanelProps } from '../../../types';
import { useAuth } from '../../../contexts/auth';
import List from 'devextreme-react/list';
import './UserPanel.scss';

export const UserPanel = ({ menuMode }: UserPanelProps) => {
  const { user } = useAuth();
  const listRef = useRef<List>(null);

  const dropDownButtonAttributes = {
    class: 'user-button'
  };

  const buttonDropDownOptions = {
    width: 'auto'
  };

  const dropDownButtonContentReady = useCallback(({ component }) => {
    component.registerKeyHandler('downArrow', () => {
      listRef.current?.instance.focus();
    });
  }, [listRef]);

  return (
    <div className='user-panel'>
      {menuMode === 'context' && (
        <DropDownButton stylingMode='text'
          icon={user?.avatarUrl} showArrowIcon={false}
          elementAttr={dropDownButtonAttributes}
          dropDownOptions={buttonDropDownOptions}
          dropDownContentTemplate='dropDownTemplate'
          onContentReady={dropDownButtonContentReady}>
          <Template name='dropDownTemplate'>
            <UserMenuSection listRef={listRef} />
          </Template>
        </DropDownButton>
      )}
      {menuMode === 'list' && (
        <UserMenuSection showAvatar />
      )}
    </div>
  );
};

// packages/angular/src/app/components/library/user-panel/user-panel.component.ts
import { Component, Input, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DxDropDownButtonModule } from 'devextreme-angular/ui/drop-down-button';
import { UserMenuSectionComponent } from '../user-menu-section/user-menu-section.component';
import { IUser } from '../../../services/auth.service';
@Component({
    selector: 'user-panel',
    templateUrl: 'user-panel.component.html',
    styleUrls: ['./user-panel.component.scss'],
    imports: [
      DxDropDownButtonModule,
      UserMenuSectionComponent,
      CommonModule,
    ],
})

export class UserPanelComponent {
  @Input()
  menuItems: any;

  @Input()
  menuMode!: string;

  @Input()
  user!: IUser | null;

  @ViewChild(UserMenuSectionComponent) userMenuSection: UserMenuSectionComponent;

  handleDropDownButtonContentReady({ component }) {
    component.registerKeyHandler('downArrow', () => {
      this.userMenuSection.userInfoList.nativeElement.focus();
    });
  }
}

<div class="user-panel">
  @if (menuMode === 'context') {
    <dx-drop-down-button
      stylingMode="text"
      dropDownContentTemplate="dropDownTemplate"
      [icon]="user?.avatarUrl"
      [showArrowIcon]="false"
      [elementAttr]="{
      class: 'user-button'
    }"
      [dropDownOptions]="{
      width: 'auto'
    }"
      (onContentReady)="handleDropDownButtonContentReady($event)"
    >
      <div *dxTemplate="let data of 'dropDownTemplate'">
        <user-menu-section
          [menuItems]="menuItems"
          [showAvatar]="false"
          [user]="user"
        ></user-menu-section>
      </div>
    </dx-drop-down-button>
  }
  @if (menuMode === 'list') {
    <div>
      <user-menu-section
        [menuItems]="menuItems"
        [showAvatar]="true"
        [user]="user"
      ></user-menu-section>
    </div>
  }
</div>
