// packages/react/src/components/change-profile-password-form/ChangeProfilePasswordForm.tsx
import './ChangeProfilePasswordForm.scss';
import React, { useState, useCallback, useMemo, useRef } from 'react';
import notify from 'devextreme/ui/notify';
import { ValidationRule } from 'devextreme/ui/validation_rules';
import Form, { Item, Label } from 'devextreme-react/form';
import { FormPopup } from '../form-popup/FormPopup';

const saveNewPassword = (): void => {
  notify({ message: 'Password Changed', position: { at: 'bottom center', my: 'bottom center' } }, 'success');
};

export const ChangeProfilePasswordForm = ({ visible }) => {
  const formPopupRef = useRef<FormPopup>();
  const confirmField = useRef();
  const [isSaveDisabled, setIsSaveDisabled] = useState(true);
  const [formData, setFormData] = useState<Record<string, any>>({});
  // figure out onvisiblechange event emitters

  const confirmPasswordValidators = useMemo((): ValidationRule[] => {
    return [{
      type: 'compare',
      message: 'Passwords do not match',
      comparisonTarget: () => formData.password,
    }];
  }, [formData]);

  const onFieldChanged = useCallback(async () => {
    const formValues = Object.entries(formData);
    setIsSaveDisabled(await (formValues.length != 3 || !!formValues.find(([key, value]) => !value) || !formPopupRef.current?.isValid()));
  }, [formData]);

  return <FormPopup
    ref={formPopupRef}
    titleText='Change Password'
    visible={visible}
    width={360}
    wrapperAttr="{class: 'change-profile-password-popup'}"
    isSaveDisabled='isSaveDisabled'
    onSave={saveNewPassword}
    onVisibleChange={onVisibleChange}
  >
    <Form id='form' // #form is id?
      labelMode='outside'
      showColonAfterLabel
      labelLocation='top'>
      <Item>
        <Label text='Current Password' />
        <PasswordTextBox
          value={formData['currentPassword']} // double binding
          placeholder='Current Password'
          onValueChange={onFieldChange}
        />
      </Item>

      <Item>
        <div className='h-separator' />
      </Item>

      <Item>
        <Label text='Password' />
        <PasswordTextBox
          value={formData['password']} // double binding
          placeholder='Password'
          onValueChange={onNewPasswordChange}
        />
      </Item>

      <Item>
        <Label text='Confirm Password' />
        <PasswordTextBox
          ref={confirmField}
          value={formData['confirmedPassword']}
          placeholder='Confirm Password'
          validators={confirmPasswordValidators}
          onValueChange={onFieldChange}
        />
      </Item>
    </Form>
  </FormPopup>;
};

// packages/angular/src/app/components/library/change-profile-password-form/change-profile-password-form.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output, ViewChild } from '@angular/core';
import { DxFormModule } from 'devextreme-angular/ui/form';
import { DxLoadIndicatorModule } from 'devextreme-angular/ui/load-indicator';
import notify from 'devextreme/ui/notify';
import { ValidationRule } from 'devextreme-angular/common';

import { PasswordTextBoxComponent } from 'src/app/components/library/password-text-box/password-text-box.component';
import { FormPopupComponent } from 'src/app/components/utils/form-popup/form-popup.component';

@Component({
  selector: 'change-profile-password-form',
  templateUrl: './change-profile-password-form.component.html',
  styleUrls: ['./change-profile-password-form.component.scss'],
  imports: [
    CommonModule,
    DxFormModule,
    DxLoadIndicatorModule,
    PasswordTextBoxComponent,
    FormPopupComponent,
  ],
})
export class ChangeProfilePasswordFormComponent {
  @ViewChild(FormPopupComponent, { static: true }) formPopup;

  @ViewChild('confirmField', { static: true }) confirmField: PasswordTextBoxComponent;

  @Input() visible = false;

  @Output() visibleChange = new EventEmitter<boolean>();

  isSaveDisabled = true;

  formData: Record<string, any> = {};

  confirmPasswordValidators: ValidationRule[] = [
    {
      type: 'compare',
      message: 'Passwords do not match',
      comparisonTarget: () => this.formData.password,
    },
  ];

  async onFieldChanged() {
    const formValues = Object.entries(this.formData);

    this.isSaveDisabled =  await (formValues.length != 3 || !!formValues.find(([_, value]) => !value) || !this.formPopup.isValid());
  }

  saveNewPassword(): void {
    notify({ message: 'Password Changed', position: {at: 'bottom center', my: 'bottom center'}}, 'success');
  }

  checkConfirm(): void {
    this.confirmField.revalidate();
  }

  onNewPasswordChanged() {
    this.checkConfirm();
    this.onFieldChanged();
  }

  changeVisible(visible: boolean): void {
    this.visible = visible;
    this.visibleChange.emit(this.visible);
  }
}

<form-popup
  titleText="Change Password"
  [visible]="visible"
  [width]="360"
  [height]="410"
  [wrapperAttr]="{ class: 'change-profile-password-popup' }"
  [isSaveDisabled]="isSaveDisabled"
  (save)="saveNewPassword()"
  (visibleChange)="changeVisible($event)"
>
  <dx-form
    #form
    labelMode="outside"
    labelLocation="top"
    [showColonAfterLabel]="true"
  >
    <dxi-item>
      <dxo-label text="Old Password"></dxo-label>
      <password-text-box
        placeholder="Enter old password"
        stylingMode="filled"
        [(value)]="formData['currentPassword']"
        (valueChanged)="onFieldChanged()"
      ></password-text-box>
    </dxi-item>

    <dxi-item>
      <div class="h-separator"></div>
    </dxi-item>

    <dxi-item>
      <dxo-label text="New Password"></dxo-label>
      <password-text-box
        placeholder="Create new password"
        stylingMode="filled"
        [(value)]="formData['password']"
        (valueChanged)="onNewPasswordChanged()"
      ></password-text-box>
    </dxi-item>

    <dxi-item>
      <dxo-label text="Re-enter Password"></dxo-label>
      <password-text-box
        #confirmField
        placeholder="Confirm new password"
        stylingMode="filled"
        [(value)]="formData['confirmedPassword']"
        [validators]="confirmPasswordValidators"
        (valueChanged)="onFieldChanged()"
      >
      </password-text-box>
    </dxi-item>
  </dx-form>
</form-popup>
