// packages/angular/src/app/components/password-text-box/password-text-box.component.ts
import {
  Component, EventEmitter, Input, NgModule, Output,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxSelectBoxModule, DxTextBoxModule, DxValidatorModule } from 'devextreme-angular';
import { ValidationRule } from 'devextreme/ui/validation_rules';
import { ApplyPipeModule } from '../../pipes/apply.pipe';
import { ContactStatusModule } from '../contact-status/contact-status.component';

@Component({
  selector: 'password-text-box',
  templateUrl: 'password-text-box.component.html',
  styles: [],
})
export class PasswordTextBoxComponent {
  @Input() value: string;

  @Input() placeholder = '';

  @Input() stylingMode = 'outlined';

  @Input() validators: ValidationRule[] = [];

  @Output() valueChange = new EventEmitter<string>();

  isPasswordMode = true;

  switchMode = () => {
    this.isPasswordMode = !this.isPasswordMode;
  }
}

@NgModule({
  imports: [
    ApplyPipeModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    ContactStatusModule,
    DxValidatorModule,
    CommonModule],
  declarations: [PasswordTextBoxComponent],
  exports: [PasswordTextBoxComponent],
})
export class PasswordTextBoxModule {}

<dx-text-box [value]="value"
             [stylingMode]="stylingMode"
             valueChangeEvent="keyup input change"
             [placeholder]="placeholder"
             [mode]="isPasswordMode ? 'password' : 'text'"
             (valueChange)="valueChange.emit($event)"
>
  <dxi-button
    name="today"
    location="after"
    [options]="{
              visible: value?.length > 0,
              icon: 'assets/icons/eye.svg',
              onClick: switchMode
            }"
  ></dxi-button>
  <dx-validator
    [validationRules]="[{type: 'required', message: 'Password is required'}] | apply
            : 'concat'
            : (validators || [])"></dx-validator>
</dx-text-box>

// packages/react/src/components/password-text-box/PasswordTextBox.tsx
import React, { useState } from 'react';
import TextBox, { Button } from 'devextreme-react/text-box';
import Validator from 'devextreme-react/validator';

export const PasswordTextBox = ({ value, onValueChange, placeholder, stylingMode, validators }) => {
  const [isPasswordMode, setIsPasswordMode] = useState(true);

  const switchMode = () => {
    setIsPasswordMode(!isPasswordMode);
  };

  return <TextBox value={value}
    stylingMode={stylingMode}
    valueChangeEvent='keyup input change'
    placeholder={placeholder}
    mode={isPasswordMode ? 'password' : 'text'}
    onValueChange={onValueChange}
  >
    <Button
      name='today'
      location='after'
      options={{
        visible: value?.length > 0,
        icon: 'assets/icons/eye.svg',
        onClick: switchMode
      }}
    />
    <Validator validationRules={
      validators ||
      [{
        type: 'required',
        message: 'Password is required'
      }]}
    />
  </TextBox>;
};
