// packages/vue/src/components/theme-switcher.vue
<template>
  <dx-button
    class="theme-button"
    :icon="`icons/${theme === 'dark' ? 'sun' : 'moon'}.svg`"
    @click="onClickButton"
  />
</template>

<script setup lang="ts">
import { DxButton } from 'devextreme-vue/button';
import { ref } from 'vue';
import { currentTheme as currentVizTheme, refreshTheme } from 'devextreme/viz/themes';

const storageKey = 'themeViewer';
const themeMarker = 'theme-';

function getCurrentTheme(): 'dark' | 'light' {
  return window.localStorage[storageKey] || 'light';
}

function getThemeStyleSheets() {
  return [...document.styleSheets]
    .filter((styleSheet) => styleSheet?.href?.includes(themeMarker));
}

function switchTheme(themeName?: string) {
  themeName = themeName || getCurrentTheme();

  const enabledStyleSheet: CSSStyleSheet[] = [];
  getThemeStyleSheets().forEach((styleSheet) => {
    if (styleSheet?.href?.includes(`${themeMarker}${themeName}`)) {
      enabledStyleSheet.push(styleSheet);
    } else {
      styleSheet.disabled = true;
    }
  });

  enabledStyleSheet.forEach((styleSheet) => {
    styleSheet.disabled = false;
  });

  window.localStorage[storageKey] = themeName;
  currentVizTheme(currentVizTheme().replace(/\.[a-z]+\.compact$/, `.${themeName}.compact`));
  refreshTheme();
}

switchTheme();

const theme = ref(getCurrentTheme());

function onClickButton() {
  theme.value = theme.value === 'dark' ? 'light' : 'dark';
  switchTheme(theme.value);
}
</script>

<style scoped lang="scss">
</style>

// packages/angular/src/app/components/theme-switcher/theme-switcher.component.ts
import {
  Component, NgModule,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxButtonModule } from "devextreme-angular";

import { currentTheme as currentVizTheme, refreshTheme } from 'devextreme/viz/themes';

type Theme = 'dark'| 'light';

const storageKey = 'themeViewer';
const themeMarker = 'theme-';

function getCurrentTheme(): Theme {
  return window.localStorage[storageKey] || 'light';
}

function getThemeStyleSheets() {
  return   [...(document.styleSheets as unknown as any[])]
    .filter((styleSheet) => styleSheet?.href?.includes(themeMarker));
}

function switchTheme(themeName?: Theme) {
  themeName = themeName || getCurrentTheme();

  getThemeStyleSheets().forEach((styleSheet) => {
      styleSheet.disabled = !styleSheet?.href?.includes(`${themeMarker}${themeName}`);
    });

  window.localStorage[storageKey] = themeName;

  currentVizTheme(currentVizTheme().replace(/\.[a-z]+\.compact$/, `.${themeName}.compact`));
  refreshTheme();
}

switchTheme();

@Component({
  selector: 'theme-switcher',
  template: `
    <dx-button class="theme-button"
               [icon]="'assets/icons/' + (theme !== 'dark' ? 'moon' : 'sun') +'.svg'"
               (click)="onClickButton()">
    </dx-button>
`,
  styleUrls: [],
})
export class ThemeSwitcherComponent {
  theme = getCurrentTheme();

  onClickButton() {
    this.theme = this.theme === 'dark' ? 'light' : 'dark';

    switchTheme(this.theme)
  }
}

@NgModule({
  imports: [CommonModule, DxButtonModule],
  declarations: [ThemeSwitcherComponent],
  exports: [ThemeSwitcherComponent],
})
export class ThemeSwitcherModule { }
