// packages/angular/src/app/components/library/task-kanban-card/task-kanban-card.component.ts
import {Component, inject, Input} from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { DxButtonModule, DxToastModule } from 'devextreme-angular';
import notify from 'devextreme/ui/notify';

import { Task } from 'src/app/types/task';
import { UserAvatarComponent } from 'src/app/components/library/user-avatar/user-avatar.component';

@Component({
    selector: 'task-kanban-card',
    templateUrl: './task-kanban-card.component.html',
    styleUrls: ['./task-kanban-card.component.scss'],
    imports: [
      DxButtonModule,
      DxToastModule,
      CommonModule,
      UserAvatarComponent,
    ],
})
export class TaskKanbanCardComponent {
  private router = inject(Router);

  @Input() task: Task;

  getAvatarText = (name: string) => name.split(' ').map((name) => name[0]).join('');

  notify = (e) => {
    e.event.stopPropagation();
    notify(`Edit '${this.task.text}' card event`);
  };

  navigateToDetails = () => {
    this.router.navigate(['/planning-task-details']);
  };
}


<div
  class="card dx-theme-text-color dx-theme-background-color"
  (click)="navigateToDetails()"
>
  <div class="card-wrapper" class="priority-{{ task.priority | lowercase }}">
    <div class="card-priority"></div>
    <dx-button
      icon="edit"
      stylingMode="text"
      (onClick)="notify($event)"
    ></dx-button>
    <div class="card-content">
      <div class="card-subject dx-theme-text-color">{{ task.text }}</div>
      <div class="card-data">
        <span class="priority">{{ task.priority }}</span>
        <span class="date dx-theme-text-color">{{
          task.dueDate | date: 'MM/dd/yyyy'
        }}</span>
      </div>
      <div class="card-assignee">
        <span class="company dx-theme-text-color">{{ task.company }}</span>
        <user-avatar [dataLetters]="getAvatarText(task.owner)"></user-avatar>
      </div>
    </div>
  </div>
</div>

// packages/react/src/components/library/task-kanban-card/TaskKanbanCard.tsx
import React, { useCallback } from 'react';
import notify from 'devextreme/ui/notify';
import { useNavigate } from 'react-router-dom';

import Button from 'devextreme-react/button';
import { formatDate } from 'devextreme/localization';

import { Task } from '../../../types/task';

import { UserAvatar } from '../user-avatar/UserAvatar';

import './TaskKanbanCard.scss';

const onClick = (task: Task) => (e) => {
  e.event.stopPropagation();
  notify(`Edit '${task.text}' card event`);
};

export const TaskKanbanCard = ({ task }: { task: Task }) => {
  const navigate = useNavigate();

  const navigateToDetails = useCallback(() => {
    navigate('/planning-task-details');
  }, []);

  return (
    <div className='kanban-card dx-card dx-theme-text-color dx-theme-background-color' onClick={navigateToDetails}>
      <div className={`card-wrapper priority-${task.priority.toLowerCase()}`}>
        <div className='card-priority' />
        <Button
          className='edit-button'
          icon='edit'
          stylingMode='text'
          onClick={onClick(task)}
        />
        <div className='card-content'>
          <div className='card-subject dx-theme-text-color'>{task.text}</div>
          <div className='card-data'>
            <span className='priority'>{task.priority}</span>
            <span className='date dx-theme-text-color'>{formatDate(new Date(task.dueDate), 'MM/dd/yyyy')}</span>
          </div>
          <div className='card-assignee'>
            <span className='company dx-theme-text-color'>{task.company}</span>
            <UserAvatar owner={task.owner} />
          </div>
        </div>
      </div>
    </div>
  );
};
