// packages/react/src/pages/planning-scheduler/planning-scheduler.tsx
import './planning-scheduler.scss';

import React, { useState, useMemo } from 'react';
import { defaultCalendarListItems } from 'dx-template-gallery-data';

import Button from 'devextreme-react/button';
import Calendar from 'devextreme-react/calendar';
import Scheduler, {
  Resource,
  SchedulerTypes,
} from 'devextreme-react/scheduler';
import SpeedDialAction from 'devextreme-react/speed-dial-action';
import Tooltip from 'devextreme-react/tooltip';

import { useScreenSize } from '../../utils/media-query';

import { useSchedulerLogic } from './use-scheduler-logic';

import { CalendarList } from '../../components/utils/calendar-list/calendar-list';
import { LeftSidePanel } from '../../components/utils/left-side-panel/left-side-panel';
import { RightSidePanel } from '../../components/utils/right-side-panel/right-side-panel';
import { Agenda } from '../../components/utils/agenda/agenda';
import { TooltipContentTemplate } from '../../components/library/scheduler-tooltip/scheduler-tooltip';

const views: SchedulerTypes.ViewType[] = ['day', 'workWeek', 'month', 'agenda'];
interface CalendarListItem {
  id: number;
  text: string;
  color: string;
  checkboxColor: string;
}

const onAppointmentFormOpening = (e) => {
  const editor = e.form.getEditor('calendarId');
  if (e.appointmentData.calendarId === undefined) {
    editor.option('value', 0);
  }
};

export const PlanningScheduler = () => {
  const { isXSmall, isSmall } = useScreenSize();
  const [calendarListItems] = useState(defaultCalendarListItems);

  const {
    agendaItems,
    currentView,
    date,
    rightPanelOpen,
    schedulerRef,
    schedulerCurrentDate,
    selectedAppointment,
    tasks,
    tooltipPosition,
    tooltipRef,
    deleteCurrentAppointment,
    editCurrentAppointment,
    onCurrentViewChange,
    onAppointmentClick,
    onAppointmentTooltipShowing,
    onAppointmentModified,
    onCellClick,
    onSelectedDateChange,
    onSelectedCalendarsChange,
    showAppointmentTooltip,
    showAppointmentCreationForm,
    toggleRightPanelOpen,
  } = useSchedulerLogic();

  const resourcesList = useMemo(() => {
    return calendarListItems.reduce((res: CalendarListItem[], calendarList) => {
      return res.concat(calendarList.items);
    }, []);
  }, [calendarListItems]);

  return (
    <div className='view-wrapper-calendar'>
      <div className='calendar-content'>
        <LeftSidePanel>
          <div
            className={
              isXSmall || isSmall ? 'left-content small' : 'left-content'
            }
          >
            <div className='buttons'>
              <Button text='Today' onClick={onSelectedDateChange} />
              <Button
                text='Create event'
                type='default'
                onClick={showAppointmentCreationForm}
              />
            </div>
            <div className='calendar'>
              <Calendar value={date} onValueChange={onSelectedDateChange} />
            </div>
            <CalendarList
              calendarItems={calendarListItems}
              onSelectedCalendarsChange={onSelectedCalendarsChange}
            />
          </div>
        </LeftSidePanel>
        <div className='main-content'>
          <Scheduler
            ref={schedulerRef}
            adaptivityEnabled={isXSmall}
            allDayPanelMode='allDay'
            defaultCurrentView='workWeek'
            dataSource={tasks}
            height='inherit'
            currentDate={schedulerCurrentDate}
            currentView={currentView}
            onCurrentViewChange={onCurrentViewChange}
            onAppointmentAdded={onAppointmentModified}
            onAppointmentClick={onAppointmentClick}
            onAppointmentDeleted={onAppointmentModified}
            onAppointmentFormOpening={onAppointmentFormOpening}
            onAppointmentTooltipShowing={onAppointmentTooltipShowing}
            onCellClick={onCellClick}
            showCurrentTimeIndicator={false}
            startDayHour={4}
            views={views}
          >
            <Resource
              dataSource={resourcesList}
              fieldExpr='calendarId'
              label='Calendar'
            />
          </Scheduler>
          <SpeedDialAction
            icon='add'
            visible={isXSmall}
            onClick={showAppointmentCreationForm}
          />

          <Tooltip
            ref={tooltipRef}
            target={selectedAppointment?.target}
            showEvent='click'
            position={tooltipPosition}
          >
            <TooltipContentTemplate
              deleteCurrentAppointment={deleteCurrentAppointment}
              editCurrentAppointment={editCurrentAppointment}
              selectedAppointmentData={selectedAppointment?.data}
            />
          </Tooltip>
        </div>
        <RightSidePanel
          showOpenButton={currentView === 'month'}
          isOpened={rightPanelOpen}
          toggleOpen={toggleRightPanelOpen}
        >
          <Agenda
            selectedAppointmentData={selectedAppointment?.data}
            toggleOpen={toggleRightPanelOpen}
            items={agendaItems}
            resources={resourcesList}
            showAppointmentTooltip={showAppointmentTooltip}
          />
        </RightSidePanel>
      </div>
    </div>
  );
};

// packages/angular/src/app/pages/planning-scheduler/planning-scheduler.component.ts
import {
  Component, OnInit, NgModule, ViewChild
} from '@angular/core';
import DataSource from 'devextreme/data/data_source';
import { CommonModule } from '@angular/common';
import {
  DxCalendarModule,
  DxButtonModule,
  DxTooltipComponent,
  DxTooltipModule,
  DxSchedulerModule,
  DxSchedulerComponent
} from "devextreme-angular";
import { Task } from 'src/app/types/task';
import { DataService, ScreenService } from 'src/app/services';
import { CalendarListModule } from 'src/app/components/utils/calendar-list/calendar-list.component';
import { LeftSidePanelModule } from 'src/app/components/utils/left-side-panel/left-side-panel.component';
import { RightSidePanelModule } from 'src/app/components/utils/right-side-panel/right-side-panel.component';
import { AgendaItem, AgendaModule } from "../../components/utils/agenda/agenda.component";
import { ApplyPipeModule } from "../../pipes/apply.pipe";
import { SchedulerTooltipModule } from "../../components/library/scheduler-tooltip/scheduler-tooltip.component";

type SelectedAppointment = { data: Record<string, any>, target: any };

@Component({
  templateUrl: './planning-scheduler.component.html',
  styleUrls: ['./planning-scheduler.component.scss'],
  providers: [DataService],
})
export class PlanningSchedulerComponent implements OnInit {
  @ViewChild('schedulerRef', { static: false }) schedulerRef: DxSchedulerComponent;

  @ViewChild('tooltipRef', { static: false }) tooltipRef: DxTooltipComponent;
  tasks: DataSource<Task> = new DataSource([]);

  currentDate = new Date();

  currentView = 'workWeek';

  isRightPanelOpen = false;

  listDataSource = [];

  resourcesList = [];

  selectedAppointment: SelectedAppointment = null;

  agendaItems: AgendaItem[] = [];

  isXSmall = this.screen.sizes['screen-small']

  constructor(private service: DataService, protected screen: ScreenService) {
    this.service.getDefaultListDS().subscribe(
   (data) => {
     this.listDataSource = data;
     this.resourcesList = data.reduce((res: Record<string,any>[], calendarList) => res.concat(calendarList.items), []);
      });

    screen.screenChanged.subscribe(({isXSmall}) => this.isXSmall = isXSmall);
  }

  ngOnInit(): void {
    this.service.getSchedulerTasks().subscribe((data) => {
      this.tasks = new DataSource(data);
      this.repaintScheduler();
    })
  }

  openRightPanelOpen() {
    this.isRightPanelOpen = true;
    this.repaintScheduler();
  }

  setCurrentDate = (date) => {
    this.currentDate = date;
  };

  onCurrentViewChange = (view) => {
    this.currentView = view;

    if (view === 'month' && !this.screen.sizes['screen-x-small']) {
      this.isRightPanelOpen = true;
      this.updateAgenda({ startDate: this.currentDate });
    }

    if (this.currentView === 'month' && view !== 'month') {
      this.isRightPanelOpen = false;
    }

    this.repaintScheduler();
  }

  onSelectedDateChange = (e?: Date) => {
    const date = e instanceof Date ? e : new Date();
    this.currentDate = date;
    this.selectedAppointment = { data: { startDate: date }, target: undefined };
    this.updateAgenda({ startDate: date });
  }

  onCellClick = ({cellData}) => {
    this.onSelectedDateChange(cellData.startDate);

    if (this.currentView === 'month' && cellData) {
      const cellAppointments = this.findAllAppointmentsForDay(cellData, this.tasks);

      if (cellAppointments.length > 1) {
        this.selectedAppointment = { data: cellData, target: null };
        this.agendaItems = cellAppointments;
        this.toggleRightPanelOpen(true);
      }
    }
  };

  calendarListChanged(selectedCalendars) {
    const filters = selectedCalendars
      .flatMap((calendar) => [['calendarId', '=', calendar.id], 'or']).slice(0, -1);

    this.tasks?.filter(filters.length > 0 ? filters : null);

    this.tasks?.load();
  }

  repaintScheduler() {
    setTimeout(() => this.schedulerRef?.instance.repaint(), 0);
  }

  getTooltipPosition = (selectedAppointment: SelectedAppointment, rightPanelOpen: boolean, isXSmall: boolean) => {
    if (isXSmall) {
      return 'bottom';
    }
    const classList = selectedAppointment?.target?.classList || selectedAppointment?.target?.[0]?.classList;
    return classList?.contains('dx-list') && rightPanelOpen ? 'left' : 'top';
  }

  toggleRightPanelOpen(isOpen?) {
    this.isRightPanelOpen = isOpen || !this.isRightPanelOpen;
    this.repaintScheduler();
  }

  showAppointmentCreationForm(appointment?) {
    this.schedulerRef?.instance.showAppointmentPopup(appointment?.data, !appointment);
  }

  findAllAppointmentsForDay = (selectedAppointment, dataSource) => {
    if (!dataSource) {
      return [];
    }
    const appointments = dataSource.items();
    if (appointments.length === 0 || !selectedAppointment) {
      return [];
    }
    return appointments
      .filter((appointment) => {
        return appointment.startDate.getDate() === selectedAppointment.startDate.getDate()
          && appointment.startDate.getMonth() === selectedAppointment.startDate.getMonth();
      });
  }

  updateAgenda = (appointmentData?) => {
    this.agendaItems = this.findAllAppointmentsForDay(appointmentData, this.tasks);
  }

  onAppointmentClick(e) {
    if (this.currentView === 'month') {
      const appointmentData = e.appointmentData;
      this.selectedAppointment = { data: appointmentData, target: e.targetElement };
      this.updateAgenda(appointmentData);
      this.toggleRightPanelOpen(true);
    }
  }

  onAppointmentTooltipShowing = (e) => {
    e.cancel = true;
    const appointmentData = e.appointments[0].appointmentData;
    const isAppointmentCollectorClicked = (e) => {
      return e.targetElement?.[0]?.classList.contains('dx-scheduler-appointment-collector');
    };

    this.selectedAppointment = { data: appointmentData, target: e.targetElement };

    if (this.currentView === 'month' || isAppointmentCollectorClicked(e)) {
      this.updateAgenda(appointmentData);
    }
    if (this.currentView === 'month' && this.screen.sizes['screen-small'] ||
        isAppointmentCollectorClicked(e)) {
      this.toggleRightPanelOpen(true);
    }
    else {
      this.tooltipRef?.instance.show();
    }
  }

  showAppointmentTooltip = (e) => {
    this.schedulerRef?.instance.showAppointmentTooltip(e.itemData, e.element);
  };

  editSelectedAppointment() {
    this.showAppointmentCreationForm(this.selectedAppointment);
    this.tooltipRef?.instance.hide();
  }

  deleteSelectedAppointment(appointmentData) {
    this.schedulerRef?.instance.deleteAppointment(this.selectedAppointment?.data);
    this.tooltipRef?.instance.hide();
    this.agendaItems = this.findAllAppointmentsForDay(appointmentData, this.tasks)
  }


}

@NgModule({
  imports: [
    ApplyPipeModule,
    DxCalendarModule,
    DxButtonModule,
    DxSchedulerModule,
    DxTooltipModule,
    CommonModule,
    CalendarListModule,
    LeftSidePanelModule,
    RightSidePanelModule,
    AgendaModule,
    SchedulerTooltipModule,
  ],
  providers: [],
  exports: [],
  declarations: [PlanningSchedulerComponent],
})
export class PlanningSchedulerModule { }

<div class="view-wrapper">
  <div class="panels">
    <left-side-panel class="left-side-panel">
      <div class="left-side-panel-content">
        <div class="buttons">
          <dx-button
            text="Today"
            (onClick)="onSelectedDateChange()"
          ></dx-button>
          <dx-button
            text="Create event"
            type="default"
            (onClick)="showAppointmentCreationForm()"
          ></dx-button>
        </div>
        <div class="calendar">
          <dx-calendar
            [value]="currentDate"
            (onValueChanged)="onCalendarDateChange($event.value)"
          ></dx-calendar>
        </div>
        <calendar-list
          [dataSource]="listDataSource"
          (listSelectionChanged)="calendarListChanged($event)"
        ></calendar-list>
      </div>
    </left-side-panel>

    <div class="scheduler-container">
      <dx-scheduler
        #schedulerRef
        height="inherit"
        [adaptivityEnabled]="!!(screen.screenChanged | async)?.isXSmall"
        [allDayPanelMode]="'allDay'"
        [dataSource]="tasks"
        [currentView]="currentView"
        [currentDate]="getSchedulerCurrentDate | apply: currentDate"
        [startDayHour]="4"
        [showCurrentTimeIndicator]="false"
        (onOptionChanged)="onSchedulerOptionChanged($event)"
        (onAppointmentClick)="onAppointmentClick($event)"
        (onAppointmentTooltipShowing)="onAppointmentTooltipShowing($event)"
        (onCellClick)="onCellClick($event)"
      >
        <dxi-resource
          fieldExpr="calendarId"
          label="Calendar"
          [dataSource]="resourcesList"
        >
        </dxi-resource>
        <dxi-view type="day"></dxi-view>
        <dxi-view type="workWeek"></dxi-view>
        <dxi-view type="month"></dxi-view>
        <dxi-view type="agenda"></dxi-view>
      </dx-scheduler>
      @if (selectedAppointment) {
        <dx-tooltip
          #tooltipRef
          showEvent="click"
          [target]="selectedAppointment?.target"
          [position]="
          getTooltipPosition
            | apply
              : selectedAppointment
              : isRightPanelOpen
              : (screen.screenChanged | async)?.isSmall
        "
        >
          <scheduler-tooltip
            [selectedAppointmentData]="selectedAppointment?.data"
            (clickEditAppointment)="editSelectedAppointment()"
            (clickDeleteAppointment)="deleteSelectedAppointment($event)"
          ></scheduler-tooltip>
        </dx-tooltip>
      }
      <dx-speed-dial-action
        icon="add"
        [visible]="!!(screen.screenChanged | async)?.isXSmall"
        (onClick)="showAppointmentCreationForm()"
      ></dx-speed-dial-action>
    </div>

    <right-side-panel
      class="right-side-panel"
      [isOpened]="isRightPanelOpen"
      [showOpenButton]="currentView === 'month'"
      [title]="
        ((selectedAppointment?.data?.startDate ?? currentDate) | date: 'EE, MMMM d') ?? ''
      "
      (openedChange)="toggleRightPanelOpen($event)"
    >
      <agenda
        [items]="agendaItems"
        [resources]="resourcesList"
        (clickAppointment)="showAppointmentTooltip($event)"
      ></agenda>
    </right-side-panel>
  </div>
</div>
