// packages/react/src/components/utils/conversion-ticker/ConversionTicker.tsx
import React from 'react';

import { TickerCard } from '../../library/ticker-card/TickerCard';
import { TickerProps } from '../../../types/analytics';

export const ConversionTicker = ({ value }: TickerProps) =>
  <TickerCard
    title='Conversion'
    icon='datausage'
    tone='warning'
    value={value}
    formatValue={(value) => `${value}%`}
    percentage={-2.3}
  />;

// packages/angular/src/app/components/utils/conversion-ticker/conversion-ticker.component.ts
import { Component } from '@angular/core';
import { TickerCardComponent } from 'src/app/components/library/ticker-card/ticker-card.component';

@Component({
    selector: 'conversion-ticker',
    templateUrl: 'conversion-ticker.component.html',
    imports: [ TickerCardComponent ],
})
export class ConversionTickerComponent {
}

<ticker-card
  titleText="Conversion"
  total="16%"
  [percentage]="-2.3"
  icon="datausage"
  tone="warning"
></ticker-card>
