// packages/react/src/components/library/theme-switcher/ThemeSwitcher.tsx
import React, { useCallback, useContext } from 'react';
import Button from 'devextreme-react/button';
import { ThemeContext } from '../../../theme/theme';

export const ThemeSwitcher = () => {
  const themeContext = useContext(ThemeContext);

  const onButtonClick = useCallback(() => {
    themeContext?.switchTheme();
  }, []);

  return (
    <div>
      <Button
        className='theme-button'
        stylingMode='text'
        icon={`${themeContext?.theme !== 'dark' ? 'moon' : 'sun'}`}
        onClick={onButtonClick}
      />
    </div>
  );
};

// packages/angular/src/app/components/library/theme-switcher/theme-switcher.component.ts
import {Component, inject} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxButtonModule } from 'devextreme-angular';
import { ThemeService } from 'src/app/services';

@Component({
    selector: 'theme-switcher',
    template: `
    <dx-button
      class="theme-button"
      stylingMode="text"
      [icon]="themeService.currentTheme !== 'dark' ? 'moon' : 'sun'"
      (onClick)="onButtonClick()"
    ></dx-button>
`,
    styleUrls: [],
    imports: [ CommonModule, DxButtonModule ],
})
export class ThemeSwitcherComponent {
  protected themeService = inject(ThemeService);

  onButtonClick () {
    this.themeService.switchTheme();
  }
}
