// packages/react/src/pages/crm-contact-list/contact-panel/contactPanel.tsx

import React, { useEffect, useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import classNames from 'classnames';
import './contactPanel.scss';
import { Button, DropDownButton, ScrollView } from 'devextreme-react';
import Toolbar, { Item as ToolbarItem } from 'devextreme-react/toolbar';
import Form, { Item as FormItem, ColCountByScreen } from 'devextreme-react/form';
import Accordion, { Item as AccordionItem } from 'devextreme-react/accordion';
import LoadPanel from 'devextreme-react/load-panel';
import { ClickEvent as ButtonClickEvent } from 'devextreme/ui/button';
import { formatNumber } from 'devextreme/localization';
import { getContact } from 'dx-template-gallery-data';
import { Contact } from '../../../shared/types/crm-contact';
import { CardActivities } from '../../../components/card-activities/CardActivities';
import { FormTextbox, FormPhoto, ContactStatus } from '../../../components';

export const ContactPanel = ({ contactId, isOpen, changePanelOpen } : { contactId: number, isOpen: boolean, changePanelOpen:()=> void }) => {

  const [contact, setContact] = useState<Contact>();
  const [loading, setLoading] = useState(false);
  const [isPin, setIsPin] = useState(false);
  const [isEditing, setIsEditing] = useState(false);

  const navigate = useNavigate();

  const loadData = useCallback(() => {
    setLoading(true);
    getContact(contactId)
      .then((data) => {
        setContact(data);
        setLoading(false);
      })
      .catch((error) => console.log(error));
  }, [contactId]);

  useEffect(() => {
    if(contactId) {
      loadData();
    }
  }, [loadData]);

  const formatPrice = (price) => {
    return formatNumber(price, {
      type: 'currency',
      currency: 'USD',
    });
  };

  const validationGroup = 'contactValidationGroup';

  const onDataChanged = useCallback(data => {
    setContact(data);
  }, []);

  const updateField = (field: string) => (value) => {
    onDataChanged({ ...contact, ...{ [field]: value } });
  };

  const pinClick = useCallback(() => {
    setIsPin(!isPin);
  }, [isPin]);

  const closePanel = useCallback(() => {
    setIsPin(false);
    changePanelOpen();
  }, []);

  const toggleEdit = useCallback(() => {
    setIsEditing(!isEditing);
  }, [isEditing]);

  const navigateToDetails = () => {
    navigate('/crm-contact-details');
  };

  const accordionTitleClick = (e: ButtonClickEvent) => {
    e.event?.stopPropagation();
  };

  const customTitle = (item) => {
    return (
      <div>
        <span>{item.title}</span>
        <Button icon='add' type='default' stylingMode='text' onClick={accordionTitleClick} />
      </div>
    );
  };

  const customOpportunities = () => {
    return (
      contact?.opportunities.map((item, idx) => {
        return (
          <div className='opportunities' key={idx}>
            <span className='value'>{item.name}</span>
            <br />
            <span className='value black small'>{formatPrice(item.price)}</span>
          </div>
        );
      }));
  };

  const customActivities = () => {
    return (<CardActivities activities={contact?.activities} />);
  };

  return (
    <div id='contact-panel' className={classNames({ 'panel': true, 'open': isOpen, 'pin': isPin })}>
      <div className='data-wrapper'>
        <div className='data-part'>
          <Toolbar className='panel-toolbar'>
            <ToolbarItem location='before'>
              <span className='contact-name value'>{contact?.name}</span>
            </ToolbarItem>
            <ToolbarItem location='before'>
              <ContactStatus text={contact?.status} />
            </ToolbarItem>
            <ToolbarItem
              location='after'
              visible
            >
              <Button icon='pin' onClick={pinClick} />
            </ToolbarItem>
            <ToolbarItem location='after'>
              <Button icon='close' onClick={closePanel} />
            </ToolbarItem>
          </Toolbar>
        </div>
        <ScrollView className='panel-scroll'>
          <div className='data-part border'>
            <Form
              labelMode='floating'
              className={classNames({ 'plain-styled-form': true, 'view-mode': !isEditing })}
              validationGroup={validationGroup}
            >
              <FormItem itemType='group' colCount={2}>
                <ColCountByScreen xs={2} />
                <FormItem cssClass='photo'>
                  <FormPhoto link={contact?.image} size={124} />
                </FormItem>
                <FormItem itemType='group'>
                  <FormItem cssClass='accent'>
                    <FormTextbox
                      label='Company'
                      value={contact?.company}
                      isEditing={!isEditing}
                      onValueChange={updateField('company')}
                    />
                  </FormItem>
                  <FormItem>
                    <FormTextbox
                      label='Position'
                      value={contact?.position}
                      isEditing={!isEditing}
                      onValueChange={updateField('position')}
                    />
                  </FormItem>
                  <FormItem cssClass='accent'>
                    <FormTextbox
                      label='Assigned to'
                      value={contact?.manager}
                      isEditing={!isEditing}
                      onValueChange={updateField('manager')}
                    />
                  </FormItem>
                </FormItem>
              </FormItem>

              <FormItem itemType='group' cssClass='contact-fields-group'>
                <FormItem>
                  <FormTextbox
                    value={contact?.phone}
                    isEditing={!isEditing}
                    onValueChange={updateField('phone')}
                    icon='tel'
                    mask='+1(000)000-0000'
                  />
                </FormItem>
                <FormItem>
                  <FormTextbox
                    value={contact?.email}
                    isEditing={!isEditing}
                    onValueChange={updateField('email')}
                    icon='email'
                  />
                </FormItem>
                <FormItem>
                  <FormTextbox
                    value={contact?.address}
                    isEditing={!isEditing}
                    onValueChange={updateField('address')}
                    icon='home'
                  />
                </FormItem>
              </FormItem>
            </Form>
          </div>

          <div className='data-part data-part-toolbar border'>
            <Toolbar>
              <ToolbarItem location='before' visible={!isEditing}>
                <Button icon='edit' text='Edit' stylingMode='outlined' type='default' onClick={toggleEdit} />
              </ToolbarItem>
              <ToolbarItem location='before' visible={!isEditing}>
                <Button text='Details' stylingMode='outlined' type='default' onClick={navigateToDetails} />
              </ToolbarItem>
              <ToolbarItem location='before' locateInMenu='before' visible={isEditing}>
                <Button text='Save' stylingMode='outlined' type='default' onClick={toggleEdit} />
              </ToolbarItem>
              <ToolbarItem location='before' locateInMenu='before' visible={isEditing}>
                <Button text='Cancel' stylingMode='text' onClick={toggleEdit} />
              </ToolbarItem>
              <ToolbarItem location='after' visible={!isEditing}>
                <DropDownButton text='Actions' width={120} stylingMode='contained' items={['Call', 'Send Fax', 'Send Email', 'Make a Meeting']} />
              </ToolbarItem>
            </Toolbar>
          </div>
          <div className='data-part'>
            <Accordion multiple collapsible itemTitleRender={customTitle}>
              <AccordionItem title='Opportunities' render={customOpportunities} />
              <AccordionItem title='Activities' render={customActivities} />
            </Accordion>
          </div>
        </ScrollView>
      </div>
      { loading && <LoadPanel container='.panel' visible position={{ of: '.panel' }} /> }
    </div>
  );
};

// packages/angular/src/app/components/library/contact-panel/contact-panel.component.ts
import {
  Component,
  OnInit,
  OnChanges,
  OnDestroy,
  Output,
  Input,
  SimpleChanges,
  EventEmitter,
  AfterViewChecked,
  inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import {
  DxAccordionModule,
  DxButtonModule,
  DxDropDownButtonModule,
  DxToolbarModule,
  DxLoadPanelModule,
  DxScrollViewModule,
  DxFormModule,
  DxValidatorModule,
  DxValidationGroupModule,
} from 'devextreme-angular';
import { DxButtonTypes } from 'devextreme-angular/ui/button';
import {
  FormTextboxComponent,
  FormPhotoComponent,
  ContactStatusComponent,
  CardActivitiesComponent,
} from 'src/app/components';
import { ScreenService, DataService } from 'src/app/services';
import { distinctUntilChanged, Subject, Subscription} from 'rxjs';
import { Contact } from 'src/app/types/contact';

@Component({
    selector: 'contact-panel',
    templateUrl: './contact-panel.component.html',
    styleUrls: ['./contact-panel.component.scss'],
    providers: [DataService],
    imports: [
      DxAccordionModule,
      DxButtonModule,
      DxDropDownButtonModule,
      DxToolbarModule,
      DxLoadPanelModule,
      DxScrollViewModule,
      DxFormModule,
      DxValidatorModule,
      DxValidationGroupModule,
      FormTextboxComponent,
      FormPhotoComponent,
      CardActivitiesComponent,
      ContactStatusComponent,
      CommonModule,
    ]
})
export class ContactPanelComponent implements OnInit, OnChanges, AfterViewChecked, OnDestroy {
  @Input() isOpened = false;

  @Input() userId: number;

  @Output() isOpenedChange = new EventEmitter<boolean>();

  @Output() pinnedChange = new EventEmitter<boolean>();

  private pinEventSubject = new Subject<boolean>();

  formData: Contact;

  contactData: Contact;

  pinned = false;

  isLoading = true;

  isEditing = false;

  isPinEnabled = false;

  userPanelSubscriptions: Subscription[] = [];

  private screen = inject(ScreenService);
  private service = inject(DataService);
  private router = inject(Router);

  constructor() {
    this.userPanelSubscriptions.push(
      this.screen.changed.subscribe(this.calculatePin),
      this
        .pinEventSubject
        .pipe(distinctUntilChanged())
        .subscribe(this.pinnedChange)
    );
  }

  ngOnInit(): void {
    this.calculatePin();
  }

  ngAfterViewChecked(): void {
    this.pinEventSubject.next(this.pinned);
  }

  ngOnChanges(changes: SimpleChanges): void {
    const { userId } = changes;

    if (userId?.currentValue) {
      this.loadUserById(userId.currentValue);
    }
  }

  ngOnDestroy(): void {
    this.userPanelSubscriptions.forEach((sub) => sub.unsubscribe());
  }

  loadUserById = (id: number) => {
    this.isLoading = true;

    this.service.getContact(id).subscribe((data) => {
      this.formData = data;
      this.contactData = { ...this.formData };
      this.isLoading = false;
      this.isEditing = false;
    })
  };

  onClosePanel = () => {
    this.isOpened = false;
    this.pinned = false;
    this.isOpenedChange.emit(this.isOpened);
  };

  onPinClick = () => {
    this.pinned = !this.pinned;
  };

  onSaveClick = ({ validationGroup } : DxButtonTypes.ClickEvent) => {
    if (!validationGroup.validate().isValid) return;
    this.contactData = { ...this.formData };
    this.isEditing = !this.isEditing;
  }

  calculatePin = () => {
    this.isPinEnabled = this.screen.sizes['screen-large'] || this.screen.sizes['screen-medium'];
    if (this.pinned && !this.isPinEnabled) {
      this.pinned = false;
    }
  };

  toggleEdit = () => {
    this.isEditing = !this.isEditing;
  };

  cancelHandler() {
    this.toggleEdit();
    this.formData = { ...this.contactData };
  }

  navigateToDetails = () => {
    this.router.navigate(['/crm-contact-details']);
  };
}

<div class="panel" [ngClass]="{ pin: pinned(), open: isOpened() }">
  <div class="data-wrapper">
    @if (!isLoading() && formData(); as form) {
      <dx-toolbar class="panel-toolbar">
        <dxi-toolbar-item location="before">
          <span class="contact-name value">{{ form.name }}</span>
        </dxi-toolbar-item>
        <dxi-toolbar-item location="before">
          <contact-status [value]="form.status"></contact-status>
        </dxi-toolbar-item>
        <dxi-toolbar-item location="after" [visible]="isPinEnabled()">
          <dx-button
            stylingMode="text"
            [icon]="pinned() ? 'pin' : 'unpin'"
            (onClick)="onPinClick()"
          ></dx-button>
        </dxi-toolbar-item>
        <dxi-toolbar-item location="after">
          <dx-button
            icon="close"
            stylingMode="text"
            (onClick)="onClosePanel()"
          ></dx-button>
        </dxi-toolbar-item>
      </dx-toolbar>

      <dx-scroll-view class="panel-scroll">
        <dx-validation-group>
          <div class="data-part border">
            <dx-form
              class="plain-styled-form"
              labelMode="floating"
              [class.view-mode]="!isEditing()"
            >
              <dxi-form-item itemType="group" [colCount]="2" cssClass="photo-row">
                <dxo-form-col-count-by-screen [xs]="2"></dxo-form-col-count-by-screen>
                <dxi-form-item cssClass="photo-box">
                  <div *dxTemplate>
                    <form-photo [link]="form.image"></form-photo>
                  </div>
                </dxi-form-item>

                <dxi-form-item itemType="group">
                  <dxi-form-item cssClass="accent">
                    <div *dxTemplate>
                      <form-textbox
                        label="Company"
                        [(value)]="form.company"
                        [isEditing]="isEditing()"
                      ></form-textbox>
                    </div>
                  </dxi-form-item>

                  <dxi-form-item>
                    <div *dxTemplate>
                      <form-textbox
                        label="Position"
                        [(value)]="form.position"
                        [isEditing]="isEditing()"
                      ></form-textbox>
                    </div>
                  </dxi-form-item>

                  <dxi-form-item cssClass="accent">
                    <div *dxTemplate>
                      <form-textbox
                        label="Assigned to"
                        [(value)]="form.manager"
                        [isEditing]="isEditing()"
                      ></form-textbox>
                    </div>
                  </dxi-form-item>
                </dxi-form-item>
              </dxi-form-item>

              <dxi-form-item itemType="group" cssClass="contact-fields-group">
                <dxi-form-item>
                  <div *dxTemplate>
                    <form-textbox
                      icon="tel"
                      mask="(000) 000-0000"
                      [(value)]="form.phone"
                      [isEditing]="isEditing()"
                    >
                    </form-textbox>
                  </div>
                </dxi-form-item>
                <dxi-form-item>
                  <div *dxTemplate>
                    <form-textbox
                      icon="email"
                      [(value)]="form.email"
                      [isEditing]="isEditing()"
                      [validators]="[{ type: 'email' }]"
                    ></form-textbox>
                  </div>
                </dxi-form-item>
                <dxi-form-item>
                  <div *dxTemplate>
                    <form-textbox
                      icon="home"
                      [(value)]="form.address"
                      [isEditing]="isEditing()"
                      [validators]="[]"
                    >
                    </form-textbox>
                  </div>
                </dxi-form-item>
              </dxi-form-item>
            </dx-form>
          </div>

          <div class="data-part data-part-toolbar border">
            <dx-toolbar>
              <dxi-toolbar-item location="after" [visible]="!isEditing()">
                <dx-button
                  text="Edit"
                  icon="edit"
                  stylingMode="contained"
                  type="default"
                  (onClick)="toggleEdit()"
                >
                </dx-button>
              </dxi-toolbar-item>
              <dxi-toolbar-item location="after" [visible]="!isEditing()">
                <dx-button
                  text="Details"
                  stylingMode="outlined"
                  type="normal"
                  (onClick)="navigateToDetails()"
                >
                </dx-button>
              </dxi-toolbar-item>
              <dxi-toolbar-item
                location="after"
                locateInMenu="never"
                [visible]="isEditing()"
              >
                <dx-button
                  text="Save"
                  icon="save"
                  stylingMode="contained"
                  type="default"
                  (onClick)="onSaveClick($event)"
                >
                </dx-button>
              </dxi-toolbar-item>
              <dxi-toolbar-item
                location="after"
                locateInMenu="never"
                [visible]="isEditing()"
              >
                <dx-button
                  text="Cancel"
                  stylingMode="outlined"
                  type="normal"
                  (onClick)="cancelHandler()"
                ></dx-button>
              </dxi-toolbar-item>
              <dxi-toolbar-item
                location="before"
                widget="dxDropDownButton"
                [options]="{
                  text: 'Actions',
                  stylingMode: 'text',
                  dropDownOptions: { width: 'auto' },
                  width: 'auto',
                  items: [
                    'Call',
                    'Send Fax',
                    'Send Email',
                    'Schedule a Meeting'
                  ]
                }"
              ></dxi-toolbar-item>
            </dx-toolbar>
          </div>
        </dx-validation-group>

        <div class="data-part">
          <dx-accordion [multiple]="true" [collapsible]="true">
            <div class="accordion-title" *dxTemplate="let t of 'title'">
              <span>{{ t.title }}</span>
            </div>

            <dxi-accordion-item title="Opportunities">
              <div *dxTemplate="let i of 'item'">
                @for (opportunity of form.opportunities; track opportunity.name) {
                  <div class="opportunities">
                    <span class="value">{{ opportunity.name }} </span>
                    <br />
                    <span class="value black small">{{
                        opportunity.price | currency: 'USD':'$':'1.0-0'
                      }}</span>
                    <br />
                  </div>
                }
              </div>
            </dxi-accordion-item>

            <dxi-accordion-item title="Activities">
              <card-activities
                [activities]="form.activities"
              ></card-activities>
            </dxi-accordion-item>
          </dx-accordion>
        </div>
      </dx-scroll-view>
    }

    <dx-load-panel
      container=".panel"
      [width]="300"
      [visible]="isLoading()"
      [showPane]="false"
      [position]="{ of: '.panel' }"
    ></dx-load-panel>
  </div>
</div>
