// packages/vue/src/components/library/contact-panel.vue
<template>
  <div
    id="contact-panel"
    class="panel"
    :class="{ pin: isPinned, open: props.isPanelOpened }"
  >
    <div class="data-wrapper">
      <dx-load-panel
        :visible="isLoading"
        :show-pane="false"
        :width="300"
        container="#contact-panel"
        :position="{ of: '#contact-panel' }"
      />
      <template v-if="panelData">
        <dx-toolbar class="panel-toolbar">
          <dx-item location="before">
            <div class="contact-name">
              {{ panelData?.name }}
            </div>
          </dx-item>
          <dx-item location="before">
            <contact-status :value="panelData?.status" />
          </dx-item>

          <dx-item
            location="after"
            widget="dxButton"
            :visible="isPinEnabled"
            :options="{
              icon: isPinned ? 'pin' : 'unpin',
              stylingMode: 'text',
              onClick: () => isPinned = !isPinned,
            }"
          />

          <dx-item
            location="after"
            widget="dxButton"
            :options="{
              icon: 'close',
              stylingMode: 'text',
              onClick: onClose,
            }"
          />
        </dx-toolbar>

        <dx-scroll-view class="panel-scroll">
          <dx-validation-group>
            <div class="data-part border">
              <dx-form
                :class="{ 'view-mode': !isEditing, 'plain-styled-form dx-form': true }"
              >
                <dx-form-group-item
                  :col-count="2"
                  css-class="photo-row"
                >
                  <DxColCountByScreen :xs="2" />
                  <dx-form-item css-class="photo-box">
                    <form-photo :link="panelData.image" />
                  </dx-form-item>

                  <dx-form-group-item>
                    <dx-form-item css-class="accent">
                      <form-textbox
                        :label="'Company'"
                        v-model="panelData['company']"
                        :is-editing="isEditing"
                      />
                    </dx-form-item>

                    <dx-form-item>
                      <form-textbox
                        v-model="panelData['position']"
                        :label="'Position'"
                        :is-editing="isEditing"
                      />
                    </dx-form-item>

                    <dx-form-item css-class="accent">
                      <form-textbox
                        :label="'Assigned to'"
                        v-model="panelData['manager']"
                        :is-editing="isEditing"
                      />
                    </dx-form-item>
                  </dx-form-group-item>
                </dx-form-group-item>

                <dx-form-group-item css-class="contact-fields-group">
                  <dx-form-item
                    v-for="(item, index) in underContactFields"
                    :key="index"
                  >
                    <form-textbox
                      :icon="item.icon"
                      v-model="panelData[item.name]"
                      :is-editing="isEditing"
                      :mask="item.mask"
                    />
                  </dx-form-item>
                </dx-form-group-item>
              </dx-form>
            </div>

            <div class="data-part data-part-toolbar border">
              <dx-toolbar>
                <dx-item
                  location="after"
                  :visible="!isEditing"
                >
                  <dx-button
                    text="Edit"
                    icon="edit"
                    styling-mode="contained"
                    type="default"
                    @click="toggleEdit()"
                  />
                </dx-item>

                <dx-item
                  location="after"
                  :visible="!isEditing"
                >
                  <dx-button
                    text="Details"
                    styling-mode="outlined"
                    type="normal"
                    @click="navigateToDetails()"
                  />
                </dx-item>

                <dx-item
                  location="after"
                  locate-in-menu="before"
                  :visible="isEditing"
                >
                  <dx-button
                    text="Save"
                    icon="save"
                    styling-mode="contained"
                    type="default"
                    @click="handleSaveClick"
                  />
                </dx-item>

                <dx-item
                  location="after"
                  locate-in-menu="before"
                  :visible="isEditing"
                >
                  <dx-button
                    text="Cancel"
                    @click="cancelHandler()"
                    styling-mode="outlined"
                    type="normal"
                  />
                </dx-item>

                <dx-item
                  location="before"
                  widget="dxDropDownButton"
                  :options="{
                    text: 'Actions',
                    dropDownOptions: { width: 'auto' },
                    stylingMode: 'text',
                    items: ['Call', 'Send Fax', 'Send Email', 'Schedule a Meeting'],
                  }"
                />
              </dx-toolbar>
            </div>
          </dx-validation-group>

          <div class="data-part">
            <dx-accordion
              :multiple="true"
              :collapsible="true"
            >
              <template #title="{ data }">
                <div class="accordion-title">
                  <span>{{ data.title }}</span>
                </div>
              </template>

              <dx-accordion-item title="Opportunities">
                <div
                  v-for="(opportunity, i) in panelData.opportunities"
                  :key="i"
                  class="opportunities"
                >
                  <span class="value">{{ opportunity.name }} </span>
                  <br>
                  <span class="value black small">{{
                    formatPrice(opportunity.price)
                  }}</span>
                  <br>
                </div>
              </dx-accordion-item>

              <dx-item title="Activities">
                <contact-activities
                  :items="panelData.activities"
                  :is-loading="false"
                />
              </dx-item>
            </dx-accordion>
          </div>
        </dx-scroll-view>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { router } from '@/router';
// eslint-disable-next-line import/no-unresolved
import { getContact } from 'dx-template-gallery-data';
import { DxAccordion, DxItem as DxAccordionItem } from 'devextreme-vue/accordion';
import { DxButton, DxButtonTypes } from 'devextreme-vue/button';
import {
  DxForm,
  DxItem as DxFormItem,
  DxGroupItem as DxFormGroupItem,
  DxColCountByScreen,
} from 'devextreme-vue/form';
import { DxScrollView } from 'devextreme-vue/scroll-view';
import { DxToolbar, DxItem } from 'devextreme-vue/toolbar';
import { DxValidationGroup } from 'devextreme-vue/validation-group';
import FormPhoto from '@/components/utils/form-photo.vue';
import ContactStatus from '@/components/utils/contact-status.vue';
import { screenInfo } from '@/utils/media-query';
import { formatPrice } from '@/utils/formatters';
import ContactActivities from '@/components/library/card-activities.vue';
import DxLoadPanel from 'devextreme-vue/load-panel';
import type { Contact } from '@/types/contact';
import FormTextbox from '@/components/utils/form-textbox.vue';

const isEditing = ref(false);
const isLoading = ref(false);
const isPinned = ref(false);
const isPinEnabled = ref(screenInfo.value.isLarge || screenInfo.value.isMedium);
const panelData = ref<Contact | null>(null);
const props = withDefaults(defineProps<{
  isPanelOpened: boolean,
  contactId: number | null
}>(), { isPanelOpened: false, contactId: null });

let contactData: Contact | null = null;

const toggleEdit = () => {
  isEditing.value = !isEditing.value;
};

const cancelHandler = () => {
  toggleEdit();
  panelData.value = structuredClone(contactData);
};

const emit = defineEmits(['close', 'pinChanged']);

const underContactFields: {
  name: 'phone' | 'email' | 'address'
  icon: string
  mask?: string
}[] = [
  {
    name: 'phone',
    mask: '+1(000)000-0000',
    icon: 'tel',
  },
  {
    name: 'email',
    icon: 'email',
  },
  {
    name: 'address',
    icon: 'home',
  }];

watch(
  screenInfo,
  (newScreenInfo) => {
    isPinEnabled.value = newScreenInfo.isLarge || newScreenInfo.isMedium;
    if (isPinEnabled.value === false) {
      isPinned.value = false;
    }
  },
);

const loadContact = async (contactId: number) => {
  isEditing.value = false;
  isLoading.value = true;
  const contactPanelData = await getContact(contactId);
  panelData.value = contactPanelData;
  contactData = structuredClone(contactPanelData);
  isLoading.value = false;
};

function handleSaveClick({ validationGroup }: DxButtonTypes.ClickEvent) {
  if (validationGroup.validate().isValid) {
    contactData = structuredClone(panelData.value);
    isEditing.value = false;
  }
}

function onClose() {
  isPinned.value = false;
  emit('close');
}

watch(
  () => props.contactId,
  (newId) => {
    if (newId !== null) {
      loadContact(newId);
    }
  },
);

watch([isPinned, () => props.isPanelOpened], () => {
  emit('pinChanged');
}, {
  flush: 'post',
});

const navigateToDetails = () => {
  router.push('/crm-contact-details');
};
</script>

<style lang="scss">
@use '@/variables' as *;

#contact-panel {
  --contact-side-panel-width: 350px;
}

.screen-x-small #contact-panel {
  --contact-side-panel-width: 100vw;
}
</style>
<style scoped lang="scss">
@use "@/variables" as *;

.panel {
  position: absolute;
  top: 0;
  bottom: 0;
  right: calc(-1 * var(--contact-side-panel-width));
  background: var(--base-bg);
  transition: right 400ms;

  :deep(.dx-layout-manager-one-col) .dx-box-item {
    .dx-single-column-item-content .contact-fields-group {
      padding-top: 20px;
    }
  }

  :deep(.photo-row) .dx-item > .dx-item-content > .dx-item:first-child  {
    max-width: 144px;

    .photo-box {
      padding-bottom: 0;
    }
  }

  .embedded.dx-viewport & {
    top: 0;
  }

  &.open {
    right: 0;
    box-shadow: 0px 0px 6px 0px rgba(0, 0, 0, 0.04), 0px 4px 4px 0px rgba(0, 0, 0, 0.12);
  }

  &.pin {
    position: absolute;
    transition: none;
    box-shadow: none;
    border-left: 1px solid var(--border-color);

    &.open {
      top: 0;
      position: relative;
    }
  }

  .data-wrapper {
    padding-bottom: var(--toolbar-vertical-padding);
    height: 100%;
    width: var(--contact-side-panel-width);

    .panel-toolbar {
      --padding: calc(var(--toolbar-vertical-padding) / 2);

      padding: var(--padding) var(--padding) var(--padding) var(--toolbar-vertical-padding);
    }

    .data-part {
      padding: 0 16px;

      &.border {
        border-bottom: 1px solid var(--border-color);
      }

      &-toolbar {
        padding: 10px 16px;
        margin-bottom: var(--toolbar-margin-bottom);

        .dx-button {
          min-width: 90px;
        }
      }
    }

    .panel-scroll {
      height: calc(100% - 20px);
    }

    .contact-name {
      font-weight: bold;
      margin-right: 8px;
    }

    .opportunities {
      padding-bottom: 10px;
    }

    .dx-accordion {
      .accordion-title {
        vertical-align: middle;
        padding-right: 10px;
        display: flex;
        align-items: center;
      }
    }
  }
}
</style>

// packages/angular/src/app/components/library/contact-panel/contact-panel.component.ts
import {
  Component,
  OnInit,
  OnChanges,
  OnDestroy,
  Output,
  Input,
  SimpleChanges,
  EventEmitter,
  AfterViewChecked,
  inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import {
  DxAccordionModule,
  DxButtonModule,
  DxDropDownButtonModule,
  DxToolbarModule,
  DxLoadPanelModule,
  DxScrollViewModule,
  DxFormModule,
  DxValidatorModule,
  DxValidationGroupModule,
} from 'devextreme-angular';
import { DxButtonTypes } from 'devextreme-angular/ui/button';
import {
  FormTextboxComponent,
  FormPhotoComponent,
  ContactStatusComponent,
  CardActivitiesComponent,
} from 'src/app/components';
import { ScreenService, DataService } from 'src/app/services';
import { distinctUntilChanged, Subject, Subscription} from 'rxjs';
import { Contact } from 'src/app/types/contact';

@Component({
    selector: 'contact-panel',
    templateUrl: './contact-panel.component.html',
    styleUrls: ['./contact-panel.component.scss'],
    providers: [DataService],
    imports: [
      DxAccordionModule,
      DxButtonModule,
      DxDropDownButtonModule,
      DxToolbarModule,
      DxLoadPanelModule,
      DxScrollViewModule,
      DxFormModule,
      DxValidatorModule,
      DxValidationGroupModule,
      FormTextboxComponent,
      FormPhotoComponent,
      CardActivitiesComponent,
      ContactStatusComponent,
      CommonModule,
    ]
})
export class ContactPanelComponent implements OnInit, OnChanges, AfterViewChecked, OnDestroy {
  @Input() isOpened = false;

  @Input() userId: number;

  @Output() isOpenedChange = new EventEmitter<boolean>();

  @Output() pinnedChange = new EventEmitter<boolean>();

  private pinEventSubject = new Subject<boolean>();

  formData: Contact;

  contactData: Contact;

  pinned = false;

  isLoading = true;

  isEditing = false;

  isPinEnabled = false;

  userPanelSubscriptions: Subscription[] = [];

  private screen = inject(ScreenService);
  private service = inject(DataService);
  private router = inject(Router);

  constructor() {
    this.userPanelSubscriptions.push(
      this.screen.changed.subscribe(this.calculatePin),
      this
        .pinEventSubject
        .pipe(distinctUntilChanged())
        .subscribe(this.pinnedChange)
    );
  }

  ngOnInit(): void {
    this.calculatePin();
  }

  ngAfterViewChecked(): void {
    this.pinEventSubject.next(this.pinned);
  }

  ngOnChanges(changes: SimpleChanges): void {
    const { userId } = changes;

    if (userId?.currentValue) {
      this.loadUserById(userId.currentValue);
    }
  }

  ngOnDestroy(): void {
    this.userPanelSubscriptions.forEach((sub) => sub.unsubscribe());
  }

  loadUserById = (id: number) => {
    this.isLoading = true;

    this.service.getContact(id).subscribe((data) => {
      this.formData = data;
      this.contactData = { ...this.formData };
      this.isLoading = false;
      this.isEditing = false;
    })
  };

  onClosePanel = () => {
    this.isOpened = false;
    this.pinned = false;
    this.isOpenedChange.emit(this.isOpened);
  };

  onPinClick = () => {
    this.pinned = !this.pinned;
  };

  onSaveClick = ({ validationGroup } : DxButtonTypes.ClickEvent) => {
    if (!validationGroup.validate().isValid) return;
    this.contactData = { ...this.formData };
    this.isEditing = !this.isEditing;
  }

  calculatePin = () => {
    this.isPinEnabled = this.screen.sizes['screen-large'] || this.screen.sizes['screen-medium'];
    if (this.pinned && !this.isPinEnabled) {
      this.pinned = false;
    }
  };

  toggleEdit = () => {
    this.isEditing = !this.isEditing;
  };

  cancelHandler() {
    this.toggleEdit();
    this.formData = { ...this.contactData };
  }

  navigateToDetails = () => {
    this.router.navigate(['/crm-contact-details']);
  };
}

<div class="panel" [ngClass]="{ pin: pinned(), open: isOpened() }">
  <div class="data-wrapper">
    @if (!isLoading() && formData(); as form) {
      <dx-toolbar class="panel-toolbar">
        <dxi-toolbar-item location="before">
          <span class="contact-name value">{{ form.name }}</span>
        </dxi-toolbar-item>
        <dxi-toolbar-item location="before">
          <contact-status [value]="form.status"></contact-status>
        </dxi-toolbar-item>
        <dxi-toolbar-item location="after" [visible]="isPinEnabled()">
          <dx-button
            stylingMode="text"
            [icon]="pinned() ? 'pin' : 'unpin'"
            (onClick)="onPinClick()"
          ></dx-button>
        </dxi-toolbar-item>
        <dxi-toolbar-item location="after">
          <dx-button
            icon="close"
            stylingMode="text"
            (onClick)="onClosePanel()"
          ></dx-button>
        </dxi-toolbar-item>
      </dx-toolbar>

      <dx-scroll-view class="panel-scroll">
        <dx-validation-group>
          <div class="data-part border">
            <dx-form
              class="plain-styled-form"
              labelMode="floating"
              [class.view-mode]="!isEditing()"
            >
              <dxi-form-item itemType="group" [colCount]="2" cssClass="photo-row">
                <dxo-form-col-count-by-screen [xs]="2"></dxo-form-col-count-by-screen>
                <dxi-form-item cssClass="photo-box">
                  <div *dxTemplate>
                    <form-photo [link]="form.image"></form-photo>
                  </div>
                </dxi-form-item>

                <dxi-form-item itemType="group">
                  <dxi-form-item cssClass="accent">
                    <div *dxTemplate>
                      <form-textbox
                        label="Company"
                        [(value)]="form.company"
                        [isEditing]="isEditing()"
                      ></form-textbox>
                    </div>
                  </dxi-form-item>

                  <dxi-form-item>
                    <div *dxTemplate>
                      <form-textbox
                        label="Position"
                        [(value)]="form.position"
                        [isEditing]="isEditing()"
                      ></form-textbox>
                    </div>
                  </dxi-form-item>

                  <dxi-form-item cssClass="accent">
                    <div *dxTemplate>
                      <form-textbox
                        label="Assigned to"
                        [(value)]="form.manager"
                        [isEditing]="isEditing()"
                      ></form-textbox>
                    </div>
                  </dxi-form-item>
                </dxi-form-item>
              </dxi-form-item>

              <dxi-form-item itemType="group" cssClass="contact-fields-group">
                <dxi-form-item>
                  <div *dxTemplate>
                    <form-textbox
                      icon="tel"
                      mask="(000) 000-0000"
                      [(value)]="form.phone"
                      [isEditing]="isEditing()"
                    >
                    </form-textbox>
                  </div>
                </dxi-form-item>
                <dxi-form-item>
                  <div *dxTemplate>
                    <form-textbox
                      icon="email"
                      [(value)]="form.email"
                      [isEditing]="isEditing()"
                      [validators]="[{ type: 'email' }]"
                    ></form-textbox>
                  </div>
                </dxi-form-item>
                <dxi-form-item>
                  <div *dxTemplate>
                    <form-textbox
                      icon="home"
                      [(value)]="form.address"
                      [isEditing]="isEditing()"
                      [validators]="[]"
                    >
                    </form-textbox>
                  </div>
                </dxi-form-item>
              </dxi-form-item>
            </dx-form>
          </div>

          <div class="data-part data-part-toolbar border">
            <dx-toolbar>
              <dxi-toolbar-item location="after" [visible]="!isEditing()">
                <dx-button
                  text="Edit"
                  icon="edit"
                  stylingMode="contained"
                  type="default"
                  (onClick)="toggleEdit()"
                >
                </dx-button>
              </dxi-toolbar-item>
              <dxi-toolbar-item location="after" [visible]="!isEditing()">
                <dx-button
                  text="Details"
                  stylingMode="outlined"
                  type="normal"
                  (onClick)="navigateToDetails()"
                >
                </dx-button>
              </dxi-toolbar-item>
              <dxi-toolbar-item
                location="after"
                locateInMenu="never"
                [visible]="isEditing()"
              >
                <dx-button
                  text="Save"
                  icon="save"
                  stylingMode="contained"
                  type="default"
                  (onClick)="onSaveClick($event)"
                >
                </dx-button>
              </dxi-toolbar-item>
              <dxi-toolbar-item
                location="after"
                locateInMenu="never"
                [visible]="isEditing()"
              >
                <dx-button
                  text="Cancel"
                  stylingMode="outlined"
                  type="normal"
                  (onClick)="cancelHandler()"
                ></dx-button>
              </dxi-toolbar-item>
              <dxi-toolbar-item
                location="before"
                widget="dxDropDownButton"
                [options]="{
                  text: 'Actions',
                  stylingMode: 'text',
                  dropDownOptions: { width: 'auto' },
                  width: 'auto',
                  items: [
                    'Call',
                    'Send Fax',
                    'Send Email',
                    'Schedule a Meeting'
                  ]
                }"
              ></dxi-toolbar-item>
            </dx-toolbar>
          </div>
        </dx-validation-group>

        <div class="data-part">
          <dx-accordion [multiple]="true" [collapsible]="true">
            <div class="accordion-title" *dxTemplate="let t of 'title'">
              <span>{{ t.title }}</span>
            </div>

            <dxi-accordion-item title="Opportunities">
              <div *dxTemplate="let i of 'item'">
                @for (opportunity of form.opportunities; track opportunity.name) {
                  <div class="opportunities">
                    <span class="value">{{ opportunity.name }} </span>
                    <br />
                    <span class="value black small">{{
                        opportunity.price | currency: 'USD':'$':'1.0-0'
                      }}</span>
                    <br />
                  </div>
                }
              </div>
            </dxi-accordion-item>

            <dxi-accordion-item title="Activities">
              <card-activities
                [activities]="form.activities"
              ></card-activities>
            </dxi-accordion-item>
          </dx-accordion>
        </div>
      </dx-scroll-view>
    }

    <dx-load-panel
      container=".panel"
      [width]="300"
      [visible]="isLoading()"
      [showPane]="false"
      [position]="{ of: '.panel' }"
    ></dx-load-panel>
  </div>
</div>
