// packages/angular/src/app/components/utils/calendar-list/calendar-list.component.ts
import {
  Component, NgModule, EventEmitter, Output, Input, OnInit,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import { DxButtonModule, DxCheckBoxModule } from 'devextreme-angular';
import { DxListModule } from 'devextreme-angular/ui/list';
import { DxButtonTypes } from 'devextreme-angular/ui/button';

@Component({
  selector: 'calendar-list',
  templateUrl: './calendar-list.component.html',
  styleUrls: ['./calendar-list.component.scss'],
})
export class CalendarListComponent implements OnInit {
  @Input() dataSource: Record<string, any>[];

  @Output() listSelectionChanged = new EventEmitter<any>();

  selectedItems = [];

  constructor() {}

  ngOnInit() {
    this.selectedItems = [...this.dataSource.flatMap((el) => el.items)];
  }

  selectionChanged(item, isSelected) {
    const selected = this.selectedItems;
    this.selectedItems = isSelected ? [...selected, item] :  selected.filter((el) => el !== item);
    this.listSelectionChanged.emit(this.selectedItems);
  }

  onAddClick(e: DxButtonTypes.ClickEvent) {
    e.event.stopImmediatePropagation();
  }
}

@NgModule({
  imports: [
    DxListModule,
    DxCheckBoxModule,
    DxButtonModule,
    HttpClientModule,
    CommonModule,
  ],
  providers: [],
  exports: [CalendarListComponent],
  declarations: [CalendarListComponent],
})
export class CalendarListModule { }

<dx-list
  class='calendar-list'
  [dataSource]="dataSource"
  [activeStateEnabled]="false"
  [focusStateEnabled]="false"
  [hoverStateEnabled]="false"
  [grouped]="true"
  [collapsibleGroups]="true"
  [scrollingEnabled]="false"
>
  <div *dxTemplate="let item of 'group'">
    <div class='list-header'>
      {{ item.key }}
      <dx-button icon='add'
                 stylingMode='contained'
                 (onClick)="onAddClick($event)"
      ></dx-button>
    </div>
  </div>

  <div *dxTemplate="let item of 'item'">
    <div class='list-item'>
      <dx-check-box [value]="selectedItems.includes(item)"
                    [focusStateEnabled]="false"
                    [ngStyle]="{'--checkbox-color': item.checkboxColor}"
                    (onValueChanged)="selectionChanged(item, $event.value)"></dx-check-box>
      <span class='list-item-text'>{{ item.text }}</span>
    </div>
  </div>
</dx-list>

// packages/vue/src/components/utils/calendar-list.vue
<template>
  <dx-list
    class="calendar-list"
    :data-source="dataSource"
    :active-state-enabled="false"
    :focus-state-enabled="false"
    :hover-state-enabled="false"
    :grouped="true"
    :collapsible-groups="true"
    :scrolling-enabled="false"
  >
    <template #group="{ data: item }">
      <div class="list-header">
        {{ item.key }}
        <dx-button
          icon="add"
          styling-mode="contained"
          @click="onAddClick"
        />
      </div>
    </template>

    <template #item="{ data: item }">
      <div>
        <div class="list-item">
          <dx-check-box
            :value="selectedItems.includes(item)"
            :focus-state-enabled="false"
            :style="{'--checkbox-color': item.checkboxColor}"
            @value-changed="(value) => selectionChanged(item, value)"
          />
          <span class="list-item-text">{{ item.text }}</span>
        </div>
      </div>
    </template>
  </dx-list>
</template>

<script setup lang="ts">
import { DxList, DxCheckBox, DxButton } from 'devextreme-vue';
import { watchEffect } from 'vue';
import { DxButtonTypes } from 'devextreme-vue/button';

const props = withDefaults(defineProps<{
  dataSource: {items: Record<string, unknown>[]}[],
}>(), {
  dataSource: () => [],
});

let selectedItems: Record<string, unknown>[] = [];

watchEffect(() => {
  selectedItems = [...props.dataSource.flatMap((el) => el.items)];
});

const emit = defineEmits(['listSelectionChanged']);

function selectionChanged(item: Record<string, unknown>, { value }: { value: boolean }) {
  selectedItems = value ? [...selectedItems, item] : selectedItems.filter((el) => el !== item);
  emit('listSelectionChanged', selectedItems);
}

function onAddClick(e: DxButtonTypes.ClickEvent) {
  e.event?.stopImmediatePropagation();
}
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

.calendar-list {
  width: 100%;

  :deep(.dx-list-group-header) {
    display: flex;
    align-items: center;
    justify-content: space-between;
    border-style: none;
    flex-direction: row-reverse;

    .dx-inkripple {
      border-radius: 4px;
    }
  }

  .list-header {
    display: flex;
    vertical-align: middle;
    align-items: center;
    gap: 8px;
    color: var(--base-text-color);

    @include h1-header-text();
  }

  :deep(.dx-list-group-body) .dx-list-item.dx-list-item-selected {
    background-color: var(--base-bg);
  }

  :deep(.dx-list-group):not(.dx-list-group-collapsed):not(:last-child) {
    border-style: none;
  }

  .list-item {
    display: flex;
    vertical-align: middle;
    align-items: center;
    border-radius: 4px;
  }

  .list-item-text {
    padding: 0 8px;

    @include calendar-items-text();
  }

  --checkbox-color: var(--accent-color);

  :deep(.dx-checkbox-checked) .dx-checkbox-icon {
    background-color: var(--checkbox-color);
  }
}
</style>
