// packages/react/src/components/utils/opportunities-ticker/OpportunitiesTicker.tsx
import React from 'react';

import { TickerCard } from '../../library/ticker-card/TickerCard';
import { TickerProps } from '../../../types/analytics';
import { formatCurrency } from '../../../utils/format-currency';

export const OpportunitiesTicker = ({ value }: TickerProps) =>
  <TickerCard
    title='Opportunities'
    icon='datatrending'
    value={value}
    formatValue={formatCurrency}
    percentage={20.3}
  />;

// packages/vue/src/components/utils/opportunities-ticker.vue
<template>
  <ticker-card
    title="Opportunities"
    :data="props.data"
    icon="datatrending"
    :percentage="20.3"
  />
</template>

<script setup lang="ts">
import TickerCard from '@/components/library/ticker-card.vue';
import { SalesOrOpportunitiesByCategory } from '../../types/analytics';

const props = withDefaults(defineProps<{
  data: SalesOrOpportunitiesByCategory | null
}>(), {
  data: () => null,
});
</script>
