// packages/react/src/components/utils/opportunity-tile/OpportunityTile.tsx
import React from 'react';

import notify from 'devextreme/ui/notify';
import { formatNumber } from 'devextreme/localization';

import './OpportunityTile.scss';

export const OpportunityTile = ({ name, products, total, manager }) => {
  const opportunityClick = () => {
    notify('Click opportunity event');
  };

  const format = (item: number) => {
    return formatNumber(item, { type: 'currency', precision: 2 });
  };

  return (
    <div className='opportunities'>
      <div onClick={opportunityClick} className='opportunity'>
        <div className='name'>{name}</div>
        <div className='product-info'>
          Products: {products}, total: <span className='total'>{format(total)}</span>
        </div>
        <div className='owner'>
          Owner: <span className='owner-name'>{manager}</span>
        </div>
      </div>
    </div>
  );
};

// packages/vue/src/components/utils/opportunity-tile.vue
<template>
  <div
    class="opportunity"
    @click="opportunityClick()"
  >
    <div class="name">
      {{ props.data.name }}
    </div>
    <div class="product-info">
      Products: {{ props.data.products }}, total:
      <span class="total">{{ formatPrice(props.data.total, 2) }}</span>
    </div>
    <div class="owner">
      Owner: <span class="owner-name">{{ props.data.manager }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { formatPrice } from '@/utils/formatters';
import { Opportunity } from '@/types/opportunities';
import notify from 'devextreme/ui/notify';

const props = defineProps<{
  data: Opportunity
}>();

const opportunityClick = () => {
  notify('Click opportunity event');
};
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

.opportunity {
  cursor: pointer;
}

.name {
  font-size: 16px;
  font-weight: 700;
  padding-bottom: 8px;
}

.product-info {
  font-size: 12px;
  padding-bottom: 16px;

  .total {
    font-size: 16px;
  }
}

.owner {
  color: $texteditor-label-color;
  font-size: 14px;

  .owner-name {
    color: $base-text-color;
  }
}
</style>
