// packages/angular/src/app/components/utils/opportunities-ticker/opportunities-ticker.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SalesOrOpportunitiesByCategory } from 'src/app/types/analytics';
import { TickerCardComponent } from 'src/app/components/library/ticker-card/ticker-card.component';

@Component({
  selector: 'opportunities-ticker',
  templateUrl: 'opportunities-ticker.component.html',
  imports: [
    CommonModule,
    TickerCardComponent,
  ]
})

export class OpportunitiesTickerComponent {
  @Input() data: SalesOrOpportunitiesByCategory = null;
}

<ticker-card
  titleText="Opportunities"
  [data]="data"
  [percentage]="20.3"
  contentClass="opportunities-total"
>
</ticker-card>

// packages/vue/src/components/utils/opportunities-ticker.vue
<template>
  <ticker-card
    title="Opportunities"
    :data="props.data"
    :percentage="20.3"
  />
</template>

<script setup lang="ts">
import TickerCard from '@/components/library/ticker-card.vue';
import { SalesOrOpportunitiesByCategory } from '../../types/analytics';

const props = withDefaults(defineProps<{
  data: SalesOrOpportunitiesByCategory | null
}>(), {
  data: () => null,
});
</script>
