// packages/angular/src/app/components/library/card-activities/card-activities.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxListModule } from 'devextreme-angular/ui/list';
import { DxLoadPanelModule } from 'devextreme-angular/ui/load-panel';
import { CardMenuComponent } from '../card-menu/card-menu.component';
import { Activity } from 'src/app/types/activities';

@Component({
  selector: 'card-activities',
  templateUrl: './card-activities.component.html',
  styleUrls: ['./card-activities.component.scss'],
  imports: [
    DxListModule,
    DxButtonModule,
    DxLoadPanelModule,
    CardMenuComponent,
    CommonModule,
  ]
})
export class CardActivitiesComponent {
  @Input() activities!: Activity[];

  @Input() showBy? = false;

  @Input() isLoading: boolean = false;

  activityMenuItems: Array<{ text: string }> = [
    { text: 'View Details' },
    { text: 'Delete Record' },
  ];
}

<div id="activities-list" [ngClass]="activities ? 'load' : null">
  @if (activities && !isLoading) {
    <dx-list
      class="activities-list"
      [items]="activities"
      [scrollingEnabled]="false"
    >
      <div *dxTemplate="let item of 'item'">
        <div class="activity">
          <div class="name">{{ item.name }}</div>
          <div class="date" [ngClass]="{ by: showBy }">
            <span>{{ item.date | date: 'MM/dd/yyyy' }}</span>
            @if (showBy) {
              <span>by</span>
            }
            <span>{{ item.manager }}</span>
          </div>
          <card-menu [items]="activityMenuItems"> </card-menu>
        </div>
      </div>
    </dx-list>
  }

  <dx-load-panel
    container="#activities-list"
    [position]="{ of: '#activities-list' }"
    [visible]="!activities || isLoading"
    [showPane]="false"
  ></dx-load-panel>
</div>

// packages/react/src/components/library/card-activities/CardActivities.tsx
import React from 'react';

import List from 'devextreme-react/list';
import { CardMenu } from '../card-menu/CardMenu';

import { formatDate } from 'devextreme/localization';

import classNames from 'classnames';

import { Activities, Activity } from '../../../types/card-activities';
import { withLoadPanel } from '../../../utils/withLoadPanel';

import './CardActivities.scss';

const activityMenuItems = [
  { text: 'View Details' },
  { text: 'Delete Record' },
];

const listItemRender = (item: Activity) => {
  return (
    <div className='activity'>
      <div className='name'>{item.name}</div>
      <div className='date by'>
        <span>{formatDate(new Date(item.date), 'MM/dd/yyyy')}</span>
        <span className='by-span'>by</span>
        <span>{item.manager}</span>
      </div>
      <CardMenu items={activityMenuItems} />
    </div>
  );
};

const ActivitiesList = ({ activities }) => {
  return (
    <List className='activities-list' dataSource={activities} scrollingEnabled={false} itemRender={listItemRender} />
  );
};

const ActivitiesWithLoadPanel = withLoadPanel(ActivitiesList);

export const CardActivities = ({ activities, isLoading }: { activities?: Activities, isLoading?: boolean }) => (
  <div className={classNames({ 'card-activities': true, load: !activities })}>
    <ActivitiesWithLoadPanel
      activities={activities}
      hasData={!!activities}
      loading={isLoading}
      panelProps={{
        container: '.card-activities',
        position: { of: '.card-activities' }
      }}
    />
  </div>
);
