// packages/react/src/components/card-messages/CardMessages.tsx
import React, { useState, useCallback, useEffect } from 'react';

import TextBox from 'devextreme-react/text-box';
import TextArea from 'devextreme-react/text-area';
import Toolbar, { Item } from 'devextreme-react/toolbar';
import Button from 'devextreme-react/button';
import FileUploder from 'devextreme-react/file-uploader';
import ScrollView from 'devextreme-react/scroll-view';

import { formatDate } from 'devextreme/localization';

import { Message, Messages } from '../../shared/types/card-messages';
import { Avatar } from '../avatar/Avatar';

import './CardMessages.scss';

const getText = (text: string, user: string) => {
  return text.replace('{username}', user);
};

const Card = ({ data, user }: { data: Message; user: string }) => (
  <div className='message-container'>
    <Avatar owner={data.manager}></Avatar>
    <div className='message dx-card'>
      <div className='message-title'>
        <div className='left-title'>
          <div className='subject'>{data.subject}</div>
          <div>
            {formatDate(new Date(data.date), 'MM/dd/yyyy')} - {data.manager}
          </div>
        </div>
        <div>
          <Button icon='overflow'></Button>
        </div>
      </div>
      <div className='message-text'>{getText(data.text, user)}</div>
    </div>
  </div>
);

export const CardMessages = ({ items, user, onMessagesCountChanged }: {
  items?: Messages; user?: string; onMessagesCountChanged: (count: number) => void
}) => {
  const [messages, setMessages] = useState(items);
  const [title, setTitle] = useState('');
  const [message, setMessage] = useState('');

  useEffect(() => {
    setMessages(items);
  }, [items]);

  const send = useCallback(() => {
    if ((message === '' && title === '') || !messages || !user) {
      return;
    }
    setMessages([...messages, { manager: user, date: new Date(), text: message, subject: title }]);
    setTitle('');
    setMessage('');
    onMessagesCountChanged(messages.length + 1);
  }, [message, title, messages, user, onMessagesCountChanged]);

  const onTitleChanged = useCallback((value) => {
    setTitle(value);
  }, []);

  const onMessageChanged = useCallback((value) => {
    setMessage(value);
  }, []);

  return (
    <div className='messages'>
      <div className='input-messages'>
        <TextBox label='Subject' stylingMode='outlined' value={title} valueChangeEvent='keyup' onValueChange={onTitleChanged}></TextBox>
        <TextArea label='Message' height={150} stylingMode='outlined' value={message} valueChangeEvent='keyup' onValueChange={onMessageChanged}></TextArea>
        <Toolbar>
          <Item
            location='before'
          >
            <FileUploder className='file-uploader' labelText='' selectButtonText='Attach file'></FileUploder>
          </Item>
          <Item
            location='after'
            widget='dxButton'
            options={{
              text: 'Send',
              stylingMode: 'outlined',
              type: 'default',
              onClick: send,
            }}
          ></Item>
        </Toolbar>
      </div>
      <ScrollView className='message-list'>
        <div className='messages-content'>
          {user && messages?.map((message, index) => (
            <Card key={index} data={message} user={user} />
          ))}
        </div>
      </ScrollView>
    </div>
  );
};

// packages/angular/src/app/shared/components/card-messages/card-messages.component.ts
import { CommonModule } from '@angular/common';
import {
  Component, Input, NgModule,
} from '@angular/core';
import { DxTextAreaModule } from 'devextreme-angular/ui/text-area';
import { DxTextBoxModule } from 'devextreme-angular/ui/text-box';
import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';
import { DxFileUploaderModule } from 'devextreme-angular/ui/file-uploader';
import { DxScrollViewModule } from 'devextreme-angular/ui/scroll-view';
import { Message, Messages } from 'src/app/shared/types/messages';

@Component({
  selector: 'card-messages',
  templateUrl: './card-messages.component.html',
  styleUrls: ['./card-messages.component.scss'],
})
export class CardMessagesComponent {
  @Input() user: string;

  @Input() items: Messages;

  messageTitle = '';

  messageText = '';

  defaultText = () => {
    this.messageTitle = '';
    this.messageText = '';
  };

  getAvatarText(name: string) {
    return name.split(' ').map((name) => name[0]).join('');
  }

  setUserName(text: string) {
    return text.replace('{username}', this.user);
  }

  add = () => {
    if (this.messageText === '' || this.messageTitle === '') {
      return;
    }

    const newMessage: Message = {
      subject: this.messageTitle,
      text: this.messageText,
      manager: this.user,
      date: new Date(),
    };

    this.items.push(newMessage);

    this.defaultText();
  };
}

@NgModule({
  imports: [
    DxTextAreaModule,
    DxTextBoxModule,
    DxToolbarModule,
    DxFileUploaderModule,
    DxScrollViewModule,

    CommonModule,
  ],
  declarations: [CardMessagesComponent],
  exports: [CardMessagesComponent],
})
export class CardMessagesModule { }

<div class="messages">
  <div class="input-content">
    <dx-text-box
      label="Subject"
      stylingMode="outlined"
      [(value)]="messageTitle"
    ></dx-text-box>
    <dx-text-area
      label="Message"
      stylingMode="outlined"
      [(value)]="messageText"
      [height]="150"
    ></dx-text-area>
    <dx-toolbar>
      <dxi-item
        location="before"
      >
        <dx-file-uploader
          class="file-uploader"
          labelText=""
          selectButtonText="Attach file"
        >
        </dx-file-uploader>
      </dxi-item>
      <dxi-item
        location="after"
        widget="dxButton"
        [options]="{
          text: 'Add',
          stylingMode: 'outlined',
          type: 'default',
          onClick: add
        }"
      >
      </dxi-item>
    </dx-toolbar>
  </div>
  <div class="messages-content">
    <dx-scroll-view>
      <div class="message-container" *ngFor="let data of items?.concat(items)">
        <div class="avatar">
          {{ getAvatarText(data.manager) }}
        </div>
        <div class="message dx-card">
          <div class="message-title">
            <div class="left-title">
              <div class="subject">{{ data.subject }}</div>
              <div>{{ data.date | date: "MM/dd/y" }} - {{ data.manager }}</div>
            </div>
            <div>
              <dx-button icon="overflow"></dx-button>
            </div>
          </div>
          <div class="message-text">{{ setUserName(data.text) }}</div>
        </div>
      </div>
    </dx-scroll-view>
  </div>
</div>
