// packages/angular/src/app/shared/components/form-textbox/form-textbox.component.ts
import {Component, EventEmitter, Input, NgModule, Output} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxTextBoxModule,
  DxValidatorModule
} from "devextreme-angular";

@Component({
  selector: 'form-textbox',
  templateUrl: './form-textbox.component.html',
  styleUrls: ['form-textbox.component.scss'],
})
export class FormTextboxComponent {
  @Input() isEditing = false;

  @Input() text: string;

  @Input() label = '';

  @Input() mask: string = null;

  @Input() icon: string = null;

  @Input() validators: any[] = [];

  @Input() value!: string;

  @Output() valueChange: EventEmitter<string> = new EventEmitter();

}

@NgModule({
  imports: [
    DxButtonModule,
    DxTextBoxModule,
    DxValidatorModule,
    CommonModule,
  ],
  declarations: [FormTextboxComponent],
  exports: [FormTextboxComponent],
})
export class FormTextboxModule { }

<dx-text-box [label]="label"
             [(value)]="value"
             [readOnly]="!isEditing"
             [mask]="mask"
             [elementAttr]="{class: 'form-editor'}"
             [inputAttr]="{class: 'form-editor-input'}"
             stylingMode="filled"
             valueChangeEvent="keyup input change"
>
  <dx-validator [validationRules]="validators || [{type: 'required'}]"></dx-validator>
  <dxi-button *ngIf="icon"
              [options]="{icon: icon, type: 'back', elementAttr: { class: 'form-editor-icon' }}"
              name="icon"
              location="before"
  ></dxi-button>
</dx-text-box>

// packages/react/src/components/form-textbox/FormTextbox.tsx
import React from 'react';

import TextBox, { Button as TextBoxButton } from 'devextreme-react/text-box';
import Validator, { RequiredRule } from 'devextreme-react/validator';
import './FormTextbox.scss';

type TextboxProps = {
  value: string,
  label?: string,
  isEditing: boolean,
  onValueChange: (data) => void,
  mask?: string,
  icon?: string,
}

export const FormTextbox = ({ value, label, isEditing, onValueChange, mask = '', icon, children }: React.PropsWithChildren<TextboxProps>) => {
  return (
    <TextBox
      label={label}
      value={value}
      mask={mask}
      readOnly={isEditing}
      elementAttr={{ class: 'form-editor' }}
      inputAttr={{ class: 'form-editor-input' }}
      stylingMode='filled'
      onValueChange={onValueChange}
    >
      { icon &&
      <TextBoxButton
        name='icon'
        location='before'
        options={{
          icon: icon,
          type: 'back',
          elementAttr: { class: 'form-editor-icon' }
        }} />
      }
      <Validator>
        <RequiredRule />
        {children}
      </Validator>
    </TextBox>
  );
};
