// packages/angular/src/app/components/library/user-menu-section/user-menu-section.component.ts
import { Component, Input, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DxListModule, DxListTypes } from 'devextreme-angular/ui/list';
import { IUser } from '../../../services/auth.service';

@Component({
  selector: 'user-menu-section',
  templateUrl: 'user-menu-section.component.html',
  styleUrls: ['./user-menu-section.component.scss'],
  imports: [ DxListModule,  CommonModule ]
})

export class UserMenuSectionComponent {
  @Input()
  menuItems: any;

  @Input()
  showAvatar!: boolean;

  @Input()
  user!: IUser | null;

  @ViewChild('userInfoList', { read: ElementRef }) userInfoList!: ElementRef<HTMLElement>;

  handleListItemClick(e: DxListTypes.ItemClickEvent) {
    e.itemData?.onClick();
  }
}

<div>
  <div class="user-info">
    @if (showAvatar) {
      <div class="image-container">
        <div
          [style.backgroundImage]="'url(' + user?.avatarUrl + ')'"
          class="user-image"
        ></div>
      </div>
    }
    <div class="user-name">{{ user?.name }}</div>
  </div>
  <dx-list
    #userInfoList
    [items]="menuItems"
    [elementAttr]="{
      class: 'user-info-list'
    }"
    (onItemClick)="handleListItemClick($event)"
  ></dx-list>
</div>

// packages/react/src/components/library/user-menu-section/UserMenuSection.tsx
import React, { useMemo, useCallback } from 'react';
import { useAuth } from '../../../contexts/auth';
import List, { ListTypes } from 'devextreme-react/list';

import './UserMenuSection.scss';
import type { UserMenuSectionProps } from '../../../types';

type MenuItem = {
  text: string;
  icon: string;
  onClick: () => void;
};

export const UserMenuSection = ({
  showAvatar,
  listRef,
}: UserMenuSectionProps) => {
  const { user, signOut } = useAuth();

  const menuItems = useMemo<MenuItem[]>(
    () => [
      {
        text: 'Logout',
        icon: 'runner',
        onClick: signOut,
      },
    ],
    []
  );

  const listElementAttr = {
    class: 'user-info-list',
  };

  const onItemClick = useCallback(
    ({ itemData }: ListTypes.ItemClickEvent<MenuItem>) => itemData?.onClick(),
    []
  );

  return (
    <>
      <div className='user-info'>
        {showAvatar && (
          <div className='image-container'>
            <div
              style={{
                backgroundImage: `url(${user?.avatarUrl})`,
              }}
              className='user-image'
            />
          </div>
        )}
        <div className='user-name'>{user?.name}</div>
      </div>
      <List
        ref={listRef}
        elementAttr={listElementAttr}
        onItemClick={onItemClick}
        items={menuItems}
      />
    </>
  );
};
