// packages/vue/src/components/revenue-card.vue
<template>
  <card-analytics
    title="Revenue"
    content-class="sales"
  >
    <dx-chart
      v-if="props.data"
      :data-source="props.data"
    >
      <dx-series value-field="total" />
      <dx-common-series-settings
        argument-field="date"
        type="splinearea"
      >
        <dx-border :visible="true" />
      </dx-common-series-settings>
      <dx-argument-axis argument-type="datetime" />
      <dx-value-axis>
        <dx-chart-label>
          <dx-chart-format
            type="currency"
            currency="USD"
          />
        </dx-chart-label>
      </dx-value-axis>
      <dx-legend :visible="false" />
      <dx-size :height="270" />
    </dx-chart>
  </card-analytics>
</template>

<script setup lang="ts">
import {
  DxChart,
  DxSeries,
  DxCommonSeriesSettings,
  DxBorder,
  DxSize,
  DxLegend,
  DxArgumentAxis,
  DxValueAxis,
  DxLabel as DxChartLabel,
  DxFormat as DxChartFormat,
} from 'devextreme-vue/chart';

import { Sales } from '@/types/analytics';
import CardAnalytics from '@/components/card-analytics.vue';

const props = defineProps<{
  data: Sales
}>();
</script>

<style scoped>

</style>

// packages/react/src/pages/analytics-dashboard/cards/RevenueCard.tsx
import React from 'react';
import Chart, { ArgumentAxis, Border, CommonSeriesSettings, Format, Label, Legend, Series, Size, ValueAxis } from 'devextreme-react/chart';
import { CardAnalytics } from '../../../components/card-analytics/CardAnalytics';
import { Sale } from '../../../shared/types/analytics';

export const RevenueCard = ({ datasource }: { datasource: Sale[]}) => (
  <CardAnalytics title='Revenue' contentClass='sales'>
    <Chart dataSource={datasource}>
      <Series valueField='total' />
      <CommonSeriesSettings argumentField='date' type='splinearea'>
        <Border visible />
      </CommonSeriesSettings>
      <ArgumentAxis argumentType='datetime' />
      <ValueAxis>
        <Label>
          <Format type='currency' currency='USD' />
        </Label>
      </ValueAxis>
      <Legend visible={false} />
      <Size height={270} />
    </Chart>
  </CardAnalytics>
);
