// packages/vue/src/components/utils/toolbar-analytics.vue
<template>
  <dx-toolbar>
    <dx-item location="before">
      <span class="toolbar-header">
        <slot />
      </span>
    </dx-item>

    <dx-item
      v-if="props.showTabs"
      location="before"
    >
      <dx-tabs
        :width="screenInfo.isXSmall ? 150 : 'auto'"
        :show-nav-buttons="false"
        :scroll-by-content="true"
        :selected-item-keys="[5]"
        key-expr="key"
        :items="analyticsPanelItems"
        @item-click="selectionChange($event)"
      />
    </dx-item>

    <dx-item
      location="after"
      locate-in-menu="auto"
      css-class="add-card"
    >
      <div>
        <dx-button
          icon="plus"
          text="Add Card"
          type="default"
          styling-mode="contained"
        />
      </div>
    </dx-item>

    <dx-item
      location="after"
      locate-in-menu="auto"
      widget="dxButton"
      show-text="inMenu"
      :options="refreshOptions"
    />

    <dx-item
      location="after"
      locate-in-menu="auto"
    >
      <div>
        <div class="separator" />
      </div>
    </dx-item>

    <dx-item
      location="after"
      locate-in-menu="auto"
      widget="dxButton"
      show-text="inMenu"
      :options="exportOptions"
    />
  </dx-toolbar>
</template>

<script setup lang="ts">
import DxButton from 'devextreme-vue/button';
import {
  DxToolbar,
  DxItem,
} from 'devextreme-vue/toolbar';
import { DxTabs } from 'devextreme-vue/tabs';
import { ItemClickEvent as TabsItemClickEvent } from 'devextreme/ui/tabs';
import { onMounted } from 'vue';
import { analyticsPanelItems } from '@/types/resource';

import { screenInfo } from '@/utils/media-query';

const props = withDefaults(defineProps<{
  showTabs?: boolean
}>(), { showTabs: false });

const emit = defineEmits(['tab-change']);
const [initialStartDate, initialEndDate] = analyticsPanelItems[4].value.split('/');

const selectionChange = (e: TabsItemClickEvent) => {
  const [startDate, endDate] = e.itemData.value.split('/');
  emit('tab-change', [startDate, endDate]);
};

onMounted(() => {
  emit('tab-change', [initialStartDate, initialEndDate]);
});

const refreshOptions = {
  text: 'Refresh',
  icon: 'refresh',
  stylingMode: 'text',
};

const exportOptions = {
  icon: 'export',
  text: 'Export',
  stylingMode: 'text',
};
</script>

<style lang="scss">
@use "@/variables.scss" as *;
@use "sass:math";

.toolbar-header {
  @include header();
}

.dx-tabs .dx-tab {
  text-align: center;
}

@media only screen and (max-width: 400px) {
  .dx-tab {
    min-width: 70px;
  }
}
</style>

// packages/angular/src/app/components/toolbar-analytics/toolbar-analytics.component.ts
import { Component, NgModule, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxTabsModule } from 'devextreme-angular/ui/tabs';
import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';

import { ItemClickEvent as TabsItemClickEvent } from 'devextreme/ui/tabs';

import { Dates, PanelItem } from 'src/app/types/resource';

@Component({
  selector: 'toolbar-analytics',
  templateUrl: './toolbar-analytics.component.html',
  styleUrls: ['./toolbar-analytics.component.scss']
})

export class ToolbarAnalyticsComponent {
  @Input() selectedItems: Array<number>;

  @Input() titleText: string;

  @Input() panelItems: Array<PanelItem>;

  @Output() selectionChanged = new EventEmitter<Dates>();

  constructor() { }

  selectionChange(e: TabsItemClickEvent) {
    const dates = e.itemData.value.split('/');

    this.selectionChanged.emit({ startDate: dates[0], endDate: dates[1] });
  }
}

@NgModule({
  imports: [
    CommonModule,
    DxButtonModule,
    DxTabsModule,
    DxToolbarModule
  ],
  declarations: [ToolbarAnalyticsComponent],
  exports: [ToolbarAnalyticsComponent],
})
export class ToolbarAnalyticsModule { }

<dx-toolbar>
  <dxi-item location="before">
    <span class="toolbar-header">{{ titleText }}</span>
  </dxi-item>

  <dxi-item
    *ngIf="panelItems"
    location="before"
    locateInMenu="auto">
    <dx-tabs
      [selectedItemKeys]="selectedItems"
      keyExpr="key"
      [items]="panelItems"
      (onItemClick)="selectionChange($event)"
    ></dx-tabs>
  </dxi-item>

  <dxi-item
    location="after"
    locateInMenu="auto"
    >
    <dx-button
      class="add-card"
      icon="plus"
      text="Add Card"
      type="default"
      stylingMode="contained"
    ></dx-button>
  </dxi-item>

  <dxi-item
    location="after"
    locateInMenu="auto"
    widget="dxButton"
    showText="inMenu"
    [options]="{
      text: 'Refresh',
      icon: 'refresh'
    }"
  ></dxi-item>

  <dxi-item location="after" locateInMenu="auto">
    <div class="separator"></div>
  </dxi-item>

  <dxi-item
    location="after"
    locateInMenu="auto"
    widget="dxButton"
    showText="inMenu"
    [options]="{
      icon: 'export',
      text: 'Export'
    }"
  ></dxi-item>
</dx-toolbar>
