// packages/angular/src/app/components/library/task-list-kanban/task-list-kanban.component.ts
import {
  Component, Input, SimpleChanges, OnChanges, ViewChild, Output, EventEmitter,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxScrollViewModule } from 'devextreme-angular/ui/scroll-view';
import { DxSortableModule, DxSortableComponent } from 'devextreme-angular/ui/sortable';
import { DxSortableTypes } from 'devextreme-angular/ui/sortable';

import { CardMenuComponent } from 'src/app/components';
import { Task } from 'src/app/types/task';
import { TaskStatus, taskStatusList } from 'src/app/types/task';
import { TaskKanbanCardComponent } from '../task-kanban-card/task-kanban-card.component';

type Board = {
  name: TaskStatus
  cards: Task[]
};

@Component({
    selector: 'task-list-kanban',
    templateUrl: './task-list-kanban.component.html',
    styleUrls: ['./task-list-kanban.component.scss'],
    imports: [
      DxButtonModule,
      DxScrollViewModule,
      DxSortableModule,
      TaskKanbanCardComponent,
      CardMenuComponent,
      CommonModule,
    ]
})
export class TaskListKanbanComponent implements OnChanges {
  @ViewChild(DxSortableComponent, { static: false }) sortable: DxSortableComponent;

  @Input() dataSource: Task[];

  @Output() addTaskEvent: EventEmitter<any> = new EventEmitter();

  kanbanDataSource: Board[] = [];

  statuses = taskStatusList;

  boardMenuItems: Array<{ text: string }> = [
    { text: 'Add card' },
    { text: 'Copy list' },
    { text: 'Move list' },
  ];

  refresh() {
    this.sortable.instance.update();
  }

  fillOutBoard = (cards: Task[]): Board[] => {
    const result: Board[] = [];
    for (const status of this.statuses) {
      const value = cards.filter((item) => item.status === status);

      result.push(<Board>{ name: status, cards: value });
    }

    return result;
  };

  ngOnChanges(changes: SimpleChanges) {
    if (changes.dataSource) {
      this.kanbanDataSource = this.fillOutBoard(changes.dataSource.currentValue);
    }
  }

  onListReorder = (e: DxSortableTypes.ReorderEvent) => {
    const { fromIndex, toIndex } = e;
    const list = this.kanbanDataSource.splice(fromIndex, 1)[0];
    this.kanbanDataSource.splice(toIndex, 0, list);
  };

  onTaskDragStart(e: DxSortableTypes.DragStartEvent) {
    const { fromData, fromIndex } = e;
    e.itemData = fromData.cards[fromIndex];
  }

  onTaskDrop(e: DxSortableTypes.ReorderEvent | DxSortableTypes.AddEvent) {
    const {
      fromData, toData, fromIndex, toIndex, itemData,
    } = e;

    itemData.status = toData.name;

    fromData.cards.splice(fromIndex, 1);
    toData.cards.splice(toIndex, 0, itemData);
  }

  addTask() {
    this.addTaskEvent.emit();
  }
}


<dx-scroll-view
  class="scrollable-board"
  direction="both"
  showScrollbar="always"
>
  <dx-sortable
    class="sortable-lists"
    itemOrientation="horizontal"
    handle=".list-title"
    (onReorder)="onListReorder($event)"
  >
    @for (board of kanbanDataSource; track board.name) {
      <div class="list">
        <div class="list-title theme-text-color">
          <span>{{ board.name }}</span>
          <card-menu [items]="boardMenuItems"> </card-menu>
        </div>
        <dx-scroll-view
          class="scrollable-list"
          direction="vertical"
          showScrollbar="always"
        >
          <dx-sortable
            class="sortable-cards"
            group="cardsGroup"
            [data]="board"
            (onDragStart)="onTaskDragStart($event)"
            (onReorder)="onTaskDrop($event)"
            (onAdd)="onTaskDrop($event)"
          >
            @for (task of board.cards; track task.id) {
              <task-kanban-card class="dx-card" [task]="task"></task-kanban-card>
            }
          </dx-sortable>

          <div class="add-task">
            <dx-button
              icon="plus"
              text="Add Task"
              stylingMode="text"
              width="100%"
              (onClick)="addTask()"
            ></dx-button>
          </div>
        </dx-scroll-view>
      </div>
    }
  </dx-sortable>
</dx-scroll-view>

// packages/vue/src/pages/planning-task-list/components/task-list-kanban/task-list-kanban.vue
<template>
  <dx-scroll-view class="scrollable-board"
                  direction="horizontal"
                  show-scrollbar="always"
  >
    <dx-sortable class="sortable-lists"
                 item-orientation="horizontal"
                 handle=".list-title"
                 @reorder="onListReorder"
    >
      <div class="list" v-for="board in kanbanDataSource">
        <div class="list-title dx-theme-text-color">
          <span>{{ board.name }}</span>
          <dx-menu :items="boardMenuItems"/>
        </div>
        <dx-scroll-view class="scrollable-list"
                        direction="vertical"
                        showScrollbar="always"
        >
          <dx-sortable class="sortable-cards"
                       group="cardsGroup"
                       :data="board"
                       @dragStart="onTaskDragStart"
                       @reorder="onTaskDrop"
                       @add="onTaskDrop"
          >
            <div v-for="task in board.cards">
              <task-kanban-card class="dx-card" :task="task"></task-kanban-card>
            </div>
          </dx-sortable>

          <div class="add-task">
            <dx-button icon="plus"
                       text="Add Task"
                       stylingMode="text"
                       @click="notify('Add task event')"
            />
          </div>
        </dx-scroll-view>
      </div>
    </dx-sortable>
  </dx-scroll-view>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import 'jspdf-autotable';
import { Task, TaskStatus, taskStatusList } from '@/types/task';
import { AddEvent, ReorderEvent, DragStartEvent } from 'devextreme/ui/sortable';
import { DxScrollView } from 'devextreme-vue/scroll-view';
import { DxSortable } from 'devextreme-vue/sortable';
import { DxButton } from 'devextreme-vue/button';
import { DxMenu } from 'devextreme-vue/menu';
import TaskKanbanCard from './components/task-kanban-card.vue';

interface Board {
  name: TaskStatus
  cards: Task[]
}

const props = withDefaults(defineProps<{
  tasks: Task[]
}>(), {
  tasks: () => [],
});

const statuses = taskStatusList;
const boardMenuItems: Array<{ icon: string, items: Array<{ text: string }> }> = [{
  icon: 'more',
  items: [
    { text: 'Add card...' },
    { text: 'Copy list..' },
    { text: 'Move list..' },
  ],
},
];

const fillOutBoard = (cards: Task[]): Board[] => {
  const result: Board[] = [];
  statuses.forEach((status) => {
    const value = cards.filter((item) => item.status === status);

    result.push({ name: status, cards: value });
  });

  return result;
};
const kanbanDataSource = computed(
  () => (props.tasks ? fillOutBoard(props.tasks) : []),
);

function onListReorder(e: ReorderEvent) {
  const { fromIndex, toIndex } = e;
  const list = kanbanDataSource.value.splice(fromIndex, 1)[0];
  kanbanDataSource.value.splice(toIndex, 0, list);
}

function onTaskDragStart(e: DragStartEvent) {
  const { fromData, fromIndex } = e;
  e.itemData = fromData.cards[fromIndex];
}

function onTaskDrop(e: ReorderEvent | AddEvent) {
  const {
    fromData, toData, fromIndex, toIndex, itemData,
  } = e;

  itemData.status = toData.name;

  fromData.cards.splice(fromIndex, 1);
  toData.cards.splice(toIndex, 0, itemData);
}

const notify = (text: string) => {
  notify(text);
};
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

.scrollable-board {
  white-space: nowrap;
}

.list {
  border-radius: 4px;
  margin: 10px;
  background-color: $background-gray-color;
  display: inline-block;
  vertical-align: top;
  white-space: normal;

  .list-title {
    font-size: 16px;
    padding: 10px;
    margin-bottom: -10px;
    font-weight: bold;
    cursor: pointer;
    display: flex;
    justify-content: space-between;

    .dx-button {
      background-color: rgba(0, 0, 0, 0);
    }
  }
}

.scrollable-list {
  width: 260px;
}

:deep(.sortable-cards) {
  padding: 10px;
  display: flex;
  flex-direction: column;
  gap: 10px;

  .dx-sortable {
    display: block;
  }
}

.add-task {
  padding: 10px;
}

:deep(.add-task) {
  .dx-icon,
  .dx-button-text {
    color: $base-accent;
  }
}
</style>
