// packages/vue/src/pages/sign-in-form.vue
<template>
  <CardAuth title="Sign In">
    <LoginForm
      resetLink="/reset-password-form"
      createAccountLink="/sign-up-form"
    ></LoginForm>
  </CardAuth>
</template>

<script setup lang="ts">
import CardAuth from '@/components/card-auth.vue';
import LoginForm from '@/components/login-form.vue';

</script>

<style scoped lang="scss">
@use "@/variables" as *;

</style>

// packages/angular/src/app/pages/sign-in-form/sign-in-form.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

import { CardAuthComponent, LoginFormComponent } from 'src/app/components';

@Component({
    selector: 'app-sign-in-form',
    templateUrl: './sign-in-form.component.html',
    styleUrls: ['./sign-in-form.component.scss'],
    imports: [
      CommonModule,
      LoginFormComponent,
      CardAuthComponent,
    ]
})
export class AppSignInComponent {
}


<app-card-auth title="Sign In">
  <app-login-form
    resetLink="/reset-password-form"
    createAccountLink="/register-form"
  ></app-login-form>
</app-card-auth>
