// packages/angular/src/app/components/library/card-analytics/card-analytics.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { DxLoadPanelModule } from 'devextreme-angular/ui/load-panel';
import { PositionConfig } from 'devextreme/animation/position';
import { CardMenuComponent } from '../card-menu/card-menu.component';
@Component({
  selector: 'card-analytics',
  templateUrl: './card-analytics.component.html',
  styleUrls: ['./card-analytics.component.scss'],
  imports: [
    DxLoadPanelModule,
    CardMenuComponent,
    CommonModule,
  ]
})

export class CardAnalyticsComponent {
  @Input() titleText: string;

  @Input() contentClass: string;

  @Input() isMenuVisible = true;

  @Input() isLoading = false;

  menuItems: Array<{ text: string }> = [
    { text: 'Configure' },
    { text: 'Remove' },
  ];

  position: PositionConfig;
}

<div class="card {{ contentClass }}">
  <div class="header">
    <card-menu [visible]="isMenuVisible" [items]="menuItems"> </card-menu>
    @if (titleText) {
      <div class="title">{{ titleText }}</div>
    }
    <ng-content select="[filter]"></ng-content>
  </div>
  @if (!isLoading) {
    <div class="content">
      <ng-content></ng-content>
    </div>
  }
</div>

// packages/react/src/components/library/card-analytics/CardAnalytics.tsx
import React, { ReactNode } from 'react';
import { CardMenu } from '../card-menu/CardMenu';
import './CardAnalytics.scss';

type CardProps = {
  title?: string;
  additionalHeaderContent?: ReactNode;
  contentClass: string;
  isLoading?: boolean;
  menuVisible?: boolean;
};

const menuItems = [{ text: 'Configure' }, { text: 'Remove' }];

export const CardAnalytics = ({
  title,
  contentClass,
  isLoading = false,
  children,
  additionalHeaderContent,
  menuVisible = true,
}: React.PropsWithChildren<CardProps>) => (
  <div className={`card ${contentClass}`}>
    <div className='header'>
      <CardMenu visible={menuVisible} items={menuItems} />
      {title && <div className='title'>{title}</div>}
      {additionalHeaderContent}
    </div>
    {!isLoading && <div className='card-contents'>{children}</div>}
  </div>
);
