// packages/angular/src/app/pages/planning-task-details/planning-task-details.component.ts
import {Component, inject, OnInit} from '@angular/core';
import { CommonModule, Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import {
  DxButtonModule,
  DxDropDownButtonModule,
  DxTabPanelModule,
  DxValidationGroupModule,
  DxScrollViewModule,
} from 'devextreme-angular';
import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';

import {
  CardActivitiesComponent,
  CardNotesComponent,
  CardMessagesComponent,
} from 'src/app/components';
import { Task } from 'src/app/types/task';
import { DataService } from 'src/app/services';
import { TaskFormComponent } from 'src/app/components/library/task-form/task-form.component';

const DEFAULT_TASK_ID = 1;

@Component({
  templateUrl: './planning-task-details.component.html',
  styleUrls: ['./planning-task-details.component.scss'],
  providers: [ DataService ],
  imports: [
    DxButtonModule,
    DxDropDownButtonModule,
    DxTabPanelModule,
    DxValidationGroupModule,
    DxToolbarModule,

    CardActivitiesComponent,
    CardNotesComponent,
    CardMessagesComponent,
    TaskFormComponent,
    DxScrollViewModule,
    CommonModule,
  ]
})
export class PlanningTaskDetailsComponent implements OnInit {
  private service = inject(DataService);

  private route = inject(ActivatedRoute);

  private location = inject(Location);

  task: Task;

  taskId: number;

  taskName = 'Loading...';

  isLoading = false;

  constructor() {
    const id = parseInt(this.route.snapshot.queryParamMap.get('id'), 10);
    this.taskId = id || DEFAULT_TASK_ID;
  }

  loadData = () => {
    this.service.getTask(this.taskId).subscribe((data) => {
      this.task = data;
      this.taskName = data.text;
      this.isLoading = false;
    });
  };

  ngOnInit(): void {
    this.loadData();
  }

  refresh = () => {
    this.isLoading = true;
    this.loadData();
  }

  navigateBack(): void {
    this.location.back()
  }
}


<dx-scroll-view class="view-wrapper-scroll">
  <div class="view-wrapper">
    <dx-toolbar class="toolbar-details theme-dependent">
      <dxi-toolbar-item location="before">
        <dx-button
          icon="arrowleft"
          stylingMode="text"
          (onClick)="navigateBack()"
        >
        </dx-button>
      </dxi-toolbar-item>
      <dxi-toolbar-item location="before" [text]="taskName()"></dxi-toolbar-item>
      <dxi-toolbar-item location="after" locateInMenu="auto">
        <dx-drop-down-button
          text="Actions"
          stylingMode="text"
          [dropDownOptions]="{ width: 'auto' }"
        >
          <dxi-drop-down-button-item text="Duplicate"></dxi-drop-down-button-item>
          <dxi-drop-down-button-item text="Close"></dxi-drop-down-button-item>
          <dxi-drop-down-button-item text="Delete"></dxi-drop-down-button-item>
        </dx-drop-down-button>
      </dxi-toolbar-item>
      <dxi-toolbar-item
        location="after"
        locateInMenu="auto"
        widget="dxButton"
        showText="inMenu"
        [options]="{
          text: 'Attach',
          icon: 'attach',
          stylingMode: 'text'
        }"
      ></dxi-toolbar-item>
      <dxi-toolbar-item
        location="after"
        locateInMenu="auto"
        widget="dxButton"
        showText="inMenu"
        [options]="{
          text: 'Refresh',
          icon: 'refresh',
          onClick: refresh,
          stylingMode: 'text'
        }"
      ></dxi-toolbar-item>
    </dx-toolbar>

    <div class="panels">
      <div class="left">
        <dx-validation-group>
          @if (task(); as currentTask) {
            <task-form [task]="currentTask" [isLoading]="isLoading()"></task-form>
          }
        </dx-validation-group>
      </div>

      <div class="right theme-dependent">
        <div class="dx-card details-card">
          <dx-tab-panel
            secondary="secondary"
            [focusStateEnabled]="false"
            [showNavButtons]="true"
            [deferRendering]="false"
          >
            @if (task(); as currentTask) {
              <dxi-tab-panel-item title="Activities">
                <card-activities
                  [isLoading]="isLoading()"
                  [activities]="currentTask.activities"
                  [showBy]="true"
                ></card-activities>
              </dxi-tab-panel-item>
              <dxi-tab-panel-item title="Notes">
                <card-notes
                  [items]="currentTask.notes"
                  [user]="currentTask.owner"
                ></card-notes>
              </dxi-tab-panel-item>
              <dxi-tab-panel-item title="Messages">
                <card-messages
                  [items]="currentTask.messages"
                  [user]="currentTask.owner"
                ></card-messages>
              </dxi-tab-panel-item>
            }
          </dx-tab-panel>
        </div>
      </div>
    </div>
  </div>
</dx-scroll-view>

// packages/react/src/pages/planning-task-details/planning-task-details.tsx
import React, { useCallback, useEffect, useState } from 'react';
import { useSearchParams, useNavigate } from 'react-router';

import { Toolbar, Item as ToolbarItem } from 'devextreme-react/toolbar';
import DropDownButton, {
  Item as DropDownItem,
} from 'devextreme-react/drop-down-button';
import TabPanel, { Item as TabPanelItem } from 'devextreme-react/tab-panel';
import ValidationGroup from 'devextreme-react/validation-group';
import Button from 'devextreme-react/button';
import ScrollView from 'devextreme-react/scroll-view';

import {
  TaskForm,
  CardActivities,
  CardNotes,
  CardMessages,
} from '../../components';

import { Task } from '../../types/task';

import { getTask } from 'dx-template-gallery-data';

import './planning-task-details.scss';

const DEFAULT_TASK_ID = 1;

export const PlanningTaskDetails = () => {
  const [searchParams] = useSearchParams();
  const id = parseInt(searchParams.get('id') || '', 10);
  const navigate = useNavigate();
  const taskId = id || DEFAULT_TASK_ID;
  const [task, setTask] = useState<Task>();
  const [isLoading, setIsLoading] = useState(false);

  const loadData = useCallback(() => {
    getTask(taskId)
      .then((data) => {
        setTask(data);
        setIsLoading(false);
      })
      .catch((error) => console.log(error));
  }, [taskId]);

  const refresh = useCallback(() => {
    setIsLoading(true);
    loadData();
  }, [loadData]);

  useEffect(() => {
    loadData();
  }, []);

  return (
    <ScrollView className='view-wrapper-scroll'>
      <div className='view-wrapper view-wrapper-details'>
        <Toolbar className='toolbar-details theme-dependent'>
          <ToolbarItem location='before'>
            <Button
              icon='arrowleft'
              stylingMode='text'
              onClick={() => navigate(-1)}
            />
          </ToolbarItem>
          <ToolbarItem location='before' text={task?.text ?? 'Loading...'} />
          <ToolbarItem location='after' locateInMenu='auto'>
            <DropDownButton
              text='Actions'
              stylingMode='text'
              dropDownOptions={{ width: 'auto' }}
            >
              <DropDownItem text='Duplicate' />
              <DropDownItem text='Close' />
              <DropDownItem text='Delete' />
            </DropDownButton>
          </ToolbarItem>
          <ToolbarItem
            location='after'
            locateInMenu='auto'
            widget='dxButton'
            showText='inMenu'
          >
            <Button text='Attach' icon='attach' stylingMode='text' />
          </ToolbarItem>
          <ToolbarItem
            location='after'
            locateInMenu='auto'
            widget='dxButton'
            showText='inMenu'
          >
            <Button
              text='Refresh'
              icon='refresh'
              stylingMode='text'
              onClick={refresh}
            />
          </ToolbarItem>
        </Toolbar>
        <div className='panels'>
          <div className='left'>
            <ValidationGroup>
              <TaskForm task={task} isLoading={isLoading} />
            </ValidationGroup>
          </div>
          <div className='right'>
            <div className='dx-card details-card'>
              <TabPanel
                showNavButtons
                focusStateEnabled={false}
                deferRendering={false}
              >
                <TabPanelItem title='Activities'>
                  <CardActivities
                    activities={task?.activities}
                    isLoading={isLoading}
                  />
                </TabPanelItem>
                <TabPanelItem title='Notes'>
                  <CardNotes items={task?.notes} user={task?.owner} />
                </TabPanelItem>
                <TabPanelItem title='Messages'>
                  <CardMessages items={task?.messages} user={task?.owner} />
                </TabPanelItem>
              </TabPanel>
            </div>
          </div>
        </div>
      </div>
    </ScrollView>
  );
};
