// packages/react/src/components/library/scheduler-tooltip/scheduler-tooltip.tsx
import React from 'react';
import Button from 'devextreme-react/button';
import './scheduler-tooltip.scss';

export const TooltipContentTemplate = ({ selectedAppointmentData, deleteCurrentAppointment, editCurrentAppointment }) => {
  if (!selectedAppointmentData || !selectedAppointmentData.endDate) {
    return null;
  }
  const timeOptions = {
    hour: 'numeric',
    minute: 'numeric',
    hour12: false
  };
  const dateOptions = {
    ...timeOptions,
    weekday: 'short',
    day: 'numeric',
    month: 'numeric',
    year: 'numeric'
  };
  const timeString = `${selectedAppointmentData.startDate.toLocaleString(undefined, dateOptions)} - ${selectedAppointmentData.endDate.toLocaleTimeString(undefined, timeOptions)}`;

  return (<div className='appointment-tooltip'>
    <div className='title'>{selectedAppointmentData.text}</div>
    <div className='content'>
      <div className='date'>
        <Button icon='clock'
          focusStateEnabled={false}
          activeStateEnabled={false}
          hoverStateEnabled={false}
        />
        {timeString}
      </div>
      {selectedAppointmentData.description &&
        <div className='description'>
          <Button icon='textdocument'
            focusStateEnabled={false}
            activeStateEnabled={false}
            hoverStateEnabled={false}
          />
          {selectedAppointmentData.description}
        </div>
      }
    </div>
    <div className='buttons'>
      <Button
        className='button-danger'
        text='Delete'
        type='danger'
        stylingMode='text'
        onClick={deleteCurrentAppointment}
      />
      <Button
        className='button-success'
        text='Edit'
        type='success'
        stylingMode='text'
        onClick={editCurrentAppointment}
      />
    </div>
  </div>);
};

// packages/angular/src/app/components/library/scheduler-tooltip/scheduler-tooltip.component.ts
import {
  Component, EventEmitter, Input, Output,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxButtonModule } from 'devextreme-angular';
import { ApplyPipeDirective } from "../../../pipes/apply.pipe";

@Component({
  selector: 'scheduler-tooltip',
  templateUrl: './scheduler-tooltip.component.html',
  styleUrls: ['./scheduler-tooltip.component.scss'],
  imports: [
    ApplyPipeDirective,
    CommonModule,
    DxButtonModule,
  ],
})
export class SchedulerTooltipComponent {
  @Input() selectedAppointmentData: Record<string, any>;

  @Output() clickDeleteAppointment = new EventEmitter<any>();

  @Output() clickEditAppointment = new EventEmitter<any>();

  getTimeString = (selectedAppointmentData) => {
    const timeOptions = {
      hour: 'numeric',
      minute: 'numeric',
      hour12: false
    };

    const dateOptions = {
      ...timeOptions,
      weekday: 'short',
      day: 'numeric',
      month: 'numeric',
      year: 'numeric'
    };

    return `${selectedAppointmentData.startDate.toLocaleString(undefined, dateOptions)} - ${selectedAppointmentData.endDate?.toLocaleTimeString(undefined, timeOptions)}`;
  }
}

<div class="appointment-tooltip">
  <div class="title">{{ selectedAppointmentData.text }}</div>
  <div class="content">
    <div class="date">
      <dx-button
        icon="clock"
        stylingMode="text"
        [focusStateEnabled]="false"
        [activeStateEnabled]="false"
        [hoverStateEnabled]="false"
      ></dx-button>
      {{ getTimeString | apply: selectedAppointmentData }}
    </div>
    @if (selectedAppointmentData.description) {
      <div class="description">
        <dx-button
          icon="textdocument"
          stylingMode="text"
          [focusStateEnabled]="false"
          [activeStateEnabled]="false"
          [hoverStateEnabled]="false"
        ></dx-button>
        {{ selectedAppointmentData.description }}
      </div>
    }
  </div>
  <div class="buttons">
    <dx-button
      class="button-danger"
      text="Delete"
      type="danger"
      stylingMode="text"
      (onClick)="clickDeleteAppointment.emit(selectedAppointmentData)"
    ></dx-button>
    <dx-button
      class="button-success"
      text="Edit"
      type="success"
      stylingMode="text"
      (onClick)="clickEditAppointment.emit()"
    ></dx-button>
  </div>
</div>
