// packages/vue/src/pages/crm-contact-details/crm-contact-details.vue
<template>
  <div class="view-wrapper">
    <dx-toolbar>
      <dx-toolbar-item location="before">
        <dx-button icon="arrowleft" />
      </dx-toolbar-item>
      <dx-toolbar-item
        location="before"
        :text="contactName"
      />
      <dx-toolbar-item
        location="after"
        locate-in-menu="auto"
      ><div>
        <dx-button
          text="Terminate"
          type="default"
          styling-mode="contained"
        />
      </div>
      </dx-toolbar-item>
      <dx-toolbar-item
        location="after"
      >
        <dx-drop-down-button
          text="Actions"
          :width="120"
          styling-mode="text"
        >
          <dx-drop-down-item text="Assign to Me" />
          <dx-drop-down-item text="Archive" />
        </dx-drop-down-button>
      </dx-toolbar-item>
      <dx-toolbar-item
        location="after"
        locate-in-menu="auto"
      >
        <div>
          <div class="separator" />
        </div>
      </dx-toolbar-item>
      <dx-toolbar-item
        location="after"
        locate-in-menu="auto"
        widget="dxButton"
        show-text="inMenu"
        :options="{
          text: 'Copy',
          icon: 'copy'
        }"
      />
      <dx-toolbar-item
        location="after"
        locate-in-menu="auto"
        widget="dxButton"
        show-text="inMenu"
        :options="{
          text: 'Refresh',
          icon: 'refresh',
          onClick: refresh
        }"
      />
    </dx-toolbar>

    <div class="panels">
      <div class="left">
        <contact-form
          :contact-data="contactData"
          :is-editing="false"
          :is-loading="isLoading && !contactData.name"
        />
      </div>

      <div class="right">
        <contact-cards
          :is-loading="isLoading"
          :contact-name="contactData?.name"
          :contact-id="contactId"
          :tasks="contactData?.tasks"
          :activities="contactData?.activities"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { DxButton } from 'devextreme-vue/button';
import { DxDropDownButton, DxItem as DxDropDownItem } from 'devextreme-vue/drop-down-button';
import {
  DxToolbar,
  DxItem as DxToolbarItem,
} from 'devextreme-vue/toolbar';
// eslint-disable-next-line import/no-unresolved
import { getContact } from 'dx-template-gallery-data';
import type { Contact } from '@/types/contact';

import ContactForm from './components/contact-form.vue';
import ContactCards from './components/contact-cards/contact-cards.vue';

const contactId = 12;
const contactName = ref('');
const contactData = ref<Contact | Record<string, unknown>>({});
const isLoading = ref(false);

async function loadData() {
  isLoading.value = true;
  const data = await getContact(contactId);

  contactData.value = data;
  contactName.value = data.name;
  isLoading.value = false;
}

const refresh = () => {
  loadData();
};

onMounted(() => {
  loadData();
});
</script>

<style scoped lang="scss">
@use "@/variables" as *;
@include separator();

$left-panel-width: 400px;
$right-panel-width: 360px;

@media only screen and (max-width: 875px) {
  :deep(.contact-name-toolbar-item) {
    min-width: calc(#{$left-panel-width} + #{$right-panel-width} - 145px);
  }
}

.dx-toolbar {
  margin-bottom: calc(#{$toolbar-margin-bottom} / 2);

  :deep(.dx-toolbar-label > div) {
    @include header();
  }
}

.view-wrapper {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
  padding: 20px 16px 0 16px;

  .panels {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    gap: 20px;

    .left {
      flex: 1 $left-panel-width;
      margin-top: 8px;
    }

    .right {
      flex: 1 calc(100% - #{$left-panel-width} - 20px);
      margin-top: 8px;
      min-width: 340px;
    }
  }
}
</style>

// packages/react/src/pages/crm-contact-details/crm-contact-details.tsx
import React, { useEffect, useState, useCallback } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';

import { Item, Toolbar } from 'devextreme-react/toolbar';
import Button from 'devextreme-react/button';
import DropDownButton from 'devextreme-react/drop-down-button';

import {
  ContactCards,
  ContactForm,
} from '../../components';

import { Contact } from '../../types/crm-contact';

import {
  getContact,
  getContactNotes,
  getContactMessages,
  getActiveContactOpportunities,
  getClosedContactOpportunities,
} from 'dx-template-gallery-data';

import './crm-contact-details.scss';
import ScrollView from 'devextreme-react/scroll-view';

const DEFAULT_CONTACT_ID = 12;

export const CRMContactDetails = () => {
  const [searchParams] = useSearchParams();
  const id = parseInt(searchParams.get('id') || '', 10);
  const navigate = useNavigate();
  const contactId = id || DEFAULT_CONTACT_ID;
  const [data, setData] = useState<Contact>();
  const [notes, setNotes] = useState();
  const [messages, setMessages] = useState([]);
  const [activeOpportunities, setActiveOpportunities] = useState();
  const [closedOpportunities, setClosedOpportunities] = useState();
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = useCallback(() => {
    Promise.all([
      getContact(contactId)
        .then((data) => {
          setData(data);
        }),
      getContactNotes(contactId)
        .then((data) => {
          setNotes(data);
        }),
      getContactMessages(contactId)
        .then((data) => {
          setMessages(data);
        }),
      getActiveContactOpportunities(contactId)
        .then((data) => {
          setActiveOpportunities(data);
        }),
      getClosedContactOpportunities(contactId)
        .then((data) => {
          setClosedOpportunities(data);
        }),
    ]).then(() => { setIsLoading(false); }).catch((error) => console.log(error));
  }, [contactId]);

  const refresh = useCallback(() => {
    setIsLoading(true);
    loadData();
  }, [loadData]);

  return (
    <ScrollView className='view-wrapper-scroll'>
      <div className='view-wrapper view-wrapper-contact-details'>
        <Toolbar className='toolbar-details theme-dependent'>
          <Item location='before'>
            <Button
              icon='arrowleft'
              stylingMode='text'
              onClick={() => navigate(-1)}
            />
          </Item>
          <Item location='before' text={ data?.name ?? 'Loading...' } />
          <Item location='after' locateInMenu='auto'>
            <Button
              text='Terminate'
              type='default'
              stylingMode='contained'
            />
          </Item>
          <Item location='after'>
            <DropDownButton
              text='Actions'
              stylingMode='text'
              dropDownOptions={{ width: 'auto' }}
              items={['Assign to Me', 'Archive']}
            />
          </Item>
          <Item location='after' locateInMenu='auto'>
            <div className='separator' />
          </Item>
          <Item
            location='after'
            locateInMenu='auto'
            widget='dxButton'
            showText='inMenu'
          >
            <Button
              text='Copy'
              icon='copy'
              stylingMode='text'
            />
          </Item>
          <Item
            location='after'
            locateInMenu='auto'
            widget='dxButton'
            showText='inMenu'
          >
            <Button
              text='Refresh'
              icon='refresh'
              stylingMode='text'
              onClick={refresh}
            />
          </Item>
        </Toolbar>

        <div className='panels'>
          <div className='left'>
            <ContactForm
              data={data}
              isLoading={isLoading}
            />
          </div>

          <div className='right'>
            <ContactCards
              isLoading={isLoading}
              activeOpportunities={activeOpportunities}
              closedOpportunities={closedOpportunities}
              notes={notes}
              messages={messages}
              tasks={data?.tasks}
              activities={data?.activities}
              name={data?.name} />
          </div>
        </div>
      </div>
    </ScrollView>
  );
};
