// packages/vue/src/pages/crm-contact-form/crm-contact-form.vue
<template>
  <div class="contact-form-container">
    <div class="view-wrapper">
      <dx-toolbar>
        <dx-toolbar-item location="before">
          <dx-button icon="arrowleft" />
        </dx-toolbar-item>
        <dx-toolbar-item
          location="before"
          :text="contactName"
        />
        <dx-toolbar-item
          location="after"
          locate-in-menu="auto"
        >
          <dx-button
            text="Terminate"
            type="default"
            styling-mode="contained"
          />
        </dx-toolbar-item>
        <dx-toolbar-item
          location="after"
          locate-in-menu="auto"
          widget="dxDropDownButton"
          :options="{
            text:'Action',
            stylingMode:'text',
            width:120,
            items: ['Assign to Me', 'Archive']
          }"
        />
        <dx-toolbar-item
          location="after"
          locate-in-menu="auto"
        >
          <div class="separator" />
        </dx-toolbar-item>

        <dx-toolbar-item
          location="after"
          locate-in-menu="auto"
          widget="dxButton"
          show-text="inMenu"
          :options="{
            text: 'Copy',
            icon: 'copy'
          }"
        />

        <dx-toolbar-item
          location="after"
          locate-in-menu="auto"
          widget="dxButton"
          show-text="inMenu"
          :options="{
            text: 'Refresh',
            icon: 'refresh',
            onClick: refresh
          }"
        />
      </dx-toolbar>

      <div class="panels">
        <div class="left">
          <contact-form :contact-data="contactData" :is-editing="false" :is-loading="isLoading"/>
        </div>

        <div class="right">
          <!--        <contact-cards
                      [contactName]="(contactData$ | async)?.name"
                      [tasks]="(contactData$ | async)?.tasks"
                      [activities]="(contactData$ | async)?.activities"
                      [activeOpportunities]="activeOpportunities"
                      [closedOpportunities]="closedOpportunities"
                      [notes]="contactNotes"
                      [messages]="contactMessages"
                  ></contact-cards>-->
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';

import DxButton from 'devextreme-vue/button';
import {
  DxToolbar,
  DxItem as DxToolbarItem,
} from 'devextreme-vue/toolbar';

import ContactService from '@/pages/api/contact-service';
import ContactForm from './components/contact-form.vue';

const contactId = 12;

const contactName = ref('');
const contactData = ref({});
const isLoading = ref(false);

function loadData() {
  isLoading.value = true;
  ContactService.getContact(contactId).then((response:any) => {
    contactData.value = response.data;
    contactName.value = response.data.name;
    isLoading.value = false;
  }).catch((e: string) => {
    console.log(e);
  });
}

const refresh = () => {
  loadData();
};

onMounted(() => {
  loadData();
});

</script>

<style scoped lang="scss">
@use "@/variables" as *;
@include separator();

.contact-form-container {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
  padding: 20px 16px 0 16px;

  &:deep(.dx-toolbar) {
    .dx-toolbar-label > div {
      @include header();
    }
  }

  .view-wrapper {
    flex-direction: column;

    .panels {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-between;
      gap: 20px;

      .left {
        flex: 1 400px;
      }

      .right {
        flex: 1 calc(100% - 400px - 20px);
        min-width: 360px;
      }
    }
  }
}
</style>

// packages/angular/src/app/pages/crm-contact-form/crm-contact-form.component.ts
import { Component, OnInit, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { getRawStatuses } from 'dx-rwa-data';
import CustomStore from 'devextreme/data/custom_store';
import {
  DxButtonModule,
  DxDataGridModule,
  DxFormModule,
  DxDropDownButtonModule,
  DxSelectBoxModule,
  DxTabPanelModule,
  DxTextBoxModule,
  DxToolbarModule,
} from 'devextreme-angular';
import {
  CardActivitiesModule,
  CardNotesModule,
  CardMessagesModule,
} from 'src/app/shared/components';
import { RwaService } from 'src/app/shared/services';
import { forkJoin, Observable, Subscription } from 'rxjs';
import { Contact } from 'src/app/shared/types/contact';
import { Messages } from 'src/app/shared/types/messages';
import { Notes } from 'src/app/shared/types/notes';
import { Activities } from 'src/app/shared/types/activities';
import { ContactFormModule } from './contact-form/contact-form.component';
import { ContactCardsModule } from './contact-cards/contact-cards.component';

type Opportunitie = {
  name: string,
  products: string,
  manager: string,
  total: string
};

@Component({
  templateUrl: './crm-contact-form.component.html',
  styleUrls: ['./crm-contact-form.component.scss'],
  providers: [RwaService],
})
export class CrmContactFormComponent implements OnInit {
  contactId = 12;

  contact$: Observable<Contact>;

  activities$: Observable<Activities>;

  contactNotes: Notes;

  contactMessages: Messages;

  activeOpportunities: Opportunitie[];

  closedOpportunities: Opportunitie[];

  contactSubscription: Subscription;

  loadData = () => {
    this.contact$ = this.service.getContact(this.contactId);
    this.contactSubscription = this.contact$.subscribe((contact) => {
      this.activities$ = new Observable((obs) => obs.next(contact.activities));
    });

    const observable = forkJoin({
      contactNotes: this.service.getContactNotes(this.contactId),
      contactMessages: this.service.getContactMessages(this.contactId),
      activeOpportunities: this.service.getActiveContactOpportunities(this.contactId),
      closedOpportunities: this.service.getClosedContactOpportunities(this.contactId),
    });

    observable.subscribe((data) => {
      Object.keys(data).forEach((key) => this[key] = data[key]);
    });
  };

  constructor(private service: RwaService) {
    this.statuses = new CustomStore({
      loadMode: 'raw',
      load: getRawStatuses,
    });

    this.refresh = this.refresh.bind(this);
  }

  ngOnInit(): void {
    this.loadData();
  }

  ngOnDestroy(): void {
    this.contactSubscription.unsubscribe();
  }

  statuses: CustomStore;

  formatPhone(number: string | number): string {
    return String(number).replace(/(\d{3})(\d{3})(\d{4})/, '+1($1)$2-$3');
  }

  getSizeQualifier(width) {
    if (width < 415) return 'xs';
    return 'lg';
  }

  refresh() {
    this.loadData();
  }
}

@NgModule({
  imports: [
    DxFormModule,
    DxToolbarModule,
    DxButtonModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    DxDropDownButtonModule,
    DxTabPanelModule,
    DxDataGridModule,

    ContactFormModule,
    ContactCardsModule,

    CardActivitiesModule,
    CardNotesModule,
    CardMessagesModule,

    CommonModule,
  ],
  providers: [],
  exports: [],
  declarations: [CrmContactFormComponent],
})
export class CrmContactFormModule { }

<div class="view-wrapper">
  <dx-toolbar>
    <dxi-item
      location="before"
      widget="dxButton"
      [options]="{ icon: 'arrowleft' }"
    >
    </dxi-item>
    <dxi-item location="before">
      <div class="toolbar-header">{{ (contact$ | async)?.name }}</div>
    </dxi-item>
    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxButton"
      [options]="{
        text: 'Terminate',
        type: 'default',
        stylingMode: 'contained'
      }"
    >
    </dxi-item>
    <dxi-item location="after" locateInMenu="auto">
      <dx-drop-down-button
        [items]="['Assign to Me', 'Archive']"
        stylingMode="text"
        [width]="120"
        text="Action"
      ></dx-drop-down-button>
    </dxi-item>
    <dxi-item location="after" locateInMenu="auto">
      <div class="separator"></div>
    </dxi-item>
    <dxi-item
      location="after"
      locateInMenu="auto"
      showText="inMenu"
      widget="dxButton"
      [options]="{ text: 'Copy', icon: 'copy' }"
    >
    </dxi-item>
    <dxi-item
      location="after"
      locateInMenu="auto"
      showText="inMenu"
      widget="dxButton"
      [options]="{ text: 'Refresh', icon: 'refresh', onClick: refresh }"
    >
    </dxi-item>
  </dx-toolbar>

  <div class="panels">
    <div class="left">
      <contact-form [contact]="contact$"></contact-form>
    </div>

    <div class="right">
      <contact-cards
        [contactName]="(contact$ | async)?.name"
        [tasks]="(contact$ | async)?.tasks"
        [activities]="(contact$ | async)?.activities"
        [activeOpportunities]="activeOpportunities"
        [closedOpportunities]="closedOpportunities"
        [notes]="contactNotes"
        [messages]="contactMessages"
      ></contact-cards>
    </div>
  </div>
</div>
