// packages/react/src/pages/crm-contact-form/crm-contact-form.tsx
import React from 'react';
import './crm-contact-form.scss';

import Toolbar, { Item as ToolbarItem } from 'devextreme-react/toolbar';
 import TabPanel, { Item as TabPanelItem } from "devextreme-react/tab-panel";
import Form, { Item as FormItem, Label } from "devextreme-react/form";
import { Button, DataGrid, DropDownButton } from 'devextreme-react';
import { getContact } from 'dx-rwa-data';

const viewData = {
  id:12,
  name:"Sammy Hill",
  firstName:"Sam",
  lastName:"Hill",
  city:"Pasadena",
  state:{
    sateId:5,
    stateShort:"CA",
    stateLong:"California",
    flag48p:null,
    flag24px:null,ssmaTimeStamp:"AAAAAAAACQk=",contacts:[]},zipCode: 91103,status:"Salaried",company:"ElectrixMax",
    position:"Sales Assistant",manager:"John Heart",phone:"6265557292",email:"sammyh@dx-email.com",
    address:"645 Prospect Crescent",activities:[{name:"Task created",date:"2020-11-27T00:03:20",manager:"John Heart"},{name:"Call planned",date:"2020-12-02T16:43:20",manager:"John Heart"},
    {name:"Outbound call logged",date:"2020-12-02T18:23:20",manager:"John Heart"},
    {name:"Message sent",date:"2021-12-03T02:03:20",manager:"John Heart"},{name:"Task completed",date:"2020-02-07T18:43:20",manager:"John Heart"}],opportunities:[{name:"Audio/Video Upgrade",price:2125.0000},{name:"Summer Discount Offer",price:3740.0000},{name:"Hospital Conference Room Set",price:898.0000},{name:"POS Touch Screens",price:2530.0000}],tasks:[{text:"Call to clarify customer requirements.",date:"2020-11-27T12:00:00"},{text:"Send pictures/brochures of new products.",date:"2020-11-27T06:26:40"},{text:"Follow up and discuss the offer.",date:"2020-11-26T11:00:00"},{text:"Obtain CEO contact information.",date:"2020-11-26T05:26:40"},{text:"Create requested product comparison report.",date:"2020-11-25T10:00:00"},{text:"Generate a quote.",date:"2020-11-25T04:26:40"},{text:"Apply discounts and generate a binding offer.",date:"2020-11-24T09:00:00"},{text:"Obtain feedback on new equipment.",date:"2020-11-24T03:26:40"},{text:"Send SWAG to customer.",date:"2020-11-23T08:00:00"},{text:"Ask if upgrade is required.",date:"2020-11-23T02:26:40"}]
  };

export default function CRMContactForm() {
  const edit = false;
  // const userId = 12;
  //let viewData: any;

  // getContact(userId).then((data) => {
  //   viewData = data;
  // });


  const formatPhone = (phone: any) : string => {
    return String(phone).replace(/(\d{3})(\d{3})(\d{4})/,"+1($1)$2-$3");
  }

  return (
    <React.Fragment>
      <div className="view crm-contact-form">
        <div className="view-wrapper">
          <Toolbar >
              <ToolbarItem location="before">
                <Button 
                  icon="arrowleft"
                />
              </ToolbarItem>
              <ToolbarItem location="before">
                  <div className="toolbar-header">{viewData.name}</div>
              </ToolbarItem>
              <ToolbarItem location="after" locateInMenu="auto">
                  <Button 
                    text="Terminate"
                    type="default"
                    stylingMode="contained"
                  />
              </ToolbarItem>
              <ToolbarItem location="after" locateInMenu="auto">
                  <DropDownButton 
                      items={['Assign to Me', 'Archive']} 
                      stylingMode="text"
                      width={120}
                      text="Action">
                  </DropDownButton>
              </ToolbarItem>
              <ToolbarItem location="after" locateInMenu="auto">
                  <div className="separator"></div>
              </ToolbarItem>
              <ToolbarItem 
                location="after" 
                locateInMenu="auto" 
                showText="inMenu" 
                widget="dxButton">

                  <Button 
                    text="Copy"
                    icon="copy"
                    stylingMode='text'
                  />
              </ToolbarItem>
              <ToolbarItem 
                location="after" 
                locateInMenu="auto" 
                showText="inMenu" 
                widget="dxButton">

                  <Button 
                    text="Refresh"
                    icon="refresh"
                    stylingMode='text'
                  />
              </ToolbarItem>
          </Toolbar>

          <div className="panels">
              <div className="left">
                  <Toolbar>
                      <ToolbarItem location="before">
                          <div className="panels-header">Details</div>
                      </ToolbarItem>
                      <ToolbarItem location="after" visible={!edit} locateInMenu="after" >
                          <Button 
                            text="Edit"
                            icon="edit"
                            type="default"
                            stylingMode="outlined"
                          />
                      </ToolbarItem>
                      <ToolbarItem location="after" visible={edit} locateInMenu="after">
                          <Button 
                            text="Save"
                            type="default"
                            stylingMode="outlined"
                          />
                      </ToolbarItem>
                      <ToolbarItem location="after" visible={edit} locateInMenu="after">
                          <Button 
                            text="Cancel"
                          />
                      </ToolbarItem>
                  </Toolbar>
                  
                  {edit ? ( 
                    <div>
                      <div className="user-info">
                        <div className="photo" >
                        </div>
                        <div className="text-info">
                          <div className="title">Status</div>
                          <div className="value status ">{viewData.status}</div>
                          <div className="title">First Name</div>
                          <div className="value black">{viewData.firstName}</div>
                          <div className="title">Last Name</div>
                          <div className="value black">{viewData.lastName}</div>
                        </div>
                      </div>
                      <div className="info">
                          <div>
                              <div className="title">Position</div>
                              <div className="value black">{}</div>
                          </div>
                          <div>
                              <div className="title">Assigned to</div>
                              <div className="value">{viewData.manager}</div>
                          </div>
                      </div>
                      <div className="info last">
                          <div>
                              <div className="title">Company</div>
                              <div className="value">{viewData.company}</div>
                          </div>
                      </div>

                      <div className="panels-header">Contacts</div>

                      <div className="info">
                          <div>
                              <div className="title">Address</div>
                              <div className="value black">{viewData.address}</div>
                          </div>
                      </div>
                      <div className="info">
                          <div>
                              <div className="title">City</div>
                              <div className="value black">{viewData.city}</div>
                          </div>
                          <div className="narrow">
                              <div>
                                  <div className="title">State</div>
                                  <div className="value black">{viewData.state.stateShort}</div>
                              </div>
                              <div>
                                  <div className="title">Zip Code</div>
                                  <div className="value black">{viewData.zipCode}</div>
                              </div>
                          </div>
                          
                      </div>
                      <div className="info last small">
                          <div>
                              <div className="title">Phone</div>
                              <div className="value black">{formatPhone(viewData.phone)}</div>
                              <Button 
                                text="Call" 
                                icon="tel" 
                                type="default"
                                stylingMode="outlined" 
                                className="button"
                              />
                          </div>
                          <div>
                              <div className="title">Email</div>
                              <div className="value black">{viewData.email}</div>
                              <Button 
                                  text="Send Email" 
                                  icon="email" 
                                  type="default" 
                                  stylingMode="outlined" 
                                  className="button"
                              />
                          </div>
                      </div>
                      </div>
                    ) : (

                      <Form 
                        className="form last" 
                        formData={viewData} 
                        labelMode="floating" 
                        colCount={1} 
                        labelLocation="top" >
                          
                          <FormItem itemType="group" colCount={2}>
                              <FormItem>
                                  <div className="user-info">
                                      <div className="photo form">
                                      </div>
                                  </div>
                              </FormItem>
                              <FormItem itemType="group" colSpan={3}>
                                  <FormItem dataField="status"></FormItem>
                                  <FormItem dataField="firstName"></FormItem>
                                  <FormItem dataField="lastName"></FormItem>
                              </FormItem>
                          </FormItem>
                          <FormItem itemType="group" colCount={2}>
                              <FormItem dataField="position"></FormItem>
                              <FormItem dataField="manager">
                                <Label text="Assigned to"></Label>
                              </FormItem>
                              <FormItem dataField="company" colSpan={2}></FormItem>
                          </FormItem>
                          <FormItem>
                              <div className="panels-header">Contacts</div>
                          </FormItem>
                          <FormItem itemType="group" colCount={4}>
                              <FormItem dataField="city" colSpan={2}></FormItem>
                              <FormItem dataField="state.stateShort"></FormItem>
                              <FormItem dataField="zipCode"></FormItem>
                              <FormItem dataField="phone" colSpan={2}></FormItem>
                              <FormItem dataField="email" colSpan={2}></FormItem>
                          </FormItem>
                      </Form>
                  )}
              </div>
              <div className="right">
                  <div className="dx-card">
                      {/* <TabPanel showNavButtons={true}>
                          <Item title="Tasks">
                              <div className="tab-content">
                                  <DataGrid dataSource={viewData.tasks} columnAutoWidth={true} selectionFilter={['done', '=', true]}>
                                      <Selection mode="multiple" deferred={true} />
                                      <Column dataField="text" caption="Name" hidingPriority={3}></Column>
                                      <Column dataField="date" dataType="date" hidingPriority={1}></Column>
                                      <Column caption="Assigned To" cellTemplate="assignTemplate" hidingPriority={0} cellRender={}>
                                      </Column>
                                  </DataGrid>
                              </div>
                          </Item>
                          <Item title="Activities">
                              <div className="tab-content">
                                  <app-activities activities={viewData.activities} showBy={true}></app-activities>
                              </div>
                          </Item>
                          <Item title="Opportunities">
                              <div className="tab-content">
                                  <div className="tiles">
                                      <div className="tiles-header">Active</div>
                                      <div className="tile" >
                                          <div className="name">{data.name}</div>
                                          <div className="product-info">Products: {{data.products}}, total: <span className="total">{}</span></div>
                                          <div className="owner">Owner: <span className="owner-name">{data.manager}</span></div>
                                      </div>
                                      <br>
                                      <Button text="Add Opportunity" icon="add" width="320" height="60" stylingMode="outlined" type="default" className="add-tile"></Button>
                                      <div className="tiles-header">Closed</div>
                                      <div className="tile" >
                                          <div className="name">{{data.name}}</div>
                                          <div className="product-info">Products: {data.products}, total: <span className="total">{}</span></div>
                                          <div className="owner">Owner: <span className="owner-name">{data.manager}</span></div>
                                      </div>
                                  </div>
                              </div>
                          </Item>
                          <Item title="Notes">

                          </Item>
                          <Item title="Messages" badge="">

                          </Item>
                      </TabPanel> */}
                  </div>
              </div>
          </div>
        </div>
    </div>
  </React.Fragment>
)}

// packages/angular/src/app/pages/crm-contact-form/crm-contact-form.component.ts
import { Component, ViewChild, OnInit, AfterViewInit, NgModule } from '@angular/core';
import { ScreenService } from '../../shared/services';
import { getRawStatuses, getContact } from 'dx-rwa-data';
import CustomStore from 'devextreme/data/custom_store';
import {
  DxButtonModule,
  DxFormModule,
  DxLoadPanelModule,
  DxSelectBoxModule,
  DxTabPanelModule,
  DxTextBoxModule,
  DxToolbarModule,
} from 'devextreme-angular';
import { ActivitiesModule } from 'src/app/shared/components/activities/activities.component';
import { CommonModule } from '@angular/common';

@Component({
  templateUrl: './crm-contact-form.component.html',
  styleUrls: ['./crm-contact-form.component.scss']
})
export class CrmContactFormComponent implements OnInit {

  constructor(private screen: ScreenService) {
    this.toggleEdit = this.toggleEdit.bind(this);

    getContact(10).then((data) => {
      this.viewData = data;
      this.load = false;
    });
    
    this.statuses = new CustomStore({
      loadMode: 'raw',
      load: getRawStatuses
    });
  }

  viewData: any;
  load = true;
  edit = false;
  statuses: CustomStore;

  toggleEdit() {
    this.edit = !this.edit;
  }

  formatPhone(number: string | number): string {
    return String(number).replace(/(\d{3})(\d{3})(\d{4})/,"+1($1)$2-$3");
  }

  ngOnInit(): void {
    
  }
}

@NgModule({
  imports: [
    DxFormModule,
    DxToolbarModule,
    DxButtonModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    DxLoadPanelModule,
    DxTabPanelModule,
    ActivitiesModule,

    CommonModule
  ],
  providers: [],
  exports: [],
  declarations: [CrmContactFormComponent]
})
export class CrmContactFormModule { }


<div class="view-wrapper">
    <ng-template [ngIf]="!load" [ngIfElse]="loading">
        <dx-toolbar width="100%">
            <dxi-item location="before" widget="dxButton" [options]="{ icon: 'arrowleft' }">
            </dxi-item>
            <dxi-item location="before">
                <div class="toolbar-header">{{viewData.name}}</div>
            </dxi-item>
            <dxi-item location="after" locateInMenu="auto" widget="dxButton"
                [options]="{ text: 'Terminate', type: 'default', stylingMode: 'outlined'}">
            </dxi-item>
            <dxi-item location="after" locateInMenu="auto">
                <dx-drop-down-button [items]="['Assign to Me', 'Archive']" stylingMode="text" [width]="120"
                    text="Action"></dx-drop-down-button>
            </dxi-item>
            <dxi-item location="after" locateInMenu="auto">
                <div class="separator"></div>
            </dxi-item>
            <dxi-item location="after" locateInMenu="auto" showText="inMenu" widget="dxButton"
                [options]="{text: 'Refresh', icon: 'copy'}">
            </dxi-item>
            <dxi-item location="after" locateInMenu="auto" showText="inMenu" widget="dxButton"
                [options]="{text: 'Refresh', icon: 'refresh'}">
            </dxi-item>
        </dx-toolbar>

        <div class="panels">
            <div class="left">
                <dx-toolbar>
                    <dxi-item location="before">
                        <div class="panels-header">Details</div>
                    </dxi-item>
                    <dxi-item location="after" [visible]='!edit' widget="dxButton"
                        [options]="{text: 'Edit', icon: 'edit', stylingMode: 'contained', onClick: toggleEdit}">
                    </dxi-item>
                    <dxi-item location="after" [visible]='edit' widget="dxButton"
                        [options]="{text: 'Save', stylingMode: 'outlined', type: 'default', onClick: toggleEdit}">
                    </dxi-item>
                    <dxi-item location="after" [visible]='edit' widget="dxButton"
                        [options]="{text: 'Cancel', onClick: toggleEdit}">
                    </dxi-item>
                </dx-toolbar>
                <ng-template [ngIf]="!edit" [ngIfElse]="editingForm">
                    <div class="user-info">
                        <div class="photo"
                            [style.backgroundImage]="'url(\'data:image/png;base64,' + viewData.image +'\')'"></div>
                        <div>
                            <div class="title">Status</div>
                            <div class="value status status-{{viewData.status.toLowerCase()}}">{{viewData.status}}</div>
                            <div class="title">First Name</div>
                            <div class="value black">{{viewData.firstName}}</div>
                            <div class="title">Last Name</div>
                            <div class="value black">{{viewData.lastName}}</div>
                        </div>
                    </div>
                    <div class="info">
                        <div>
                            <div class="title">Position</div>
                            <div class="value black">{{viewData.position}}</div>
                        </div>
                        <div>
                            <div class="title">Assigned to</div>
                            <div class="value">{{viewData.manager}}</div>
                        </div>
                    </div>
                    <div class="info last">
                        <div>
                            <div class="title">Company</div>
                            <div class="value">{{viewData.company}}</div>
                        </div>
                    </div>

                    <div class="panels-header">Contacts</div>

                    <div class="info">
                        <div>
                            <div class="title">Address</div>
                            <div class="value black">{{viewData.address}}</div>
                        </div>
                    </div>
                    <div class="info">
                        <div>
                            <div class="title">City</div>
                            <div class="value black">{{viewData.city}}</div>
                        </div>
                        <div class="narrow">
                            <div class="title">State</div>
                            <div class="value black">{{viewData.state.stateShort}}</div>
                        </div>
                        <div class="narrow">
                            <div class="title">Zip Code</div>
                            <div class="value black">{{viewData.zipCode}}</div>
                        </div>
                    </div>
                    <div class="info last">
                        <div>
                            <div class="title">Phone</div>
                            <div class="value black">{{formatPhone(viewData.phone)}}</div>
                        </div>
                        <div>
                            <div class="title">Email</div>
                            <div class="value black">{{viewData.email}}</div>
                        </div>
                    </div>
                    <div class="info last">
                        <div>
                            <dx-button text="Call" icon="tel"></dx-button>
                        </div>
                        <div>
                            <dx-button text="Send Email" icon="email"></dx-button>
                        </div>
                    </div>
                </ng-template>
                <ng-template #editingForm>
                    <dx-form class="form" [formData]="viewData" labelMode="floating" colCount="auto"
                        labelLocation="top">
                        <dxi-item itemType="group" [colCount]="2">
                            <dxi-item>
                                <div class="user-info">
                                    <div class="photo form"
                                        [style.backgroundImage]="'url(\'data:image/png;base64,' + viewData.image +'\')'">
                                    </div>
                                </div>
                            </dxi-item>
                            <dxi-item itemType="group" [colSpan]="3">
                                <dxi-item dataField="status">
                                    <div *dxTemplate>
                                        <dx-select-box
                                            [(value)]="viewData.status"
                                            [dataSource]="statuses"
                                            valueExpr="status"
                                            fieldTemplate="field"
                                            [dropDownOptions]="{ container: '.view-wrapper' }"
                                        >
                                            <div *dxTemplate="let data of 'field'">
                                                <div>
                                                    <div class="value input status status-{{data.status | lowercase}}">{{data.status}}
                                                    </div>
                                                    <dx-text-box [value]="data" [readOnly]="true" [visible]="false"
                                                        [inputAttr]="{ class: 'status status-' + data.status | lowercase }">
                                                    </dx-text-box>
                                                </div>
                                            </div>
                                            <div *dxTemplate="let data of 'item'">
                                                <div class="value status status-{{data.status | lowercase}}">{{data.status}}
                                                </div>
                                            </div>
                                        </dx-select-box>
                                    </div>
                                </dxi-item>
                                <dxi-item dataField="firstName"></dxi-item>
                                <dxi-item dataField="lastName"></dxi-item>

                            </dxi-item>
                        </dxi-item>
                        <dxi-item itemType="group" [colCount]="2">
                            <dxi-item dataField="position"></dxi-item>
                            <!-- TODO manager, company - selectboxes -->
                            <dxi-item dataField="manager" [label]="{ text: 'Assigned to'}"></dxi-item>
                            <dxi-item dataField="company" [colSpan]="2"></dxi-item>
                        </dxi-item>
                        <dxi-item>
                            <div class="panels-header">Contacts</div>
                        </dxi-item>
                        <dxi-item itemType="group" [colCount]="4">
                            <dxi-item dataField="city" [colSpan]="2"></dxi-item>
                            <dxi-item dataField="state.stateShort"></dxi-item>
                            <dxi-item dataField="zipCode"></dxi-item>
                            <dxi-item dataField="phone" [colSpan]="2"></dxi-item>
                            <dxi-item dataField="email" [colSpan]="2"></dxi-item>
                        </dxi-item>
                    </dx-form>
                </ng-template>

            </div>
            <div class="right">
                <div class="dx-card">
                    <dx-tab-panel>
                        <dxi-item title="Tasks">
                            <div class="tab-content">
                                <dx-data-grid [dataSource]="viewData.tasks">
                                    <dxi-column
                                        dataField="done"
                                        cellTemplate="doneTemplate"
                                        [width]="70"
                                        alignment="left"
                                        caption="Done"
                                    >
                                        <div *dxTemplate="let data of 'doneTemplate'">
                                            <dx-check-box [value]="!!data.value"></dx-check-box>
                                        </div>
                                    </dxi-column>
                                    <dxi-column dataField="text" caption="Name"></dxi-column>
                                    <dxi-column dataField="date" dataType="date" [width]="100"></dxi-column>
                                    <dxi-column caption="Assigned To" cellTemplate="assignTemplate" [width]="120">
                                        <div *dxTemplate="let data of 'assignTemplate'">
                                            {{viewData.manager}}
                                        </div>
                                    </dxi-column>
                                    <dxi-column [width]="40" type="buttons">
                                        <dxi-button
                                            icon="overflow"
                                            ></dxi-button>
                                    </dxi-column>
                                </dx-data-grid>
                            </div>
                        </dxi-item>
                        <dxi-item title="Activities">
                            <div class="tab-content">
                                <app-activities [activities]="viewData.activities" [showBy]="true"></app-activities>
                            </div>
                        </dxi-item>
                        <dxi-item title="Opportunities">
                            <div class="tab-content">
                                <dx-tile-view
                                    [dataSource]="opportunities"
                                    [itemMargin]="10"
                                    [baseItemHeight]="110"
                                    [baseItemWidth]="320"
                                    direction="vertical"
                                    itemTemplate="tile"
                                    [activeStateEnabled]="false">
                                    <div class="tile" *dxTemplate="let data of 'tile'">
                                        <div class="name">{{data.name}}</div>
                                        <div class="product-info">Products: {{data.products}}, total: <span class="total">{{data.total | currency}}</span></div>
                                        <div class="owner">Owner: <span class="owner-name">{{data.manager}}</span></div>
                                    </div>
                                </dx-tile-view>
                            </div>
                        </dxi-item>
                    </dx-tab-panel>
                </div>
            </div>
        </div>
    </ng-template>
    <ng-template #loading>
        <dx-load-panel [visible]="load"></dx-load-panel>
    </ng-template>
</div>
