// packages/angular/src/app/pages/analytics-dashboard/analytics-dashboard.component.ts
import {
  Component, OnInit, NgModule, OnDestroy,
} from '@angular/core';

import { DxPieChartModule } from 'devextreme-angular/ui/pie-chart';
import { DxChartModule } from 'devextreme-angular/ui/chart';
import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';
import { DxFunnelModule } from 'devextreme-angular/ui/funnel';
import { DxBulletModule } from 'devextreme-angular/ui/bullet';

import { CommonModule } from '@angular/common';
import { RwaService } from 'src/app/shared/services';
import { forkJoin, map, Subscription } from 'rxjs';

import { CardAnalyticsModule } from 'src/app/shared/components/card-analytics/card-analytics.component';
import { ToolbarAnalyticsModule } from 'src/app/shared/components/toolbar-analytics/toolbar-analytics.component';

import { analyticsPanelItems, Dates } from 'src/app/shared/types/resource';
import {
  Sales, SalesByState, SalesOrOpportunitiesByCategory,
} from 'src/app/shared/types/analytics';

@Component({
  templateUrl: './analytics-dashboard.component.html',
  styleUrls: ['./analytics-dashboard.component.scss'],
  providers: [RwaService],
})
export class AnalyticsDashboardComponent implements OnInit, OnDestroy {
  analyticsPanelItems = analyticsPanelItems;

  opportunities: SalesOrOpportunitiesByCategory;

  sales: Sales;

  salesByState: SalesByState;

  salesByCategory: SalesOrOpportunitiesByCategory;

  subscriptions: Subscription[] = [];

  salesTotal: number;

  opportunitiesTotal: number;

  constructor(private service: RwaService) {
  }

  selectionChange(dates: Dates) {
    this.loadData(dates.startDate, dates.endDate);
  }

  customizeOppText(arg: { valueText: string }) {
    return `$${arg.valueText}`;
  }

  customizeSaleText(arg: { percentText: string }) {
    return arg.percentText;
  }

  getTotal(data: Array<any>) {
    if (!data) return;
    return data.reduce((total, item) => total + (item.value || item.total), 0);
  }

  loadData = (startDate: string, endDate: string) => {
    const observable$ = forkJoin([
      this.service.getOpportunitiesByCategory(startDate, endDate),
      this.service.getSalesByCategory(startDate, endDate),
      this.service.getSales(startDate, endDate),
    ]).pipe(
      map(([opportunities, salesByCategory, sales]) => ({ opportunities, salesByCategory, sales }))
    );

    this.subscriptions.push(this.service.getSalesByStateAndCity(startDate, endDate).subscribe((data) => {
      this.salesByState = this.service.getSalesByState(data);
    }));

    this.subscriptions.push(observable$.subscribe((data) => {
      Object.keys(data).forEach((key) => this[key] = data[key]);

      this.salesTotal = this.getTotal(this.sales);
      this.opportunitiesTotal = this.getTotal(this.opportunities);
    }));
  };

  ngOnInit(): void {
    const dates = analyticsPanelItems[4].value.split('/');

    this.loadData(dates[0], dates[1]);
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach((sub) => sub.unsubscribe());
  }
}

@NgModule({
  imports: [
    DxDataGridModule,
    DxBulletModule,
    DxFunnelModule,
    DxPieChartModule,
    DxChartModule,
    CardAnalyticsModule,
    ToolbarAnalyticsModule,

    CommonModule,
  ],
  providers: [],
  exports: [],
  declarations: [AnalyticsDashboardComponent],
})
export class AnalyticsDashboardModule { }

<div class="view-wrapper">
  <dx-toolbar>
    <dxi-item location="before">
      <span class="toolbar-header">Dashboard</span>
    </dxi-item>

    <dxi-item 
      location="before"
      locateInMenu="auto">
      <dx-tabs
        [selectedItemKeys]="[5]"
        keyExpr="key"
        [items]="analyticsPanelItems"
        (onItemClick)="selectionChange($event)"
      ></dx-tabs>
    </dxi-item>

    <dxi-item 
      location="after" 
      locateInMenu="auto"
      cssclass="add-card"
      >
      <dx-button
        icon="plus"
        text="Add Card"
        type="default"
        stylingMode="contained"
      ></dx-button>
    </dxi-item>

    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxButton"
      showText="inMenu"
      [options]="{
        text: 'Refresh',
        icon: 'refresh'
      }"
    ></dxi-item>

    <dxi-item location="after" locateInMenu="auto">
      <div class="separator"></div>
    </dxi-item>

    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxButton"
      showText="inMenu"
      [options]="{
        icon: 'export'
      }"
    ></dxi-item>
  </dx-toolbar>

  <div class="cards grey">
    <card-analytics
      class="grey"
      titleText="Opportunities"
      [showData]="getTotal(opportunities)"
      contentClass="opportunities-total"
    >
      <div *ngIf="getTotal(opportunities)">
        <div class="total">
          {{ getTotal(opportunities) | currency: "USD":"$":"1.0-0" }}
        </div>
        <div class="percentage">
          <i class="dx-icon-spinup"></i>
          <span>20.3%</span>
        </div>
      </div>
    </card-analytics>
    <card-analytics
      class="grey"
      titleText="Revenue Total"
      [showData]="getTotal(sales)"
      contentClass="revenue-total" 
    >
    <div *ngIf="getTotal(sales)">
      <div class="total">
        {{ getTotal(sales) | currency: "USD":"$":"1.0-0" }}
      </div>
      <div class="percentage">
        <i class="dx-icon-spinup"></i>
        <span>14.7%</span>
      </div>
    </div>
    </card-analytics>
    <card-analytics
      class="grey"
      titleText="Conversion"
      [showData]="true"
      contentClass="revenue-total"
    >
      <div class="total">16%</div>
      <div class="percentage">
        <i class="dx-icon-spindown"></i>
        <span>2.3%</span>
      </div>
    </card-analytics>
    <card-analytics
      class="grey"
      titleText="Leads"
      [showData]="true"
      contentClass="revenue-total"
    >
      <div class="total">51</div>
      <div class="percentage">
        <i class="dx-icon-spinup"></i>
        <span>8.5%</span>
      </div>
    </card-analytics>
  </div>

  <div class="cards">
    <card-analytics titleText="Revenue" contentClass="sales" [showData]="!!sales" [component]="chart">
      <dx-chart #chart [dataSource]="sales">
        <dxi-series valueField="total"></dxi-series>
        <dxo-common-series-settings argumentField="date" type="splinearea">
          <dxo-border [visible]="true"></dxo-border>
        </dxo-common-series-settings>
        <dxo-argument-axis argumentType="datetime"></dxo-argument-axis>
        <dxi-value-axis>
            <dxo-label>
              <dxo-format type="currency" currency="USD"></dxo-format>
            </dxo-label>
        </dxi-value-axis>
        <dxo-legend [visible]="false"> </dxo-legend>
        <dxo-size [height]="270"></dxo-size>
      </dx-chart>
    </card-analytics>
    <card-analytics
      titleText="Conversion Funnel (All Products)"
      contentClass="opportunities"
      [showData]="!!opportunities"
      [component]="funnel"
    >
      <dx-funnel
        #funnel
        [dataSource]="opportunities"
        argumentField="name"
        valueField="value"
      >
        <dxo-label
          [visible]="true"
          position="inside"
          backgroundColor="none"
          [customizeText]="customizeOppText"
        >
          <dxo-format type="largeNumber" [precision]="1"> </dxo-format>
        </dxo-label>

        <dxo-legend [visible]="true">
          <dxo-margin [top]="70"></dxo-margin>
        </dxo-legend>

        <dxo-size [height]="270"></dxo-size>
      </dx-funnel>
    </card-analytics>
    <card-analytics
      titleText="Revenue Analysis"
      contentClass="sales-by-state"
      [showData]="!!salesByState"
    >
      <dx-data-grid [dataSource]="salesByState" [height]="270">
        <dxi-column 
          caption="State" 
          dataField="stateName"
        >
        </dxi-column>

        <dxi-column
          alignment="left"
          caption="Sales"
          dataField="total"
          dataType="number"
          format="currency"
          sortOrder="desc"
          [hidingPriority]="2"
        >
        </dxi-column>

        <dxi-column
          alignment="left"
          caption="% Sold"
          dataField="percentage"
          name="percentN"
          format="percent"
          [hidingPriority]="1"
        >
        </dxi-column>

        <dxi-column
          alignment="left"
          caption="Percentage"
          dataField="percentage"
          name="percentB"
          cellTemplate="salesBullet"
          [width]="200"
        >
        </dxi-column>

        <div *dxTemplate="let cellInfo of 'salesBullet'">
          <dx-bullet
            [showTarget]="false"
            [showZeroLevel]="false"
            [value]="cellInfo.data.percentage * 100"
            [startScaleValue]="0"
            [endScaleValue]="100"
          >
            <dxo-tooltip enabled="false"></dxo-tooltip>
            <dxo-size [width]="200" [height]="20"></dxo-size>
          </dx-bullet>
        </div>
      </dx-data-grid>
    </card-analytics>
    <card-analytics
      titleText="Revenue Snapshot (All Products)"
      contentClass="sales-by-category"
      [showData]="!!salesByCategory"
      [component]="pie"
    >
      <dx-pie-chart
        #pie
        [dataSource]="salesByCategory"
        type="doughnut"
        [diameter]="0.8"
        [innerRadius]="0.6"
      >
        <dxi-series argumentField="name" valueField="value">
          <dxo-label
            backgroundColor="none"
            [radialOffset]="-20"
            [visible]="true"
            [customizeText]="customizeSaleText"
          >
            <dxo-font color="#757575" [size]="15"></dxo-font>
          </dxo-label>
        </dxi-series>

        <dxo-legend>
          <dxo-margin [top]="70"></dxo-margin>
        </dxo-legend>

        <dxo-size [height]="270"> </dxo-size>
      </dx-pie-chart>
    </card-analytics>
  </div>
</div>

// packages/react/src/pages/analytics-dashboard/analytics-dashboard.tsx
import Toolbar, { Item } from 'devextreme-react/toolbar';
import Bullet, { Size as BulletSize, Tooltip } from 'devextreme-react/bullet';
import Chart, { Series, CommonSeriesSettings, ArgumentAxis, ValueAxis, Legend, Size, Label, Format, Border } from 'devextreme-react/chart';
import Funnel, { Label as FunnelLabel, Format as FunnelFormat, Legend as FunnelLegend, Size as FunnelSize, Margin } from 'devextreme-react/funnel';
import PieChart, { Label as PielLabel, Legend as PieLegend, Size as PieSize, Series as PieSeries, Font, Margin as PieMargin } from 'devextreme-react/pie-chart';
import DataGrid, { Column } from 'devextreme-react/data-grid';
import React, { useCallback, useEffect, useState } from 'react';
import { CardAnalytics } from '../../components/card-analytics/CardAnalytics';
import { getOpportunitiesByCategory, getSalesByCategory, getSales, getSalesByStateAndCity, getSalesByState } from 'dx-rwa-data';
import './analytics-dashboard.scss';

type PanelItem = { text: string; value: string; key: number };

const tabItems = {
  Week: {
    period: '2020-01-24/2020-01-31',
    index: 0,
  },
  '2 Weeks': {
    period: '2020-01-14/2020-01-31',
    index: 1,
  },
  Month: {
    period: '2020-01-01/2020-02-01',
    index: 2,
  },
  Year: {
    period: '2020-01-01/2021-01-01',
    index: 3,
  },
  All: {
    period: '2018-01-01/2022-01-01',
    index: 4,
  },
};

const DEFAULT_TAB_KEY = 'All';

const calculateTotal = (data: Array<any>) => {
  if (!data) return;
  return data.reduce((total, item) => total + (item.value || item.total), 0);
};

export const AnalyticsDashboard = () => {
  const [tabIndex, setTabIndex] = useState(tabItems[DEFAULT_TAB_KEY].index);
  const [dateRange, setDateRange] = useState(tabItems[DEFAULT_TAB_KEY].period.split('/'));
  const [opportunities, setOpportunities] = useState([]);
  const [salesByCategory, setSalesByCategory] = useState([]);
  const [sales, setSales] = useState([]);
  const [salesByState, setSalesByState] = useState([]);
  const [salesTotal, setSalesTotal] = useState(0);
  const [opportunitiesTotal, setOpportunitiesTotal] = useState(0);

  useEffect(() => {
    getOpportunitiesByCategory(...dateRange)
      .then((data) => {
        setOpportunities(data);
        setOpportunitiesTotal(calculateTotal(data));
      })
      .catch((error) => console.log(error));

    getSalesByCategory(...dateRange)
      .then((data) => setSalesByCategory(data))
      .catch((error) => console.log(error));

    getSales(...dateRange)
      .then((data) => {
        setSales(data);
        setSalesTotal(calculateTotal(data));
      })
      .catch((error) => console.log(error));

    getSalesByStateAndCity(...dateRange)
      .then((data) => getSalesByState(data))
      .then((data) => setSalesByState(data))
      .catch((error) => console.log(error));
  }, [dateRange]);

  const onTabClick = useCallback((e: { itemData: string }) => {
    const { index, period } = tabItems[e.itemData];
    setTabIndex(index);
    setDateRange(period.split('/'));
  }, []);

  return (
    <div className='view-wrapper'>
      <Toolbar>
        <Item location='before'>
          <span className='toolbar-header'>Dashboard</span>
        </Item>
        <Item
          location='before'
          widget='dxTabs'
          options={{
            dataSource: Object.keys(tabItems),
            selectedIndex: tabIndex,
            onItemClick: onTabClick,
          }}
        />
      </Toolbar>
      <div className='cards grey'>
        <CardAnalytics title='Opportunities'>
          <div className='total'>${opportunitiesTotal}</div>
          <div className='percentage'>
            <i className='dx-icon-spinup'></i>
            <span>20.3%</span>
          </div>
        </CardAnalytics>
        <CardAnalytics title='Revenue Total'>
          <div className='total'>${salesTotal}</div>
          <div className='percentage'>
            <i className='dx-icon-spinup'></i>
            <span>14.7%</span>
          </div>
        </CardAnalytics>
        <CardAnalytics title='Conversion'>
          <div className='total'>16%</div>
          <div className='percentage'>
            <i className='dx-icon-spindown'></i>
            <span>2.3%</span>
          </div>
        </CardAnalytics>
        <CardAnalytics title='Leads'>
          <div className='total'>51</div>
          <div className='percentage'>
            <i className='dx-icon-spinup'></i>
            <span>8.5%</span>
          </div>
        </CardAnalytics>
      </div>
      <div className='cards'>
        <CardAnalytics title='Revenue'>
          <Chart dataSource={sales}>
            <Series valueField='total' />
            <CommonSeriesSettings argumentField='date' type='splinearea'>
              <Border visible={true} />
            </CommonSeriesSettings>
            <ArgumentAxis argumentType='datetime' />
            <ValueAxis>
              <Label>
                <Format type='currency' currency='USD' />
              </Label>
            </ValueAxis>
            <Legend visible={false} />
            <Size height={270} />
          </Chart>
        </CardAnalytics>
        <CardAnalytics title='Conversion Funnel (All Products)'>
          <Funnel dataSource={opportunities} argumentField='name' valueField='value'>
            <FunnelLabel visible={true} position='inside' backgroundColor='none' customizeText={({ valueText }) => `$${valueText}`}>
              <FunnelFormat type='largeNumber' precision='1' />
            </FunnelLabel>
            <FunnelLegend visible={true}>
              <Margin top={70} />
            </FunnelLegend>
            <FunnelSize height={270} />
          </Funnel>
        </CardAnalytics>
        <CardAnalytics title='Revenue Analysis'>
          <DataGrid dataSource={salesByState} height={270}>
            <Column caption='State' dataField='stateName' />
            <Column alignment='left' caption='Sales' dataField='total' dataType='number' format='currency' sortOrder='desc' hidingPriority={2} />
            <Column alignment='left' caption='% Sold' dataField='percentage' name='percentN' format='percent' hidingPriority={1} />
            <Column
              alignment='left'
              caption='Percentage'
              dataField='percentage'
              name='percentB'
              cellRender={(cellInfo) => (
                <Bullet showTarget={false} showZeroLevel={false} value={cellInfo.data.percentage * 100} startScaleValue={0} endScaleValue={100}>
                  <Tooltip enabled={false} />
                  <Size width={200} height={20} />
                </Bullet>
              )}
              width={200}
            />
          </DataGrid>
        </CardAnalytics>
        <CardAnalytics title='Revenue Snapshot (All Products)'>
          <PieChart dataSource={salesByCategory} type='doughnut' diameter={0.8} innerRadius={0.6}>
            <PieSeries argumentField='name' valueField='value'>
              <PielLabel backgroundColor='none' radialOffset={-20} visible={true}>
                <Font color='#757575' size={15} />
              </PielLabel>
            </PieSeries>
            <PieLegend>
              <PieMargin top={70} />
            </PieLegend>
            <PieSize height={270} />
          </PieChart>
        </CardAnalytics>
      </div>
    </div>
  );
};
