// packages/angular/src/app/pages/crm-contact-list/crm-contact-list.component.ts
import {
  Component, ViewChild, OnInit, NgModule, OnDestroy,
} from '@angular/core';
import {
  DxButtonModule,
  DxDataGridModule,
  DxDataGridComponent,
  DxDropDownButtonModule,
  DxSelectBoxModule,
  DxTextBoxModule,
} from 'devextreme-angular';
import { RowClickEvent, RowPreparedEvent, ColumnCustomizeTextArg } from 'devextreme/ui/data_grid';
import { exportDataGrid as exportDataGridToPdf } from 'devextreme/pdf_exporter';
import { exportDataGrid as exportDataGridToXLSX } from 'devextreme/excel_exporter';
import {
  CardActivitiesModule,
  ContactStatusModule,
} from 'src/app/shared/components';
import { Contact, contactStatusList, ContactStatus } from 'src/app/shared/types/contact';
import { SelectionChangedEvent } from 'devextreme/ui/drop_down_button';
import { CommonModule } from '@angular/common';
import { RwaService } from 'src/app/shared/services';
import { Subscription } from 'rxjs';
import { Workbook } from 'exceljs';
import { saveAs } from 'file-saver-es';
import { jsPDF } from 'jspdf';
import { UserPanelModule } from './user-panel/user-panel.component';

type FilterContactStatus = ContactStatus | 'All';

@Component({
  templateUrl: './crm-contact-list.component.html',
  styleUrls: ['./crm-contact-list.component.scss'],
  providers: [RwaService],
})
export class CrmContactListComponent implements OnInit, OnDestroy {
  @ViewChild(DxDataGridComponent, { static: true }) dataGrid: DxDataGridComponent;

  statusList = contactStatusList;

  filterStatusList = ['All', ...contactStatusList];

  isPanelOpen = false;

  userId: number;

  dataSource: Contact[];

  dataSubscription: Subscription = new Subscription();

  constructor(private service: RwaService) {
  }

  ngOnInit(): void {
    this.dataSubscription = this.service.getContacts().subscribe((data) => {
      this.dataSource = data;
    });
  }

  ngOnDestroy(): void {
    this.dataSubscription.unsubscribe();
  }

  addContact = () => {
    this.userId = null;
    this.isPanelOpen = true;
  };

  refresh = () => {
    this.dataGrid.instance.refresh();
  };

  rowClick(e: RowClickEvent) {
    const { data } = e;

    this.userId = data.id;
    this.isPanelOpen = true;
  }

  rowPrepared = (e: RowPreparedEvent) => {
    const { rowElement } = e;

    rowElement.classList.add('clickable-row');
  };

  filterByStatus = (e: SelectionChangedEvent) => {
    const { item: status }: { item: FilterContactStatus } = e;

    if (status === 'All') {
      this.dataGrid.instance.clearFilter();
    } else {
      this.dataGrid.instance.filter(['status', '=', status]);
    }
  };

  formatPhone = (number: string | number): string => String(number).replace(/(\d{3})(\d{3})(\d{4})/, '+1($1)$2-$3');

  customizePhoneCell = (cellInfo: ColumnCustomizeTextArg) => {
    const { value } = cellInfo;

    if (!value) {
      return undefined;
    }

    return this.formatPhone(value.toString());
  };

  onExporting(e) {
    if (e.format === 'pdf') {
      const doc = new jsPDF();
      exportDataGridToPdf({
        jsPDFDocument: doc,
        component: e.component,
      }).then(() => {
        doc.save('Contacts.pdf');
      });
    } else {
      const workbook = new Workbook();
      const worksheet = workbook.addWorksheet('Contacts');

      exportDataGridToXLSX({
        component: e.component,
        worksheet,
        autoFilterEnabled: true,
      }).then(() => {
        workbook.xlsx.writeBuffer().then((buffer) => {
          saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Contacts.xlsx');
        });
      });
      e.cancel = true;
    }
  }
}

@NgModule({
  imports: [
    DxButtonModule,
    DxDataGridModule,
    DxDropDownButtonModule,
    DxSelectBoxModule,
    DxTextBoxModule,

    UserPanelModule,

    CardActivitiesModule,
    ContactStatusModule,

    CommonModule,
  ],
  providers: [],
  exports: [],
  declarations: [CrmContactListComponent],
})
export class CrmContactListModule { }

<div class="view-wrapper">
  <dx-data-grid
    class="grid"
    noDataText=""
    [dataSource]="dataSource"
    (onRowClick)="rowClick($event)"
    (onRowPrepared)="rowPrepared($event)"
    (exporting)="onExporting($event)"
  >
    <dxo-scrolling mode="virtual"></dxo-scrolling>
    <dxo-selection
      selectAllMode="allPages"
      showCheckBoxesMode="always"
      mode="multiple"
    ></dxo-selection>
    <dxo-sorting mode="multiple"></dxo-sorting>
    <dxo-header-filter [visible]="true"></dxo-header-filter>
    <dxo-column-chooser [enabled]="true"></dxo-column-chooser>
    <dxo-search-panel
      [visible]="true"
      placeholder="Contact Search"
    ></dxo-search-panel>
    <dxo-export 
      [enabled]="true" 
      [allowExportSelectedData]="true" 
      [formats]="['xlsx', 'pdf']">
    </dxo-export>

    <dxo-toolbar>
      <dxi-item location="before">
        <div class="grid-header">Contacts</div>
      </dxi-item>
      <dxi-item location="before" locateInMenu="auto">
        <dx-drop-down-button
          stylingMode="text"
          [width]="160"
          [useSelectMode]="true"
          [items]="filterStatusList"
          [selectedItemKey]="filterStatusList[0]"
          (onSelectionChanged)="filterByStatus($event)"
        ></dx-drop-down-button>
      </dxi-item>
      <dxi-item location="after" locateInMenu="auto">
        <dx-button
          text="Add Contact"
          icon="plus"
          type="default"
          stylingMode="contained"
          (onClick)="addContact()"
        ></dx-button>
      </dxi-item>
      <dxi-item
        location="after"
        locateInMenu="auto"
        showText="inMenu"
        widget="dxButton"
        [options]="{ text: 'Refresh', icon: 'refresh', onClick: refresh }"
      ></dxi-item>
      <dxi-item location="after" locateInMenu="auto">
        <div class="separator"></div>
      </dxi-item>
      <dxi-item name="exportButton"></dxi-item>
      <dxi-item location="after" locateInMenu="auto">
        <div class="separator"></div>
      </dxi-item>
      <dxi-item name="columnChooserButton" locateInMenu="auto"></dxi-item>
      <dxi-item name="searchPanel" locateInMenu="auto"></dxi-item>
    </dxo-toolbar>

    <dxi-column
      dataField="name"
      caption="Name"
      sortOrder="asc"
      [hidingPriority]="5"
      [minWidth]="150"
      cellTemplate="name"
    ></dxi-column>
    <dxi-column
      dataField="company"
      caption="Company"
      [hidingPriority]="5"
      [minWidth]="150"
    ></dxi-column>
    <dxi-column
      dataField="status"
      caption="Status"
      cellTemplate="cellStatus"
      editCellTemplate="editCellStatus"
      [hidingPriority]="3"
      [minWidth]="100"
    ></dxi-column>
    <dxi-column
      dataField="assignedTo"
      caption="Assigned to"
      [hidingPriority]="4"
    ></dxi-column>
    <dxi-column
      dataField="phone"
      caption="Phone"
      [customizeText]="customizePhoneCell"
      [hidingPriority]="2"
    ></dxi-column>
    <dxi-column
      dataField="email"
      caption="Email"
      [hidingPriority]="1"
    ></dxi-column>

    <div *dxTemplate="let cellInfo of 'name'" class="name-template">
      <div>{{ cellInfo.data.name }}</div>
      <div class="position">{{ cellInfo.data.position }}</div>
    </div>

    <div *dxTemplate="let cellInfo of 'cellStatus'">
      <contact-status [value]="cellInfo.data.status"></contact-status>
    </div>

    <div *dxTemplate="let cellInfo of 'editCellStatus'">
      <dx-select-box
        class="edit-cell"
        [(value)]="cellInfo.value"
        [items]="statusList"
        (onValueChanged)="cellInfo.setValue($event.value)"
        (onSelectionChanged)="cellInfo.component.updateDimensions()"
        fieldTemplate="field"
      >
        <div *dxTemplate="let data of 'field'">
          <contact-status [value]="cellInfo.value"></contact-status>
          <dx-text-box [readOnly]="true"></dx-text-box>
        </div>
        <div *dxTemplate="let data of 'item'">
          <contact-status [value]="data"></contact-status>
        </div>
      </dx-select-box>
    </div>
  </dx-data-grid>

  <user-panel [userId]="userId" [(isOpen)]="isPanelOpen"></user-panel>
</div>

// packages/vue/src/pages/crm-contact-list/crm-contact-list.vue
<template>
  <div class="view-wrapper">
    <dx-data-grid
      ref="dataGrid"
      :data-source="dataSource"
      :allow-column-reordering="true"
      height="100%"
      class="grid"
      @row-click="rowClick"
      @exporting="onExporting"
    >
      <!-- Options -->
      <dx-scrolling :mode="'virtual'" />
      <dx-column-chooser :enabled="true" />
      <dx-sorting mode="multiple" />
      <dx-header-filter :visible="true" />
      <dx-load-panel
        :enabled="true"
        :show-pane="false"
      />
      <dx-selection
        select-all-mode="allPages"
        show-check-boxes-mode="always"
        mode="multiple"
      />
      <dx-search-panel
        :visible="true"
        placeholder="Contact Search"
      />
      <dx-export
        :enabled="true"
        :allow-export-selected-data="true"
        :formats="['xlsx', 'pdf']"
      />

      <!-- Toolbar -->
      <dx-grid-toolbar>
        <dx-grid-toolbar-item location="before">
          <div class="grid-header">
            Contacts
          </div>
        </dx-grid-toolbar-item>

        <dx-grid-toolbar-item
          location="before"
          locate-in-menu="auto"
        >
          <dx-drop-down-button
            styling-mode="text"
            :width="160"
            :use-select-mode="true"
            :items="filterStatusList"
            :selected-item-key="filterStatusList[0]"
            @selection-changed="filterByStatus"
          />
        </dx-grid-toolbar-item>

        <dx-grid-toolbar-item
          location="after"
          locate-in-menu="auto"
        >
          <div>
            <dx-button
              text="Add Contact"
              icon="plus"
              type="default"
              styling-mode="contained"
              @click="addContact"
            />
          </div>
        </dx-grid-toolbar-item>

        <dx-grid-toolbar-item
          location="after"
          locate-in-menu="auto"
          show-text="inMenu"
          widget="dxButton"
          :options="{ text: 'Refresh', icon: 'refresh', onClick: refresh }"
        />

        <dx-grid-toolbar-item
          location="after"
          locate-in-menu="auto"
        >
          <div>
            <div class="separator" />
          </div>
        </dx-grid-toolbar-item>

        <dx-grid-toolbar-item name="exportButton" />

        <dx-grid-toolbar-item
          location="after"
          locate-in-menu="auto"
        >
          <div>
            <div class="separator" />
          </div>
        </dx-grid-toolbar-item>

        <dx-grid-toolbar-item
          name="columnChooserButton"
          locate-in-menu="auto"
        />

        <dx-grid-toolbar-item
          name="searchPanel"
          locate-in-menu="auto"
        />
      </dx-grid-toolbar>

      <!-- Columns -->
      <dx-column
        data-field="name"
        caption="Name"
        sort-order="asc"
        cell-template="nameCellTemplate"
        :hiding-priority="5"
        :min-width="150"
      >
        <dx-required-rule />
      </dx-column>
      <dx-column
        data-field="company"
        caption="Company"
        :hiding-priority="5"
        :min-width="150"
      />
      <dx-column
        data-field="status"
        caption="Status"
        data-type="string"
        cell-template="statusCellTemplate"
        :hiding-priority="3"
        :min-width="100"
      />
      <dx-column
        data-field="assignedTo"
        caption="Assigned to"
        :hiding-priority="4"
      />
      <dx-column
        data-field="phone"
        caption="Phone"
        :hiding-priority="2"
        :customize-text="customizePhoneCell"
      >
        <dx-required-rule />
      </dx-column>
      <dx-column
        data-field="email"
        caption="Email"
        :hiding-priority="1"
      >
        <dx-required-rule />
      </dx-column>

      <!-- Templates  -->
      <template #nameCellTemplate="{ data }">
        <div class="name-template">
          <div>{{ data.data.name }}</div>
          <div class="position">
            {{ data.data.position }}
          </div>
        </div>
      </template>

      <template #statusCellTemplate="{ data }">
        <contact-status :value="data.data?.status" />
      </template>
    </dx-data-grid>

    <!--  Contact panel  -->
    <contact-panel
      :contact-id="panelData?.id"
      :is-panel-opened="isPanelOpened"
      @close="isPanelOpened = false"
    />
  </div>

  <form-popup
    title="New Contact"
    v-model:is-visible="isAddContactPopupOpened"
    @save="onSaveContactNewForm"
  >
    <contact-new-form />
  </form-popup>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import DxDropDownButton from 'devextreme-vue/drop-down-button';
import { DxButton } from 'devextreme-vue/button';
import DxDataGrid, {
  DxColumn,
  DxColumnChooser,
  DxHeaderFilter,
  DxExport,
  DxLoadPanel,
  DxRequiredRule,
  DxSelection,
  DxScrolling,
  DxSorting,
  DxToolbar as DxGridToolbar,
  DxItem as DxGridToolbarItem,
  DxSearchPanel,
} from 'devextreme-vue/data-grid';
import { getContacts } from 'dx-template-gallery-data';
import { saveAs } from 'file-saver-es';
import { Workbook } from 'exceljs';

import { jsPDF as JsPdf } from 'jspdf';
import { contactStatusList, Contact } from '@/types/contact';
import { ExportingEvent, RowClickEvent } from 'devextreme/ui/data_grid';
import DataSource from 'devextreme/data/data_source';
import { SelectionChangedEvent } from 'devextreme/ui/drop_down_button';
import { exportDataGrid as exportDataGridToPdf } from 'devextreme/pdf_exporter';
import { exportDataGrid as exportDataGridToXLSX } from 'devextreme/excel_exporter';
import { formatPhone } from '@/utils/formatters';
import ContactStatus from '@/components/contact-status.vue';
import FormPopup from '@/components/form-popup.vue';
import ContactNewForm from './components/contact-new-form.vue';
import ContactPanel from './components/contact-panel.vue';

const filterStatusList = ['All', ...contactStatusList];
type FilterContactStatus = typeof filterStatusList[number];

const panelData = ref<Array<Contact> | null>(null);
const isPanelOpened = ref(false);
const dataGrid = ref<InstanceType<typeof DxDataGrid> | null>(null);

const isAddContactPopupOpened = ref(false);

const dataSource = new DataSource({
  key: 'id',
  load: () => getContacts(),
});

const rowClick = (e: RowClickEvent) => {
  if (e.data.id) {
    panelData.value = e.data;
    isPanelOpened.value = true;
  }
};

const addContact = () => {
  isAddContactPopupOpened.value = true;
};

const filterByStatus = (e: SelectionChangedEvent) => {
  const { item: status }: { item: FilterContactStatus } = e;

  if (status === 'All') {
    dataGrid.value?.instance.clearFilter();
  } else {
    dataGrid.value?.instance.filter(['status', '=', status]);
  }
};

const onExporting = (e: ExportingEvent) => {
  if (e.format === 'pdf') {
    const doc = new JsPdf();
    exportDataGridToPdf({
      jsPDFDocument: doc,
      component: e.component,
    }).then(() => {
      doc.save('Contacts.pdf');
    });
  } else {
    const workbook = new Workbook();
    const worksheet = workbook.addWorksheet('Contacts');

    exportDataGridToXLSX({
      component: e.component,
      worksheet,
      autoFilterEnabled: true,
    }).then(() => {
      workbook.xlsx.writeBuffer().then((buffer) => {
        saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Contacts.xlsx');
      });
    });
    e.cancel = true;
  }
};

const refresh = () => {
  dataSource.reload();
};

const customizePhoneCell = (cellInfo: {value: string}) => {
  const { value } = cellInfo;

  if (!value) {
    return undefined;
  }

  return formatPhone(value.toString());
};

const onSaveContactNewForm = () => {
  isAddContactPopupOpened.value = false;
};
</script>

<style scoped lang="scss">
@use "@/variables" as *;

@include separator();

.view-wrapper {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;

  .grid  {
    .name-template {

      .position {
        font-size: 12px;
        color: $texteditor-label-color;
      }
    }

    :deep(.dx-datagrid-header-panel) {
      padding: 0 $content-padding;

      .dx-toolbar {
        margin-bottom: 0;
        padding: $toolbar-margin-bottom 0;
      }
    }

    .clickable-row {
      cursor: pointer;
    }

    .grid-header {
      @include header();
    }
  }
}

.edit-cell {
  position: relative;

  contact-status {
    position: absolute;
    margin-top: 10px;
    margin-left: 11px;
  }
}
</style>
