// packages/angular/src/app/pages/crm-contact-form/contact-form/contact-form.component.ts
import {
  Component, OnInit, NgModule, Input, OnDestroy,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxFormModule,
  DxLoadPanelModule,
  DxSelectBoxModule,
  DxTextBoxModule,
  DxToolbarModule,
} from 'devextreme-angular';
import { Properties as TextBoxProperties } from 'devextreme/ui/text_box';
import {
  ContactStatusModule,
  FormItemBlueModule,
  FormItemPhotoModule,
  FormItemWithButtonModule,
} from 'src/app/shared/components';
import { Observable, Subscription } from 'rxjs';
import { Contact, contactStatusList } from 'src/app/shared/types/contact';

@Component({
  selector: 'contact-form',
  templateUrl: './contact-form.component.html',
  styleUrls: ['./contact-form.component.scss'],
})
export class ContactFormComponent implements OnInit, OnDestroy {
  @Input() contact: Observable<Contact>;

  contact$: Contact;

  statusList = contactStatusList;

  isEditing = false;

  isLoading = true;

  stylingMode: TextBoxProperties['stylingMode'] = 'underlined';

  editorOptions: TextBoxProperties = { stylingMode: this.stylingMode };

  contactSubscription: Subscription = new Subscription();

  ngOnInit() {
    this.setEditorMode(this.isEditing);

    this.contactSubscription = this.contact.subscribe((data) => {
      this.contact$ = data;
      this.isLoading = false;
    });
  }

  ngOnDestroy() {
    this.contactSubscription.unsubscribe();
  }

  toggleEdit = () => {
    this.isEditing = !this.isEditing;
    this.setEditorMode(this.isEditing);
  };

  setEditorMode = (isEditing: boolean) => {
    this.stylingMode = isEditing ? 'filled' : 'underlined';
    this.editorOptions = {
      stylingMode: this.stylingMode,
    };
  };
}

@NgModule({
  imports: [
    DxToolbarModule,
    DxFormModule,
    DxSelectBoxModule,
    DxButtonModule,
    DxTextBoxModule,
    DxLoadPanelModule,

    ContactStatusModule,
    FormItemBlueModule,
    FormItemPhotoModule,
    FormItemWithButtonModule,

    CommonModule,
  ],
  providers: [],
  exports: [ContactFormComponent],
  declarations: [ContactFormComponent],
})
export class ContactFormModule { }

<div id="contact-form">
  <dx-toolbar>
    <dxi-item location="after" locateInMenu="after" [visible]="!isEditing">
      <dx-button
        text="Edit"
        icon="edit"
        stylingMode="outlined"
        type="default"
        (onClick)="toggleEdit()"
      ></dx-button>
    </dxi-item>
    <dxi-item location="after" locateInMenu="after" [visible]="isEditing">
      <dx-button
        text="Save"
        stylingMode="outlined"
        type="default"
        (onClick)="toggleEdit()"
      ></dx-button>
    </dxi-item>
    <dxi-item location="after" locateInMenu="after" [visible]="isEditing">
      <dx-button text="Cancel" (onClick)="toggleEdit()" stylingMode="text"></dx-button>
    </dxi-item>
  </dx-toolbar>

  <dx-form
    *ngIf="!isLoading"
    class="form last"
    [formData]="contact$"
    labelMode="floating"
    [readOnly]="!isEditing"
  >
    <dxi-item itemType="group" [colCount]="2" caption="Details">
      <dxi-item dataField="image" template="photo"></dxi-item>
      <dxi-item itemType="group">
        <dxi-item
          dataField="status"
          [template]="!isEditing ? 'statusField' : 'statusEditing'"
          [editorOptions]="editorOptions"
        >
        </dxi-item>
        <dxi-item
          dataField="firstName"
          [editorOptions]="editorOptions"
        ></dxi-item>
        <dxi-item
          dataField="lastName"
          [editorOptions]="editorOptions"
        ></dxi-item>
      </dxi-item>
      <dxi-item
        dataField="position"
        [editorOptions]="editorOptions"
      ></dxi-item>
      <dxi-item
        dataField="manager"
        template="blue-text"
        [editorOptions]="editorOptions"
      >
        <dxo-label text="Assigned to"></dxo-label>
      </dxi-item>
      <dxi-item
        dataField="company"
        template="blue-text"
        [editorOptions]="editorOptions"
        [colSpan]="2"
      ></dxi-item>
    </dxi-item>

    <dxi-item itemType="group" [colCount]="4" caption="Contacts">
      <dxi-item
        dataField="address"
        [editorOptions]="editorOptions"
        [colSpan]="4"
      ></dxi-item>
      <dxi-item
        dataField="city"
        [editorOptions]="editorOptions"
        [colSpan]="2"
      ></dxi-item>
      <dxi-item dataField="state.stateShort" [editorOptions]="editorOptions">
        <dxo-label text="State"></dxo-label>
      </dxi-item>
      <dxi-item
        dataField="zipCode"
        [editorOptions]="editorOptions"
      ></dxi-item>
      <dxi-item
        dataField="phone"
        template="phone"
        [colSpan]="2"
      ></dxi-item>
      <dxi-item
        dataField="email"
        template="email"
        [colSpan]="2"
      ></dxi-item>
    </dxi-item>

    <!-- T1085831 -->
    <div *dxTemplate="let data of 'blue-text'">
      <div *ngIf="!isEditing then blue; else editing;"></div>
      <ng-template #blue>
        <form-item-blue
          [label]="data.editorOptions.label"
          [value]="data.editorOptions.value"
        ></form-item-blue>
      </ng-template>
      <ng-template #editing>
        <dx-text-box
          [(value)]="contact$[data.dataField]"
          [label]="data.editorOptions.label"
        ></dx-text-box>
      </ng-template>
    </div>

    <div *dxTemplate="let data of 'photo'">
      <form-item-photo
        [link]="data.editorOptions.value"
        [size]="184"
      ></form-item-photo>
    </div>

    <div *dxTemplate="let data of 'statusField'">
      <div class="info">
        <label class="dx-texteditor-label">{{
          data.editorOptions.label
        }}</label>
        <contact-status [value]="data.editorOptions.value"></contact-status>
      </div>
    </div>

    <div *dxTemplate="let data of 'statusEditing'">
      <dx-select-box
        [(value)]="contact$.status"
        [items]="statusList"
        [stylingMode]="stylingMode"
        [label]="data.editorOptions.label"
        [readOnly]="!isEditing"
        fieldTemplate="field"
      >
        <div *dxTemplate="let data of 'field'">
          <div class="form-custom-list-prop">
            <contact-status [value]="contact$.status"></contact-status>
            <dx-text-box [readOnly]="true"></dx-text-box>
          </div>
        </div>
        <div *dxTemplate="let data of 'item'">
          <contact-status [value]="data"></contact-status>
        </div>
      </dx-select-box>
    </div>

    <div *dxTemplate="let data of 'phone'">
      <form-item-with-button
        [(value)]="contact$.phone"
        [isEditing]="isEditing"
        [textBoxOptions]="{
          label: data.editorOptions.label,
          stylingMode: stylingMode,
          mask: '+1(000)000-0000'
        }"
        [buttonOptions]="{
          text: 'Call',
          icon: 'tel',
          type: 'default',
          stylingMode: 'outlined'
        }"
      ></form-item-with-button>
    </div>

    <div *dxTemplate="let data of 'email'">
      <form-item-with-button
        [(value)]="contact$.email"
        [isEditing]="isEditing"
        [textBoxOptions]="{
          label: data.editorOptions.label,
          stylingMode: stylingMode
        }"
        [buttonOptions]="{
          text: 'Send Email',
          icon: 'email',
          type: 'default',
          stylingMode: 'outlined'
        }"
      ></form-item-with-button>
    </div>
  </dx-form>

  <dx-load-panel
    container="#contact-form"
    [position]="{ of: '#contact-form' }"
    [visible]="isLoading"
  ></dx-load-panel>
</div>

// packages/vue/src/pages/crm-contact-form/components/contact-form.vue
<template>
  <div id="contact-form">
    <dx-toolbar>
      <dx-toolbar-item location="after" locateInMenu="after" :visible="!isEditing">
        <dx-button
          text="Edit"
          icon="edit"
          stylingMode="outlined"
          type="default"
          :visible="!isLoading"
          @click="startEdit()"
        ></dx-button>
      </dx-toolbar-item>
      <dx-toolbar-item location="after" locateInMenu="after" :visible="isEditing">
        <dx-button
          text="Save"
          stylingMode="outlined"
          type="default"
          @click="saveEdit()"
        ></dx-button>
      </dx-toolbar-item>
      <dx-toolbar-item location="after" locateInMenu="after" :visible="isEditing">
        <dx-button
          text="Cancel"
          @click="cancelEdit()"
          styling-mode="text"
        ></dx-button>
      </dx-toolbar-item>
    </dx-toolbar>
    <load-component
      :is-loading="isLoading"
      :container-selector="'#contact-form'"
    >
      <dx-form :formData="contactData"
               label-mode="floating"
               :read-only="!isEditing"
      >
        <dx-form-group-item :col-count="2" caption="Details">
          <dx-form-item data-field="image">
            <user-photo :link="contactData.image" :size="184"></user-photo>
          </dx-form-item>

          <dx-form-group-item>

            <dx-form-item data-field="status">
              <div class="info" v-if="!isEditing">
                <label class="dx-texteditor-label">Status</label>
                <contact-status :status="contactData?.status"/>
              </div>

              <dx-select-box v-else
                             :value="contactData?.status"
                             :items="contactStatusList"
                             :styling-mode="editorOptions.stylingMode"
                             label="Status"
                             :read-only="false"
                             field-template="field"
                             item-template="item"
                             @value-changed="onChangeStatusSelect"
              >
                <template #field>
                  <div class="form-custom-list-prop">
                    <contact-status :status="contactData?.status"></contact-status>
                    <dx-text-box :readOnly="true"></dx-text-box>
                  </div>
                </template>
                <template #item="{ data }">
                  <contact-status :status="data"></contact-status>
                </template>
              </dx-select-box>
            </dx-form-item>

            <dx-form-item
              data-field="firstName"
              :editor-options="editorOptions"
            >
            </dx-form-item>

            <dx-form-item
              data-field="lastName"
              :editor-options="editorOptions"
            >
            </dx-form-item>
          </dx-form-group-item>

          <dx-form-item
            dataField="position"
            :editor-options="editorOptions"
          />

          <dx-form-item
            dataField="manager"
            :editor-options="editorOptions"
          >
            <form-item-editable
              :data="contactData"
              :data-field="'manager'"
              label="Assigned to"
              :is-editing = "isEditing"
              :editor-options="editorOptions"
            ></form-item-editable>
          </dx-form-item>

          <dx-form-item
            dataField="company"
            :editor-options="editorOptions"
            :col-span="2"
          >
            <form-item-editable
              :data="contactData"
              :data-field="'company'"
              :is-editing = "isEditing"
              :editor-options="editorOptions"
            ></form-item-editable>
          </dx-form-item>
        </dx-form-group-item>

        <dx-form-group-item :col-count="4" caption="Contacts">
          <dx-form-item
            data-field="address"
            :col-span="4"
            :editor-options="editorOptions"
          />
          <dx-form-item
            data-field="city"
            :col-span="2"
            :editor-options="editorOptions"
          />
          <dx-form-item
            data-field="state.stateShort"
            :editor-options="editorOptions"
            :label="{text: 'State'}"
          />
          <dx-form-item data-field="zipCode" :editor-options="editorOptions"/>
          <dx-form-item data-field="phone" :col-span="2" >
            <form-item-with-button
              :data="contactData"
              :data-field="'phone'"
              :is-editing = "isEditing"
              :text-box-options="{ stylingMode: editorOptions.stylingMode,
                                 label: 'Phone',
                                 mask: '+1(000)000-0000', }"
              :button-options="{
                               text: 'Call',
                               icon: 'tel',
                               type: 'default',
                               stylingMode: 'outlined'
                              }"
            ></form-item-with-button>
          </dx-form-item>
          <dx-form-item data-field="email" :col-span="2" >
            <form-item-with-button
              :data="contactData"
              :data-field="'email'"
              :is-editing = "isEditing"
              :text-box-options="{ stylingMode: editorOptions.stylingMode,
                                 label: 'Email',}"
              :button-options="{
                               text: 'Send Email',
                               icon: 'email',
                               type: 'default',
                               stylingMode: 'outlined'
                              }"
            ></form-item-with-button>
          </dx-form-item>
        </dx-form-group-item>
      </dx-form>
    </load-component>
  </div>

</template>
<script setup lang="ts">
import { computed, ref, watch } from 'vue';

import DxButton from 'devextreme-vue/button';
import { DxSelectBox } from 'devextreme-vue';
import { DxTextBox } from 'devextreme-vue/text-box';
import {
  DxToolbar,
  DxItem as DxToolbarItem,
} from 'devextreme-vue/toolbar';

import {
  DxForm,
  DxItem as DxFormItem,
  DxGroupItem as DxFormGroupItem,
} from 'devextreme-vue/form';
import LoadComponent from '@/components/load-component.vue';
import { Contact, ContactStatus as ContactStatusType, contactStatusList } from '@/types/contact';
import UserPhoto from '@/components/user-photo.vue';
import ContactStatus from '@/components/user-status.vue';
import FormItemEditable from '@/components/form-item-editable.vue';
import FormItemWithButton from '@/components/form-item-with-button.vue';

type FormData = Contact | Record<string, unknown>;

const props = withDefaults(defineProps<{
  isLoading: boolean,
  contactData: Contact | null
}>(), {
  isLoading: true,
  contactData: null,
});

const isEditing = ref(false);
const editorOptions = computed(() => ({ stylingMode: isEditing.value ? 'filled' : 'underlined' }));
const contactData = ref<FormData>({});

let contactDataSaved: FormData;

const onChangeStatusSelect = ({ value }: {[value: string]: ContactStatusType}) => {
  contactData.value.status = value;
};

watch(
  () => props.contactData,
  (contactDataNew: Contact | null) => {
    if (contactDataNew != null) {
      contactData.value = contactDataNew;
    }
  },
);

function startEdit() {
  contactDataSaved = { ...contactData.value };
  isEditing.value = true;
}

function saveEdit() {
  isEditing.value = false;
}

function cancelEdit() {
  contactData.value = contactDataSaved;
  isEditing.value = false;
}
</script>

<style scoped lang="scss">
#contact-form {
  min-height: 300px;

  .info {
    position: relative;
    padding-bottom: 30px;

    .status {
      position: absolute;
      margin-top: 20px;
    }
  }

  .status {
    font-size: 13px;
  }
}

.form-custom-list-prop {
  padding-left: 11px;

  .status {
    position: absolute;
    margin-top: 15px;
  }
}
</style>
