// packages/react/src/components/side-panel/left-side-panel.tsx
import React, { useState } from 'react';
import classNames from 'classnames';
import Button from 'devextreme-react/button';
import { useScreenSize } from '../../utils/media-query';
import './left-side-panel.scss';

export const LeftSidePanel = ({ children }) => {
  const { isXSmall, isSmall, isMedium, isLarge } = useScreenSize();
  const [isOpened, setIsOpened] = useState(isMedium || isLarge);

  return <div
    id='left-side-panel'
    className={classNames({
      'left-side-panel': true,
      'overlapping': isXSmall || isSmall,
      'open': isOpened,
    })}
  >
    <div className='side-panel-container'>
      {(isXSmall || isSmall) &&
        <div
          className='button-container'>
          <Button className='open-button'
            icon={isOpened ? 'hidepanel' : 'showpanel'}
            onClick={() => { setIsOpened(!isOpened); }} />

        </div>
      }
      <div className='side-panel-content-wrapper'>
        {children}
      </div>
    </div>
  </div>;
};

// packages/angular/src/app/components/utils/left-side-panel/left-side-panel.component.ts
import {Component, inject} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxButtonModule } from 'devextreme-angular';
import { ScreenService } from 'src/app/services';
import { DxScrollViewModule } from "devextreme-angular/ui/scroll-view";

@Component({
  selector: 'left-side-panel',
  templateUrl: './left-side-panel.component.html',
  styleUrls: ['./left-side-panel.component.scss'],
  imports: [
    DxButtonModule,
    DxScrollViewModule,
    CommonModule,
  ],
})
export class LeftSidePanelComponent {
  private screen = inject(ScreenService);
  isSmallScreen = false;
  isOpened = !(this.screen.sizes['screen-x-small'] || this.screen.sizes['screen-small']);

  constructor() {
    this.screen.smallScreenChanged.subscribe((isSmall) => {
      this.isSmallScreen = isSmall;

      if (!isSmall) {
        this.isOpened = true;
      }
    });
  }

  toggleOpen = () => {
    this.isOpened = !this.isOpened;
  };
}


<div
  class="left-side-panel"
  [class.overlapping]="isSmallScreen"
  [class.open]="isOpened"
>
  <div class="side-panel-container">
    @if (isSmallScreen) {
      <div class="button-container">
        <dx-button
          class="open-button"
          [icon]="isOpened ? 'hidepanel' : 'showpanel'"
          (onClick)="toggleOpen()"
        >
        </dx-button>
      </div>
    }

    <div class="side-panel-content-wrapper">
      <dx-scroll-view style="max-height: 100%">
        <ng-content></ng-content>
      </dx-scroll-view>
    </div>
  </div>
</div>
