// packages/angular/src/app/shared/components/card-opprtunities/card-opportunities.component.ts
import {
  Component, Input, NgModule, OnChanges, OnInit, SimpleChanges,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxLoadPanelModule,
} from 'devextreme-angular';
import notify from 'devextreme/ui/notify';
import { Activities } from 'src/app/shared/types/activities';

@Component({
  selector: 'card-opportunities',
  templateUrl: './card-opportunities.component.html',
  styleUrls: ['./card-opportunities.component.scss'],
})
export class CardOpportunitiesComponent implements OnChanges {
  @Input() active: Activities;

  @Input() closed: Activities;

  messageToast = '';

  isLoading = true;

  isVisibleToast = false;

  ngOnChanges(changes: SimpleChanges) {
    const isLoadActive = !changes.active?.currentValue;
    const isLoadClosed = !changes.closed?.currentValue;

    this.isLoading = isLoadActive || isLoadClosed;
  }

  addOpportunity = () => {
    notify('Add opportunity event');
  };

  opportunityClick() {
    notify('Click opportunity event');
  }
}

@NgModule({
  imports: [
    DxButtonModule,
    DxLoadPanelModule,

    CommonModule,
  ],
  declarations: [CardOpportunitiesComponent],
  exports: [CardOpportunitiesComponent],
})
export class CardOpportunitiesModule { }

<div id="card-opportunies">
  <ng-container *ngIf="!isLoading">
    <dx-button
      text="Add Opportunity"
      icon="add"
      width="300"
      height="115"
      stylingMode="outlined"
      type="default"
      class="add-tile"
      (onClick)="addOpportunity()"
    ></dx-button>

    <div class="opportunities-block">
      <div class="dx-form-group-caption">Active</div>
      <div class="opportunities-container">
        <div class="opportunities" *ngFor="let data of active">
          <ng-conteiner
            [ngTemplateOutlet]="opportunity"
            [ngTemplateOutletContext]="{ item: data }"
          ></ng-conteiner>
        </div>
      </div>
    </div>

    <div class="opportunities-block">
      <div class="dx-form-group-caption">Closed</div>
      <div class="opportunities-container">
        <div class="opportunities" *ngFor="let data of closed">
          <ng-conteiner
            [ngTemplateOutlet]="opportunity"
            [ngTemplateOutletContext]="{ item: data }"
          ></ng-conteiner>
        </div>
      </div>
    </div>

    <ng-template #opportunity let-item="item">
      <div (click)="opportunityClick()" class="opportunity">
        <div class="name">{{ item.name }}</div>
        <div class="product-info"
          >Products: {{ item.products }}, total:
          <span class="total">{{ item.total | currency }}</span>
        </div>
        <div class="owner">
          Owner: <span class="owner-name">{{ item.manager }}</span>
        </div>
      </div>
    </ng-template>
  </ng-container>

  <dx-load-panel
    [visible]="isLoading"
    [showPane]="false"
    container="#card-opportunies"
    [position]="{ of: '#card-opportunies' }"
  ></dx-load-panel>
</div>

// packages/react/src/components/card-opportunities/CardOpportunities.tsx
import React from 'react';

import Button from 'devextreme-react/button';
import notify from 'devextreme/ui/notify';
import { formatNumber } from 'devextreme/localization';

import { Opportunities } from '../../shared/types/card-opportunities';

import { withLoadPanel } from '../../shared/utils/withLoadPanel';

import './CardOpportunities.scss';

const addOpportunity = () => {
  notify('Add opportunity event');
};
const opportunityClick = () => {
  notify('Click opportunity event');
};

const format = (item: number) => {
  return formatNumber(item, { type: 'currency', precision: 2 });
};

const CardTemplate = ({ items, title }: { items: Opportunities, title: string}) => (
  <div className='opportunities-block'>
    <div className='dx-form-group-caption'>{title}</div>
    <div className='opportunities-container'>
      {items.map((item) => (
        <div key={item.name} className='opportunities'>
          <div onClick={opportunityClick} className='opportunity'>
            <div className='name'>{item.name}</div>
            <div className='product-info'>
              Products: {item.products}, total: <span className='total'>{format(item.total)}</span>
            </div>
            <div className='owner'>
              Owner: <span className='owner-name'>{item.manager}</span>
            </div>
          </div>
        </div>
      ))}
    </div>
  </div>
);

const Cards = ({ active, closed }: { active: Opportunities, closed: Opportunities }) => (
  <>
    <Button
      text='Add Opportunity'
      icon='add'
      width={300}
      height={115}
      stylingMode='outlined'
      type='default'
      className='add-tile'
      onClick={addOpportunity}
    ></Button>

    <CardTemplate title='Active' items={active} />
    <CardTemplate title='Closed' items={closed} />
  </>
);

const CardsWithLoadPanel = withLoadPanel(Cards);

export const CardOpportunities = ({ active, closed }: { active?: Opportunities, closed?: Opportunities }) => {
  return (
    <div className='card-opportunies'>
      <CardsWithLoadPanel
        active={active}
        closed={closed}
        loading={!active || !closed}
        panelProps={{
          container: '.card-opportunies',
          position: { of: '.card-opportunies' }
        }}
      />
    </div>
  );
};
