// packages/react/src/components/utils/form-photo/FormPhoto.tsx
import React from 'react';

import './FormPhoto.scss';
import { FileUploader } from 'devextreme-react';

export const FormPhoto = ({
  link,
  size,
  editable = false,
}: {
  link: string;
  size: number;
  editable?: boolean;
}) => {
  return (
    <div className='form-photo-view'>
      <div
        className={`form-photo ${editable ? 'editable' : ''}`}
        style={{
          width: size,
          height: size,
          maxHeight: size,
          backgroundImage: `url('data:image/png;base64,${link}')`,
        }}
      >
        {editable && <i className='edit-icon dx-icon-photooutline' />}
      </div>
      {editable && (
        <FileUploader
          dialogTrigger='.edit-icon'
          accept='image/*'
          visible={false}
        />
      )}
    </div>
  );
};

// packages/angular/src/app/components/utils/form-photo/form-photo.component.ts
import { Component, ElementRef, Input, OnInit } from '@angular/core';
import { CommonModule } from "@angular/common";
import { DxFileUploaderComponent } from "devextreme-angular";

@Component({
    selector: 'form-photo',
    templateUrl: './form-photo.component.html',
    styleUrls: ['./form-photo.component.scss'],
    imports: [
      DxFileUploaderComponent,
      CommonModule,
    ],
})
export class FormPhotoComponent implements OnInit {
  @Input() link: string;

  @Input() editable = false;

  @Input() size = 124;

  imageUrl: string;

  hostRef = this.elRef.nativeElement;

  constructor(private elRef:ElementRef) {}

  ngOnInit() {
    this.imageUrl = `url('data:image/png;base64,${this.link}')`;
  }
}

<div
  [ngStyle]="{
      'width.px': size,
      'height.px': size,
      'max-height.px': size,
      'background-image': imageUrl
    }"
  class="photo"
  [class.editable]="editable"
>
  <i *ngIf="editable" class="edit-icon dx-icon-photooutline"></i>
</div>
<dx-file-uploader *ngIf="editable"
                  [dialogTrigger]="hostRef"
                  [visible]="false"
                  accept="image/*"
></dx-file-uploader>
