// packages/react/src/layouts/single-card/single-card.js
import React from 'react';
import ScrollView from 'devextreme-react/scroll-view';
import './single-card.scss';

export default ({ title, description, children }) => (
  <ScrollView height={'100%'} width={'100%'} className={'with-footer single-card'}>
    <div className={'dx-card content'}>
      <div className={'header'}>
        <div className={'title'}>{title}</div>
        <div className={'description'}>{description}</div>
      </div>
      {children}
    </div>
  </ScrollView>
);

// packages/angular/src/app/layouts/single-card/single-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxScrollViewModule } from 'devextreme-angular/ui/scroll-view';
import { CardAuthComponent } from '../../components/library/card-auth/card-auth.component'

@Component({
  selector: 'app-single-card',
  templateUrl: './single-card.component.html',
  styleUrls: ['./single-card.component.scss'],
  imports: [
    CommonModule,
    DxScrollViewModule,
    CardAuthComponent,
  ],
})
export class SingleCardComponent {
  @Input()
  title!: string;

  @Input()
  description!: string;
}


<dx-scroll-view height="100%" width="100%" class="app-content-wrapper single-card">
  <div class="dx-card content">
    <div class="header">
      <div class="title">{{ title }}</div>
      <div class="description">{{ description }}</div>
    </div>
    <ng-content></ng-content>
  </div>
</dx-scroll-view>
