// packages/angular/src/app/pages/planning-task-list/planning-task-list.component.ts
import {
  Component, OnInit, NgModule, ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';
import { DxTabsModule } from 'devextreme-angular/ui/tabs';
import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';
import { ItemClickEvent as TabsItemClickEvent } from 'devextreme/ui/tabs';
import { InputEvent as TextBoxInputEvent } from 'devextreme/ui/text_box';
import { taskPanelItems } from 'src/app/types/resource';
import { Task, newTask } from 'src/app/types/task';
import { DataService, ScreenService } from 'src/app/services';
import { forkJoin, map, Observable } from 'rxjs';
import { TaskFormModule } from '../../components/task-form/task-form.component';
import { FormPopupModule, FormPopupComponent} from 'src/app/components';
import { TaskListGridComponent, TaskListModule } from '../../components/task-list-grid/task-list-grid.component';
import { TaskListKanbanModule, TaskListKanbanComponent } from '../../components/task-list-kanban/task-list-kanban.component';
import { TaskListGanttComponent, TaskListGanttModule } from '../../components/task-list-gantt/task-list-gantt.component';
import { DxLoadPanelModule } from 'devextreme-angular/ui/load-panel';

@Component({
  templateUrl: './planning-task-list.component.html',
  styleUrls: ['./planning-task-list.component.scss'],
  providers: [DataService],
})
export class PlanningTaskListComponent implements OnInit {
  @ViewChild('planningDataGrid', { static: false }) dataGrid: TaskListGridComponent;

  @ViewChild('planningGantt', { static: false }) gantt: TaskListGanttComponent;

  @ViewChild('planningKanban', { static: false }) kanban: TaskListKanbanComponent;

  @ViewChild('taskPopup', { static: true }) taskPopup: FormPopupComponent;

  newTask = newTask;

  taskPanelItems = taskPanelItems;

  displayTaskComponent = this.taskPanelItems[0].text;

  displayGrid = this.displayTaskComponent === this.taskPanelItems[0].text;

  displayKanban = this.displayTaskComponent === this.taskPanelItems[1].text;

  taskCollections$: Observable<{ allTasks: Task[]; filteredTasks: Task[] }>;

  constructor(private service: DataService, private screen: ScreenService) {
  }

  ngOnInit(): void {
    this.taskCollections$ = forkJoin([
      this.service.getFilteredTasks(),
      this.service.getTasks()
    ]).pipe(
      map(
        ([filteredTasks, allTasks]) => { return { allTasks, filteredTasks }  })
    );
  }

  tabValueChange(e: TabsItemClickEvent) {
    const { itemData } = e;

    this.displayTaskComponent = itemData.text;
    this.displayGrid = this.displayTaskComponent === this.taskPanelItems[0].text;
    this.displayKanban = this.displayTaskComponent === this.taskPanelItems[1].text;
  };

  addTask = () => {
    this.taskPopup.popupVisible = true;
  };

  getTabWidth = () => {
    return this.screen.isXSmallScreen() ? 220 : 'auto';
  };

  refresh = () => {
    if (this.displayGrid) {
      this.dataGrid.refresh();
    } else if (this.displayKanban) {
      this.kanban.refresh();
    } else {
      this.gantt.refresh();
    }
  };

  chooseColumnDataGrid = () => this.dataGrid.showColumnChooser();

  searchDataGrid = (e: TextBoxInputEvent) => this.dataGrid.search(e.component.option('text'));

  exportToPdf = () => {
    if (this.displayGrid) {
      this.dataGrid.onExportingToPdf();
    } else {
      this.gantt.onExporting();
    }
  };

  exportDataGridToXSLX = () => this.dataGrid.onExportingToXLSX();
}

@NgModule({
  imports: [
    DxButtonModule,
    DxDataGridModule,
    DxTabsModule,
    DxToolbarModule,
    DxLoadPanelModule,
    FormPopupModule,

    TaskFormModule,
    TaskListKanbanModule,
    TaskListModule,
    TaskListGanttModule,

    CommonModule,
  ],
  providers: [],
  exports: [],
  declarations: [PlanningTaskListComponent],
})
export class PlanningTaskListModule { }

<div class="view-wrapper">
  <dx-toolbar>
    <dxi-item location="before">
      <span class="toolbar-header">Tasks</span>
    </dxi-item>
    <dxi-item location="before">
      <dx-tabs
        secondary="secondary"
        [width]="(screen.xSmallScreenChanged | async) ? 220 : 'auto'"
        [showNavButtons]="false"
        [scrollByContent]="true"
        [selectedIndex]="0"
        [items]="taskPanelItems"
        (onItemClick)="tabValueChange($event)"
      ></dx-tabs>
    </dxi-item>

    <dxi-item location="after" locateInMenu="auto">
      <dx-button
        icon="plus"
        text="Add Task"
        type="default"
        stylingMode="contained"
        (onClick)="addTask()"
      ></dx-button>
    </dxi-item>

    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxButton"
      showText="inMenu"
      [options]="{
        text: 'Refresh',
        icon: 'refresh',
        onClick: refresh,
        stylingMode: 'text'
      }"
    ></dxi-item>

    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxButton"
      showText="inMenu"
      [disabled]="!displayGrid"
      [options]="{
        text: 'Column Chooser',
        icon: 'columnchooser',
        onClick: chooseColumnDataGrid,
        stylingMode: 'text'
      }"
    ></dxi-item>

    <dxi-item location="after" locateInMenu="auto">
      <div class="separator"></div>
    </dxi-item>

    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxButton"
      showText="inMenu"
      [disabled]="displayKanban"
      [options]="{
        text: 'Export to PDF',
        icon: 'exportpdf',
        onClick: exportToPdf,
        stylingMode: 'text'
      }"
    ></dxi-item>

    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxButton"
      showText="inMenu"
      [disabled]="!displayGrid"
      [options]="{
        text: 'Export to Exel',
        icon: 'exportxlsx',
        onClick: exportDataGridToXSLX,
        stylingMode: 'text'
      }"
    ></dxi-item>

    <dxi-item
      location="after"
      locateInMenu="auto"
      widget="dxTextBox"
      [disabled]="!displayGrid"
      [options]="{
        placeholder: 'Task Search',
        mode: 'search',
        onInput: searchDataGrid
      }"
    ></dxi-item>
  </dx-toolbar>
  <ng-container
    *ngIf="taskCollections$ | async as taskCollections; else loading"
  >
    <ng-container *ngIf="taskCollections" [ngSwitch]="displayTaskComponent">
      <div *ngSwitchCase="taskPanelItems[0].text" class="grid">
        <task-list-grid
          #planningDataGrid
          [dataSource]="taskCollections.allTasks"
          (tabValueChanged)="tabValueChange($event)"
        >
        </task-list-grid>
      </div>
      <div *ngSwitchCase="taskPanelItems[1].text" class="kanban">
        <task-list-kanban
          #planningKanban
          [dataSource]="taskCollections.filteredTasks"
          (addTaskEvent)="addTask()"
        ></task-list-kanban>
      </div>
      <div *ngSwitchCase="taskPanelItems[2].text" class="gantt">
        <task-list-gantt
          #planningGantt
          [dataSource]="taskCollections.filteredTasks"
        ></task-list-gantt>
      </div>
    </ng-container>
  </ng-container>
  <ng-template #loading>
    <dx-load-panel
      [visible]="true"
      [showPane]="false"
      container=".content"
      [position]="{ of: '.content' }"
    >
    </dx-load-panel>
  </ng-template>
  <form-popup [(visible)]="isAddTaskPopupOpened" (save)= "onClickSaveNewTask()" titleText="New Task">
    <task-form [task]="newTask" [isCreateMode]="true"></task-form>
  </form-popup>
</div>

// packages/vue/src/pages/planning/planning-task-list/planning-task-list.vue
<template>
  <div class="view-wrapper">
    <dx-toolbar>
      <dx-toolbar-item location="before">
        <span class="toolbar-header">Tasks</span>
      </dx-toolbar-item>
      <dx-toolbar-item location="before">
        <dx-tabs
          :selected-index="0"
          :items="taskPanelItems"
          @item-click="tabValueChange"
        />
      </dx-toolbar-item>

      <dx-toolbar-item
        location="after"
        locate-in-menu="auto"
        css-class="add-grid-row"
      >
        <div>
          <dx-button
            icon="plus"
            text="Add Task"
            type="default"
            styling-mode="contained"
            @click="addTask"
          />
        </div>
      </dx-toolbar-item>
      <dx-toolbar-item
        location="after"
        locate-in-menu="auto"
        widget="dxButton"
        show-text="inMenu"
        :options="{
          text: 'Refresh',
          icon: 'refresh',
          onClick: reload
        }"
      />

      <dx-toolbar-item
        :disabled="activeTabId !== 'grid'"
        location="after"
        locate-in-menu="auto"
        widget="dxButton"
        show-text="inMenu"
        :options="{
          text: 'Column Chooser',
          icon: 'columnchooser',
          onClick: chooseColumnDataGrid
        }"
      />

      <dx-toolbar-item
        location="after"
        locate-in-menu="auto"
      >
        <div>
          <div class="separator" />
        </div>
      </dx-toolbar-item>

      <dx-toolbar-item
        :disabled="!['grid', 'gantt'].includes(activeTabId)"
        location="after"
        locate-in-menu="auto"
        widget="dxButton"
        show-text="inMenu"
        :options="{
          text: 'Export to PDF',
          icon: 'exportpdf',
          onClick: exportToPdf
        }"
      />

      <dx-toolbar-item
        :disabled="!['grid'].includes(activeTabId)"
        location="after"
        locate-in-menu="auto"
        widget="dxButton"
        show-text="inMenu"
        :options="{
          text: 'Export to Exel',
          icon: 'exportxlsx',
          onClick: exportToXlsx
        }"
      />
      <dx-toolbar-item
        :disabled="!['grid'].includes(activeTabId)"
        location="after"
        locate-in-menu="auto"
        widget="dxTextBox"
        :options="{
          placeholder: 'Task Search',
          mode: 'search',
          onInput: searchDataGrid
        }"
      />
    </dx-toolbar>
    <load-component :is-loading="isLoading">
      <div class="task-list">
        <div
          v-if="taskPanelItems[0].text === displayTaskComponent"
          class="grid"
        >
          <task-list-grid
            ref="tasksGridCmp"
            :data-source="gridData"
          />
        </div>
        <div
          v-else-if="taskPanelItems[1].text === displayTaskComponent"
          class="kanban"
        >
          <task-list-kanban
            :tasks="kanbanData"
            @add-task="addTask"
          />
        </div>
        <div
          v-else-if="taskPanelItems[2].text === displayTaskComponent"
          class="gantt"
        >
          <task-list-gantt
            ref="tasksGanttCmp"
            :tasks="ganttData"
          />
        </div>
      </div>
    </load-component>
  </div>
  <form-popup
    title="New Task"
    v-model:is-visible="isNewTaskPopupOpened"
    @save="onSaveNewTask"
  >
    <task-form
      :content-by-screen="{ xs: 1, sm: 1 }"
      :is-create-mode="true"
    />
  </form-popup>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import DxButton from 'devextreme-vue/button';
import DxTabs from 'devextreme-vue/tabs';
import { ItemClickEvent as TabsItemClickEvent } from 'devextreme/ui/tabs';
import { InputEvent as TextBoxInputEvent } from 'devextreme/ui/text_box';
import {
  DxToolbar,
  DxItem as DxToolbarItem,
} from 'devextreme-vue/toolbar';

// eslint-disable-next-line import/no-unresolved
import { getTasks, getFilteredTasks } from 'dx-template-gallery-data';
import { taskPanelItems, TaskPanelItemsIds } from '@/types/resource';
import type { Task } from '@/types/task';
import FormPopup from '@/components/form-popup.vue';
import LoadComponent from '@/components/load-component.vue';
import TaskForm from '../components/task-form.vue';
import TaskListGrid from './components/task-list-grid.vue';
import TaskListKanban from './components/task-list-kanban/task-list-kanban.vue';
import TaskListGantt from './components/task-list-gantt.vue';

const isLoading = ref(true);
const displayTaskComponent = ref(taskPanelItems[0].text);
const activeTabId = ref<TaskPanelItemsIds>('grid');
const tasksGridCmp = ref<InstanceType<typeof TaskListGrid> | null>(null);
const tasksGanttCmp = ref<InstanceType<typeof TaskListGantt> | null>(null);

const gridData = ref<Task[]>([]);
const kanbanData = ref<Task[]>([]);
const ganttData = ref<Task[]>([]);
const isNewTaskPopupOpened = ref(false);

const addTask = () => {
  isNewTaskPopupOpened.value = true;
};
const chooseColumnDataGrid = () => tasksGridCmp.value.showColumnChooser();
const searchDataGrid = (e: TextBoxInputEvent) => tasksGridCmp.value.search(e.component.option('text'));
const exportToPdf = () => {
  ({
    grid: tasksGridCmp,
    gantt: tasksGanttCmp,
    kanban: null,
  })[activeTabId.value]?.value.exportToPdf();
};

const exportToXlsx = () => {
  tasksGridCmp.value.exportToXlsx();
};

const loadFilteredTasksAsync = async () => {
  isLoading.value = true;

  const filteredTasks = await getFilteredTasks();

  kanbanData.value = [...filteredTasks];
  ganttData.value = filteredTasks;
  isLoading.value = false;
};

const loadTasksAsync = async () => {
  isLoading.value = true;
  const tasks = await getTasks();

  gridData.value = tasks.filter((item) => !!item.status && !!item.priority);
  isLoading.value = false;
};

const tabValueChange = (e: TabsItemClickEvent) => {
  const { itemData } = e;
  displayTaskComponent.value = itemData.text;
  const tabId = taskPanelItems.find((item) => displayTaskComponent.value === item.text)?.id;
  activeTabId.value = tabId || 'grid';

  if (tabId !== 'grid' && kanbanData.value.length === 0) {
    loadFilteredTasksAsync();
  } else if (tabId === 'grid' && gridData.value.length === 0) {
    loadTasksAsync();
  }
};

const reload = () => {
  isLoading.value = true;
  if (activeTabId.value === 'grid') {
    loadTasksAsync();
    ganttData.value = [];
    kanbanData.value = [];
  } else {
    gridData.value = [];
    loadFilteredTasksAsync();
  }
};

const onSaveNewTask = () => {
  isNewTaskPopupOpened.value = false;
};

loadTasksAsync();
</script>

<style scoped lang="scss">
@use "@/variables" as *;
@use "sass:math";

@include separator();

.view-wrapper {
  display: flex;
  flex-direction: column;
  flex-grow: 1;

  .dx-toolbar {
    padding: 20px $content-padding $content-padding;
  }
}

:deep(.dx-toolbar) {

  .toolbar-header {
    @include header();
  }

  .dx-tabs .dx-tab {
    background-color: $background-color;
  }
}

.view-wrapper {
  flex-direction: column;
}

.gantt,
.kanban {
  padding: 0 $content-padding;
}
</style>
