// packages/vue/src/components/card-messages.vue
<template>
  <dx-validation-group>
    <div
      class="messages"
      id="card-messages"
    >
      <load-component
        :is-loading="props.isLoading"
        :container-selector="'#card-messages'"
      >
        <div class="input-content">
          <dx-text-box
            label="Subject"
            styling-mode="outlined"
            :value="messageTitle"
            value-change-event="keyup"
            @value-changed="e => messageTitle = e.value"
          >
            <dx-validator>
              <dx-required-rule />
            </dx-validator>
          </dx-text-box>
          <dx-text-area
            label="Message"
            styling-mode="outlined"
            :value="messageText"
            :height="150"
            value-change-event="keyup"
            @value-changed="e => messageText = e.value"
          >
            <dx-validator>
              <dx-required-rule />
            </dx-validator>
          </dx-text-area>

          <dx-toolbar>
            <dx-item location="before">
              <dx-file-uploader
                class="file-uploader"
                label-text=""
                select-button-text="Attach file"
              />
            </dx-item>
            <dx-item
              widget="dxButton"
              location="after"
              :options="{
                text: 'Send',
                stylingMode: 'outlined',
                type: 'default',
                onClick: send,
              }"
            />
          </dx-toolbar>
        </div>
        <div class="messages-content">
          <div class="message-list">
            <div
              class="message-container"
              v-for="data in items"
            >
              <div class="avatar">
                {{ getAvatarText(data.manager) }}
              </div>
              <div class="message dx-card">
                <div class="message-title">
                  <div>
                    <div class="subject">
                      {{ data.subject }}
                    </div>
                    <div>{{ formatDate(new Date(data.date)) }} - {{ data.manager }}</div>
                  </div>
                  <dx-button icon="overflow" />
                </div>
                <div class="message-text">
                  {{ setUserName(data) }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </load-component>
    </div>
  </dx-validation-group>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { defaultUser } from '@/auth';
import { DxTextArea } from 'devextreme-vue/text-area';
import { DxTextBox } from 'devextreme-vue/text-box';
import { DxButton } from 'devextreme-vue/button';
import { DxToolbar, DxItem } from 'devextreme-vue/toolbar';
import { DxFileUploader } from 'devextreme-vue/file-uploader';
import { DxValidationGroup } from 'devextreme-vue/validation-group';
import DxValidator, { DxRequiredRule } from 'devextreme-vue/validator';

import { ClickEvent } from 'devextreme/ui/button';

import { formatDate } from '@/utils/formatters';
import LoadComponent from '@/components/load-component.vue';

import type { Message } from '@/types/messages';

const props = withDefaults(defineProps<{
  isLoading: boolean,
  user: string,
  messages: Message[],
}>(), {
  user: '',
  isLoading: true,
  messages: () => [],
});

const items = ref<Message[]>(props.messages);
const messageText = ref<string>('');
const messageTitle = ref<string>('');

watch(
  () => props.messages,
  (newValue) => {
    items.value = newValue;
  },
);

function getAvatarText(name: string) {
  return name.split(' ').map((namePart) => namePart[0]).join('');
}

function setUserName(data: Message) {
  return data.text.replace('{username}', data.manager === props.user ? defaultUser.fullName : props.user);
}

function send(e: ClickEvent) {
  if (!e.validationGroup.validate().isValid) {
    return;
  }

  const newMessage: Message = {
    subject: messageTitle.value,
    text: messageText.value,
    manager: props.user,
    date: new Date(),
  };

  items.value.push(newMessage);

  e.validationGroup.reset();
}
</script>

<style scoped lang="scss">
@use "@/variables" as *;

@include messages-content();

#card-messages {
  min-height: 300px;
}
.input-content {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.file-uploader {
  :deep(.dx-fileuploader-wrapper) {
    padding: 0;

    .dx-fileuploader-input-wrapper {
      padding: 0;
    }
  }
}

.input-content {
  padding: 20px;
}

.message-container {
  display: flex;

  &:nth-child(odd) {
    flex-direction: row-reverse;
  }

  .avatar {
    width: 32px;
    height: 32px;
    border-radius: 16px;
    flex-shrink: 0;
    margin: 2px 5px;
    background: $base-accent;
    font-size: 12px;
    font-weight: 500;
    display: flex;
    align-items: center;
    justify-content: center;
    color: $base-bg;
  }

  .message {
    background-color: $base-bg;
    padding: 10px;
    margin-bottom: 10px;

    .message-title {
      @include message-title();

      .subject {
        color: $base-text-color;
        font-weight: 700;
      }
    }

    .message-text {
      @include message-text();
    }
  }
}
</style>

// packages/angular/src/app/components/card-messages/card-messages.component.ts
import { CommonModule } from '@angular/common';
import {
  Component, Input, NgModule,
} from '@angular/core';
import { defaultUser } from 'src/app/services';
import {
  DxTextAreaModule,
  DxTextBoxModule,
  DxButtonModule,
  DxToolbarModule,
  DxFileUploaderModule,
  DxValidationGroupModule,
  DxValidatorModule,
} from 'devextreme-angular';
import { Message, Messages } from 'src/app/types/messages';

@Component({
  selector: 'card-messages',
  templateUrl: './card-messages.component.html',
  styleUrls: ['./card-messages.component.scss'],
})
export class CardMessagesComponent {
  @Input() user: string;

  @Input() items: Messages;

  messageTitle = '';

  messageText = '';

  getAvatarText(name: string) {
    return name.split(' ').map((name) => name[0]).join('');
  }

  setUserName(data: Message) {
    return data.text.replace('{username}',  data.manager === this.user ? defaultUser.name : this.user);
  }

  send = (e) => {
    if (!e.validationGroup.validate().isValid) {
      return;
    }

    const newMessage: Message = {
      subject: this.messageTitle,
      text: this.messageText,
      manager: this.user,
      date: new Date(),
    };

    this.items.push(newMessage);

    e.validationGroup.reset();
  };
}

@NgModule({
  imports: [
    DxTextAreaModule,
    DxTextBoxModule,
    DxToolbarModule,
    DxFileUploaderModule,
    DxButtonModule,
    DxValidationGroupModule,
    DxValidatorModule,
    CommonModule,
  ],
  declarations: [CardMessagesComponent],
  exports: [CardMessagesComponent],
})
export class CardMessagesModule { }

<dx-validation-group>
  <div class="messages">
    <div class="input-content">
      <dx-text-box
        label="Subject"
        stylingMode="outlined"
        [(value)]="messageTitle"
      >
        <dx-validator>
          <dxi-validation-rule type="required"></dxi-validation-rule>
        </dx-validator>
      </dx-text-box>
      <dx-text-area
        label="Message"
        stylingMode="outlined"
        [(value)]="messageText"
        [height]="150"
      >
        <dx-validator>
          <dxi-validation-rule type="required"></dxi-validation-rule>
        </dx-validator>
      </dx-text-area>
      <dx-toolbar>
        <dxi-item
          location="before"
        >
          <dx-file-uploader
            class="file-uploader"
            labelText=""
            [showFileList]="false"
            selectButtonText="Attach file"
          >
          </dx-file-uploader>
        </dxi-item>
        <dxi-item
          location="after"
          widget="dxButton"
          [options]="{
            text: 'Send',
            stylingMode: 'outlined',
            type: 'default',
            onClick: send
          }"
        >
        </dxi-item>
      </dx-toolbar>
    </div>
    <div class="messages-content">
        <div class="message-list">
          <div class="message-container" *ngFor="let data of items">
            <div class="avatar">
              {{ getAvatarText(data.manager) }}
            </div>
            <div class="message dx-card">
              <div class="message-title">
                <div>
                  <div class="subject">{{ data.subject }}</div>
                  <div>{{ data.date | date: "MM/dd/y" }} - {{ data.manager }}</div>
                </div>
                <div>
                  <dx-button icon="overflow"></dx-button>
                </div>
              </div>
              <div class="message-text">{{ setUserName(data) }}</div>
            </div>
          </div>
        </div>
    </div>
  </div>
</dx-validation-group>
