// packages/react/src/components/calendar-list/calendar-list.tsx
/* eslint-disable @typescript-eslint/no-unused-vars */
import React, { useState, useCallback } from 'react';
import List from 'devextreme-react/list';
import Button from 'devextreme-react/button';
import './calendar-list.scss';
import { CheckBox } from 'devextreme-react';

const onAddClick = (e) => {
  e.event.stopImmediatePropagation();
};

const listTitleRender = (item) => {
  return <div className='list-header'>
    {item.key}
    <Button icon='add' stylingMode='contained' onClick={onAddClick} />
  </div>;
};

export const CalendarList = ({ calendarItems, onSelectedCalendarsChange }) => {
  const [selectedItems, setSelectedItems] = useState<string[]>(calendarItems || []);

  const onSelectedItemKeysChange = useCallback((checkedItems) => {
    setSelectedItems(checkedItems);
    onSelectedCalendarsChange(checkedItems);
  }, [onSelectedCalendarsChange]);

  const listItemsRender = useCallback((item) => {
    return (
      <div className='list-item'>
        <CheckBox value={!selectedItems.includes(item)}
          style={{
            '--checkbox-color': item.checkboxColor,
            // '--checkbox-secondary-color': item.color
          }} />
        <span className='list-item-text'>{item.text}</span>
      </div>
    );
  }, [selectedItems]);
  return (
    <div className='calendar-list'>
      <List
        className='calendar-list'
        dataSource={calendarItems}
        activeStateEnabled={false}
        groupRender={listTitleRender}
        itemRender={listItemsRender}
        grouped
        collapsibleGroups
        scrollingEnabled={false}
        selectionMode='multiple'
        onSelectedItemKeysChange={onSelectedItemKeysChange}
      />
    </div>
  );
};

// packages/angular/src/app/components/utils/calendar-list/calendar-list.component.ts
import { Component, EventEmitter, Output, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxButtonModule, DxCheckBoxModule } from 'devextreme-angular';
import { DxListModule } from 'devextreme-angular/ui/list';

@Component({
  selector: 'calendar-list',
  templateUrl: './calendar-list.component.html',
  styleUrls: ['./calendar-list.component.scss'],
  imports: [
    DxListModule,
    DxCheckBoxModule,
    DxButtonModule,
    CommonModule
  ],
})
export class CalendarListComponent implements OnInit {
  @Input() dataSource: Record<string, any>[];

  @Output() listSelectionChanged = new EventEmitter<any>();

  selectedItems = [];

  constructor() {}

  ngOnInit() {
    this.selectedItems = [...this.dataSource.flatMap((el) => el.items)];
  }

  selectionChanged(item, isSelected) {
    const selected = this.selectedItems;
    this.selectedItems = isSelected ? [...selected, item] :  selected.filter((el) => el !== item);
    this.listSelectionChanged.emit(this.selectedItems);
  }
}

<dx-list
  class='calendar-list'
  [dataSource]="dataSource"
  [activeStateEnabled]="false"
  [focusStateEnabled]="false"
  [hoverStateEnabled]="false"
  [grouped]="true"
  [collapsibleGroups]="true"
  [scrollingEnabled]="false"
>
  <div *dxTemplate="let item of 'group'">
    <div class='list-header'>
      {{ item.key }}
      <dx-button icon='add'
                 stylingMode='contained'
                 (onClick)="onAddClick($event)"
      ></dx-button>
    </div>
  </div>

  <div *dxTemplate="let item of 'item'">
    <div class='list-item'>
      <dx-check-box [value]="selectedItems.includes(item)"
                    [focusStateEnabled]="false"
                    [ngStyle]="{'--checkbox-color': item.checkboxColor}"
                    (onValueChanged)="selectionChanged(item, $event.value)"></dx-check-box>
      <span class='list-item-text'>{{ item.text }}</span>
    </div>
  </div>
</dx-list>
