// packages/react/src/pages/analytics-sales-report/cards/SalesRangeCard.tsx
import RangeSelector, { Chart, Label, LoadingIndicator, Marker, MinorTick, Scale, Series, Size } from 'devextreme-react/range-selector';
import React from 'react';
import { CardAnalytics } from '../../../components/card-analytics/CardAnalytics';

export const SalesRangeCard = ({ datasource, range, onRangeChanged }) => (
  <CardAnalytics title='' contentClass='sales-range' isLoading={!datasource.length} menuVisible={false}>
    <RangeSelector id='range' dataSource={datasource} value={range} onValueChanged={onRangeChanged}>
      <Scale minorTickInterval='day' tickInterval='month' valueType='datetime'>
        <MinorTick visible={false} />
        <Marker visible={false} />
        <Label format='MMM yyyy' />
      </Scale>
      <Size height={90} />
      <LoadingIndicator show />
      <Chart>
        <Series type='line' argumentField='date' valueField='total' />
      </Chart>
    </RangeSelector>
  </CardAnalytics>
);

// packages/angular/src/app/components/utils/sales-range-card/sales-range-card.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
} from '@angular/core';
import { CardAnalyticsComponent } from '../../library/card-analytics/card-analytics.component';
import { DxRangeSelectorModule } from 'devextreme-angular/ui/range-selector';
import { Sale } from 'src/app/types/analytics';

@Component({
    selector: 'sales-range-card',
    templateUrl: './sales-range-card.component.html',
    styleUrls: ['./sales-range-card.component.scss'],
    imports: [
      CardAnalyticsComponent,
      DxRangeSelectorModule,
    ],
})
export class SalesRangeCardComponent {
  @Input() data: Sale[];

  @Input() visualRange: unknown = {};

  @Output() visualRangeChange = new EventEmitter<unknown>();

  @Output() salesRangeChanged = new EventEmitter();

  onRangeChanged(event) {
    this.salesRangeChanged.emit(event);
    this.visualRangeChange.emit(this.visualRange);
  }
}


<card-analytics contentClass="sales-range" [isMenuVisible]="false">
  @if (data && data.length > 0) {
    <dx-range-selector
      [dataSource]="data"
      [(value)]="visualRange"
      (onValueChanged)="onRangeChanged($event)"
    >
      <dxo-range-selector-scale
        minorTickInterval="day"
        tickInterval="month"
        valueType="datetime"
      >
        <dxo-range-selector-minor-tick [visible]="false"></dxo-range-selector-minor-tick>
        <dxo-range-selector-marker [visible]="false"></dxo-range-selector-marker>
        <dxo-range-selector-label format="MMM yyyy"></dxo-range-selector-label>
      </dxo-range-selector-scale>
      <dxo-range-selector-size [height]="90"></dxo-range-selector-size>

      <dxo-range-selector-chart>
        <dxi-range-selector-series type="line" argumentField="date" valueField="total">
        </dxi-range-selector-series>
      </dxo-range-selector-chart>
    </dx-range-selector>
  } @else {
  <dx-load-indicator class="centered"></dx-load-indicator>
  }
</card-analytics>
