// packages/react/src/pages/analytics-dashboard/cards/RevenueAnalysisCard.tsx
import React from 'react';
import Bullet, { Size, Tooltip } from 'devextreme-react/bullet';
import DataGrid, { Column } from 'devextreme-react/data-grid';
import { CardAnalytics } from '../../../components/card-analytics/CardAnalytics';
import { SaleByState } from '../../../shared/types/analytics';

export const RevenueAnalysisCard = ({ datasource }: { datasource: SaleByState[] }) => (
  <CardAnalytics title='Revenue Analysis' contentClass='sales-by-state grid'>
    <DataGrid dataSource={datasource} height={290}>
      <Column caption='State' dataField='stateName' />
      <Column alignment='left' caption='Sales' dataField='total' dataType='number' format='currency' sortOrder='desc' hidingPriority={2} />
      <Column alignment='left' caption='% Sold' dataField='percentage' name='percentN' format='percent' hidingPriority={1} />
      <Column
        alignment='left'
        caption='Percentage'
        dataField='percentage'
        cssClass='sales-bullet'
        name='percentB'
        cellRender={(cellInfo) => (
          <Bullet showTarget={false} showZeroLevel={false} value={cellInfo.data.percentage * 100} startScaleValue={0} endScaleValue={100}>
            <Tooltip enabled={false} />
            <Size width={200} height={20} />
          </Bullet>
        )}
        width={200}
      />
    </DataGrid>
  </CardAnalytics>
);

// packages/vue/src/pages/analytics/analytics-dashboard/components/revenue-analysis-card.vue
<template>
  <card-analytics
    title="Revenue Analysis"
    content-class="sales-by-state"
  >
    <dx-data-grid
      :data-source="props.data"
      :height="270"
      :load-panel="{enabled: false}"
    >
      <dx-column
        caption="State"
        data-field="stateName"
      />
      <dx-column
        alignment="left"
        caption="Sales"
        data-field="total"
        data-type="number"
        format="currency"
        sort-order="desc"
        :hiding-priority="2"
      />
      <dx-column
        alignment="left"
        caption="% Sold"
        data-field="percentage"
        name="percentN"
        format="percent"
        :hiding-priority="1"
      />
      <dx-column
        alignment="left"
        caption="Percentage"
        data-field="percentage"
        name="percentB"
        cell-template="salesBullet"
        :width="200"
      />

      <template #salesBullet="{ data }">
        <dx-bullet
          :show-target="false"
          :show-zero-level="false"
          :value="data.data?.percentage * 100"
          :start-scale-value="0"
          :end-scale-value="100"
        >
          <dx-bullet-tooltip :enabled="false" />
          <dx-bullet-size
            :width="200"
            :height="20"
          />
        </dx-bullet>
      </template>
    </dx-data-grid>
  </card-analytics>
</template>

<script setup lang="ts">
import { DxDataGrid, DxColumn } from 'devextreme-vue/data-grid';
import { DxBullet, DxTooltip as DxBulletTooltip, DxSize as DxBulletSize } from 'devextreme-vue/bullet';

import { SalesByState } from '@/types/analytics';
import CardAnalytics from '../../components/card-analytics.vue';

const props = defineProps<{
  data: SalesByState
}>();
</script>
