// packages/angular/src/app/pages/planning-task-list/task-list-grid/task-list-grid.component.ts
import {
 Component, OnInit, NgModule, ViewChild, EventEmitter, Output, Input, SimpleChanges, OnChanges,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import {
  DxButtonModule,
  DxDataGridComponent,
  DxDataGridModule,
  DxDropDownButtonModule,
  DxLoadPanelModule,
  DxTabsModule,
  DxToolbarModule,
} from 'devextreme-angular';
import { RowPreparedEvent } from 'devextreme/ui/data_grid';
import { ItemClickEvent as TabsItemClickEvenet } from 'devextreme/ui/tabs';
import {
  TaskProirityModule,
  TaskStatusModule,
} from 'src/app/shared/components';
import { exportDataGrid } from 'devextreme/excel_exporter';
import { Workbook } from 'exceljs';
import { saveAs } from 'file-saver-es';
import { taskPriorityList, taskStatusList } from 'src/app/shared/types/task';
import { Task } from 'src/app/shared/types/task';

@Component({
  selector: 'task-list-grid',
  templateUrl: './task-list-grid.component.html',
  styleUrls: ['./task-list-grid.component.scss'],
})
export class TaskListGridComponent implements OnInit, OnChanges {
  @ViewChild(DxDataGridComponent, { static: false }) component: DxDataGridComponent;

  @Input() dataSource: Task[];

  @Output() tabValueChanged: EventEmitter<any> = new EventEmitter<EventEmitter<any>>();

  @Output() addRow = () => this.component.instance.addRow();

  @Output() refresh = () => this.component.instance.refresh();

  @Output() showColumnChooser = () => this.component.instance.showColumnChooser();

  @Output() search = (text: string) => this.component.instance.searchByText(text);

  @Output() onExporting = (selectedRowsOnly: boolean) => {
    const workbook = new Workbook();
    const worksheet = workbook.addWorksheet('Employees');

    exportDataGrid({
      component: this.component.instance,
      worksheet,
      autoFilterEnabled: true,
      selectedRowsOnly,
    }).then(() => {
      workbook.xlsx.writeBuffer().then((buffer) => {
        saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'DataGrid.xlsx');
      });
    });
  };

  isLoading: Boolean = true;

  statusList = taskStatusList;

  priorityList = taskPriorityList;

  constructor() {
  }

  ngOnInit() {
  }

  ngOnChanges(changes: SimpleChanges) {
    this.isLoading = changes.dataSource.currentValue === undefined;
  }

  onRowPreparedGrid = (e: RowPreparedEvent<Task, number>) => {
    const { rowType, rowElement, data } = e;

    if (rowType === 'header') return;

    if (data.status === 'Completed') {
      rowElement.classList.add('completed');
    }
  };

  tabsItemClick = (e: TabsItemClickEvenet) => {
    this.tabValueChanged.emit(e);
  };
}

@NgModule({
  imports: [
    DxButtonModule,
    DxDataGridModule,
    DxTabsModule,
    DxDropDownButtonModule,
    DxToolbarModule,
    DxLoadPanelModule,

    TaskProirityModule,
    TaskStatusModule,

    HttpClientModule,
    CommonModule,
  ],
  providers: [],
  exports: [TaskListGridComponent],
  declarations: [TaskListGridComponent],
})
export class TaskListModule { }

<dx-data-grid
  [dataSource]="tasks"
  (onRowPrepared)="onRowPreparedGrid($event)"
  (onRowClick)="navigateToDetails($event)"
  (onEditingStart)="onEditingStart()"
  (onEditCanceled)="onEditEnd()"
  (onSaved)="onEditEnd()"
  [hoverStateEnabled]="true"
  [columnAutoWidth]="true"
>
  <dxo-paging [pageSize]="15"> </dxo-paging>
  <dxo-pager [visible]="true" [showPageSizeSelector]="true"> </dxo-pager>
  <dxo-editing mode="row" [allowUpdating]="true"> </dxo-editing>
  <dxo-selection
    selectAllMode="allPages"
    showCheckBoxesMode="always"
    mode="multiple"
  ></dxo-selection>
  <dxo-sorting mode="multiple"></dxo-sorting>
  <dxo-header-filter [visible]="true"></dxo-header-filter>

  <dxi-column dataField="text" caption="Subject" [hidingPriority]="7">
    <dxi-validation-rule type="required"></dxi-validation-rule>
  </dxi-column>
  <dxi-column dataField="company" caption="Company" [hidingPriority]="6">
    <dxi-validation-rule type="required"></dxi-validation-rule>
  </dxi-column>
  <dxi-column
    dataField="priority"
    caption="Priority"
    [hidingPriority]="4"
    cellTemplate="cellPriority"
    editCellTemplate="editCellPriority"
  >
    <dxo-lookup [dataSource]="priorityList"></dxo-lookup>
    <dxi-validation-rule type="required"></dxi-validation-rule>
  </dxi-column>
  <dxi-column
    dataField="startDate"
    caption="Start Date"
    dataType="date"
    [hidingPriority]="2"
  >
    <dxi-validation-rule type="required"></dxi-validation-rule>
  </dxi-column>
  <dxi-column
    dataField="dueDate"
    caption="Due Date"
    dataType="date"
    sortOrder="asc"
    [hidingPriority]="1"
  >
    <dxi-validation-rule type="required"></dxi-validation-rule>
  </dxi-column>
  <dxi-column dataField="owner" caption="Owner" [hidingPriority]="5">
    <dxi-validation-rule type="required"></dxi-validation-rule>
  </dxi-column>
  <dxi-column
    dataField="status"
    caption="Status"
    [hidingPriority]="3"
    [minWidth]="120"
    cellTemplate="cellStatus"
    editCellTemplate="editCellStatus"
  >
    <dxo-lookup [dataSource]="statusList"></dxo-lookup>
    <dxi-validation-rule type="required"></dxi-validation-rule>
  </dxi-column>

  <div *dxTemplate="let cellInfo of 'cellPriority'">
    <status-indicator
      [isField]="false"
      [showBar]="true"
      [value]="cellInfo.data.priority">
    </status-indicator>
  </div>

  <div *dxTemplate="let cellInfo of 'editCellPriority'">
    <dx-select-box
      class="edit-cell"
      [(value)]="cellInfo.value"
      [items]="priorityList"
      (onValueChanged)="cellInfo.setValue($event.value)"
      (onSelectionChanged)="cellInfo.component.updateDimensions()"
      fieldTemplate="field"
    >
      <div *dxTemplate="let data of 'field'">
        <status-indicator [showBar]="true" [value]="cellInfo.value"></status-indicator>
      </div>
      <div *dxTemplate="let data of 'item'">
        <status-indicator [showBar]="true" [isField]="false" [value]="data"></status-indicator>
      </div>
    </dx-select-box>
  </div>

  <div *dxTemplate="let cellInfo of 'cellStatus'">
    <status-indicator [isField]="false" [value]="cellInfo.data.status"></status-indicator>
  </div>

  <div *dxTemplate="let cellInfo of 'editCellStatus'">
    <dx-select-box
      class="edit-cell"
      [(value)]="cellInfo.value"
      [items]="statusList"
      (onValueChanged)="cellInfo.setValue($event.value)"
      (onSelectionChanged)="cellInfo.component.updateDimensions()"
      fieldTemplate="field"
    >
      <div *dxTemplate="let data of 'field'">
        <status-indicator [value]="cellInfo.value"></status-indicator>
      </div>
      <div *dxTemplate="let s of 'item'">
        <status-indicator [isField]="false" [value]="s"></status-indicator>
      </div>
    </dx-select-box>
  </div>
</dx-data-grid>

// packages/vue/src/pages/planning/planning-task-list/components/task-list-grid.vue
<template>
  <dx-data-grid
    ref="dxDataGridCmp"
    height="100%"
    id="tasks-grid"
    :data-source="dataSource"
    @row-click="navigateToDetails($event)"
    @row-prepared="onRowPreparedGrid"
    @editing-start="onEditingStart"
    @edit-canceled="onEditEnd"
    @saved="onEditEnd"
    :hover-state-enabled="true"
    :column-auto-width="true"
  >
    <dx-load-panel
      :enabled="true"
      :show-pane="false"
    />
    <dx-scrolling row-rendering-mode="virtual" />
    <dx-paging :page-size="15" />
    <dx-pager
      :visible="true"
      :show-page-size-selector="true"
    />
    <dx-editing
      mode="row"
      :allow-updating="true"
    />

    <dx-selection
      select-all-mode="allPages"
      show-check-boxes-mode="always"
      mode="multiple"
    />
    <dx-sorting mode="multiple" />
    <dx-header-filter :visible="true" />

    <dx-column
      data-field="text"
      caption="Subject"
      :hiding-priority="7"
    >
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="company"
      caption="Company"
      :hiding-priority="6"
    >
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="priority"
      caption="Priority"
      :hiding-priority="4"
      cell-template="cellPriority"
      edit-cell-template="editCellPriority"
    >
      <dx-column-lookup :data-source="priorityList" />
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="startDate"
      caption="Start Date"
      data-type="date"
      :hiding-priority="2"
    >
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="dueDate"
      caption="Due Date"
      data-type="date"
      sort-order="asc"
      :hiding-priority="1"
    >
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="owner"
      caption="Owner"
      :hiding-priority="5"
    >
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="status"
      caption="Status"
      :hiding-priority="3"
      :min-width="120"
      cell-template="cellStatus"
      edit-cell-template="editCellStatus"
    >
      <dx-column-lookup :data-source="statusList" />
      <dx-required-rule />
    </dx-column>

    <template #cellPriority="{ data }">
      <status-indicator
        :show-bar="true"
        :value="data?.data?.priority || ''"
      />
    </template>

    <template #editCellPriority="{ data: cellData }">
      <dx-select-box
        class="edit-cell"
        :value="cellData?.value"
        :items="priorityList"
        @value-changed="(e) => onPrioritySelectChange(e.value, cellData)"
        @selection-changed="cellData.component.updateDimensions"
        field-template="field"
      >
        <template #field>
          <div class="form-custom-list-prop">
            <status-indicator
              :show-bar="true"
              :is-field="true"
              :value="cellData.value"
            />
          </div>
        </template>
        <template #item="{ data }">
          <status-indicator
            :show-bar="true"
            :value="data"
          />
        </template>
      </dx-select-box>
    </template>

    <template #cellStatus="{ data }">
      <status-indicator :value="data.value" />
    </template>

    <template #editCellStatus="{ data: cellInfo }">
      <dx-select-box
        class="edit-cell"
        :value="cellInfo.value"
        :items="statusList"
        @value-changed="(e) => onStatusSelectChange(e.value, cellInfo)"
        @selection-changed="cellInfo.component.updateDimensions"
        field-template="field"
      >
        <template #field>
          <status-indicator
            :is-field="true"
            :value="cellInfo.value"
          />
        </template>
        <template #item="{data}">
          <status-indicator
            :value="data"
          />
        </template>
      </dx-select-box>
    </template>
  </dx-data-grid>
  <dx-load-panel
    :visible="props.isLoading"
    container=".content"
    :position="{ of: '.content' }"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import {
  DxDataGrid,
  DxColumn,
  DxHeaderFilter,
  DxLoadPanel,
  DxRequiredRule,
  DxSelection,
  DxScrolling,
  DxSorting,
  DxColumnLookup,
  DxPager,
  DxPaging,
  DxEditing,
} from 'devextreme-vue/data-grid';
import 'jspdf-autotable';
import { DxTextBox } from 'devextreme-vue/text-box';
import { DxSelectBox } from 'devextreme-vue/select-box';
import { jsPDF as JsPDF } from 'jspdf';
import { saveAs } from 'file-saver-es';
import { exportDataGrid as exportGridToPdf } from 'devextreme/pdf_exporter';
import { exportDataGrid as exportToXLSX } from 'devextreme/excel_exporter';

import { router } from '@/router';
import type { Task } from '@/types/task';
import type { RowPreparedEvent, RowClickEvent } from 'devextreme/ui/data_grid';
import { taskPriorityList as priorityList, taskStatusList as statusList } from '@/types/task';
import { Workbook } from 'exceljs';
import StatusIndicator from '@/components/status-indicator.vue';

const props = withDefaults(defineProps<{
  dataSource: Task[] | null
}>(), {
  dataSource: () => null,
});

const dxDataGridCmp = ref<InstanceType<typeof DxDataGrid> | null>(null);
const navigation = ref<boolean>(true);

const onRowPreparedGrid = (e: RowPreparedEvent<Task, number>) => {
  const { rowType, rowElement, data } = e;

  if (rowType === 'header') return;

  if (data.status === 'Completed') {
    rowElement.classList.add('completed');
  }
};

const navigateToDetails = (e: RowClickEvent) => {
  if(navigation.value && e.rowType !== 'detailAdaptive') {
    router.push('/planning-task-details');
  }
};

const onEditingStart = () {
  navigation.value = false;
}

const onEditEnd = () {
  navigation.value = true;
};

const addRow = () => dxDataGridCmp.value?.instance.addRow();
const onPrioritySelectChange = (value: string, cellData: Record<string, any>) => {
  cellData.setValue(value);
  cellData.component.refresh();
  cellData.component.focus();
};

const onStatusSelectChange = (value: string, cellInfo: Record<string, any>) => {
  cellInfo.setValue(value);
  cellInfo.component.refresh();
};

const exportToPdf = () => {
  const doc = new JsPDF();
  exportGridToPdf({
    jsPDFDocument: doc,
    component: dxDataGridCmp.value.instance,
  }).then(() => {
    doc.save('Tasks.pdf');
  });
};

const exportToXlsx = () => {
  const workbook = new Workbook();
  const worksheet = workbook.addWorksheet('Tasks');

  exportToXLSX({
    component: dxDataGridCmp.value.instance,
    worksheet,
    autoFilterEnabled: true,
  }).then(() => {
    workbook.xlsx.writeBuffer().then((buffer) => {
      saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Tasks.xlsx');
    });
  });
};

defineExpose({
  addRow,
  exportToPdf,
  exportToXlsx,
  showColumnChooser() {
    dxDataGridCmp.value.instance.showColumnChooser();
  },
  search(text: string) {
    dxDataGridCmp.value.instance.searchByText(text);
  },
});
</script>

<style scoped lang="scss">
@use "@/variables" as *;
@use "sass:math";

#tasks-grid {
  min-height: 300px;

  :deep(.priority span) {
    font-size: 13px;
  }
}

:deep(.dx-row.completed) {
  background: $background-gray-color;
}

:deep(.edit-cell) {
  position: relative;

}
</style>
