// packages/angular/src/app/components/utils/sales-by-range-card/sales-by-range-card.component.ts
import { Component, Input } from '@angular/core';
import { CardAnalyticsComponent } from '../../library/card-analytics/card-analytics.component';
import { DxPieChartModule } from 'devextreme-angular/ui/pie-chart';
import { DxChartModule } from 'devextreme-angular/ui/chart';
import { DxoValueAxisModule } from 'devextreme-angular/ui/nested';
import { SalesOrOpportunitiesByCategory } from 'src/app/types/analytics';

@Component({
    selector: 'sales-by-range-card',
    templateUrl: './sales-by-range-card.component.html',
    styleUrls: ['./sales-by-range-card.component.scss'],
    imports: [
      CardAnalyticsComponent,
      DxPieChartModule,
      DxChartModule,
      DxoValueAxisModule,
    ],
})
export class SalesByRangeCardComponent {
  @Input() data: SalesOrOpportunitiesByCategory;

  customizeSaleText(arg: { percentText: string }) {
    return arg.percentText;
  }
}


<card-analytics
  titleText="Sales by Date Range"
  contentClass="sales-by-category"
>
  <dx-pie-chart
    class="sales-pie"
    [dataSource]="data"
    type="doughnut"
    [diameter]="0.8"
    [innerRadius]="0.6"
  >
    <dxi-pie-chart-series argumentField="name" valueField="value">
      <dxo-pie-chart-label
        backgroundColor="none"
        [radialOffset]="-20"
        [visible]="true"
        [customizeText]="customizeSaleText"
      >
        <dxo-pie-chart-font color="#757575" [size]="15"></dxo-pie-chart-font>
      </dxo-pie-chart-label>
    </dxi-pie-chart-series>

    <dxo-pie-chart-legend>
      <dxo-pie-chart-margin [top]="70"></dxo-pie-chart-margin>
    </dxo-pie-chart-legend>

    <dxo-pie-chart-size [height]="270"></dxo-pie-chart-size>

    <dxo-pie-chart-legend [visible]="false"></dxo-pie-chart-legend>
  </dx-pie-chart>

  <dx-chart class="sales-bars" [dataSource]="data" [rotated]="true">
    <dxo-chart-common-axis-settings [visible]="false">
      <dxo-chart-tick [visible]="false"></dxo-chart-tick>
    </dxo-chart-common-axis-settings>

    <dxo-chart-legend [visible]="false"></dxo-chart-legend>

    <dxo-chart-common-series-settings
      argumentField="name"
      valueField="value"
      type="bar"
      [ignoreEmptyPoints]="true"
    >
    </dxo-chart-common-series-settings>

    <dxo-chart-series-template nameField="name"> </dxo-chart-series-template>

    <dxo-value-axis>
      <dxo-chart-label>
        <dxo-chart-format type="largeNumber"></dxo-chart-format>
      </dxo-chart-label>
    </dxo-value-axis>
  </dx-chart>
</card-analytics>

// packages/react/src/components/utils/sales-by-range-card/SalesByRangeCard.tsx
import React from 'react';
import PieChart, {
  Font,
  Label,
  Legend,
  Margin,
  Series,
  Size,
} from 'devextreme-react/pie-chart';
import Chart, {
  CommonAxisSettings,
  Tick,
  Legend as ChartLegend,
  CommonSeriesSettings,
  SeriesTemplate,
  ValueAxis,
  Label as ChartLabel,
  Format,
} from 'devextreme-react/chart';
import { CardAnalytics } from '../../library/card-analytics/CardAnalytics';
import { SaleOrOpportunityByCategory } from '../../../types/analytics';

type SalesByRangeCardProps = { datasource: SaleOrOpportunityByCategory[] };

export const SalesByRangeCard = React.memo<SalesByRangeCardProps>(
  ({ datasource }) => (
    <CardAnalytics title='Sales by Date Range' contentClass='sales-by-category'>
      <PieChart
        id='pie'
        className='sales-pie'
        dataSource={datasource}
        type='doughnut'
        diameter={0.8}
        innerRadius={0.6}
      >
        <Series argumentField='name' valueField='value'>
          <Label
            backgroundColor='none'
            radialOffset={-20}
            visible
            customizeText={(pointInfo) => pointInfo['percentText']}
          >
            <Font color='#757575' size={15} />
          </Label>
        </Series>
        <Legend visible={false}>
          <Margin top={70} />
        </Legend>
        <Size height={270} />
      </PieChart>
      <Chart id='bar' dataSource={datasource} className='sales-bars' rotated>
        <CommonAxisSettings visible={false}>
          <Tick visible={false} />
        </CommonAxisSettings>
        <ChartLegend visible={false} />
        <CommonSeriesSettings
          argumentField='name'
          valueField='value'
          type='bar'
          ignoreEmptyPoints
        />
        <SeriesTemplate nameField='name' />
        <ValueAxis>
          <ChartLabel>
            <Format type='largeNumber' />
          </ChartLabel>
        </ValueAxis>
      </Chart>
    </CardAnalytics>
  )
);
