// packages/react/src/components/library/card-menu/CardMenu.tsx
import React from 'react';
import { DropDownButton } from 'devextreme-react/ui/drop-down-button';

import './CardMenu.scss';

export const CardMenu = ({ items, visible = true }) => {
  return (
    <DropDownButton
      className='overflow-menu'
      items={items}
      visible={visible}
      icon='overflow'
      stylingMode='text'
      showArrowIcon={false}
      dropDownOptions={{ width: 'auto' }}
    />
  );
};

// packages/vue/src/components/card-menu.vue
<template>
  <drop-down-button
    :items="props.items"
    :visible="props.visible"
    icon="overflow"
    :show-arrow-icon="false"
    styling-mode="text"
    :drop-down-options="{ width: 'auto' }"
  />
</template>

<script setup lang="ts">
import DropDownButton from 'devextreme-vue/drop-down-button';

const props = withDefaults(defineProps<{
  items: Array<{ text: string }>,
  visible?: boolean
  }>(), {
  visible: true,
});
</script>
<style lang="scss">
</style>
