// packages/react/src/components/library/change-profile-password-form/ChangeProfilePasswordForm.tsx
import './ChangeProfilePasswordForm.scss';
import React, { useState, useCallback, useMemo, useRef } from 'react';
import notify from 'devextreme/ui/notify';
import { ValidationRule } from 'devextreme/ui/validation_rules';
import Form, { Item, Label } from 'devextreme-react/form';
import Validator from 'devextreme-react/validator';
import { FormPopup } from '../../utils/form-popup/FormPopup';
import { PasswordTextBox } from '../password-text-box/PasswordTextBox';
import { ValidationGroup } from 'devextreme-react';

interface FormData {
  currentPassword?: string,
  password?: string,
  confirmedPassword?: string
}

const saveNewPassword = (): void => {
  notify({ message: 'Password Changed', position: { at: 'bottom center', my: 'bottom center' } }, 'success');
};

export const ChangeProfilePasswordForm = ({ visible, setVisible }) => {
  const validationGroup = useRef<ValidationGroup>(null);
  const confirmField = useRef<Validator>(null);
  const [formData, setFormData] = useState<FormData>({});
  const [isSaveDisabled, setIsSaveDisabled] = useState(true);

  const confirmPasswordValidators = useMemo((): ValidationRule[] => {
    return [{
      type: 'compare',
      message: 'Passwords do not match',
      comparisonTarget: () => formData.password,
    }];
  }, [formData]);

  const onFieldChange = useCallback(
    () => {
      const formValues = Object.entries(formData);
      setIsSaveDisabled(
        formValues.length != 3 ||
        !!formValues.find(([, value]) => !value) ||
        !validationGroup.current?.instance.validate().isValid
      );
    }, [formData]);

  const checkConfirm = useCallback(() => {
    confirmField.current?.instance.validate();
  }, []);

  const onCurrentPasswordChange = useCallback((value) => {
    setFormData({
      ...formData,
      currentPassword: value
    });

    onFieldChange();
  }, []);

  const onConfirmPasswordChange = useCallback((value) => {
    setFormData({
      ...formData,
      confirmedPassword: value
    });

    onFieldChange();
  }, []);

  const onNewPasswordChange = useCallback((value) => {
    setFormData({
      ...formData,
      password: value
    });

    checkConfirm();
    onFieldChange();
  }, [checkConfirm, onFieldChange]);

  return <FormPopup
    validationGroup={validationGroup}
    title='Change Password'
    visible={visible}
    width={360}
    wrapperAttr={{ class: 'change-profile-password-popup' }}
    isSaveDisabled={isSaveDisabled}
    onSave={saveNewPassword}
    setVisible={setVisible}
  >
    <Form id='form'
      labelMode='outside'
      showColonAfterLabel
      labelLocation='top'>
      <Item>
        <Label text='Current Password' />
        <PasswordTextBox
          value={formData['currentPassword']}
          placeholder='Current Password'
          onValueChange={onCurrentPasswordChange}
        />
      </Item>

      <Item>
        <div className='h-separator' />
      </Item>

      <Item>
        <Label text='Password' />
        <PasswordTextBox
          value={formData['password']}
          placeholder='Password'
          onValueChange={onNewPasswordChange}
        />
      </Item>

      <Item>
        <Label text='Confirm Password' />
        <PasswordTextBox
          ref={confirmField}
          value={formData['confirmedPassword']}
          placeholder='Confirm Password'
          validators={confirmPasswordValidators}
          onValueChange={onConfirmPasswordChange}
        />
      </Item>
    </Form>
  </FormPopup>;
};

// packages/vue/src/components/change-profile-password-form.vue
<template>
  <form-popup
    title="Change Password"
    ref="formPopup"
    :visible="visible"
    :is-save-disabled="isSaveDisabled"
    @update:visible="changeVisibleState"
    :width="360"
    :wrapper-attr="{class: 'change-profile-password-popup'}"
    @save="saveNewPassword()"
  >
    <dx-form
      label-mode="outside"
      label-location="top"
      :show-colon-after-label="true"
    >
      <dx-item>
        <dx-label text="Current Password" />
        <password-text-box
          v-model="formData['currentPassword']"
          placeholder="Current Password"
          @value-changed="onFieldChanged()"
        />
      </dx-item>
      <dx-item>
        <div class="h-separator" />
      </dx-item>
      <dx-item>
        <dx-label text="Password" />
        <password-text-box
          v-model="formData['password']"
          placeholder="Password"
          @value-changed="onFieldChanged()"
        />
      </dx-item>
      <dx-item>
        <dx-label text="Confirm Password" />
        <password-text-box
          v-model="formData['confirmedPassword']"
          placeholder="Confirm Password"
          :validators="confirmPasswordValidators"
          @value-changed="onFieldChanged()"
        />
      </dx-item>
    </dx-form>
  </form-popup>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import notify from 'devextreme/ui/notify';
import { DxForm, DxItem, DxLabel } from 'devextreme-vue/form';
import FormPopup from '@/components/form-popup.vue';
import PasswordTextBox from '@/components/password-text-box.vue';
import { SimpleObject } from '@/types';
import { DxValidationRule } from 'devextreme-vue/validator';

withDefaults(defineProps<{
  visible: boolean,
}>(), {
  visible: false,
});

const formPopup = ref<InstanceType<typeof FormPopup> | null>(null);

const visibleState = ref(false);

const isSaveDisabled = ref(true);

const emit = defineEmits(['update:visible']);

const formData: SimpleObject = {};

const confirmPasswordValidators: (typeof DxValidationRule)[] = [
  {
    type: 'compare',
    message: 'Passwords do not match',
    comparisonTarget: () => formData.password,
  },
];

function changeVisibleState(value: boolean) {
  visibleState.value = value;
  emit('update:visible', value);
}

function onFieldChanged() {
  const formValues = Object.entries(formData);

  isSaveDisabled.value = !formPopup.value?.isValid() || formValues.length !== 3
    || !!formValues.find(([, value]) => !value);
}

function close() {
  emit('update:visible', false);
}

function saveNewPassword() {
  notify({ message: 'Password Changed', position: { at: 'bottom center', my: 'bottom center' } }, 'success');
  close();
}
</script>
<style lang="scss">
.change-profile-password-popup {
  .dx-form {
    padding: 0 8px;
  }

  .dx-popup-normal {
    border-radius: 8px;
    padding: 8px 0;

    .dx-toolbar {
      padding: 0 24px 8px;
    }
  }
}
</style>
