// packages/angular/src/app/components/contact-form/contact-form.component.ts
import {
  Component, NgModule, Input,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxFormModule,
  DxLoadPanelModule,
  DxNumberBoxModule,
  DxSelectBoxModule,
  DxTextBoxModule,
  DxToolbarModule,
  DxValidatorModule,
  DxValidationGroupModule,
} from 'devextreme-angular';
import {
  ContactStatusModule,
  FormTextboxModule,
  FormPhotoModule,
  StatusSelectBoxModule,
} from 'src/app/components';
import { Contact } from 'src/app/types/contact';
import { ValidationRule } from 'devextreme/ui/validation_rules';
import { ClickEvent } from 'devextreme/ui/button';

@Component({
  selector: 'contact-form',
  templateUrl: './contact-form.component.html',
  styleUrls: ['./contact-form.component.scss'],
})
export class ContactFormComponent {
  @Input() contactData: Contact;

  @Input() isLoading: boolean;

  savedData: Contact = null;

  isEditing = false;

  zipCodeValidator: ValidationRule = { type: 'pattern', pattern: /^\d{5}$/, message: 'Zip is invalid' };

  handleEditClick() {
    this.savedData = { ...this.contactData };
    this.isEditing = true;
  }

  handleSaveClick({ validationGroup }: ClickEvent) {
    if(!validationGroup.validate().isValid) return;
    this.isEditing = false;
    this.savedData = null;
  }

  handleCancelClick() {
    this.contactData = { ...this.savedData };
    this.isEditing = false;
  }
}

@NgModule({
  imports: [
    DxToolbarModule,
    DxFormModule,
    DxSelectBoxModule,
    DxButtonModule,
    DxTextBoxModule,
    DxNumberBoxModule,
    DxLoadPanelModule,
    DxValidationGroupModule,

    FormTextboxModule,
    ContactStatusModule,
    FormPhotoModule,
    DxValidatorModule,
    CommonModule,
    StatusSelectBoxModule,
  ],
  providers: [],
  exports: [ContactFormComponent],
  declarations: [ContactFormComponent],
})
export class ContactFormModule { }

<div id="contact-form">
  <dx-validation-group>
    <dx-toolbar>
      <dxi-item location="before"><span class="form-title">Details</span></dxi-item>
      <dxi-item location="after" locateInMenu="after" [visible]="!isEditing">
        <dx-button
          text="Edit"
          icon="edit"
          stylingMode="outlined"
          type="default"
          (onClick)="handleEditClick()"
        ></dx-button>
      </dxi-item>
      <dxi-item location="after" locateInMenu="after" [visible]="isEditing">
        <dx-button
          text="Save"
          stylingMode="outlined"
          type="default"
          (onClick)="handleSaveClick($event)"
        ></dx-button>
      </dxi-item>
      <dxi-item location="after" locateInMenu="after" [visible]="isEditing">
        <dx-button
          text="Cancel"
          (onClick)="handleCancelClick()"
          stylingMode="text"
        ></dx-button>
      </dxi-item>
    </dx-toolbar>

    <dx-form *ngIf="contactData"
              class="form last plain-styled-form"
              [formData]="contactData"
              labelMode="floating"
              [class.view-mode]="!isEditing">
      <dxi-item itemType="group" [colCount]="2">
        <dxo-col-count-by-screen [xs]="2"></dxo-col-count-by-screen>
        <dxi-item>
          <div *dxTemplate>
            <form-photo
              [link]="contactData.image"
              [size]="184"
            ></form-photo>
          </div>
        </dxi-item>
        <dxi-item itemType="group">
          <dxi-item>
            <status-select-box *dxTemplate
                               [(value)]="contactData.status"
                               [readOnly]="!isEditing"
                               stylingMode="filled"
            ></status-select-box>
          </dxi-item>

          <dxi-item>
            <form-textbox *dxTemplate
                          label="First Name"
                          [(value)]="contactData.firstName"
                          [isEditing]="isEditing"
            ></form-textbox>
          </dxi-item>

          <dxi-item>
            <form-textbox *dxTemplate
                          label="Last Name"
                          [(value)]="contactData.lastName"
                          [isEditing]="isEditing"
            ></form-textbox>
          </dxi-item>
        </dxi-item>

        <dxi-item>
          <form-textbox *dxTemplate
                        label="Position"
                        [(value)]="contactData.position"
                        [isEditing]="isEditing"
          ></form-textbox>
        </dxi-item>

        <dxi-item cssClass="accent">
          <form-textbox *dxTemplate
                        label="Assigned to"
                        [(value)]="contactData.manager"
                        [isEditing]="isEditing"
          ></form-textbox>
        </dxi-item>

        <dxi-item cssClass="accent" [colSpan]="2">
          <form-textbox *dxTemplate
                        label="Company"
                        [(value)]="contactData.company"
                        [isEditing]="isEditing"
          ></form-textbox>
        </dxi-item>
      </dxi-item>

      <dxi-item itemType="group" [colCount]="4" caption="Contacts">
        <dxo-col-count-by-screen [xs]="2"></dxo-col-count-by-screen>
        <dxi-item [colSpan]="4">
          <form-textbox *dxTemplate
                        label="Address"
                        [(value)]="contactData.address"
                        [isEditing]="isEditing"></form-textbox>
        </dxi-item>

        <dxi-item  [colSpan]="2">
          <form-textbox *dxTemplate
                        label="City"
                        [(value)]="contactData.city"
                        [isEditing]="isEditing"></form-textbox>
        </dxi-item>

        <dxi-item>
          <form-textbox *dxTemplate
                        label="State"
                        [(value)]="contactData.state.stateShort"
                        [isEditing]="isEditing"></form-textbox>
        </dxi-item>

        <dxi-item>
          <dx-number-box  *dxTemplate
                          label="Zip Code"
                          [(value)]="contactData.zipCode"
                          [readOnly]="!isEditing"
                          [elementAttr]="{class: 'form-editor'}"
                          [inputAttr]="{class: 'form-editor-input'}"
                          stylingMode="filled"
                          valueChangeEvent="keyup input change">
            <dx-validator [validationRules]="[zipCodeValidator]"></dx-validator>
          </dx-number-box>
        </dxi-item>
      </dxi-item>

      <dxi-item itemType="group" [colCount]="2" cssClass="contact-fields-group">
        <dxo-col-count-by-screen [xs]="2"></dxo-col-count-by-screen>
        <dxi-item>
          <div *dxTemplate>
            <form-textbox label="Phone"
                          [(value)]="contactData.phone"
                          [isEditing]="isEditing"
                          mask="+1(000)000-0000"
                          [validators]="[]"
            ></form-textbox>
            <dx-button class="form-item-button"
                       [visible]="!isEditing"
                       [text]="'Call'"
                       [icon]="'tel'"
                       [type]="'default'"
                       stylingMode="outlined"
            ></dx-button>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <form-textbox label="Email"
                        [(value)]="contactData.email"
                        [isEditing]="isEditing"
                        [validators]="[{type: 'email'}]"
            ></form-textbox>
            <dx-button class="form-item-button"
                      [visible]="!isEditing"
                      [text]="'Send Email'"
                      [icon]="'email'"
                      [type]="'default'"
                      stylingMode="outlined"
            ></dx-button>
          </div>
        </dxi-item>
      </dxi-item>
    </dx-form>
  </dx-validation-group>
  <dx-load-panel
    container="#contact-form"
    [position]="{ of: '#contact-form' }"
    [visible]="!contactData || isLoading"
    [showPane]="false"
  ></dx-load-panel>
</div>

// packages/vue/src/components/contact-form.vue
<template>
  <div id="contact-form">
    <dx-validation-group>
      <dx-toolbar>
        <dx-toolbar-item location="before">
          <span class="dx-form-group-caption">Details</span>
        </dx-toolbar-item>
        <dx-toolbar-item
          location="after"
          locate-in-menu="after"
          :visible="!isEditing"
        >
          <dx-button
            text="Edit"
            icon="edit"
            styling-mode="outlined"
            type="default"
            @click="startEdit()"
          />
        </dx-toolbar-item>
        <dx-toolbar-item
          location="after"
          locate-in-menu="after"
          :visible="isEditing"
        >
          <dx-button
            text="Save"
            styling-mode="outlined"
            type="default"
            @click="handleSaveClick"
          />
        </dx-toolbar-item>
        <dx-toolbar-item
          location="after"
          locate-in-menu="after"
          :visible="isEditing"
        >
          <dx-button
            text="Cancel"
            @click="cancelEdit()"
            styling-mode="text"
          />
        </dx-toolbar-item>
      </dx-toolbar>
      <load-component
        :is-loading="isLoading"
        :container-selector="'#contact-form'"
        :show-content="!!props.contactData"
      >
        <dx-form
          class="plain-styled-form dx-form"
          :class="{'view-mode': !isEditing}"
        >
          <dx-form-group-item :col-count="2">
            <dx-col-count-by-screen :xs="2" />
            <dx-form-item>
              <form-photo
                :link="contactData.image"
                :size="184"
              />
            </dx-form-item>

            <dx-form-group-item>
              <dx-form-item>
                <status-select-box
                  v-model="contactData.status"
                  :items="contactStatusList"
                  :read-only="!isEditing"
                  styling-mode="filled"
                />
              </dx-form-item>

              <dx-form-item>
                <form-textbox
                  label="First Name"
                  v-model="contactData.firstName"
                  :is-editing="isEditing"
                />
              </dx-form-item>

              <dx-form-item>
                <form-textbox
                  label="Last Name"
                  v-model="contactData.lastName"
                  :is-editing="isEditing"
                />
              </dx-form-item>
            </dx-form-group-item>

            <dx-form-item>
              <form-textbox
                label="Position"
                v-model="contactData.position"
                :is-editing="isEditing"
              />
            </dx-form-item>

            <dx-form-item css-class="accent">
              <form-textbox
                label="Assigned to"
                v-model="contactData.manager"
                :is-editing="isEditing"
              />
            </dx-form-item>

            <dx-form-item
              :col-span="2"
              css-class="accent"
            >
              <form-textbox
                label="Company"
                v-model="contactData.company"
                :is-editing="isEditing"
              />
            </dx-form-item>
          </dx-form-group-item>

          <dx-form-group-item
            :col-count="4"
            caption="Contacts"
          >
            <dx-col-count-by-screen :xs="2" />
            <dx-form-item :col-span="4">
              <form-textbox
                label="Address"
                v-model="contactData.address"
                :is-editing="isEditing"
              />
            </dx-form-item>
            <dx-form-item :col-span="2">
              <form-textbox
                label="City"
                v-model="contactData.city"
                :is-editing="isEditing"
              />
            </dx-form-item>

            <dx-form-item>
              <form-textbox
                label="State"
                v-model="contactData.state.stateShort"
                :is-editing="isEditing"
              />
            </dx-form-item>
            <dx-form-item>
              <dx-number-box
                label="Zip Code"
                v-model.number="contactData.zipCode"
                :is-editing="isEditing"
                v-bind="formEditorProps"
              >
                <dx-validator :validation-rules="[zipCodeValidator]" />
              </dx-number-box>
            </dx-form-item>
          </dx-form-group-item>
          <dx-form-group-item
            :col-count="2"
            css-class="contact-fields-group"
          >
            <dx-col-count-by-screen :xs="2" />
            <dx-form-item>
              <form-textbox
                label="Phone"
                v-model.number="contactData.phone"
                :is-editing="isEditing"
                mask="+1(000)000-0000"
              />
              <dx-button
                v-if="!isEditing"
                class="form-item-button"
                v-bind="{
                  text: 'Call',
                  icon: 'tel',
                  type: 'default',
                  stylingMode: 'outlined'
                }"
                :validators="[]"
              />
            </dx-form-item>
            <dx-form-item>
              <form-textbox
                label="Email"
                v-model.number="contactData.email"
                :is-editing="isEditing"
                :validators="[{type: 'email'}]"
              />
              <dx-button
                v-if="!isEditing"
                class="form-item-button"
                v-bind="{
                  text: 'Send Email',
                  icon: 'email',
                  type: 'default',
                  stylingMode: 'outlined'
                }"
              />
            </dx-form-item>
          </dx-form-group-item>
        </dx-form>
      </load-component>
    </dx-validation-group>
  </div>
</template>
<script setup lang="ts">
import { ref, watch } from 'vue';

import { DxButton } from 'devextreme-vue/button';
import {
  DxToolbar,
  DxItem as DxToolbarItem,
} from 'devextreme-vue/toolbar';

import {
  DxForm,
  DxItem as DxFormItem,
  DxGroupItem as DxFormGroupItem,
  DxColCountByScreen,
} from 'devextreme-vue/form';
import { DxNumberBox } from 'devextreme-vue/number-box';
import { DxValidator } from 'devextreme-vue/validator';
import { DxValidationGroup } from 'devextreme-vue/validation-group';
import { ClickEvent } from 'devextreme/ui/button';
import { formEditorProps } from '@/shared/form-editor-config';
import LoadComponent from '@/components/load-component.vue';
import { Contact, contactStatusList } from '@/types/contact';
import FormPhoto from '@/components/form-photo.vue';
import FormTextbox from '@/components/form-textbox.vue';
import StatusSelectBox from '@/components/status-select-box.vue';

const emptyContact = { state: { stateShort: '' } } as Contact;

const props = withDefaults(defineProps<{
  isLoading: boolean,
  contactData: Contact | null
}>(), {
  isLoading: true,
  contactData: null,
});

const isEditing = ref(false);
const contactData = ref(emptyContact);

let contactDataSaved = emptyContact;
const zipCodeValidator = { type: 'pattern', pattern: /^\d{5}$/, message: 'Zip is invalid' };

watch(
  () => props.contactData,
  (contactDataNew: Contact| null) => {
    contactData.value = contactDataNew || emptyContact;
  },
);

function startEdit() {
  contactDataSaved = { ...contactData.value };
  isEditing.value = true;
}

function handleSaveClick({ validationGroup }: ClickEvent) {
  if (validationGroup.validate().isValid) {
    isEditing.value = false;
  }
}

function cancelEdit() {
  contactData.value = contactDataSaved;
  isEditing.value = false;
}
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

#contact-form {
  min-height: 300px;

  .form-title {
    font-size: 16px;
  }

  .dx-toolbar {
    margin-bottom: $toolbar-margin-bottom;
  }
}

.info {
  position: relative;
  padding-bottom: 30px;
}
</style>
