// packages/angular/src/app/shared/components/form-item-with-button/form-item-with-button.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  EventEmitter,
  Input,
  NgModule,
  Output,
} from '@angular/core';
import {
  DxButtonModule,
  DxTextBoxModule,
} from 'devextreme-angular';
import { Properties as DxTextBoxOptions } from 'devextreme/ui/text_box';
import { Properties as DxButtonOptions } from 'devextreme/ui/button';

@Component({
  selector: 'form-item-with-button',
  templateUrl: './form-item-with-button.component.html',
  styles: [`
  .dx-button {
    margin-top: 10px;
  }
  `],
})
export class FormItemWithButtonComponent {
  @Input() value: string;

  @Output() valueChange = new EventEmitter();

  @Input() textBoxOptions?: DxTextBoxOptions = {};

  @Input() buttonOptions?: DxButtonOptions = {};

  @Input() isEditing? = true;
}

@NgModule({
  imports: [
    DxButtonModule,
    DxTextBoxModule,

    CommonModule,
  ],
  declarations: [FormItemWithButtonComponent],
  exports: [FormItemWithButtonComponent],
})
export class FormItemWithButtonModule { }

<dx-text-box
    [(value)]="value"
    [label]="textBoxOptions.label"
    [readOnly]="!isEditing"
    [stylingMode]="textBoxOptions.stylingMode"
    [mask]="textBoxOptions.mask"
></dx-text-box>
<dx-button
    [visible]="!isEditing"
    [text]="buttonOptions.text"
    [icon]="buttonOptions.icon"
    [type]="buttonOptions.type"
    [stylingMode]="buttonOptions.stylingMode"
></dx-button>

// packages/vue/src/components/form-item-with-button.vue
<template>
  <dx-text-box
               :value="props.data[props.dataField]"
               :label="props.textBoxOptions.label"
               :stylingMode="props.textBoxOptions.stylingMode"
               :mask="props.textBoxOptions.mask"
               :readOnly="!props.isEditing"
               @value-changed="e => {
                 /* eslint-disable-next-line vue/no-mutating-props */
                 props.data[props.dataField] = e.value}"
  ></dx-text-box>

  <dx-button
    v-if="!props.isEditing"
    :text="props.buttonOptions.text"
    :icon="props.buttonOptions.icon"
    :type="props.buttonOptions.type"
    :stylingMode="props.buttonOptions.stylingMode"
  ></dx-button>
</template>

<script setup lang="ts">
import { DxTextBox } from 'devextreme-vue/text-box';
import { DxButton } from 'devextreme-vue/button';

const props = withDefaults(defineProps<{
      data: {[key:string]: unknown},
      dataField: string,
      isEditing: boolean,
      textBoxOptions: {[key:string]: unknown},
      buttonOptions: {[key:string]: unknown},
    }>(), {
  data: () => ({}),
  dataField: '',
  isEditing: false,
  textBoxOptions: () => ({}),
  buttonOptions: () => ({}),
});

</script>

<style scoped lang="scss">
.dx-button {
  margin-top: 10px;
}
</style>
