// packages/angular/src/app/shared/components/form-photo/form-photo.component.ts
import { CommonModule } from '@angular/common';
import {
  Component, Input, NgModule, OnInit,
} from '@angular/core';

@Component({
  selector: 'form-photo',
  template: `
  <div
    [ngStyle]="{
      'width.px': size,
      'height.px': size,
      'background-image': imageUrl
    }"
    class="photo dx-card"
    [style.backgroundImage]="imageUrl"
  ></div>
`,
  styles: [`
    :host{
      position: relative;
      display: flex;
    }
    .photo {
      border-radius: 8px;
      background-repeat: no-repeat;
      background-size: cover;
    }
  `],
})
export class FormPhotoComponent implements OnInit {
  @Input() link: string;

  @Input() size?: number = 124;

  imageUrl: string;

  ngOnInit() {
    this.imageUrl = `url('data:image/png;base64,${this.link}')`;
  }
}

@NgModule({
  imports: [CommonModule],
  declarations: [FormPhotoComponent],
  exports: [FormPhotoComponent],
})
export class FormPhotoModule { }

// packages/vue/src/components/form-photo.vue
<template>
  <div class="host">
    <div
      :style="{
        width: props.size + 'px',
        height: props.size+ 'px',
        maxHeight: props.size+ 'px',
        'backgroundImage': `url('data:image/png;base64,${props.link}')`
      }"
      class="photo"
    />
  </div>
</template>

<script setup lang="ts">
const props = withDefaults(defineProps<{
  link: string,
  size?: number
}>(), {
  size: 124,
  link: '',
});
</script>

<style scoped lang="scss">
@use "@/variables" as *;

.host {
  position: relative;
  display: flex;

  .photo {
    border-radius: 8px;
    background-repeat: no-repeat;
    background-size: cover;
    border: 1px solid $border-color;
  }
}
</style>
