// packages/angular/src/app/components/utils/form-photo-uploader/form-photo-uploader.component.ts
import { CommonModule } from '@angular/common';
import {
  Component, NgModule,
} from '@angular/core';
import { DxFileUploaderModule } from 'devextreme-angular/ui/file-uploader';

@Component({
  selector: 'form-photo-uploader',
  template: `
    <div 
      id="uploader"
      [ngClass]="
        isDropZoneActive
          ? ['dx-theme-accent-as-border-color']
          : ['dx-theme-border-color']
      "
    >
      <span>Drag and drop a photo here or click the area to select it from a folder</span>
    </div>
    <dx-file-uploader
      accept="image/*"
      uploadMode="instantly"
      dialogTrigger="#uploader"
      dropZone="#uploader"
      [multiple]="false"
      [showFileList]=false
      [visible]="false"
      (onDropZoneEnter)="onDropZoneEnter($event)"
      (onDropZoneLeave)="onDropZoneLeave($event)"
    ></dx-file-uploader>
`,
  styles: [`
    #uploader {
      background-color: rgba(183, 183, 183, 0.1);
      border-width: 2px;
      border-style: dashed;
      border-radius: 8px;
      padding: 10px;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      height: 124px;
      user-select: none;
      line-height: inherit;
      margin-bottom: 10px;

      & > span {
        font-weight: 100;
        opacity: 0.5;
        text-align: center;
      }
    }
  `],
})
export class FormPhotoUploaderComponent { 
  isDropZoneActive = false;

  onDropZoneEnter(e) {
    if (e.dropZoneElement.id === 'uploader') { this.isDropZoneActive = true; }
  }

  onDropZoneLeave(e) {
    if (e.dropZoneElement.id === 'uploader') { this.isDropZoneActive = false; }
  }
}

@NgModule({
  imports: [CommonModule, DxFileUploaderModule],
  declarations: [FormPhotoUploaderComponent],
  exports: [FormPhotoUploaderComponent],
})
export class FormPhotoUploaderModule { }

// packages/vue/src/components/form-photo-uploader.vue
<template>
  <div
    id="dropzone"
    ref="dropzone"
    :class="isDropZoneActive
      ? 'dx-theme-accent-as-border-color'
      : 'dx-theme-border-color'
    "
  >
    <span>Drag and drop a photo here or click the area to select it from a folder</span>
  </div>
  <dx-file-uploader
    :drop-zone="dropzone"
    :dialog-trigger="dropzone"
    :multiple="false"
    :show-file-list="false"
    :visible="false"
    accept="image/*"
    upload-mode="instantly"
    @drop-zone-enter="onDropZoneEnter"
    @drop-zone-leave="onDropZoneLeave"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { DxFileUploader } from 'devextreme-vue/file-uploader';

const isDropZoneActive = ref(false);
const dropzone = ref<InstanceType<typeof HTMLElement>>();

const onDropZoneEnter = (e: {dropZoneElement: HTMLElement}) => {
  if (e.dropZoneElement === dropzone.value) { isDropZoneActive.value = true; }
};

const onDropZoneLeave = (e: {dropZoneElement: HTMLElement}) => {
  if (e.dropZoneElement === dropzone.value) { isDropZoneActive.value = false; }
};
</script>

<style scoped lang="scss">
#dropzone {
  background-color: rgba(183, 183, 183, 0.1);
  border-width: 2px;
  border-style: dashed;
  border-radius: 8px;
  padding: 10px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 124px;
  user-select: none;
  line-height: inherit;
  margin-bottom: 10px;

  & > span {
    font-weight: 100;
    opacity: 0.5;
    text-align: center;
  }
}
</style>
