// packages/angular/src/app/shared/components/form-textbox/form-textbox.component.ts
import {Component, EventEmitter, Input, NgModule, Output} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxTextBoxModule,
  DxValidatorModule
} from "devextreme-angular";

@Component({
  selector: 'form-textbox',
  templateUrl: './form-textbox.component.html',
  styleUrls: ['form-textbox.component.scss'],
})
export class FormTextboxComponent {
  @Input() isEditing = false;

  @Input() text: string;

  @Input() label = '';

  @Input() mask: string = null;

  @Input() icon: string = null;

  @Input() validationGroup: string = undefined;

  @Input() validators: any[] = [];

  @Input() value!: string;

  @Output() valueChange: EventEmitter<string> = new EventEmitter();

}

@NgModule({
  imports: [
    DxButtonModule,
    DxTextBoxModule,
    DxValidatorModule,
    CommonModule,
  ],
  declarations: [FormTextboxComponent],
  exports: [FormTextboxComponent],
})
export class FormTextboxModule { }

<dx-text-box [label]="label"
             [(value)]="value"
             [readOnly]="!isEditing"
             [mask]="mask"
             [elementAttr]="{class: 'form-editor'}"
             [inputAttr]="{class: 'form-editor-input'}"
             stylingMode="filled"
             valueChangeEvent="keyup input change"
>
  <dx-validator [validationRules]="validators || [{type: 'required'}]" [validationGroup]="validationGroup"></dx-validator>
  <dxi-button *ngIf="icon"
              [options]="{icon: icon, type: 'back', elementAttr: { class: 'form-editor-icon' }}"
              name="icon"
              location="before"
  ></dxi-button>
</dx-text-box>

// packages/vue/src/components/form-textbox.vue
<template>
  <dx-text-box :label="label"
               v-model="value"
               :readOnly="!isEditing"
               :mask="mask"
               :elementAttr="{class: 'form-editor'}"
               :inputAttr="{class: 'form-editor-input'}"
               stylingMode="filled"
               valueChangeEvent="keyup input change"
  >
    <dx-validator :validationRules="validators || [{type: 'required'}]"
                  :validationGroup="validationGroup"/>
    <dx-text-box-button v-if="icon"
                :options="{icon: icon, type: 'back', elementAttr: { class: 'form-editor-icon' }}"
                name="icon"
                location="before"
    ></dx-text-box-button>
  </dx-text-box>
</template>

<script setup lang="ts">
import { DxTextBox, DxButton as DxTextBoxButton } from 'devextreme-vue/text-box';
import { DxValidator } from 'devextreme-vue/validator';
import { computed } from 'vue';

const props = defineProps<{
  modelValue?: number | string | Date,
  isEditing: boolean,
  label?: string,
  icon?: string,
  mask?: string,
  validationGroup?: string,
  validators?: Record<string, any>[],
}>();
const emit = defineEmits(['update:modelValue']);

const value = computed({
  get() {
    return props.modelValue;
  },
  set(newValue) {
    emit('update:modelValue', newValue);
  },
});
</script>
<style scoped lang="scss">
@use "@/variables" as *;

.dx-texteditor.form-editor :deep(.form-editor-icon:first-child) {
  margin-left: 0;
  pointer-events: none;
  border-color: transparent;
  background-color: transparent;
}
</style>
