// packages/react/src/components/pictured-item-select-box/PicturedItemSelectBox.tsx
import './PicturedItemSelectBox.scss';
import React from 'react';
import SelectBox from 'devextreme-react/select-box';
import TextBox from 'devextreme-react/text-box';

const fieldRender = (data) => {
  return <div
    className='pictured-item-select-field'>
    <img alt={data.name}
      className='pictured-item-image'
      src='data:image/png;base64,{{data.image}}'
    />
    <TextBox
      hoverStateEnabled={false}
      inputAttr={{ class: 'pictured-item-editor-input' }}
      readOnly
      value={data.name}
    />
  </div>;
};

const ItemRender = (data) => {
  return <div>
    <img alt='data.name'
      className='pictured-item-image'
      height='20px'
      src='data:image/png;base64,{{data.image}}' />
    {data.name}
  </div>;
};

export const PicturedItemSelectBox = ({ value, label = '', items = [], onValueChange }) => {
  return <SelectBox
    className='pictured-item-select-box'
    value={value}
    onValueChange={onValueChange}
    label={label}
    items={items}
    itemRender={ItemRender}
    valueExpr='name'
    stylingMode='outlined'
    labelMode='hidden'
    width='100%'
    fieldTemplate={fieldRender}
    dropDownOptions={{ wrapperAttr: { class: 'pictured-item-select-box-dropdown' } }}
  />;
};

// packages/vue/src/components/pictured-item-select-box.vue
<template>
  <dx-select-box
    class="pictured-item-select-box"
    :label="label"
    :value="modelValue"
    :items="items"
    :drop-down-options="{wrapperAttr: {class: 'pictured-item-select-box-dropdown'}}"
    value-expr="name"
    styling-mode="outlined"
    label-mode="hidden"
    width="100%"
    field-template="field"
    @value-changed="emitChangedValue"
  >
    <template #field="{ data }">
      <div class="pictured-item-select-field">
        <img
          v-if="modelValue"
          :alt="data?.name"
          class="pictured-item-image"
          :src="`data:image/png;base64,${data?.image}`"
        >
        <dx-text-box
          :hover-state-enabled="false"
          :input-attr="{class: 'pictured-item-editor-input'}"
          :read-only="true"
          :value="data?.name"
        />
      </div>
    </template>

    <template #item="{ data }">
      <div>
        <img
          :alt="data?.name"
          class="pictured-item-image"
          :src="`data:image/png;base64,${data?.image}`"
        >
        {{ data?.name }}
      </div>
    </template>
  </dx-select-box>
</template>

<script setup lang="ts">
import { DxSelectBox } from 'devextreme-vue/select-box';
import { DxTextBox } from 'devextreme-vue/text-box';
import { SimpleObject } from '@/types';

withDefaults(defineProps<{
  label: string,
  modelValue: string,
  items: Record<string, unknown>[]
}>(), {});

const emit = defineEmits(['update:modelValue']);

function emitChangedValue(changedData: SimpleObject) {
  emit('update:modelValue', changedData.value);
}
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

:global(.pictured-item-select-box-dropdown .pictured-item-image),
.pictured-item-select-box .pictured-item-image {
  flex: 0 0 2em;
  width: 2em;
  height: 2em;
  border: 1px solid $border-color;
  border-radius: 50%;
  margin-right: 8px;
}

:global(.pictured-item-select-box-dropdown .dx-list-item-content),
.pictured-item-select-field {
  display: flex;
  align-items: center;
}

.pictured-item-select-field {
  :deep(.pictured-item-editor-input) {
    padding-left: 0;
  }

  .pictured-item-image {
    margin-left: var(--list-padding-left);
  }
}
</style>
