// packages/angular/src/app/components/library/status-indicator/status-indicator.component.ts
import { CommonModule } from '@angular/common';
import {
  Component, Input, OnInit,
} from '@angular/core';
import { TaskStatus, TaskPriority } from 'src/app/types/task';
import { DxTextBoxModule } from 'devextreme-angular/ui/text-box';

@Component({
  selector: 'status-indicator',
  template: `
    <div
      [ngClass]="{'input-with-bar': showBar }"
      class="
      status
      status-indicator
      status-indicator-{{ dashValue }}">
      @if (!isField) {
        <span class="status-indicator-{{ dashValue }}">{{ getValue(value) }}</span>
      }
      @if (isField) {
        <dx-text-box
          class="status-indicator-{{ dashValue }}"
          [inputAttr]="{class: 'status-input status-editor-input'}"
          [hoverStateEnabled]="false"
          [readOnly]="true"
          [value]="getValue(value)">
        </dx-text-box>
      }
    </div>
  `,
  styleUrls: ['./status-indicator.component.scss'],
  imports: [
    CommonModule,
    DxTextBoxModule,
  ]
})
export class StatusIndicatorComponent implements OnInit {
  @Input() value!: TaskStatus | TaskPriority;

  @Input() isField = true;

  @Input() showBar = false;

  dashValue = '';

  ngOnInit() {
    this.dashValue = this.spaceToDash(this.value).toLowerCase();
  }

  getValue(value: string): string {
    return (this.showBar ? '| ' : '') + value;
  }

  spaceToDash = (value: TaskStatus) =>
    (value?.replace(/ /g, '-') || '');
}

// packages/vue/src/components/status-indicator.vue
<template>
  <div
    :class="[{ 'input-with-bar': props.showBar }, 'status-indicator-' + statusClass]"
    class="status status-indicator"
  >
    <span
      v-if="!props.isField"
      :class="['status-indicator-' + statusClass]"
    >{{ getValue() }}
    </span>
    <dx-text-box
      v-if="props.isField"
      :class="['status-indicator-' + statusClass]"
      :input-attr="{ class: 'status-input status-editor-input' }"
      :hover-state-enabled="false"
      :read-only="true"
      :value="getValue()"
    />
  </div>
</template>
<script setup lang="ts">
import { DxTextBox } from 'devextreme-vue/text-box';
import { computed } from 'vue';

const props = withDefaults(
  defineProps<{
    value: string,
    showBar?: boolean,
    isField?: boolean,
  }>(),
  {
    value: '',
    showBar: false,
    isField: false,
  },
);

const statusClass = computed(() => props.value.replace(/\s+/g, '-').toLowerCase());

function getValue(): string {
  return (props.showBar ? '| ' : '') + props.value;
}
</script>
<style scoped lang="scss">

.status {
  span {
    font-size: 13px;
  }
}
</style>
