// packages/react/src/components/utils/toolbar-form/ToolbarForm.tsx
import React from 'react';

import Toolbar, { Item } from 'devextreme-react/toolbar';
import Button from 'devextreme-react/button';

import './ToolbarForm.scss';

export const ToolbarForm = ({ editing, toggleEditing, onCancelClick, onSaveClick }: {
  editing: boolean, toggleEditing: () => void, onCancelClick: () => void, onSaveClick: (e) => void
}) => {
  return (
    <Toolbar className='toolbar-form'>
      <Item location='before'>
        <span className='dx-form-group-caption'>Details</span>
      </Item>
      <Item location='after' visible={!editing}>
        <Button text='Edit' icon='edit' stylingMode='contained' type='default' onClick={toggleEditing} />
      </Item>
      <Item location='after' visible={editing}>
        <Button text='Save' stylingMode='contained' type='default' onClick={onSaveClick} />
      </Item>
      <Item location='after' visible={editing}>
        <Button text='Cancel' stylingMode='outlined' type='normal' onClick={onCancelClick} />
      </Item>
    </Toolbar>
  );
};

// packages/angular/src/app/components/utils/toolbar-form/toolbar-form.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';
import { DxButtonComponent } from "devextreme-angular";

@Component({
    selector: 'toolbar-form',
    templateUrl: './toolbar-form.component.html',
    styleUrls: ['./toolbar-form.component.scss'],
    imports: [
      DxToolbarModule,
      DxButtonComponent,
      CommonModule,
    ],
})
export class ToolbarFormComponent {
  @Input() isEditing: boolean;

  @Input() titleClass: string;

  @Output() editModeToggled = new EventEmitter();

  @Output() saveButtonClicked = new EventEmitter();

  @Output() editingCancelled = new EventEmitter();

  handleCancelEditClick () {
    this.editingCancelled.emit();
  }

  handleEditClick () {
    this.editModeToggled.emit();
  }

  handleSaveButtonClick (event) {
    this.saveButtonClicked.emit(event);
  }
}

<dx-toolbar>
  <dxi-toolbar-item location="before"
    ><span [class]="titleClass">Details</span>
  </dxi-toolbar-item>
  <dxi-toolbar-item location="after" locateInMenu="auto" [visible]="!isEditing">
    <dx-button
      text="Edit"
      icon="edit"
      stylingMode="contained"
      type="default"
      (onClick)="handleEditClick()"
    ></dx-button>
  </dxi-toolbar-item>
  <dxi-toolbar-item location="after" locateInMenu="auto" [visible]="isEditing">
    <dx-button
      text="Save"
      stylingMode="contained"
      type="default"
      (onClick)="handleSaveButtonClick($event)"
    ></dx-button>
  </dxi-toolbar-item>
  <dxi-toolbar-item location="after" locateInMenu="auto" [visible]="isEditing">
    <dx-button
      text="Cancel"
      (onClick)="handleCancelEditClick()"
      stylingMode="outlined"
      type="normal"
    ></dx-button>
  </dxi-toolbar-item>
</dx-toolbar>
