// packages/react/src/components/utils/form-textbox/FormTextbox.tsx
import React from 'react';

import TextBox, { Button as TextBoxButton } from 'devextreme-react/text-box';
import Validator, { RequiredRule } from 'devextreme-react/validator';
import './FormTextbox.scss';

type TextboxProps = {
  value: string,
  label?: string,
  isEditing: boolean,
  onValueChange: (data) => void,
  mask?: string,
  icon?: string,
}

export const FormTextbox = ({ value, label, isEditing, onValueChange, mask = '', icon, children }: React.PropsWithChildren<TextboxProps>) => {
  return (
    <TextBox
      label={label}
      value={value}
      mask={mask}
      readOnly={isEditing}
      elementAttr={{ class: 'form-editor' }}
      inputAttr={{ class: 'form-editor-input' }}
      stylingMode='filled'
      onValueChange={onValueChange}
    >
      { icon &&
      <TextBoxButton
        name='icon'
        location='before'
        options={{
          icon: icon,
          stylingMode: 'text',
          elementAttr: { class: 'form-editor-icon' }
        }} />
      }
      <Validator>
        <RequiredRule />
        {children}
      </Validator>
    </TextBox>
  );
};

// packages/angular/src/app/components/utils/form-textbox/form-textbox.component.ts
import {
  Component,
  EventEmitter,
  Input,
  Output
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxTextBoxModule,
  DxValidatorModule
} from 'devextreme-angular';
import { ValidationRule } from 'devextreme-angular/common';

@Component({
    selector: 'form-textbox',
    templateUrl: './form-textbox.component.html',
    styleUrls: ['form-textbox.component.scss'],
    imports: [
      DxButtonModule,
      DxTextBoxModule,
      DxValidatorModule,
      CommonModule,
    ],
})
export class FormTextboxComponent {
  @Input() isEditing = false;

  @Input() text: string;

  @Input() label = '';

  @Input() mask: string = null;

  @Input() icon: string = null;

  @Input() validators: ValidationRule[] = [{ type: 'required' }];

  @Input() value!: string;

  @Output() valueChange = new EventEmitter<string>();

  valueChanged(e) {
    this.valueChange.emit(e.value);
  }

}

<dx-text-box [label]="label"
             [(value)]="value"
             [readOnly]="!isEditing"
             [mask]="mask"
             [elementAttr]="{class: 'form-editor'}"
             [inputAttr]="{class: 'form-editor-input'}"
             stylingMode="filled"
             (onValueChanged)="valueChanged($event)"
             valueChangeEvent="keyup input change"
>
  <dx-validator [validationRules]="validators"></dx-validator>
  <dxi-button *ngIf="icon"
              [options]="{icon: icon, elementAttr: { class: 'form-editor-icon' }}"
              name="icon"
              location="before"
  ></dxi-button>
</dx-text-box>
