// packages/angular/src/app/components/library/contact-form/contact-form.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxFormModule,
  DxLoadPanelModule,
  DxNumberBoxModule,
  DxSelectBoxModule,
  DxTextBoxModule,
  DxValidatorModule,
  DxValidationGroupModule,
} from 'devextreme-angular';
import {
  FormTextboxComponent,
  FormPhotoComponent,
  StatusSelectBoxComponent,
} from 'src/app/components';
import { Contact } from 'src/app/types/contact';
import { ValidationRule } from 'devextreme-angular/common';
import { DxButtonTypes } from 'devextreme-angular/ui/button';
import { ToolbarFormComponent } from 'src/app/components/utils/toolbar-form/toolbar-form.component';
import { US_STATES } from 'src/app/shared/constants';

@Component({
  selector: 'contact-form',
  templateUrl: './contact-form.component.html',
  styleUrls: ['./contact-form.component.scss'],
  imports: [
    DxFormModule,
    DxSelectBoxModule,
    DxButtonModule,
    DxTextBoxModule,
    DxNumberBoxModule,
    DxLoadPanelModule,
    DxValidationGroupModule,
    FormTextboxComponent,
    FormPhotoComponent,
    DxValidatorModule,
    ToolbarFormComponent,
    CommonModule,
    StatusSelectBoxComponent,
  ]
})
export class ContactFormComponent {
  @Input() contactData?: Contact;

  @Input() isLoading!: boolean;

  savedData: Contact | null = null;

  isEditing = false;

  zipCodeValidator: ValidationRule = { type: 'pattern', pattern: /^\d{5}$/, message: 'Zip is invalid' };

  usStates = US_STATES;

  handleEditClick() {
    if (!this.contactData) {
      return;
    }
    this.savedData = { ...this.contactData };
    this.isEditing = true;
  }

  handleSaveClick({ validationGroup }: DxButtonTypes.ClickEvent) {
    if(!validationGroup.validate().isValid) return;
    this.isEditing = false;
    this.savedData = null;
  }

  handleCancelClick() {
    if (!this.savedData) {
      return;
    }
    this.contactData = { ...this.savedData };
    this.isEditing = false;
  }
}

<div id="contact-form">
  <dx-validation-group>
    <toolbar-form
      [isEditing]="isEditing"
      titleClass="dx-form-group-caption"
      (editingCancelled)="handleCancelClick()"
      (editModeToggled)="handleEditClick()"
      (saveButtonClicked)="handleSaveClick($event)"
    >
    </toolbar-form>

    @if (contactData) {
      <dx-form
        class="form last plain-styled-form"
        [formData]="contactData"
        labelMode="floating"
        [class.view-mode]="!isEditing"
      >
        <dxi-form-item itemType="group" [colCount]="2">
          <dxo-form-col-count-by-screen [xs]="2"></dxo-form-col-count-by-screen>
          <dxi-form-item>
            <div *dxTemplate>
              <form-photo [link]="contactData.image" [size]="184"></form-photo>
            </div>
          </dxi-form-item>
          <dxi-form-item itemType="group">
            <dxi-form-item>
              <status-select-box
                *dxTemplate
                classList="contact-status"
                [(value)]="contactData.status"
                [readOnly]="!isEditing"
              ></status-select-box>
            </dxi-form-item>

            <dxi-form-item>
              <form-textbox
                *dxTemplate
                label="First Name"
                [(value)]="contactData.firstName"
                [isEditing]="isEditing"
              ></form-textbox>
            </dxi-form-item>

            <dxi-form-item>
              <form-textbox
                *dxTemplate
                label="Last Name"
                [(value)]="contactData.lastName"
                [isEditing]="isEditing"
              ></form-textbox>
            </dxi-form-item>
          </dxi-form-item>

          <dxi-form-item>
            <form-textbox
              *dxTemplate
              label="Position"
              [(value)]="contactData.position"
              [isEditing]="isEditing"
            ></form-textbox>
          </dxi-form-item>

          <dxi-form-item cssClass="accent">
            <form-textbox
              *dxTemplate
              label="Assigned to"
              [(value)]="contactData.manager"
              [isEditing]="isEditing"
            ></form-textbox>
          </dxi-form-item>

          <dxi-form-item cssClass="accent" [colSpan]="2">
            <form-textbox
              *dxTemplate
              label="Company"
              [(value)]="contactData.company"
              [isEditing]="isEditing"
            ></form-textbox>
          </dxi-form-item>
        </dxi-form-item>

        <dxi-form-item itemType="group" [colCount]="4" caption="Contacts">
          <dxo-form-col-count-by-screen [xs]="2"></dxo-form-col-count-by-screen>
          <dxi-form-item [colSpan]="4">
            <form-textbox
              *dxTemplate
              label="Address"
              [(value)]="contactData.address"
              [isEditing]="isEditing"
            ></form-textbox>
          </dxi-form-item>

          <dxi-form-item [colSpan]="2">
            <form-textbox
              *dxTemplate
              label="City"
              [(value)]="contactData.city"
              [isEditing]="isEditing"
            ></form-textbox>
          </dxi-form-item>

          <dxi-form-item>
            <dx-select-box
              *dxTemplate
              label="State"
              stylingMode="filled"
              valueChangeEvent="keyup input change"
              [(value)]="contactData.state.stateShort"
              [items]="usStates"
              [readOnly]="!isEditing"
              [searchEnabled]="true"
              [elementAttr]="{ class: 'form-editor' }"
            ></dx-select-box>
          </dxi-form-item>

          <dxi-form-item>
            <dx-number-box
              *dxTemplate
              label="Zip Code"
              stylingMode="filled"
              valueChangeEvent="keyup input change"
              [(value)]="contactData.zipCode"
              [readOnly]="!isEditing"
              [elementAttr]="{ class: 'form-editor' }"
              [inputAttr]="{ class: 'form-editor-input' }"
            >
              <dx-validator [validationRules]="[zipCodeValidator]"></dx-validator>
            </dx-number-box>
          </dxi-form-item>
        </dxi-form-item>

        <dxi-form-item itemType="group" [colCount]="2" cssClass="contact-fields-group">
          <dxo-form-col-count-by-screen [xs]="2"></dxo-form-col-count-by-screen>
          <dxi-form-item>
            <div *dxTemplate>
              <form-textbox
                mask="(000) 000-0000"
                label="Phone"
                [(value)]="contactData.phone"
                [isEditing]="isEditing"
                [validators]="[]"
              ></form-textbox>
              <dx-button
                class="form-item-button"
                stylingMode="outlined"
                [visible]="!isEditing"
                [text]="'Call'"
                [icon]="'tel'"
                [type]="'default'"
              ></dx-button>
            </div>
          </dxi-form-item>

          <dxi-form-item>
            <div *dxTemplate>
              <form-textbox
                label="Email"
                [(value)]="contactData.email"
                [isEditing]="isEditing"
                [validators]="[{ type: 'email' }]"
              ></form-textbox>
              <dx-button
                class="form-item-button"
                stylingMode="outlined"
                [visible]="!isEditing"
                [text]="'Send Email'"
                [icon]="'email'"
                [type]="'default'"
              ></dx-button>
            </div>
          </dxi-form-item>
        </dxi-form-item>
      </dx-form>
    }
  </dx-validation-group>
  <dx-load-panel
    container="#contact-form"
    [position]="{ of: '#contact-form' }"
    [visible]="!contactData || isLoading"
    [showPane]="false"
  ></dx-load-panel>
</div>

// packages/vue/src/components/library/contact-form.vue
<template>
  <div id="contact-form">
    <dx-validation-group>
      <toolbar-form
        :is-editing="isEditing"
        @edit-canceled="cancelEdit()"
        @edit-toggled="startEdit()"
        @save-clicked="handleSaveClick"
      />
      <dx-load-panel
        :visible="isLoading"
        :show-pane="false"
        width="auto"
        container="#contact-form"
        :position="{ of: '#contact-form' }"
      />
      <dx-form
        class="plain-styled-form dx-form"
        :class="{'view-mode': !isEditing}"
        v-if="!!props.contactData"
      >
        <dx-form-group-item :col-count="2">
          <dx-col-count-by-screen :xs="2" />
          <dx-form-item>
            <form-photo
              :link="contactData.image"
              :size="184"
            />
          </dx-form-item>

          <dx-form-group-item>
            <dx-form-item>
              <status-select-box
                v-model="contactData.status"
                :items="contactStatusList"
                :read-only="!isEditing"
                styling-mode="filled"
              />
            </dx-form-item>

            <dx-form-item>
              <form-textbox
                label="First Name"
                v-model="contactData.firstName"
                :is-editing="isEditing"
              />
            </dx-form-item>

            <dx-form-item>
              <form-textbox
                label="Last Name"
                v-model="contactData.lastName"
                :is-editing="isEditing"
              />
            </dx-form-item>
          </dx-form-group-item>

          <dx-form-item>
            <form-textbox
              label="Position"
              v-model="contactData.position"
              :is-editing="isEditing"
            />
          </dx-form-item>

          <dx-form-item css-class="accent">
            <form-textbox
              label="Assigned to"
              v-model="contactData.manager"
              :is-editing="isEditing"
            />
          </dx-form-item>

          <dx-form-item
            :col-span="2"
            css-class="accent"
          >
            <form-textbox
              label="Company"
              v-model="contactData.company"
              :is-editing="isEditing"
            />
          </dx-form-item>
        </dx-form-group-item>

        <dx-form-group-item
          :col-count="4"
          caption="Contacts"
        >
          <dx-col-count-by-screen :xs="2" />
          <dx-form-item :col-span="4">
            <form-textbox
              label="Address"
              v-model="contactData.address"
              :is-editing="isEditing"
            />
          </dx-form-item>
          <dx-form-item :col-span="2">
            <form-textbox
              label="City"
              v-model="contactData.city"
              :is-editing="isEditing"
            />
          </dx-form-item>

          <dx-form-item>
            <form-textbox
              label="State"
              v-model="contactData.state.stateShort"
              :is-editing="isEditing"
            />
          </dx-form-item>
          <dx-form-item>
            <dx-number-box
              label="Zip Code"
              v-model.number="contactData.zipCode"
              :is-editing="isEditing"
              v-bind="formEditorProps"
            >
              <dx-validator :validation-rules="[zipCodeValidator]" />
            </dx-number-box>
          </dx-form-item>
        </dx-form-group-item>
        <dx-form-group-item
          :col-count="2"
          css-class="contact-fields-group"
        >
          <dx-col-count-by-screen :xs="2" />
          <dx-form-item>
            <form-textbox
              label="Phone"
              v-model.number="contactData.phone"
              :is-editing="isEditing"
              mask="+1(000)000-0000"
            />
            <dx-button
              v-if="!isEditing"
              class="form-item-button"
              v-bind="{
                text: 'Call',
                icon: 'tel',
                type: 'default',
                stylingMode: 'outlined'
              }"
              :validators="[]"
            />
          </dx-form-item>
          <dx-form-item>
            <form-textbox
              label="Email"
              v-model.number="contactData.email"
              :is-editing="isEditing"
              :validators="[{type: 'email'}]"
            />
            <dx-button
              v-if="!isEditing"
              class="form-item-button"
              v-bind="{
                text: 'Send Email',
                icon: 'email',
                type: 'default',
                stylingMode: 'outlined'
              }"
            />
          </dx-form-item>
        </dx-form-group-item>
      </dx-form>
    </dx-validation-group>
  </div>
</template>
<script setup lang="ts">
import { ref, watch } from 'vue';

import { DxButton } from 'devextreme-vue/button';
import {
  DxForm,
  DxItem as DxFormItem,
  DxGroupItem as DxFormGroupItem,
  DxColCountByScreen,
} from 'devextreme-vue/form';
import { DxNumberBox } from 'devextreme-vue/number-box';
import { DxValidator } from 'devextreme-vue/validator';
import { DxValidationGroup } from 'devextreme-vue/validation-group';
import { ClickEvent } from 'devextreme/ui/button';
import { formEditorProps } from '@/shared/form-editor-config';
import DxLoadPanel from 'devextreme-vue/load-panel';
import { Contact, contactStatusList } from '@/types/contact';
import FormPhoto from '@/components/utils/form-photo.vue';
import FormTextbox from '@/components/utils/form-textbox.vue';
import StatusSelectBox from '@/components/library/status-select-box.vue';
import ToolbarForm from '@/components/utils/toolbar-form.vue';

const emptyContact = { state: { stateShort: '' } } as Contact;

const props = withDefaults(defineProps<{
  isLoading: boolean,
  contactData: Contact | null
}>(), {
  isLoading: true,
  contactData: null,
});

const isEditing = ref(false);
const contactData = ref(emptyContact);

let contactDataSaved = emptyContact;
const zipCodeValidator = { type: 'pattern', pattern: /^\d{5}$/, message: 'Zip is invalid' };

watch(
  () => props.contactData,
  (contactDataNew: Contact| null) => {
    contactData.value = contactDataNew || emptyContact;
  },
);

function startEdit() {
  contactDataSaved = { ...contactData.value };
  isEditing.value = true;
}

function handleSaveClick({ validationGroup }: ClickEvent) {
  if (validationGroup.validate().isValid) {
    isEditing.value = false;
  }
}

function cancelEdit() {
  contactData.value = contactDataSaved;
  isEditing.value = false;
}
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

#contact-form {
  min-height: 300px;

  .form-title {
    font-size: 16px;
  }
}

.info {
  position: relative;
  padding-bottom: 30px;
}
</style>
