// packages/angular/src/app/components/library/login-oauth/login-oauth.component.ts
import { Component } from '@angular/core';
import { DxButtonModule, DxButtonTypes } from 'devextreme-angular/ui/button';
import { ThemeService } from '../../../services/theme.service';

@Component({
    selector: 'app-login-oauth',
    templateUrl: './login-oauth.component.html',
    styleUrls: ['./login-oauth.component.scss'],
    imports: [
      DxButtonModule
    ]
})
export class LoginOauthComponent {
  btnStylingMode: DxButtonTypes.ButtonStyle;

  constructor(private themeService: ThemeService) {
    this.themeService.isDark.subscribe((value: boolean) => {
      this.btnStylingMode = value ? 'outlined' : 'contained';
    });
  }


}

<div class="oauth-button-container">
  <p>or</p>
  <dx-button
    width="100%"
    icon="assets/icons/google-logo.svg"
    text="Sign In with Google"
    [stylingMode]="btnStylingMode()"
  ></dx-button>
  <dx-button
    width="100%"
    icon="assets/icons/microsoft-logo.svg"
    text="Sign In with Microsoft"
    [stylingMode]="btnStylingMode()"
  ></dx-button>
</div>

// packages/vue/src/components/library/login-oauth.vue
<template>
  <div class="oauth-button-container">
    <p>or</p>
    <dx-button
      width="100%"
      icon="icons/google-logo.svg"
      text="Sign In with Google"
      :styling-mode="buttonStylingMode"
    />
    <dx-button
      width="100%"
      icon="icons/microsoft-logo.svg"
      text="Sign In with Microsoft"
      :styling-mode="buttonStylingMode"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import DxButton, { DxButtonTypes } from 'devextreme-vue/button';
import { themeService } from '@/theme/theme-service';

const { currentTheme } = themeService;

 
const buttonStylingMode = computed<DxButtonTypes.ButtonStyle>(() => {
  return currentTheme.value === 'dark' ? 'outlined' : 'contained';
});

</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

.oauth-button-container {
  text-align: center;

  > p {
    margin: 16px 0;
  }

  .dx-button {
    margin-top: 8px;
  }
}
</style>
