// packages/angular/src/app/components/library/task-list-grid/task-list-grid.component.ts
import {
  Component, ViewChild, EventEmitter, Output, Input, SimpleChanges, OnChanges, inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import {
  DxButtonModule,
  DxDataGridComponent,
  DxDataGridModule,
  DxDropDownButtonModule,
  DxSelectBoxModule,
  DxToolbarModule,
} from 'devextreme-angular';
import { DxDataGridTypes } from 'devextreme-angular/ui/data-grid';
import { StatusIndicatorComponent } from 'src/app/components';
import { exportDataGrid as exportToPdf } from 'devextreme/pdf_exporter';
import { exportDataGrid as exportToXLSX } from 'devextreme/excel_exporter';
import { Workbook } from 'exceljs';
import { saveAs } from 'file-saver-es';
import { jsPDF } from 'jspdf';
import { taskPriorityList, taskStatusList } from 'src/app/types/task';
import { Task } from 'src/app/types/task';
import 'jspdf-autotable';

@Component({
  selector: 'task-list-grid',
  templateUrl: './task-list-grid.component.html',
  styleUrls: ['./task-list-grid.component.scss'],
  imports: [
    DxButtonModule,
    DxDataGridModule,
    DxDropDownButtonModule,
    DxSelectBoxModule,
    DxToolbarModule,
    StatusIndicatorComponent,
    CommonModule
  ],
  providers: []
})
export class TaskListGridComponent implements OnChanges {
  @ViewChild(DxDataGridComponent, { static: false }) grid!: DxDataGridComponent;

  @Input() dataSource!: Task[];

  @Output() tabValueChanged: EventEmitter<any> = new EventEmitter<EventEmitter<any>>();

  private router = inject(Router);

  tasks: Task[] = [];

  priorityList = taskPriorityList;

  statusList = taskStatusList;

  isLoading = true;

  useNavigation = true;

  displayExprFn = () => '';

  refresh() {
    this.grid.instance.refresh();
  }

  showColumnChooser() {
    this.grid.instance.showColumnChooser();
  }

  search(text: string) {
    this.grid.instance.searchByText(text);
  }

  onExportingToPdf() {
    const doc = new jsPDF();
    exportToPdf({
      jsPDFDocument: doc,
      component: this.grid.instance,
    }).then(() => {
      doc.save('Tasks.pdf');
    });
  };

  onExportingToXLSX() {
    const workbook = new Workbook();
    const worksheet = workbook.addWorksheet('Tasks');

    exportToXLSX({
      component: this.grid.instance,
      worksheet,
      autoFilterEnabled: true,
    }).then(() => {
      workbook.xlsx.writeBuffer().then((buffer) => {
        saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Tasks.xlsx');
      });
    });
  };

  ngOnChanges(changes: SimpleChanges) {
    if (changes.dataSource) {
      this.tasks = changes.dataSource.currentValue.filter((item: Task) => !!item.status && !!item.priority);
    }
  };

  toogleUseNavigation = () => {
    this.useNavigation = !this.useNavigation;
  };

  navigateToDetails = (e: DxDataGridTypes.RowClickEvent) => {
    if(this.useNavigation && e.rowType !== 'detailAdaptive') {
      this.router.navigate(['/planning-task-details'], {
        queryParams: { id: e.data.id }
      });
    }
  };
}


<dx-data-grid
  id="tasks-grid"
  class="theme-dependent"
  height="100%"
  [dataSource]="tasks"
  (onRowClick)="navigateToDetails($event)"
  (onEditingStart)="toogleUseNavigation()"
  (onEditCanceled)="toogleUseNavigation()"
  (onSaved)="toogleUseNavigation()"
  [hoverStateEnabled]="true"
  [columnAutoWidth]="true"
  [showBorders]="true"
>
  <dxo-data-grid-paging [pageSize]="30"></dxo-data-grid-paging>
  <dxo-data-grid-pager [visible]="true"></dxo-data-grid-pager>
  <dxo-data-grid-editing mode="row" [allowUpdating]="true"> </dxo-data-grid-editing>
  <dxo-data-grid-selection
    selectAllMode="allPages"
    showCheckBoxesMode="always"
    mode="multiple"
  ></dxo-data-grid-selection>
  <dxo-data-grid-scrolling mode="virtual"></dxo-data-grid-scrolling>
  <dxo-data-grid-sorting mode="multiple"></dxo-data-grid-sorting>
  <dxo-data-grid-header-filter [visible]="true"></dxo-data-grid-header-filter>

  <dxi-data-grid-column dataField="text" caption="Subject" [hidingPriority]="7">
    <dxi-data-grid-validation-rule type="required"></dxi-data-grid-validation-rule>
  </dxi-data-grid-column>
  <dxi-data-grid-column dataField="company" caption="Company" [hidingPriority]="6">
    <dxi-data-grid-validation-rule type="required"></dxi-data-grid-validation-rule>
  </dxi-data-grid-column>
  <dxi-data-grid-column
    dataField="priority"
    caption="Priority"
    [hidingPriority]="4"
    cellTemplate="cellPriority"
    editCellTemplate="editCellPriority"
  >
    <dxo-data-grid-lookup [dataSource]="priorityList"></dxo-data-grid-lookup>
    <dxi-data-grid-validation-rule type="required"></dxi-data-grid-validation-rule>
  </dxi-data-grid-column>
  <dxi-data-grid-column
    dataField="startDate"
    caption="Start Date"
    dataType="date"
    [hidingPriority]="2"
  >
    <dxi-data-grid-validation-rule type="required"></dxi-data-grid-validation-rule>
  </dxi-data-grid-column>
  <dxi-data-grid-column
    dataField="dueDate"
    caption="Due Date"
    dataType="date"
    sortOrder="asc"
    [hidingPriority]="1"
  >
    <dxi-data-grid-validation-rule type="required"></dxi-data-grid-validation-rule>
  </dxi-data-grid-column>
  <dxi-data-grid-column dataField="owner" caption="Owner" [hidingPriority]="5">
    <dxi-data-grid-validation-rule type="required"></dxi-data-grid-validation-rule>
  </dxi-data-grid-column>
  <dxi-data-grid-column
    dataField="status"
    caption="Status"
    [hidingPriority]="3"
    [minWidth]="120"
    cellTemplate="cellStatus"
    editCellTemplate="editCellStatus"
  >
    <dxo-data-grid-lookup [dataSource]="statusList"></dxo-data-grid-lookup>
    <dxi-data-grid-validation-rule type="required"></dxi-data-grid-validation-rule>
  </dxi-data-grid-column>

  <div *dxTemplate="let cellInfo of 'cellPriority'">
    <status-indicator
      [isField]="false"
      [showBar]="true"
      [value]="cellInfo.data.priority"
    >
    </status-indicator>
  </div>

  <div *dxTemplate="let cellInfo of 'editCellPriority'">
    <dx-select-box
      class="edit-cell"
      [(value)]="cellInfo.value"
      [items]="priorityList"
      (onValueChanged)="cellInfo.setValue($event.value)"
      (onSelectionChanged)="cellInfo.component.updateDimensions()"
      placeholder=""
      [displayExpr]="displayExprFn"
    >
      <dxo-select-box-field-addons beforeTemplate="before"></dxo-select-box-field-addons>
      <div *dxTemplate="let data of 'before'">
        <status-indicator
          [showBar]="true"
          [isField]="false"
          [value]="cellInfo.value"
        ></status-indicator>
      </div>
      <div *dxTemplate="let data of 'item'">
        <status-indicator
          [showBar]="true"
          [isField]="false"
          [value]="data"
        ></status-indicator>
      </div>
    </dx-select-box>
  </div>

  <div *dxTemplate="let cellInfo of 'cellStatus'">
    <status-indicator
      [isField]="false"
      [value]="cellInfo.data.status"
    ></status-indicator>
  </div>

  <div *dxTemplate="let cellInfo of 'editCellStatus'">
    <dx-select-box
      class="edit-cell"
      [(value)]="cellInfo.value"
      [items]="statusList"
      (onValueChanged)="cellInfo.setValue($event.value)"
      (onSelectionChanged)="cellInfo.component.updateDimensions()"
      placeholder=""
      [displayExpr]="displayExprFn"
    >
      <dxo-select-box-field-addons beforeTemplate="before"></dxo-select-box-field-addons>
      <div *dxTemplate="let data of 'before'">
        <status-indicator [isField]="false" [value]="cellInfo.value"></status-indicator>
      </div>
      <div *dxTemplate="let s of 'item'">
        <status-indicator [isField]="false" [value]="s"></status-indicator>
      </div>
    </dx-select-box>
  </div>
</dx-data-grid>

// packages/vue/src/components/library/task-list-grid.vue
<template>
  <dx-data-grid
    ref="dxDataGridCmp"
    id="tasks-grid"
    class="theme-dependent"
    height="100%"
    :data-source="dataSource"
    @row-click="navigateToDetails($event)"
    @editing-start="toogleUseNavigation"
    @edit-canceled="toogleUseNavigation"
    @saved="toogleUseNavigation"
    :hover-state-enabled="true"
    :column-auto-width="true"
    :show-borders="true"
  >
    <dx-load-panel
      :enabled="false"
    />
    <dx-scrolling mode="virtual" />
    <dx-paging :page-size="15" />
    <dx-pager
      :visible="true"
      :show-page-size-selector="true"
    />
    <dx-editing
      mode="row"
      :allow-updating="true"
    />

    <dx-selection
      select-all-mode="allPages"
      show-check-boxes-mode="always"
      mode="multiple"
    />
    <dx-sorting mode="multiple" />
    <dx-header-filter :visible="true" />

    <dx-column
      data-field="text"
      caption="Subject"
      :hiding-priority="7"
    >
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="company"
      caption="Company"
      :hiding-priority="6"
    >
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="priority"
      caption="Priority"
      :hiding-priority="4"
      cell-template="cellPriority"
      edit-cell-template="editCellPriority"
    >
      <dx-column-lookup :data-source="priorityList" />
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="startDate"
      caption="Start Date"
      data-type="date"
      :hiding-priority="2"
    >
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="dueDate"
      caption="Due Date"
      data-type="date"
      sort-order="asc"
      :hiding-priority="1"
    >
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="owner"
      caption="Owner"
      :hiding-priority="5"
    >
      <dx-required-rule />
    </dx-column>
    <dx-column
      data-field="status"
      caption="Status"
      :hiding-priority="3"
      :min-width="120"
      cell-template="cellStatus"
      edit-cell-template="editCellStatus"
    >
      <dx-column-lookup :data-source="statusList" />
      <dx-required-rule />
    </dx-column>

    <template #cellPriority="{ data }">
      <status-indicator
        :show-bar="true"
        :value="data?.data?.priority || ''"
      />
    </template>

    <template #editCellPriority="{ data: cellData }">
      <dx-select-box
        class="edit-cell"
        :value="cellData?.value"
        :items="priorityList"
        @value-changed="(e) => onPrioritySelectChange(e.value, cellData)"
        @selection-changed="cellData.component.updateDimensions"
        field-template="field"
      >
        <template #field>
          <div class="form-custom-list-prop">
            <status-indicator
              :show-bar="true"
              :is-field="true"
              :value="cellData.value"
            />
          </div>
        </template>
        <template #item="{ data }">
          <status-indicator
            :show-bar="true"
            :value="data"
          />
        </template>
      </dx-select-box>
    </template>

    <template #cellStatus="{ data }">
      <status-indicator :value="data.value" />
    </template>

    <template #editCellStatus="{ data: cellInfo }">
      <dx-select-box
        class="edit-cell"
        :value="cellInfo.value"
        :items="statusList"
        @value-changed="(e) => onStatusSelectChange(e.value, cellInfo)"
        @selection-changed="cellInfo.component.updateDimensions"
        field-template="field"
      >
        <template #field>
          <status-indicator
            :is-field="true"
            :value="cellInfo.value"
          />
        </template>
        <template #item="{ data }">
          <status-indicator
            :value="data"
          />
        </template>
      </dx-select-box>
    </template>
  </dx-data-grid>
  <dx-load-panel
    :visible="props.isLoading"
    container=".content"
    :position="{ of: '.content' }"
  />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import {
  DxDataGrid,
  DxColumn,
  DxHeaderFilter,
  DxLoadPanel,
  DxRequiredRule,
  DxSelection,
  DxScrolling,
  DxSorting,
  DxColumnLookup,
  DxPager,
  DxPaging,
  DxEditing,
  DxDataGridTypes,
} from 'devextreme-vue/data-grid';
import 'jspdf-autotable';
import { DxSelectBox } from 'devextreme-vue/select-box';
import { jsPDF as JsPDF } from 'jspdf';
import { saveAs } from 'file-saver-es';
import { exportDataGrid as exportGridToPdf } from 'devextreme/pdf_exporter';
import { exportDataGrid as exportToXLSX } from 'devextreme/excel_exporter';

import { router } from '@/router';
import type { Task } from '@/types/task';
import { taskPriorityList as priorityList, taskStatusList as statusList } from '@/types/task';
import { Workbook } from 'exceljs';
import StatusIndicator from '@/components/library/status-indicator.vue';

const props = withDefaults(defineProps<{
  dataSource: Task[] | null
}>(), {
  dataSource: () => null,
});

const dxDataGridCmp = ref<InstanceType<typeof DxDataGrid> | null>(null);
let useNavigation = true;

const navigateToDetails = (e: DxDataGridTypes.RowClickEvent) => {
  if (useNavigation && e.rowType !== 'detailAdaptive') {
    router.push('/planning-task-details');
  }
};

const toogleUseNavigation = () => {
  useNavigation = !useNavigation;
};

const addRow = () => dxDataGridCmp.value?.instance.addRow();
const onPrioritySelectChange = (value: string, cellData: Record<string, unknown>) => {
  cellData.setValue(value);
  cellData.component.refresh();
  cellData.component.focus();
};

const onStatusSelectChange = (value: string, cellInfo: Record<string, unknown>) => {
  cellInfo.setValue(value);
  cellInfo.component.refresh();
};

const exportToPdf = () => {
  const doc = new JsPDF();
  exportGridToPdf({
    jsPDFDocument: doc,
    component: dxDataGridCmp.value.instance,
  }).then(() => {
    doc.save('Tasks.pdf');
  });
};

const exportToXlsx = () => {
  const workbook = new Workbook();
  const worksheet = workbook.addWorksheet('Tasks');

  exportToXLSX({
    component: dxDataGridCmp.value.instance,
    worksheet,
    autoFilterEnabled: true,
  }).then(() => {
    workbook.xlsx.writeBuffer().then((buffer) => {
      saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Tasks.xlsx');
    });
  });
};

defineExpose({
  addRow,
  exportToPdf,
  exportToXlsx,
  showColumnChooser() {
    dxDataGridCmp.value.instance.showColumnChooser();
  },
  search(text: string) {
    dxDataGridCmp.value.instance.searchByText(text);
  },
  refresh() {
    dxDataGridCmp.value.instance.refresh();
  },
});
</script>

<style scoped lang="scss">
@use "@/variables" as *;

#tasks-grid {
  min-height: 300px;

  :deep(.priority span) {
    font-size: 13px;
  }
}

:deep(.edit-cell) {
  position: relative;
}
</style>
