// packages/angular/src/app/components/library/task-list-gantt/task-list-gantt.component.ts
import { Component, Input, ViewChild, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { DxGanttModule, DxGanttComponent } from 'devextreme-angular/ui/gantt';
import { exportGantt as exportGanttToPdf } from 'devextreme/pdf_exporter';
import { jsPDF } from 'jspdf';
import { Task } from 'src/app/types/task';

import 'jspdf-autotable';

@Component({
  selector: 'task-list-gantt',
  templateUrl: './task-list-gantt.component.html',
  styleUrls: ['./task-list-gantt.component.scss'],
  imports: [
    DxGanttModule,
    CommonModule,
  ],
})
export class TaskListGanttComponent {
  @ViewChild(DxGanttComponent, { static: false }) gantt: DxGanttComponent;

  @Input() dataSource: Task[];

  private router = inject(Router);

  refresh() {
    this.gantt.instance.refresh();
  }

  onExporting() {
    exportGanttToPdf(
      {
        component: this.gantt.instance,
        createDocumentMethod: (args?: any) => new jsPDF(args),
      },
    ).then((doc) => doc.save('Tasks.pdf'));
  };

  navigateToDetails = () => {
    this.router.navigate(['/planning-task-details']);
  };
}

<dx-gantt
  [taskListWidth]="500"
  scaleType="weeks"
  (onTaskClick)="navigateToDetails()"
  [height]="700"
>
  <dxo-gantt-tasks
    [dataSource]="dataSource"
    keyExpr="taskId"
    startExpr="startDate"
    endExpr="dueDate"
    titleExpr="text"
  >
  </dxo-gantt-tasks>

  <dxi-gantt-column dataField="text" caption="Subject" [width]="300"></dxi-gantt-column>
  <dxi-gantt-column
    dataField="startDate"
    caption="Start Date"
    dataType="date"
    sortOrder="asc"
  ></dxi-gantt-column>
  <dxi-gantt-column
    dataField="dueDate"
    caption="Due Date"
    dataType="date"
  ></dxi-gantt-column>

  <dxo-gantt-toolbar>
    <dxi-gantt-item name="undo" [options]="{ icon: 'revert' }"></dxi-gantt-item>
    <dxi-gantt-item name="redo" [options]="{ icon: 'redo' }"></dxi-gantt-item>
    <dxi-gantt-item name="separator"></dxi-gantt-item>
    <dxi-gantt-item name="collapseAll" [options]="{ icon: 'arrowdown' }"></dxi-gantt-item>
    <dxi-gantt-item name="expandAll" [options]="{ icon: 'arrowup' }"></dxi-gantt-item>
    <dxi-gantt-item name="separator"></dxi-gantt-item>
    <dxi-gantt-item name="addTask" [options]="{ icon: 'add' }"></dxi-gantt-item>
    <dxi-gantt-item name="deleteTask" [options]="{ icon: 'trash' }"></dxi-gantt-item>
    <dxi-gantt-item name="separator"></dxi-gantt-item>
    <dxi-gantt-item name="zoomIn" [options]="{ icon: 'zoominoutline' }"></dxi-gantt-item>
    <dxi-gantt-item name="zoomOut" [options]="{ icon: 'zoomoutoutline' }"></dxi-gantt-item>
  </dxo-gantt-toolbar>

  <dxo-gantt-validation [autoUpdateParentTasks]="true"></dxo-gantt-validation>
  <dxo-gantt-editing [enabled]="true"></dxo-gantt-editing>
</dx-gantt>

// packages/vue/src/components/library/task-list-gantt.vue
<template>
  <dx-gantt
    ref="dxGanttCmp"
    :task-list-width="500"
    :scale-type="'weeks'"
    @task-click="onTaskClick"
    :height="700"
  >
    <dx-tasks
      :data-source="props.tasks"
      :key-expr="'taskId'"
      :start-expr="'startDate'"
      :end-expr="'dueDate'"
      title-expr="text"
    />

    <dx-gantt-column
      data-field="text"
      caption="Subject"
      :width="300"
    />
    <dx-gantt-column
      data-field="startDate"
      caption="Start Date"
      data-type="date"
      sort-order="asc"
    />
    <dx-gantt-column
      data-field="dueDate"
      caption="Due Date"
      data-type="date"
    />

    <dx-gantt-toolbar>
      <dx-item name="undo"
        :options="toolbarItemOptions.undo"
      />
      <dx-item name="redo"
        :options="toolbarItemOptions.redo"
      />
      <dx-item name="separator" />
      <dx-item name="collapseAll"
        :options="toolbarItemOptions.collapseAll"
      />
      <dx-item name="expandAll"
        :options="toolbarItemOptions.expandAll"
      />
      <dx-item name="separator" />
      <dx-item name="addTask"
        :options="toolbarItemOptions.addTask"
      />
      <dx-item name="deleteTask"
        :options="toolbarItemOptions.deleteTask"
      />
      <dx-item name="separator" />
      <dx-item name="zoomIn"
        :options="toolbarItemOptions.zoomIn"
      />
      <dx-item name="zoomOut"
        :options="toolbarItemOptions.zoomOut"
      />
    </dx-gantt-toolbar>

    <dx-validation :auto-update-parent-tasks="true" />
    <dx-editing :enabled="true" />
  </dx-gantt>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { router } from '@/router';
import {
  DxGantt,
  DxTasks,
  DxEditing,
  DxValidation,
  DxColumn as DxGanttColumn,
  DxToolbar as DxGanttToolbar,
  DxItem,
  DxGanttTypes,
} from 'devextreme-vue/gantt';
import { Task } from '@/types/task';
import { jsPDF as JsPDF } from 'jspdf';
import { exportGantt } from 'devextreme/pdf_exporter';

const props = withDefaults(defineProps<{
  tasks: Task[]
}>(), {
  tasks: () => [],
});

const dxGanttCmp = ref<InstanceType<typeof DxGantt> | null>(null);

const onExporting = () => {
  const doc = new JsPDF();
  exportGantt({
    jsPDFDocument: doc,
    component: dxGanttCmp.value.instance,
  }).then(() => {
    doc.save('Tasks.pdf');
  });
};

const navigateToDetails = () => {
  router.push('/planning-task-details');
};

const onTaskClick = (e: DxGanttTypes.TaskClickEvent) => {
  if (!e.event?.target?.closest('.dx-treelist-expanded, .dx-treelist-collapsed')) {
    navigateToDetails();
  }
};

const toolbarItemOptions = {
  undo: { icon: 'revert' },
  redo: { icon: 'redo' },
  collapseAll: { icon: 'arrowdown' },
  expandAll: { icon: 'arrowup' },
  addTask: { icon: 'add' },
  deleteTask: { icon: 'trash' },
  zoomIn: { icon: 'zoominoutline' },
  zoomOut: { icon: 'zoomoutoutline' },
};

defineExpose({
  onExporting,
});
</script>

<style scoped lang="scss">
.dx-gantt {
  border-radius: 8px;
}
</style>
