// packages/react/src/components/library/theme-switcher/ThemeSwitcher.tsx
import React, { useCallback, useContext } from 'react';
import Button from 'devextreme-react/button';
import { ThemeContext } from '../../../theme/theme';

export const ThemeSwitcher = () => {
  const themeContext = useContext(ThemeContext);

  const onButtonClick = useCallback(() => {
    themeContext?.switchTheme();
  }, []);

  return <div>
    <Button className='theme-button'
      icon={`${themeContext?.theme !== 'dark' ? 'moon' : 'sun'}`}
      onClick={onButtonClick} />
  </div>;
};

// packages/vue/src/components/library/theme-switcher.vue
<template>
  <dx-button
    class="theme-button"
    :icon="currentTheme === 'dark' ? 'sun' : 'moon'"
    @click="onClickButton"
  />
</template>

<script setup lang="ts">
import { DxButton } from 'devextreme-vue/button';
import { themeService } from '@/theme/theme-service';

const { currentTheme } = themeService;

function onClickButton() {
  themeService.switchAppTheme();
}
</script>
