// packages/react/src/components/library/ticker-card/TickerCard.tsx
import React from 'react';
import './TickerCard.scss';

export const TickerCard = ({
  title,
  icon,
  tone,
  value,
  percentage,
  formatValue = (value) => `${value}`,
}: {
  title: string;
  icon: string;
  tone?: 'warning' | 'info';
  value: number;
  percentage: number;
  formatValue?: (value: number) => string;
}) => (
  <div className='ticker'>
    <div
      className={`icon-wrapper ${
        tone || (percentage > 0 ? 'positive' : 'negative')
      }`}
    >
      <i className={`dx-icon dx-icon-${icon} `} />
    </div>
    <div className='middle'>
      <div className='title'>{title}</div>
      <div className='total'>{formatValue(value)}</div>
    </div>
    <div className={`percentage ${percentage > 0 ? 'positive' : 'negative'}`}>
      <div className={`dx-icon-${percentage > 0 ? 'spinup' : 'spindown'}`} />
      <div className='value'>{`${Math.abs(percentage)}%`}</div>
    </div>
  </div>
);

// packages/angular/src/app/components/library/ticker-card/ticker-card.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { Sales, SalesOrOpportunitiesByCategory } from '../../../types/analytics';
import { ApplyPipeDirective } from "src/app/pipes/apply.pipe";

@Component({
  selector: 'ticker-card',
  templateUrl: './ticker-card.component.html',
  styleUrls: ['./ticker-card.component.scss'],
  imports: [
    ApplyPipeDirective,
    CommonModule,
  ],
})

export class TickerCardComponent {
  @Input() titleText: string;

  @Input() data: SalesOrOpportunitiesByCategory | Sales | null = null;

  @Input() total: string | null = null;

  @Input() percentage: number;

  @Input() icon: string;

  @Input() tone?: 'warning' | 'info';

  @Input() contentClass: string | null = null;

  getTotal(data: Array<{value?: number, total?: number}> ): number {
    return (data || []).reduce((total, item) => total + (item.value || item.total), 0);
  }

  abs(value: number): number {
    return Math.abs(value);
  }

  getIconClass = () => this.tone || (this.percentage > 0 ? 'positive' : 'negative');
}


<div class="tile"
>
  <div
  class="icon-wrapper"
  [class]="getIconClass()"
>
  <i [class]="'dx-icon dx-icon-' + icon"></i>
</div>
  <div class="middle">
    <div class="title">
      {{ titleText }}
    </div>
    <div class="total">
      {{
      total === null
        ? (getTotal | apply: data | currency: 'USD':'$':'1.0-0')
        : total
      }}
    </div>
  </div>
  <div *ngIf="percentage !== 0"
       class="percentage"
       [class.positive]="percentage > 0"
       [class.negative]="percentage < 0"

  >
    <div [class]="'dx-icon-'+ (percentage > 0 ? 'spinup' : 'spindown')"></div>
    <i class="value"></i>
    <span>{{ abs(percentage) }}%</span>
  </div>
</div>
