// packages/vue/src/components/library/contact-new-form.vue
<template>
  <dx-form
    class="plain-styled-form"
    :screen-by-width="getSizeQualifier"
  >
    <dx-form-item item-type="group">
      <dx-col-count-by-screen
        :xs="1"
        :sm="1"
        :md="1"
        :lg="1"
      />
      <dx-form-item class="uploader">
        <div>
          <form-photo-uploader />
        </div>
      </dx-form-item>
    </dx-form-item>

    <dx-form-item
      item-type="group"
    >
      <dx-col-count-by-screen
        :xs="1"
        :sm="2"
        :md="2"
        :lg="2"
      />
      <dx-form-item>
        <form-textbox
          label="First Name"
          v-model="contact.firstName"
          :is-editing="true"
        />
      </dx-form-item>
      <dx-form-item css-class="accent">
        <form-textbox
          label="Last Name"
          v-model="contact.lastName"
          :is-editing="true"
        />
      </dx-form-item>
      <dx-form-item css-class="accent">
        <form-textbox
          label="Company"
          v-model="contact.company"
          :is-editing="true"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          label="Position"
          v-model="contact.position"
          :is-editing="true"
        />
      </dx-form-item>
    </dx-form-item>

    <dx-form-item
      item-type="group"
      css-class="contact-fields-group"
    >
      <dx-col-count-by-screen
        :xs="1"
        :sm="2"
        :md="2"
        :lg="2"
      />
      <dx-form-item css-class="accent">
        <form-textbox
          label="Assigned to"
          v-model="contact.manager"
          :is-editing="true"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model="contact.phone"
          :is-editing="true"
          icon="tel"
          mask="+1(000)000-0000"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model="contact.email"
          :is-editing="true"
          icon="email"
          :validators="[{type: 'email'}, {type: 'required'}]"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model="contact.address"
          :is-editing="true"
          icon="home"
        />
      </dx-form-item>
    </dx-form-item>
  </dx-form>
</template>

<script setup lang="ts">
import { getSizeQualifier } from '@/utils/media-query';
import {
  DxForm,
  DxItem as DxFormItem,
  DxColCountByScreen,
} from 'devextreme-vue/form';
import { ref } from 'vue';
import { newContact } from '@/types/contact';
import FormTextbox from '@/components/utils/form-textbox.vue';
import FormPhotoUploader from '../utils/form-photo-uploader.vue';

const contact = ref({ ...newContact });
</script>

// packages/react/src/components/contact-new-form/ContactNewForm.tsx

import React, { useState } from 'react';

import Form, { Item as FormItem, GroupItem, ColCountByScreen } from 'devextreme-react/form';
import { Contact } from '../../types/crm-contact';
import { newContact } from '../../shared/constants';
import { FormTextbox, FormPhotoUploader } from '../../components';
import { EmailRule } from 'devextreme-react/validator';
import { getSizeQualifier } from '../../utils/media-query';

export const ContactNewForm = () => {
  const [newContactData, setNewContactData] = useState<Contact>(newContact);

  const updateField = (field: string) => (value) => {
    setNewContactData((prevState) => ({ ...prevState, ...{ [field]: value } }));
  };

  return (
    <Form
      className='plain-styled-form'
      screenByWidth={getSizeQualifier}
    >
      <GroupItem>
        <ColCountByScreen xs={1} sm={1} md={1} lg={1} />
        <FormItem>
          <FormPhotoUploader />
        </FormItem>
      </GroupItem>

      <GroupItem>
        <ColCountByScreen xs={1} sm={2} md={2} lg={2} />
        <FormItem>
          <FormTextbox
            label='First Name'
            value={newContactData.firstName}
            isEditing={false}
            onValueChange={updateField('firstName')}
          />
        </FormItem>
        <FormItem>
          <FormTextbox
            label='Last Name'
            value={newContactData.lastName}
            isEditing={false}
            onValueChange={updateField('lastName')}
          />
        </FormItem>
        <FormItem>
          <FormTextbox
            label='Company'
            value={newContactData.company}
            isEditing={false}
            onValueChange={updateField('company')}
          />
        </FormItem>
        <FormItem>
          <FormTextbox
            label='Position'
            value={newContactData.position}
            isEditing={false}
            onValueChange={updateField('position')}
          />
        </FormItem>
      </GroupItem>

      <GroupItem cssClass='contact-fields-group'>
        <ColCountByScreen xs={1} sm={2} md={2} lg={2} />
        <FormItem>
          <FormTextbox
            value={newContactData.manager}
            label='Assigned to'
            isEditing={false}
            onValueChange={updateField('manager')}
          />
        </FormItem>
        <FormItem>
          <FormTextbox
            value={newContactData.phone}
            isEditing={false}
            onValueChange={updateField('phone')}
            icon='tel'
            mask='+1(000)000-0000'
          />
        </FormItem>
        <FormItem>
          <FormTextbox
            value={newContactData.email}
            onValueChange={updateField('email')}
            isEditing={false}
            icon='email'
          >
            <EmailRule />
          </FormTextbox>
        </FormItem>
        <FormItem>
          <FormTextbox
            value={newContactData.address}
            isEditing={false}
            onValueChange={updateField('address')}
            icon='home'
          />
        </FormItem>
      </GroupItem>
    </Form>
  );
};
