// packages/angular/src/app/components/status-select-box/status-select-box.component.ts
import {
  Component, EventEmitter, Input, NgModule, Output,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxSelectBoxModule, DxTextBoxModule } from 'devextreme-angular';
import { contactStatusList } from '../../types/contact';
import { ContactStatusModule } from '../contact-status/contact-status.component';

@Component({
  selector: 'status-select-box',
  templateUrl: 'status-select-box.component.html',
  styleUrls: ['./status-select-box.component.scss'],
})
export class StatusSelectBoxComponent {
  @Input() value: string;

  @Input() label = '';

  @Input() items = contactStatusList;

  @Input() readOnly = false;

  @Input() stylingMode = 'outlined';

  @Input() labelMode = 'floating';

  @Output() valueChange = new EventEmitter<string>();
}

@NgModule({
  imports: [
    DxSelectBoxModule,
    DxTextBoxModule,
    ContactStatusModule,
    CommonModule],
  declarations: [StatusSelectBoxComponent],
  exports: [StatusSelectBoxComponent],
})
export class StatusSelectBoxModule {}

<dx-select-box
  label="Status"
  [value]="value"
  (valueChange)="valueChange.emit($event)"
  [items]="items"
  [readOnly]="readOnly"
  [stylingMode]="stylingMode"
  [labelMode]="labelMode"
  width="100%"
  fieldTemplate="field"
>
  <div *dxTemplate="let data of 'field'"
       class="status-editor-field">
    <contact-status class="status-indicator"
                    [showText]="false"
                    [value]="data">
    </contact-status>
    <dx-text-box
      class="status-{{data | lowercase}}"
      [hoverStateEnabled]="false"
      [inputAttr]="{class: 'status-input status-editor-input'}"
      [readOnly]="true"
      [value]="data">
    </dx-text-box>
  </div>
  <div *dxTemplate="let data of 'item'">
    <contact-status [value]="data">
    </contact-status>
  </div>
</dx-select-box>

// packages/react/src/components/library/status-select-box/StatusSelectBox.tsx
import './StatusSelectBox.scss';
import React from 'react';
import SelectBox from 'devextreme-react/select-box';
import TextBox from 'devextreme-react/text-box';
import type { EditorStyle, LabelMode } from 'devextreme-react/common';
import { ContactStatus } from '../../utils/contact-status/ContactStatus';
import { CONTACT_STATUS_LIST } from '../../../shared/constants';

interface StatusSelectBoxProps {
  value: string,
  readOnly?: boolean,
  stylingMode?: EditorStyle,
  labelMode?: LabelMode,
  onValueChange: (value) => void,
}

const FieldRender = (data) => {
  return <div className='status-editor-field'>
    <ContactStatus
      text={data}
      showText={false}
      contentClass='status-indicator'
    />
    <TextBox
      className={`status-${data?.toLowerCase()}`}
      value={data}
      hoverStateEnabled={false}
      inputAttr={{ class: 'status-input', statusEditorInput: '' }}
      readOnly
    />
  </div>;
};

const ItemRender = (item) => {
  return <div>
    <ContactStatus text={item} />
  </div>;
};

export const StatusSelectBox = ({
  value,
  readOnly,
  stylingMode = 'outlined',
  labelMode = 'floating',
  onValueChange
}: StatusSelectBoxProps) => {
  return <SelectBox
    label='Status'
    value={value}
    items={CONTACT_STATUS_LIST}
    onValueChange={onValueChange}
    itemRender={ItemRender}
    readOnly={readOnly}
    stylingMode={stylingMode}
    labelMode={labelMode}
    width='100%'
    fieldRender={FieldRender}
  />;
};
