// packages/vue/src/components/utils/chat-floating-button.vue
<template>
  <dx-speed-dial-action
    icon="sparkle"
    :label="screenInfo.isLarge ? 'AI Insights' : ''"
    @click="$emit('click')"
  />
</template>

<script setup lang="ts">
import { DxSpeedDialAction } from 'devextreme-vue/speed-dial-action';
import { screenInfo } from '@/utils/media-query';

defineEmits<{
  (e: 'click'): void;
}>();
</script>

// packages/react/src/components/utils/chat-floating-button/ChatFloatingButton.tsx
import React from 'react';
import SpeedDialAction from 'devextreme-react/speed-dial-action';
import { useScreenSize } from '../../../utils/media-query';

type ChatFloatingButtonProps = {
  onClick: () => void;
};

export const ChatFloatingButton = ({ onClick }: ChatFloatingButtonProps) => {
  const { isLarge } = useScreenSize();
  const isSmallScreen = !isLarge;
  return (
    <SpeedDialAction
      icon='sparkle'
      label={isSmallScreen ? '' : 'AI Insights'}
      onClick={onClick}
    />
  );
};
