// packages/vue/src/components/utils/chat-floating-button.vue
<template>
  <dx-speed-dial-action
    icon="sparkle"
    :label="screenInfo.isLarge ? 'AI Insights' : ''"
    @click="$emit('click')"
  />
</template>

<script setup lang="ts">
import { DxSpeedDialAction } from 'devextreme-vue/speed-dial-action';
import { screenInfo } from '@/utils/media-query';

defineEmits<{
  (e: 'click'): void;
}>();
</script>

// packages/react/src/components/utils/chat-floating-button/chat-floating-button.tsx
import React from 'react';
import SpeedDialAction from 'devextreme-react/speed-dial-action';

type ChatFloatingButtonProps = {
  onClick: () => void;
};

export const ChatFloatingButton = ({ onClick }: ChatFloatingButtonProps) => {
  return <SpeedDialAction icon='sparkle' label='AI Inside' onClick={onClick} />;
};
