// packages/react/src/pages/analytics-sales-report/analytics-sales-report.tsx
import React, { useState, useEffect, useCallback } from 'react';
import RangeSelector, { Scale, MinorTick, Marker, Label, Size, LoadingIndicator, Chart as RangeChart, Series } from 'devextreme-react/range-selector';
import { CardAnalytics } from '../../components/card-analytics/CardAnalytics';
import { DashboardContainer } from '../../components/dashboard-container/DashboardContainer';
import { getSalesByCategory, getSales, getSalesByOrderDate } from 'dx-rwa-data';
import PieChart, { Font, Legend, Margin, Label as PieLabel } from 'devextreme-react/pie-chart';
import { DashboardCardsGroup } from '../../components/dashboard-container/DashboardCardGroup';
import Chart, {
  CommonAxisSettings,
  Tick,
  Legend as ChartLegend,
  CommonSeriesSettings,
  SeriesTemplate,
  ValueAxis,
  Label as ChartLabel,
  Format,
  Point,
  Tooltip,
  ArgumentAxis,
  Size as ChartSize,
} from 'devextreme-react/chart';
import './analytics-sales-report.scss';
import DropDownButton from 'devextreme-react/drop-down-button';

export const SalesRangeCard = ({ datasource, range, onRangeChanged }) => (
  <CardAnalytics title='' contentClass='sales-range' isLoading={!datasource.length}>
    <RangeSelector id='range' dataSource={datasource} value={range} onValueChanged={onRangeChanged}>
      <Scale minorTickInterval='day' tickInterval='month' valueType='datetime'>
        <MinorTick visible={false} />
        <Marker visible={false} />
        <Label format='MMM yyyy' />
      </Scale>
      <Size height={90} />
      <LoadingIndicator show />
      <RangeChart>
        <Series type='line' argumentField='date' valueField='total' />
      </RangeChart>
    </RangeSelector>
  </CardAnalytics>
);

export const ProductSaleByRangeCard = ({ datasource }) => (
  <CardAnalytics title='Product Sale by Range' contentClass='sales-by-category' isLoading={!datasource.length}>
    <PieChart id='pie' className='sales-pie' dataSource={datasource} type='doughnut' diameter={0.8} innerRadius={0.6}>
      <Series argumentField='name' valueField='value'>
        <PieLabel backgroundColor='none' radialOffset={-20} visible customizeText={({ percentText }) => percentText}>
          <Font color='#757575' size={15} />
        </PieLabel>
      </Series>
      <Legend>
        <Margin top={70} />
      </Legend>
      <Size height={270} />
    </PieChart>
    <Chart id='bar' dataSource={datasource} className='sales-bars' rotated>
      <CommonAxisSettings visible={false}>
        <Tick visible={false} />
      </CommonAxisSettings>
      <ChartLegend visible={false} />
      <CommonSeriesSettings argumentField='name' valueField='value' type='bar' ignoreEmptyPoints />
      <SeriesTemplate nameField='name' />
      <ValueAxis>
        <ChartLabel>
          <Format type='largeNumber' />
        </ChartLabel>
      </ValueAxis>
    </Chart>
  </CardAnalytics>
);

export const SalesPerformanceCard = ({ datasource, periods, selectedPeriod, onPeriodChanged, range }) => (
  <CardAnalytics title='Sales Perfomance' contentClass='sales' isLoading={!datasource.length}>
    <div className='sales-filter'>
      <DropDownButton stylingMode='text' useSelectMode items={periods} selectedItemKey={selectedPeriod} onSelectionChanged={onPeriodChanged} />
    </div>
    <Chart id='chart' dataSource={datasource}>
      <ArgumentAxis visualRange={range} />
      <Tooltip enabled />
      <SeriesTemplate nameField='category' />
      <CommonSeriesSettings argumentField='name' valueField='total' hoverMode='includePoints'>
        <Point hoverMode='allArgumentPoints' />
      </CommonSeriesSettings>
      <ArgumentAxis argumentType='datetime' valueMarginsEnabled='false' />
      <ChartLegend visible={false} />
      <ChartSize height={270} />
    </Chart>
  </CardAnalytics>
);

const formatDate = (dateTime: Date) => {
  return dateTime.toLocaleDateString('en-GB').split('/').reverse().join('-');
};

const groupByPeriods = ['Day', 'Month'];

export const AnalyticsSalesReport = () => {
  const [sales, setSales] = useState([]);
  const [salesByCategory, setSalesByCategory] = useState([]);
  const [salesByDateAndCategory, setSalesByDateAndCategory] = useState([]);
  const [dateRange, setDateRange] = useState([new Date('2018-01-01'), new Date('2022-01-01')]);
  const [visualRange, setVisualRange] = useState(['2018-01-01', '2022-01-01']);
  const [groupByPeriod, setGroupByPeriod] = useState(groupByPeriods[1]);

  const onRangeChanged = useCallback((e) => {
    const [startDate, endDate] = e.value;
    setVisualRange([formatDate(startDate), formatDate(endDate)]);
    setDateRange([startDate, endDate]);
  }, []);

  const onPeriodChanged = useCallback((e) => {
    const groupByPeriod = e.item;
    setGroupByPeriod(groupByPeriod);
  }, []);

  useEffect(() => {
    getSales(...visualRange)
      .then((data) => setSales(data))
      .catch((error) => console.log(error));
  }, []);

  useEffect(() => {
    getSalesByCategory(...visualRange)
      .then((data) => setSalesByCategory(data))
      .catch((error) => console.log(error));

    getSalesByOrderDate(groupByPeriod)
      .then((data) => setSalesByDateAndCategory(data))
      .catch((error) => console.log(error));
  }, [visualRange]);

  return (
    <DashboardContainer>
      <DashboardCardsGroup kind='wide'>
        <SalesRangeCard datasource={sales} range={dateRange} onRangeChanged={onRangeChanged} />
        <ProductSaleByRangeCard datasource={salesByCategory} />
        <SalesPerformanceCard datasource={salesByDateAndCategory} periods={groupByPeriods} selectedPeriod={groupByPeriod} onPeriodChanged={onPeriodChanged} range={dateRange} />
      </DashboardCardsGroup>
    </DashboardContainer>
  );
};

// packages/angular/src/app/pages/analytics-sales-report/analytics-sales-report.component.ts
import {
  Component, OnInit, NgModule, OnDestroy,
} from '@angular/core';

import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';
import { DxPieChartModule } from 'devextreme-angular/ui/pie-chart';
import { DxChartModule } from 'devextreme-angular/ui/chart';
import { DxRangeSelectorModule } from 'devextreme-angular/ui/range-selector';
import { DxDropDownButtonModule } from 'devextreme-angular/ui/drop-down-button';

import { SelectionChangedEvent } from 'devextreme/ui/drop_down_button';

import { ValueChangedEvent } from 'devextreme/viz/range_selector';

import { CommonModule, formatDate } from '@angular/common';
import { RwaService } from 'src/app/shared/services';
import { forkJoin, Subscription } from 'rxjs';

import { CardAnalyticsModule } from 'src/app/shared/components/card-analytics/card-analytics.component';
import { ToolbarAnalyticsModule } from 'src/app/shared/components/toolbar-analytics/toolbar-analytics.component';

import { analyticsPanelItems } from 'src/app/shared/types/resource';

import { Sales, SalesOrOpportunitiesByCategory } from 'src/app/shared/types/analytics';

@Component({
  templateUrl: './analytics-sales-report.component.html',
  styleUrls: ['./analytics-sales-report.component.scss'],
  providers: [RwaService],
})
export class AnalyticsSalesReportComponent implements OnInit, OnDestroy {
  subscriptions: Subscription[] = [];

  groupByPeriods = ['Day', 'Month'];

  sales: Sales;

  salesByDateAndCategory: Sales;

  visualRange: unknown = {};

  salesByCategory: SalesOrOpportunitiesByCategory;

  constructor(private service: RwaService) { }

  formatDate(dateTime: string | number | Date) {
    return formatDate(dateTime, 'YYYY-MM-dd', 'en');
  }
  selectionChange(e: SelectionChangedEvent) {
    var groupByPeriod = e.item.toLowerCase();
    this.subscriptions.push(
      this.service.getSalesByOrderDate(groupByPeriod)
        .subscribe((data) => {
          this.salesByDateAndCategory = data;
        }),
    );
  }

  onRangeChanged = (e: ValueChangedEvent) => {
    const [startDate, endDate] = e.value;
    this.subscriptions
      .push(
        this.service.getSalesByCategory(this.formatDate(startDate), this.formatDate(endDate))
          .subscribe((data) => {
            this.salesByCategory = data;
          }),
      );
  };

  customizeSaleText(arg: { percentText: string }) {
    return arg.percentText;
  }

  loadData = (groupBy: string) => {
    const [startDate, endDate] = analyticsPanelItems[4].value.split('/');
    this.subscriptions = [
      ...this.subscriptions,
      (forkJoin(
        [
          this.service.getSales(startDate, endDate),
          this.service.getSalesByOrderDate(groupBy),
          this.service.getSalesByCategory(startDate, endDate),
        ],
      ).subscribe(([sales, salesByDateAndCategory, salesByCategory]) => {
        this.sales = sales;
        this.salesByDateAndCategory = salesByDateAndCategory;
        this.salesByCategory = salesByCategory;
      })
      ),
    ];
  };

  customiseToolip({ seriesName }) {
    return { text: seriesName };
  }

  ngOnInit(): void {
    this.loadData(this.groupByPeriods[1].toLowerCase());
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach((sub) => sub.unsubscribe());
  }
}

@NgModule({
  imports: [
    DxToolbarModule,
    DxPieChartModule,
    DxChartModule,
    DxDropDownButtonModule,
    DxRangeSelectorModule,
    CardAnalyticsModule,
    ToolbarAnalyticsModule,

    CommonModule,
  ],
  providers: [],
  exports: [],
  declarations: [AnalyticsSalesReportComponent],
})
export class AnalyticsSalesReportModule { }

<div class="view-wrapper">

  <toolbar-analytics
    titleText="Sales Report"
  >
  </toolbar-analytics>

  <div class="cards wide">
    <card-analytics
      contentClass="sales-range"
      [isMenuVisible]="false"
    >
    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" fill="none" stroke="none" stroke-width="0" id="rangeSElector" class="dxrs
   dxrs-range-selector" width="964" height="90" style="line-height: normal;
   user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); display:
   block; overflow: hidden; touch-action: pan-y;" direction="ltr">
    <defs>
        <filter id="DevExpress_1" x="-50%" y="-50%" width="200%" height="200%" transform="translate(0,0)">
            <feGaussianBlur in="SourceGraphic" result="gaussianBlurResult" stdDeviation="3"></feGaussianBlur>
            <feOffset in="gaussianBlurResult" result="offsetResult" dx="2" dy="6"></feOffset>
            <feFlood result="floodResult" flood-color="" flood-opacity="0.8"></feFlood>
            <feComposite in="floodResult" in2="offsetResult" operator="in" result="compositeResult"></feComposite>
            <feComposite in="SourceGraphic" in2="compositeResult" operator="over"></feComposite>
        </filter>
        <clipPath id="DevExpress_2">
            <rect x="0" y="0" width="964" height="90" transform="translate(0,0)"></rect>
        </clipPath>
        <clipPath id="DevExpress_3">
            <rect x="24" y="20" width="916" height="51" transform="translate(0,0)"></rect>
        </clipPath>
    </defs>
    <g class="dxrs-view" clip-path="url(#DevExpress_3)">
        <g class="dxrs-series-group">
            <g class="dxc-series">
                <g class="dxc-elements" stroke="#1db2f5" stroke-width="2">
                    <path d="M 24 48 L 60 25 L 97 38 L 135 53 L 170 65 L 207
   65 L 243 63 L 280 69 L 316 70 L 354 56 L 391 62 L 427 52 L 465 71 L 501 66
   L 538 58 L 575 65 L 609 61 L 646 61 L 682 62 L 720 64 L 756 60 L 793 68 L
   830 62 L 867 63 L 904 63 L 940 59" transform="translate(0,0)" stroke-width="2"></path>
                </g>
                <g fill="#1db2f5" stroke="#1db2f5" stroke-width="0" r="6" visibility="hidden" class="dxc-markers"
                    opacity="1"></g>
            </g>
            <g class="dxc-labels" pointer-events="none" opacity="1" transform="translate(0,0)"></g>
        </g>
    </g>
    <g class="dxrs-slidersContainer" clip-path="url(#DevExpress_2)">
        <path d="M 24
   20 L 24 20 L 24 71 L 24 71 Z M 940 20 L 940 20 L 940 71 L 940 71 Z" transform="translate(0,0)" fill="#ffffff"
            fill-opacity="0.75"></path>
        <g class="slider" transform="translate(24,20)">
            <path d="M 0 0 L 0 51" transform="translate(0.5,0)" stroke-width="1" stroke="#03a9f4" stroke-opacity="0.5">
            </path>
            <g class="slider-marker" transform="translate(0,-20)">
                <path d="M 0 0 L 57 0 L 57 16 L 4 16 L 0 20 L
   0 16 L 0 16 Z" transform="translate(0,0)" fill="#03a9f4"></path><text x="0" y="0" transform="translate(4,12)"
                    text-anchor="start" style="white-space: pre; fill: rgb(255, 255, 255); font-size: 11px;
   font-family: Roboto, RobotoFallback, Helvetica, Arial, sans-serif;
   font-weight: 400; cursor: default;">11/1/2019</text>
            </g>
        </g>
        <g class="slider" transform="translate(940,20)">
            <path d="M 0 0 L 0 51" transform="translate(0.5,0)" stroke-width="1" stroke="#03a9f4" stroke-opacity="0.5">
            </path>
            <g class="slider-marker" transform="translate(0,-20)">
                <path d="M -56 0 L 1 0 L 1 16 L 1 16 L 1 20 L
   -3 16 L -56 16 Z" transform="translate(0,0)" fill="#03a9f4"></path><text id="range-text" x="0" y="0" transform="translate(-52,12)"
                    text-anchor="start" style="white-space: pre; fill: rgb(255, 255, 255); font-size: 11px;
   font-family: Roboto, RobotoFallback, Helvetica, Arial, sans-serif;
   font-weight: 400; cursor: default;">12/1/2021</text>
            </g>
        </g>
    </g>
    <g class="dxrs-scale" clip-path="url(#DevExpress_2)">
        <g class="dxrs-range-selector-axis" transform="translate(0,-5.5)">
            <g class="dxrs-range-selector-line">
                <path d="M 24 26 L 24 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 60 26
   L 60 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1" stroke-opacity="0.17" opacity="1"></path>
                <path d="M 97 26 L 97 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 135 26 L 135 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 170 26 L 170 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 207 26 L 207 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 243 26 L 243 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 280 26 L 280 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 316 26 L 316 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 354 26 L 354 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 391 26 L 391 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 427 26 L 427 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 465 26 L 465 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 501 26 L 501 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 538 26 L 538 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 575 26 L 575 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 609 26 L 609 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 646 26 L 646 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 682 26 L 682 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 720 26 L 720 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 756 26 L 756 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 793 26 L 793 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 830 26 L 830 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 867 26 L 867 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 904 26 L 904 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
                <path d="M 940 26 L 940 77" transform="translate(0.5,0)" stroke="#000000" stroke-width="1"
                    stroke-opacity="0.17" opacity="1"></path>
            </g>
            <g class="dxrs-range-selector-title"></g>
        </g>
    </g>
    <g class="dxrs-scale-elements" clip-path="url(#DevExpress_2)">
        <g class="dxrs-range-selector-elements" transform="translate(0,-5.5)"><text x="24" y="51"
                transform="translate(0,41.5)" text-anchor="middle" style="white-space: pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54);
   font-family: Roboto, RobotoFallback, Helvetica, Arial, sans-serif;
   font-weight: 400; cursor: default;">Nov 2019</text><text x="97" y="51" transform="translate(0,41.5)"
                text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">Jan 2020</text><text x="170" y="51" transform="translate(0,41.5)" text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">Mar 2020</text><text x="243" y="51" transform="translate(0,41.5)" text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">May 2020</text><text x="316" y="51" transform="translate(0,41.5)" text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">Jul 2020</text><text x="391" y="51" transform="translate(0,41.5)" text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">Sep 2020</text><text x="465" y="51" transform="translate(0,41.5)" text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">Nov 2020</text><text x="538" y="51" transform="translate(0,41.5)" text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">Jan 2021</text><text x="609" y="51" transform="translate(0,41.5)" text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">Mar 2021</text><text x="682" y="51" transform="translate(0,41.5)" text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">May 2021</text><text x="756" y="51" transform="translate(0,41.5)" text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">Jul 2021</text><text x="830" y="51" transform="translate(0,41.5)" text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">Sep 2021</text><text x="904" y="51" transform="translate(0,41.5)" text-anchor="middle" style="white-space:
   pre; font-size: 11px; fill: rgba(0, 0, 0, 0.54); font-family: Roboto,
   RobotoFallback, Helvetica, Arial, sans-serif; font-weight: 400; cursor:
   default;">Nov 2021</text></g>
    </g>
    <g class="dxrs-scale-breaks"></g>
</svg>
    </card-analytics>

    <card-analytics
      titleText="Product Sale by Range"
      contentClass="sales-by-category"
      [component]="bar"
    >
      <dx-pie-chart
        #pie
        class="sales-pie"
        [dataSource]="salesByCategory"
        type="doughnut"
        theme="material.blue.light.compact"
        [diameter]="0.8"
        [innerRadius]="0.6"
      >
        <dxi-series argumentField="name" valueField="value">
          <dxo-label backgroundColor="none" [radialOffset]="-20" [visible]="true" [customizeText]="customizeSaleText">
            <dxo-font color="#757575" [size]="15"></dxo-font>
          </dxo-label>
        </dxi-series>

        <dxo-legend>
          <dxo-margin [top]="70"></dxo-margin>
        </dxo-legend>

        <dxo-size [height]="270"></dxo-size>

        <dxo-legend [visible]="false"></dxo-legend>
      </dx-pie-chart>

      <dx-chart #bar class="sales-bars" [dataSource]="salesByCategory" [rotated]="true" theme="material.blue.light.compact">
        <dxo-common-axis-settings [visible]="false">
          <dxo-tick [visible]="false"></dxo-tick>
        </dxo-common-axis-settings>

        <dxo-legend [visible]="false"></dxo-legend>

        <dxo-common-series-settings argumentField="name" valueField="value" type="bar" [ignoreEmptyPoints]="true">
        </dxo-common-series-settings>

        <dxo-series-template nameField="name"> </dxo-series-template>

        <dxo-value-axis>
          <dxo-label>
            <dxo-format type="largeNumber"></dxo-format>
          </dxo-label>
        </dxo-value-axis>
      </dx-chart>
    </card-analytics>

    <card-analytics titleText="Sales Performance" className="sales" [component]="chart">
      <div filter class="sales-filter" >
      <dx-drop-down-button stylingMode="text" [useSelectMode]="true"
        [items]="groupByPeriods" [selectedItemKey]="groupByPeriods[1]" (onSelectionChanged)="selectionChange($event)">
      </dx-drop-down-button>
      </div>

      <dx-chart #chart [dataSource]="salesByDateAndCategory" theme="material.blue.light.compact">
        <dxo-argument-axis [visualRange]="visualRange"> </dxo-argument-axis>
        <dxo-tooltip [enabled]="true" [customizeTooltip]="customiseToolip"></dxo-tooltip>
        <dxo-series-template nameField="category"> </dxo-series-template>

        <dxo-common-series-settings argumentField="date" valueField="total" hoverMode="includePoints">
          <dxo-point hoverMode="allArgumentPoints"></dxo-point>
        </dxo-common-series-settings>

        <dxo-argument-axis argumentType="datetime" [valueMarginsEnabled]="false">
        </dxo-argument-axis>

        <dxo-legend [visible]="false"></dxo-legend>

        <dxo-size [height]="270"></dxo-size>
      </dx-chart>
    </card-analytics>
  </div>
</div>
<dx-load-panel
  container=".view-wrapper"
  [position]="{of: '.app-content-wrapper'}"
  [visible]="isLoading | apply: [sales, salesByCategory, salesByDateAndCategory]"
  [showPane]="true"
></dx-load-panel>
