// packages/react/src/components/user-menu-section/UserMenuSection.tsx
import React, { useMemo } from 'react';
import { useAuth } from '../../contexts/auth';
import List from 'devextreme-react/list';

import './UserMenuSection.scss';
import type { UserMenuSectionProps } from '../../types';

export const UserMenuSection = ({ showAvatar }: UserMenuSectionProps) => {
  const { user, signOut } = useAuth();

  const menuItems = useMemo(
    () => [
      {
        text: 'Logout',
        icon: 'runner',
        onClick: signOut,
      },
    ],
    [signOut]
  );

  return (
    <>
      <div className='user-info'>
        { showAvatar && (
          <div className='image-container'>
            <div
              style={{
                background: `url(${user?.avatarUrl}) no-repeat #fff`,
                backgroundSize: 'cover',
              }}
              className='user-image'
            />
          </div>
        )}
        <div className='user-name'>{user?.name}</div>
      </div>
      <List items={menuItems} />
    </>
  );
};

// packages/angular/src/app/components/user-menu-section/user-menu-section.component.ts
import { Component, NgModule, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DxListModule } from 'devextreme-angular/ui/list';
import { IUser } from '../../services/auth.service';

@Component({
  selector: 'user-menu-section',
  templateUrl: 'user-menu-section.component.html',
  styleUrls: ['./user-menu-section.component.scss'],
})

export class UserMenuSectionComponent {
  @Input()
  menuItems: any;

  @Input()
  showAvatar!: boolean;

  @Input()
  user!: IUser | null;

  constructor() {}
}

@NgModule({
  imports: [
    DxListModule,
    CommonModule,
  ],
  declarations: [UserMenuSectionComponent],
  exports: [UserMenuSectionComponent],
})
export class UserMenuSectionModule { }

<div>
  <div class="user-info">
    <div
      class="image-container"
      *ngIf="showAvatar"
    >
      <div
        [style.background]="'url(' + user?.avatarUrl + ') no-repeat #fff'"
        [style.backgroundSize]="'cover'"
        class="user-image"
      ></div>
    </div>
    <div class='user-name'>{{ user?.name }}</div>
  </div>
  <dx-list [items]="menuItems"></dx-list>
</div>
