// packages/vue/src/components/contact-new-form.vue
<template>
  <dx-form
    class="plain-styled-form"
  >
    <dx-form-item item-type="group">
      <dx-col-count-by-screen
        :xs="1"
        :sm="1"
        :md="1"
        :lg="1"
      />
      <dx-form-item class="uploader">
        <div>
          <form-photo-uploader />
        </div>
      </dx-form-item>
    </dx-form-item>

    <dx-form-item item-type="group">
      <dx-col-count-by-screen
        :xs="1"
        :sm="1"
        :md="2"
        :lg="2"
      />
      <dx-form-item>
        <form-textbox
          label="First Name"
          v-model="contact.firstName"
          :is-editing="true"
        />
      </dx-form-item>
      <dx-form-item css-class="accent">
        <form-textbox
          label="Last Name"
          v-model="contact.lastName"
          :is-editing="true"
        />
      </dx-form-item>
      <dx-form-item css-class="accent">
        <form-textbox
          label="Company"
          v-model="contact.company"
          :is-editing="true"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          label="Position"
          v-model="contact.position"
          :is-editing="true"
        />
      </dx-form-item>
    </dx-form-item>

    <dx-form-item
      item-type="group"
      css-class="contact-fields-group"
    >
      <dx-col-count-by-screen
        :xs="1"
        :sm="1"
        :md="2"
        :lg="2"
      />

      <dx-form-item css-class="accent">
        <form-textbox
          label="Assigned to"
          v-model="contact.manager"
          :is-editing="true"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model="contact.phone"
          :is-editing="true"
          icon="tel"
          mask="+1(000)000-0000"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model="contact.email"
          :is-editing="true"
          icon="email"
          :validators="[{type: 'email'}, {type: 'required'}]"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model="contact.address"
          :is-editing="true"
          icon="home"
        />
      </dx-form-item>
    </dx-form-item>
  </dx-form>
</template>

<script setup lang="ts">
import {
  DxForm,
  DxItem as DxFormItem,
  DxColCountByScreen,
} from 'devextreme-vue/form';
import { ref } from 'vue';
import { newContact } from '@/types/contact';
import FormTextbox from '@/components/form-textbox.vue';
import FormPhotoUploader from './form-photo-uploader.vue';

const contact = ref({ ...newContact });
</script>

// packages/angular/src/app/components/library/contact-new-form/contact-new-form.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxTextBoxModule,
  DxFormModule,
  DxValidatorModule,
} from 'devextreme-angular';
import {
  FormTextboxModule,
  FormPhotoUploaderModule,
} from 'src/app/components';
import { newContact } from 'src/app/types/contact';
import { getSizeQualifier } from 'src/app/services/screen.service';

@Component({
    selector: 'contact-new-form',
    templateUrl: './contact-new-form.component.html',
    imports: [
      DxTextBoxModule,
      DxFormModule,
      DxValidatorModule,
      FormTextboxModule,
      FormPhotoUploaderModule,
      CommonModule,
    ]
})

export class ContactNewFormComponent {
  newUser = newContact;

  getSizeQualifier = getSizeQualifier;

  getNewContactData = ()=> ({ ...this.newUser })
}

<dx-form class="plain-styled-form" [screenByWidth]="getSizeQualifier">
  <dxi-form-item itemType="group">
    <dxo-form-col-count-by-screen
      [xs]="1"
      [sm]="1"
      [md]="1"
      [lg]="1"
    ></dxo-form-col-count-by-screen>
    <dxi-form-item class="uploader">
      <div *dxTemplate>
        <form-photo-uploader></form-photo-uploader>
      </div>
    </dxi-form-item>
  </dxi-form-item>

  <dxi-form-item itemType="group">
    <dxo-form-col-count-by-screen
      [xs]="1"
      [sm]="2"
      [md]="2"
      [lg]="2"
    ></dxo-form-col-count-by-screen>
    <dxi-form-item>
      <div *dxTemplate>
        <form-textbox
          label="First Name"
          [(value)]="newUser.firstName"
          [isEditing]="true"
        >
        </form-textbox>
      </div>
    </dxi-form-item>
    <dxi-form-item>
      <div *dxTemplate>
        <form-textbox
          label="Last Name"
          [(value)]="newUser.lastName"
          [isEditing]="true"
        >
        </form-textbox>
      </div>
    </dxi-form-item>
    <dxi-form-item>
      <div *dxTemplate>
        <form-textbox
          label="Company"
          [(value)]="newUser.company"
          [isEditing]="true"
        >
        </form-textbox>
      </div>
    </dxi-form-item>
    <dxi-form-item>
      <div *dxTemplate>
        <form-textbox
          label="Position"
          [(value)]="newUser.position"
          [isEditing]="true"
        >
        </form-textbox>
      </div>
    </dxi-form-item>
  </dxi-form-item>

  <dxi-form-item itemType="group" cssClass="contact-fields-group">
    <dxo-form-col-count-by-screen
      [xs]="1"
      [sm]="2"
      [md]="2"
      [lg]="2"
    ></dxo-form-col-count-by-screen>
    <dxi-form-item>
      <div *dxTemplate>
        <form-textbox
          label="Assigned to"
          [(value)]="newUser.manager"
          [isEditing]="true"
        >
        </form-textbox>
      </div>
    </dxi-form-item>
    <dxi-form-item>
      <div *dxTemplate>
        <form-textbox
          icon="tel"
          label="Phone"
          mask="(000) 000-0000"
          [(value)]="newUser.phone"
          [isEditing]="true"
        >
        </form-textbox>
      </div>
    </dxi-form-item>
    <dxi-form-item>
      <div *dxTemplate>
        <form-textbox
          icon="email"
          label="Email"
          [(value)]="newUser.email"
          [validators]="[{ type: 'email' }, { type: 'required' }]"
          [isEditing]="true"
        ></form-textbox>
      </div>
    </dxi-form-item>
    <dxi-form-item>
      <div *dxTemplate>
        <form-textbox
          icon="home"
          label="Address"
          [(value)]="newUser.address"
          [isEditing]="true"
        ></form-textbox>
      </div>
    </dxi-form-item>
  </dxi-form-item>
</dx-form>
