// packages/react/src/components/profile-card/ProfileCard.tsx
import './ProfileCard.scss';
import React, { useRef } from 'react';
import Form, { Item, Label, ValidationRule } from 'devextreme-react/form';
import { StatusSelectBox } from '../status-select-box/StatusSelectBox';
import { PicturedItemSelectBox } from '../pictured-item-select-box/PicturedItemSelectBox';
import { useScreenSize, getSizeQualifier } from '../../utils/media-query';

interface ProfileCardItem {
  dataField: any,
  editorType: any,
  colSpan: number,
  label: string,
  validators: any[],
}

interface ProfileCardProps {
  items: ProfileCardItem[],
  colCount: number,
  title: string,
  cardData: any,
  onDataChanged: (cardData: any) => void,
}

const SwitchComponent = ({ item, cardData, onFieldChange }) => {
  switch (item.dataField) {
    case 'status': {
      return <StatusSelectBox
        labelMode='hidden'
        value={cardData[item.dataField]}
        onValueChange={onFieldChange(item.dataField)}
      />;
    }
    case 'supervisor': {
      return <PicturedItemSelectBox
        label={item.label}
        value={cardData[item.dataField]}
        items={item.itemsList}
        onValueChange={onFieldChange(item.dataField)}
      />;
    }
    case 'default': {
      return null;
    }
  }
  return null;
};

export const ProfileCard = ({
  items = [],
  colCount = 2,
  title = '',
  cardData,
  onDataChanged,
  children
}: React.PropsWithChildren<ProfileCardProps>) => {
  const { isXSmall } = useScreenSize();
  const formRef = useRef<Form>(null);
  const onFieldChange = (fieldName) => (value) => {
    const isValid = formRef.current?.instance.validate().isValid;

    if (!isValid) {
      return;
    }

    if (fieldName) {
      cardData[fieldName] = value;
    }

    onDataChanged(cardData);
  };

  return <div className='panel'>
    <div className='title-text panel-header'>
      {title}
    </div>
    <div className='form-container'>
      {children}
      <Form
        ref={formRef}
        formData={cardData}
        showColonAfterLabel
        colCount={isXSmall ? 2 : colCount}
        screenByWidth={getSizeQualifier}
        labelLocation='top'
        labelMode='outside'
        onFieldDataChanged={onFieldChange}
      >
        {items.map((item, index) => (
          <Item key={index}
            dataField={item.dataField}
            editorType={item.editorType}
            // editorOptions = {assign | apply:{stylingMode: 'outlined'}: item.editorOptions}
            colSpan={item.colSpan}>
            {item.label && <Label text={item.label} />}
            {item.validators.map((rule, index) =>
              <ValidationRule
                key={index}
                type={rule.type}
              />)
            }
            <SwitchComponent item={item} cardData={cardData} onFieldChange={onFieldChange} />
          </Item>
        ))}
      </Form>
    </div>
  </div>;
};

// packages/angular/src/app/components/library/profile-card/profile-card.component.ts
import {Component, EventEmitter, inject, Input, Output, ViewChild} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxDateBoxModule,
  DxFormComponent,
  DxFormModule,
  DxNumberBoxModule,
  DxSelectBoxModule,
  DxTextBoxModule,
  DxToolbarModule,
  DxValidatorModule,
  DxScrollViewModule
} from 'devextreme-angular';
import { FormTextboxModule } from 'src/app/components/utils/form-textbox/form-textbox.component';
import { ApplyPipeModule } from 'src/app/pipes/apply.pipe';
import { PicturedItemSelectBoxComponent } from 'src/app/components/library/pictured-item-select-box/pictured-item-select-box.component';
import { ScreenService } from 'src/app/services';
import { StatusSelectBoxComponent } from 'src/app/components/library/status-select-box/status-select-box.component';
import { getSizeQualifier } from 'src/app/services/screen.service';

type CardData = Record<string, any>;

@Component({
    selector: 'profile-card',
    templateUrl: './profile-card.component.html',
    styleUrls: ['profile-card.component.scss'],
    imports: [
      ApplyPipeModule,
      DxButtonModule,
      DxDateBoxModule,
      DxFormModule,
      DxNumberBoxModule,
      DxToolbarModule,
      DxSelectBoxModule,
      DxScrollViewModule,
      DxTextBoxModule,
      FormTextboxModule,
      DxValidatorModule,
      CommonModule,
      PicturedItemSelectBoxComponent,
      StatusSelectBoxComponent,
    ],
})
export class ProfileCardComponent {
  @ViewChild('form', { static: true }) form: DxFormComponent;

  @Input() items: Record<string, any>[] = [];

  @Input() colCount: number = 2;

  @Input() title: string = '';

  @Output() dataChanged = new EventEmitter<any>();

  @Input() cardData: CardData;

  getSizeQualifier = getSizeQualifier;

  assign = Object.assign;

  public screen = inject(ScreenService);

  onFieldChange(fieldName?, value?) {
    const {isValid} = this.form.instance.validate();

    if (!isValid) {
      return;
    }

    if (fieldName) {
      this.cardData[fieldName] = value;
    }

    this.dataChanged.emit(this.cardData);
  }
}

<div class="panel">
  <div class="title-text panel-header">
    {{ title }}
  </div>
  <div class="form-container">
    <ng-content select="[top-item]"></ng-content>
    <dx-form
      #form
      labelLocation="top"
      labelMode="outside"
      [formData]="cardData"
      [showColonAfterLabel]="true"
      [colCount]="(screen.xSmallScreenChanged | async) ? 2 : colCount"
      [screenByWidth]="getSizeQualifier"
      (onFieldDataChanged)="onFieldChange()"
    >
      <ng-container *ngFor="let item of items">
        <dxi-item
          [dataField]="item.dataField"
          [editorType]="item.editorType"
          [editorOptions]="
            assign
              | apply
                : { stylingMode: 'filled', valueChangeEvent: 'input' }
                : item.editorOptions
          "
          [colSpan]="item.colSpan"
        >
          <dxo-label *ngIf="item.label" [text]="item.label"> </dxo-label>
          <dxi-validation-rule
            *ngFor="let rule of item.validators"
            [type]="rule.type"
          ></dxi-validation-rule>
          <ng-container [ngSwitch]="item.dataField">
            <ng-container *ngSwitchCase="'status'">
              <div *dxTemplate>
                <status-select-box
                  labelMode="hidden"
                  stylingMode="filled"
                  [value]="cardData[item.dataField]"
                  (valueChange)="onFieldChange(item.dataField, $event)"
                >
                </status-select-box>
              </div>
            </ng-container>

            <ng-container *ngSwitchCase="'supervisor'">
              <pictured-item-select-box
                *dxTemplate
                [label]="item.label"
                [value]="cardData[item.dataField]"
                [items]="item.itemsList"
                (valueChange)="onFieldChange(item.dataField, $event)"
              ></pictured-item-select-box>
            </ng-container>
          </ng-container>
        </dxi-item>
      </ng-container>
    </dx-form>
  </div>
</div>
