// packages/angular/src/app/components/contact-form/contact-form.component.ts
import {
  Component, NgModule, Input,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxFormModule,
  DxLoadPanelModule,
  DxNumberBoxModule,
  DxSelectBoxModule,
  DxTextBoxModule,
  DxToolbarModule,
  DxValidatorModule,
  DxValidationGroupModule,
} from 'devextreme-angular';
import {
  ContactStatusModule,
  FormTextboxModule,
  FormPhotoModule,
} from 'src/app/components';
import { Contact, contactStatusList } from 'src/app/types/contact';
import { ValidationRule } from 'devextreme/ui/validation_rules';
import { ClickEvent } from 'devextreme/ui/button';

@Component({
  selector: 'contact-form',
  templateUrl: './contact-form.component.html',
  styleUrls: ['./contact-form.component.scss'],
})
export class ContactFormComponent {
  @Input() contactData: Contact;

  statusList = contactStatusList;

  isEditing = false;

  zipCodeValidator: ValidationRule = { type: 'pattern', pattern: /^\d{5}$/, message: 'Zip is invalid' };

  handleEditClick() {
    this.isEditing = true;
  }

  handleSaveClick({ validationGroup }: ClickEvent) {
    if(!validationGroup.validate().isValid) return;
    this.isEditing = false;
  }

  handleCancelClick() {
    this.isEditing = false;
  }
}

@NgModule({
  imports: [
    DxToolbarModule,
    DxFormModule,
    DxSelectBoxModule,
    DxButtonModule,
    DxTextBoxModule,
    DxNumberBoxModule,
    DxLoadPanelModule,
    DxValidationGroupModule,

    FormTextboxModule,
    ContactStatusModule,
    FormPhotoModule,
    DxValidatorModule,
    CommonModule,
  ],
  providers: [],
  exports: [ContactFormComponent],
  declarations: [ContactFormComponent],
})
export class ContactFormModule { }

<div id="contact-form">
  <dx-validation-group>
    <dx-toolbar>
      <dxi-item location="before"><span class="form-title">Details</span></dxi-item>
      <dxi-item location="after" locateInMenu="after" [visible]="!isEditing">
        <dx-button
          text="Edit"
          icon="edit"
          stylingMode="outlined"
          type="default"
          (onClick)="handleEditClick()"
        ></dx-button>
      </dxi-item>
      <dxi-item location="after" locateInMenu="after" [visible]="isEditing">
        <dx-button
          text="Save"
          stylingMode="outlined"
          type="default"
          (onClick)="handleSaveClick($event)"
        ></dx-button>
      </dxi-item>
      <dxi-item location="after" locateInMenu="after" [visible]="isEditing">
        <dx-button
          text="Cancel"
          (onClick)="handleCancelClick()"
          stylingMode="text"
        ></dx-button>
      </dxi-item>
    </dx-toolbar>

    <dx-form *ngIf="contactData"
              class="form last plain-styled-form"
              [formData]="contactData"
              labelMode="floating"
              [class.view-mode]="!isEditing">
      <dxi-item itemType="group" [colCount]="2">
        <dxo-col-count-by-screen [xs]="2"></dxo-col-count-by-screen>
        <dxi-item>
          <div *dxTemplate>
            <form-photo
              [link]="contactData.image"
              [size]="184"
            ></form-photo>
          </div>
        </dxi-item>
        <dxi-item itemType="group">
          <dxi-item>
            <div *dxTemplate>
              <dx-select-box
                label="Status"
                [(value)]="contactData.status"
                [items]="statusList"
                [readOnly]="!isEditing"
                stylingMode="filled"
                width="100%"
                fieldTemplate="field"
              >
                <div *dxTemplate="let data of 'field'" class="status-editor-field">
                  <contact-status class="status-indicator" [showText]="false" [value]="data"></contact-status>
                  <dx-text-box
                    class="status-{{data | lowercase}}"
                    [hoverStateEnabled]="false"
                    [inputAttr]="{class: 'status-input status-editor-input'}"
                    [readOnly]="true"
                    [value]="data">
                  </dx-text-box>
                </div>
                <div *dxTemplate="let data of 'item'">
                  <contact-status [value]="data"></contact-status>
                </div>
              </dx-select-box>
            </div>
          </dxi-item>

          <dxi-item>
            <div *dxTemplate>
              <form-textbox label="First Name"
                          [(value)]="contactData.firstName"
                          [isEditing]="isEditing"
              ></form-textbox>
            </div>
          </dxi-item>

          <dxi-item>
            <div *dxTemplate>
              <form-textbox label="Last Name"
                          [(value)]="contactData.lastName"
                          [isEditing]="isEditing"
              ></form-textbox>
            </div>
          </dxi-item>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <form-textbox label="Position"
                        [(value)]="contactData.position"
                        [isEditing]="isEditing"
            ></form-textbox>
          </div>
        </dxi-item>

        <dxi-item cssClass="accent">
          <div *dxTemplate>
            <form-textbox label="Assigned to"
                        [(value)]="contactData.manager"
                        [isEditing]="isEditing"
            ></form-textbox>
          </div>
        </dxi-item>

        <dxi-item cssClass="accent" [colSpan]="2">
          <div *dxTemplate>
            <form-textbox label="Company"
                        [(value)]="contactData.company"
                        [isEditing]="isEditing"
            ></form-textbox>
          </div>
        </dxi-item>
      </dxi-item>

      <dxi-item itemType="group" [colCount]="4" caption="Contacts">
        <dxo-col-count-by-screen [xs]="2"></dxo-col-count-by-screen>
        <dxi-item [colSpan]="4">
          <div *dxTemplate>
            <form-textbox label="Address"
                        [(value)]="contactData.address"
                        [isEditing]="isEditing"
            ></form-textbox>
        </div>
        </dxi-item>

        <dxi-item  [colSpan]="2">
          <div *dxTemplate>
            <form-textbox label="City"
                        [(value)]="contactData.city"
                        [isEditing]="isEditing"
            ></form-textbox>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <form-textbox label="State"
                        [(value)]="contactData.state.stateShort"
                        [isEditing]="isEditing"
            ></form-textbox>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <dx-number-box  label="Zip Code"
              [(value)]="contactData.zipCode"
              [readOnly]="!isEditing"
              [elementAttr]="{class: 'form-editor'}"
              [inputAttr]="{class: 'form-editor-input'}"
              stylingMode="filled"
              valueChangeEvent="keyup input change"
            >
              <dx-validator [validationRules]="[zipCodeValidator]"></dx-validator>
            </dx-number-box>
          </div>
        </dxi-item>
      </dxi-item>

      <dxi-item itemType="group" [colCount]="2" cssClass="contact-fields-group">
        <dxo-col-count-by-screen [xs]="2"></dxo-col-count-by-screen>
        <dxi-item>
          <div *dxTemplate>
            <form-textbox label="Phone"
                        [(value)]="contactData.phone"
                        [isEditing]="isEditing"
                        mask="+1(000)000-0000"
                        [validators]="[]"
            ></form-textbox>
            <dx-button class="form-item-button"
                      [visible]="!isEditing"
                      [text]="'Call'"
                      [icon]="'tel'"
                      [type]="'default'"
                      stylingMode="outlined"
            ></dx-button>
          </div>
        </dxi-item>

        <dxi-item>
          <div *dxTemplate>
            <form-textbox label="Email"
                        [(value)]="contactData.email"
                        [isEditing]="isEditing"
                        [validators]="[{type: 'email'}]"
            ></form-textbox>
            <dx-button class="form-item-button"
                      [visible]="!isEditing"
                      [text]="'Send Email'"
                      [icon]="'email'"
                      [type]="'default'"
                      stylingMode="outlined"
            ></dx-button>
          </div>
        </dxi-item>
      </dxi-item>
    </dx-form>
  </dx-validation-group>
  <dx-load-panel
    container="#contact-form"
    [position]="{ of: '#contact-form' }"
    [visible]="!contactData || isLoading"
    [showPane]="false"
  ></dx-load-panel>
</div>

// packages/vue/src/pages/crm-contact-details/components/contact-form.vue
<template>
  <div id="contact-form" >
    <dx-toolbar>
      <dx-toolbar-item location="before">
        <span class="dx-form-group-caption">Details</span>
      </dx-toolbar-item>
      <dx-toolbar-item location="after" locateInMenu="after" :visible="!isEditing">
        <dx-button
          text="Edit"
          icon="edit"
          stylingMode="outlined"
          type="default"
          :visible="!isLoading"
          @click="startEdit()"
        ></dx-button>
      </dx-toolbar-item>
      <dx-toolbar-item location="after" locateInMenu="after" :visible="isEditing">
        <dx-button
          text="Save"
          stylingMode="outlined"
          type="default"
          @click="saveEdit()"
        ></dx-button>
      </dx-toolbar-item>
      <dx-toolbar-item location="after" locateInMenu="after" :visible="isEditing">
        <dx-button
          text="Cancel"
          @click="cancelEdit()"
          styling-mode="text"
        ></dx-button>
      </dx-toolbar-item>
    </dx-toolbar>
    <load-component :is-loading="isLoading"
                    :container-selector="'#contact-form'">
        <dx-form class="plain-styled-form"
                 :class="{'view-mode': !isEditing}"
                 labelMode="floating">
          <dx-form-group-item :col-count="2">
            <dx-col-count-by-screen :xs="2"/>
            <dx-form-item>
              <user-photo :link="contactData.image" :size="184"/>
            </dx-form-item>

            <dx-form-group-item>
              <dx-form-item>
                <dx-select-box label="Status"
                               v-model="contactData.status"
                               :items="contactStatusList"
                               :read-only="!isEditing"
                               :element-attr="{class: 'form-editor'}"
                               :input-attr="{class: 'form-editor-input'}"
                               field-template="field"
                               item-template="item"
                >
                  <template #field>
                    <div class="status-editor-field">
                      <contact-status :status="contactData?.status" class="contact-status"/>
                      <dx-text-box :read-only="true"/>
                    </div>

                  </template>
                  <template #item="{ data }">
                    <contact-status :status="data" class="contact-status"/>
                  </template>
                </dx-select-box>
              </dx-form-item>

              <dx-form-item>
                <form-textbox label="First Name"
                              v-model="contactData.firstName"
                              :is-editing = "isEditing"/>
              </dx-form-item>

              <dx-form-item>
                <form-textbox label="Last Name"
                              v-model="contactData.lastName"
                              :is-editing = "isEditing"/>
              </dx-form-item>
            </dx-form-group-item>

            <dx-form-item>
              <form-textbox label="Position"
                            v-model="contactData.position"
                            :is-editing = "isEditing"/>
            </dx-form-item>

            <dx-form-item cssClass="accent">
              <form-textbox label="Assigned to"
                            v-model="contactData.manager"
                            :is-editing = "isEditing"/>
            </dx-form-item>

            <dx-form-item :col-span="2" cssClass="accent">
              <form-textbox label="Company"
                            v-model="contactData.company"
                            :is-editing = "isEditing"
              />
            </dx-form-item>
          </dx-form-group-item>

          <dx-form-group-item :col-count="4" caption="Contacts">
            <dx-col-count-by-screen :xs="2"></dx-col-count-by-screen>
            <dx-form-item :col-span="4" >
              <form-textbox label="Address"
                            v-model="contactData.address"
                            :is-editing = "isEditing"
              />
            </dx-form-item>
            <dx-form-item :col-span="2">
              <form-textbox label="City"
                            v-model="contactData.city"
                            :is-editing = "isEditing"/>
            </dx-form-item>

            <dx-form-item>
              <form-textbox label="State"
                            v-model="contactData.state.stateShort"
                            :is-editing = "isEditing"/>
            </dx-form-item>
            <dx-form-item>
              <form-textbox label="Zip Code"
                            v-model.number="contactData.zipCode"
                            :is-editing = "isEditing"
                            :validators="[zipCodeValidator]"
              />
            </dx-form-item>
          </dx-form-group-item>
          <dx-form-group-item :col-count="2" cssClass="contact-fields-group">
            <dx-col-count-by-screen :xs="2"></dx-col-count-by-screen>
            <dx-form-item>
              <form-textbox label="Phone"
                            v-model.number="contactData.phone"
                            :is-editing = "isEditing"
                            mask="+1(000)000-0000"/>
              <dx-button v-if="!isEditing"
                         class="form-item-button"
                         v-bind="{
                                  text: 'Call',
                                  icon: 'tel',
                                  type: 'default',
                                  stylingMode: 'outlined'
                                 }"
                         :validators="[]"/>
            </dx-form-item>
            <dx-form-item>
              <form-textbox label="Email"
                            v-model.number="contactData.email"
                            :is-editing = "isEditing"
                            :validators="[{type: 'email'}]"/>
              <dx-button v-if="!isEditing"
                         class="form-item-button"
                         v-bind="{
                               text: 'Send Email',
                               icon: 'email',
                               type: 'default',
                               stylingMode: 'outlined'
                              }"/>
            </dx-form-item>
          </dx-form-group-item>
        </dx-form>
    </load-component>
  </div>

</template>
<script setup lang="ts">
import { ref, watch } from 'vue';

import { DxButton } from 'devextreme-vue/button';
import {
  DxToolbar,
  DxItem as DxToolbarItem,
} from 'devextreme-vue/toolbar';

import {
  DxForm,
  DxItem as DxFormItem,
  DxGroupItem as DxFormGroupItem,
  DxColCountByScreen,
} from 'devextreme-vue/form';
import { DxTextBox } from 'devextreme-vue/text-box';
import { DxSelectBox } from 'devextreme-vue';
import LoadComponent from '@/components/load-component.vue';
import { Contact, contactStatusList } from '@/types/contact';
import UserPhoto from '@/components/user-photo.vue';
import ContactStatus from '@/components/contact-status.vue';
import FormTextbox from '@/components/form-textbox.vue';

const emptyContact = { state: { stateShort: '' } } as Contact;

const props = withDefaults(defineProps<{
  isLoading: boolean,
  contactData: Contact | null
}>(), {
  isLoading: true,
  contactData: null,
});

const isEditing = ref(false);
const contactData = ref(emptyContact);

let contactDataSaved = emptyContact;
const zipCodeValidator = { type: 'pattern', pattern: /^\d{5}$/, message: 'Zip is invalid' };

watch(
  () => props.contactData,
  (contactDataNew: Contact| null) => {
    contactData.value = contactDataNew || emptyContact;
  },
);

function startEdit() {
  contactDataSaved = { ...contactData.value };
  isEditing.value = true;
}

function saveEdit() {
  isEditing.value = false;
}

function cancelEdit() {
  contactData.value = contactDataSaved;
  isEditing.value = false;
}
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

#contact-form {
  min-height: 300px;

  .form-title {
    font-size: 16px;
  }

  .dx-toolbar {
    margin-bottom: $toolbar-margin-bottom;
  }
}

.plain-styled-form {
  .form-item-button {
    margin-left: 10px;
    margin-top: 5px;
  }
}

.info {
  position: relative;
  padding-bottom: 30px;

  contact-status {
    position: absolute;
    margin-top: 20px;
  }
}

.status-editor-field {
  .contact-status {
    position: absolute;
    bottom: 0;
    font-size: 13px;
    padding-left: calc(#{$filled-texteditor-input-horizontal-padding} + 2px);
  }
}
</style>
