// packages/angular/src/app/pages/crm-contact-details/contact-form/contact-form.component.ts
import {
  Component, NgModule, Input,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
  DxFormModule,
  DxLoadPanelModule, DxNumberBoxModule,
  DxSelectBoxModule,
  DxTextBoxModule,
  DxToolbarModule,
  DxValidatorModule,
} from 'devextreme-angular';
import {
  ContactStatusModule,
  FormTextboxModule,
  FormPhotoModule,
} from 'src/app/shared/components';
import { Contact, contactStatusList } from 'src/app/shared/types/contact';
import { ValidationRule } from 'devextreme/ui/validation_rules';

@Component({
  selector: 'contact-form',
  templateUrl: './contact-form.component.html',
  styleUrls: ['./contact-form.component.scss'],
})
export class ContactFormComponent {
  @Input() contactData: Contact;

  statusList = contactStatusList;

  isEditing = false;

  zipCodeValidator: ValidationRule = { type: 'pattern', pattern: /^\d{5}$/, message: 'Zip is invalid' };

  handleEditClick() {
    this.isEditing = true;
  }

  handleSaveClick() {
    this.isEditing = false;
  }

  handleCancelClick() {
    this.isEditing = false;
  }
}

@NgModule({
  imports: [
    DxToolbarModule,
    DxFormModule,
    DxSelectBoxModule,
    DxButtonModule,
    DxTextBoxModule,
    DxNumberBoxModule,
    DxLoadPanelModule,

    FormTextboxModule,
    ContactStatusModule,
    FormPhotoModule,
    DxValidatorModule,
    CommonModule,
  ],
  providers: [],
  exports: [ContactFormComponent],
  declarations: [ContactFormComponent],
})
export class ContactFormModule { }

<div id="contact-form">
  <dx-toolbar>
    <dxi-item location="before"><span class="form-title">Details</span></dxi-item>
    <dxi-item location="after" locateInMenu="after" [visible]="!isEditing">
      <dx-button
        text="Edit"
        icon="edit"
        stylingMode="outlined"
        type="default"
        (onClick)="handleEditClick()"
      ></dx-button>
    </dxi-item>
    <dxi-item location="after" locateInMenu="after" [visible]="isEditing">
      <dx-button
        text="Save"
        stylingMode="outlined"
        type="default"
        (onClick)="handleSaveClick()"
      ></dx-button>
    </dxi-item>
    <dxi-item location="after" locateInMenu="after" [visible]="isEditing">
      <dx-button
        text="Cancel"
        (onClick)="handleCancelClick()"
        stylingMode="text"
      ></dx-button>
    </dxi-item>
  </dx-toolbar>

  <div class="form-compact">
    <dx-form #contactForm
      *ngIf="!isLoading"
      class="form last"
      [formData]="contactData$"
      labelMode="floating"
      [validationGroup]="validationGroup"
    >
      <dxi-item itemType="group" [colCount]="2">
        <dxi-item>
          <form-item-photo
            [link]="contactData$.image"
            [size]="184"
          ></form-item-photo>
        </dxi-item>
        <dxi-item itemType="group">
          <dxi-item>
            <edit-view-item label="Status"
                             [isEditing]="isEditing"
                             [value]="contactData$.status"
            >
              <contact-status view-content [value]="contactData$.status"></contact-status>
              <dx-select-box editor-content
                             label="Status"
                             [(value)]="contactData$.status"
                             [items]="statusList"
                             [readOnly]="!isEditing"
                             width="100%"
                             fieldTemplate="field"
              >
                <div *dxTemplate="let data of 'field'">
                  <div class="form-custom-list-prop">
                    <contact-status [value]="contactData$.status"></contact-status>
                    <dx-text-box [readOnly]="true"></dx-text-box>
                  </div>
                </div>
                <div *dxTemplate="let data of 'item'">
                  <contact-status [value]="data"></contact-status>
                </div>
              </dx-select-box>
            </edit-view-item>
          </dxi-item>

          <dxi-item>
            <edit-view-item label="First Name"
                            [isEditing]="isEditing"
                            [validators]="[{type: 'required'}]"
                            [validationGroup]="validationGroup"
                            [(value)]="contactData$.firstName"></edit-view-item>
          </dxi-item>

          <dxi-item>
            <edit-view-item label="Last Name"
                            [isEditing]="isEditing"
                            [validators]="[{type: 'required'}]"
                            [validationGroup]="validationGroup"
                            [(value)]="contactData$.lastName"></edit-view-item>
          </dxi-item>
        </dxi-item>

        <dxi-item>
          <edit-view-item label="Position"
                          [isEditing]="isEditing"
                          [validators]="[{type: 'required'}]"
                          [validationGroup]="validationGroup"
                          [(value)]="contactData$.position"></edit-view-item>
        </dxi-item>

        <dxi-item cssClass="accent">
          <edit-view-item label="Assigned to"
                          [isEditing]="isEditing"
                          [validators]="[{type: 'required'}]"
                          [validationGroup]="validationGroup"
                          [(value)]="contactData$.manager"></edit-view-item>
        </dxi-item>

        <dxi-item cssClass="accent" [colSpan]="2">
          <edit-view-item label="Company"
                         [isEditing]="isEditing"
                         [validators]="[{type: 'required'}]"
                         [validationGroup]="validationGroup"
                         [(value)]="contactData$.company"></edit-view-item>
        </dxi-item>
      </dxi-item>

      <dxi-item itemType="group" [colCount]="4" caption="Contacts">
        <dxi-item [colSpan]="4">
          <edit-view-item label="Address"
                          [isEditing]="isEditing"
                          [validators]="[{type: 'required'}]"
                          [validationGroup]="validationGroup"
                          [(value)]="contactData$.address"></edit-view-item></dxi-item>

        <dxi-item  [colSpan]="2" >
          <edit-view-item label="City"
                           [isEditing]="isEditing"
                           [validators]="[{type: 'required'}]"
                           [validationGroup]="validationGroup"
                           [(value)]="contactData$['city']"></edit-view-item>
        </dxi-item>

        <dxi-item>
          <edit-view-item label="State"
                           [isEditing]="isEditing"
                           [(value)]="contactData$.state.stateShort"
          ></edit-view-item>
        </dxi-item>

        <dxi-item>
          <edit-view-item label="Zip Code"
                          [isEditing]="isEditing"
                          [validators]="[zipCodeValidator]"
                          [validationGroup]="validationGroup"
                          [(value)]="contactData$.zipCode"></edit-view-item>
        </dxi-item>

        <dxi-item [colSpan]="2">
          <edit-view-item label="Phone"
                           [isEditing]="isEditing"
                           [value]="contactData$.phone"
                           mask="+1(000)000-0000"
                           [renderedValue]="contactData$.phone | phone"
          ></edit-view-item>
          <dx-button class="form-item-button"
                     [visible]="!isEditing"
                     [text]="'Call'"
                     [icon]="'tel'"
                     [type]="'default'"
                     stylingMode="outlined"
          ></dx-button>
        </dxi-item>

        <dxi-item [colSpan]="2">
          <edit-view-item label="Email"
                           [isEditing]="isEditing"
                           [value]="contactData$.email"
                           [validators]="[{type: 'email'}] "
          ></edit-view-item>
          <dx-button class="form-item-button"
                     [visible]="!isEditing"
                     [text]="'Send Email'"
                     [icon]="'email'"
                     [type]="'default'"
                     stylingMode="outlined"
          ></dx-button>
        </dxi-item>
      </dxi-item>

    </dx-form>
  </div>
  <dx-load-panel
    container="#contact-form"
    [position]="{ of: '#contact-form' }"
    [visible]="isLoading"
    [showPane]="false"
  ></dx-load-panel>
</div>

// packages/vue/src/pages/crm-contact-details/components/contact-form.vue
<template>
  <div id="contact-form" >
    <dx-toolbar>
      <dx-toolbar-item location="before">
        <span class="dx-form-group-caption">Details</span>
      </dx-toolbar-item>
      <dx-toolbar-item location="after" locateInMenu="after" :visible="!isEditing">
        <dx-button
          text="Edit"
          icon="edit"
          stylingMode="outlined"
          type="default"
          :visible="!isLoading"
          @click="startEdit()"
        ></dx-button>
      </dx-toolbar-item>
      <dx-toolbar-item location="after" locateInMenu="after" :visible="isEditing">
        <dx-button
          text="Save"
          stylingMode="outlined"
          type="default"
          @click="saveEdit()"
        ></dx-button>
      </dx-toolbar-item>
      <dx-toolbar-item location="after" locateInMenu="after" :visible="isEditing">
        <dx-button
          text="Cancel"
          @click="cancelEdit()"
          styling-mode="text"
        ></dx-button>
      </dx-toolbar-item>
    </dx-toolbar>
    <load-component :is-loading="isLoading"
                    :container-selector="'#contact-form'">
        <dx-form class="plain-styled-form"
                 :class="{'view-mode': !isEditing}"
                 labelMode="floating">
          <dx-form-group-item :col-count="2">
            <dx-col-count-by-screen :xs="2"/>
            <dx-form-item>
              <user-photo :link="contactData.image" :size="184"/>
            </dx-form-item>

            <dx-form-group-item>
              <dx-form-item>
                <dx-select-box label="Status"
                               v-model="contactData.status"
                               :items="contactStatusList"
                               :read-only="!isEditing"
                               :element-attr="{class: 'form-editor'}"
                               :input-attr="{class: 'form-editor-input'}"
                               field-template="field"
                               item-template="item"
                >
                  <template #field>
                    <div class="status-editor-field">
                      <contact-status :status="contactData?.status" class="contact-status"/>
                      <dx-text-box :read-only="true"/>
                    </div>

                  </template>
                  <template #item="{ data }">
                    <contact-status :status="data" class="contact-status"/>
                  </template>
                </dx-select-box>
              </dx-form-item>

              <dx-form-item>
                <form-textbox label="First Name"
                              v-model="contactData.firstName"
                              :is-editing = "isEditing"/>
              </dx-form-item>

              <dx-form-item>
                <form-textbox label="Last Name"
                              v-model="contactData.lastName"
                              :is-editing = "isEditing"/>
              </dx-form-item>
            </dx-form-group-item>

            <dx-form-item>
              <form-textbox label="Position"
                            v-model="contactData.position"
                            :is-editing = "isEditing"/>
            </dx-form-item>

            <dx-form-item cssClass="accent">
              <form-textbox label="Assigned to"
                            v-model="contactData.manager"
                            :is-editing = "isEditing"/>
            </dx-form-item>

            <dx-form-item :col-span="2" cssClass="accent">
              <form-textbox label="Company"
                            v-model="contactData.company"
                            :is-editing = "isEditing"
              />
            </dx-form-item>
          </dx-form-group-item>

          <dx-form-group-item :col-count="4" caption="Contacts">
            <dx-col-count-by-screen :xs="2"></dx-col-count-by-screen>
            <dx-form-item :col-span="4" >
              <form-textbox label="Address"
                            v-model="contactData.address"
                            :is-editing = "isEditing"
              />
            </dx-form-item>
            <dx-form-item :col-span="2">
              <form-textbox label="City"
                            v-model="contactData.city"
                            :is-editing = "isEditing"/>
            </dx-form-item>

            <dx-form-item>
              <form-textbox label="State"
                            v-model="contactData.state.stateShort"
                            :is-editing = "isEditing"/>
            </dx-form-item>
            <dx-form-item>
              <form-textbox label="Zip Code"
                            v-model.number="contactData.zipCode"
                            :is-editing = "isEditing"
                            :validators="[zipCodeValidator]"
              />
            </dx-form-item>
          </dx-form-group-item>
          <dx-form-group-item :col-count="2" cssClass="contact-fields-group">
            <dx-col-count-by-screen :xs="2"></dx-col-count-by-screen>
            <dx-form-item>
              <form-textbox label="Phone"
                            v-model.number="contactData.phone"
                            :is-editing = "isEditing"
                            mask="+1(000)000-0000"/>
              <dx-button v-if="!isEditing"
                         class="form-item-button"
                         v-bind="{
                                  text: 'Call',
                                  icon: 'tel',
                                  type: 'default',
                                  stylingMode: 'outlined'
                                 }"
                         :validators="[]"/>
            </dx-form-item>
            <dx-form-item>
              <form-textbox label="Email"
                            v-model.number="contactData.email"
                            :is-editing = "isEditing"
                            :validators="[{type: 'email'}]"/>
              <dx-button v-if="!isEditing"
                         class="form-item-button"
                         v-bind="{
                               text: 'Send Email',
                               icon: 'email',
                               type: 'default',
                               stylingMode: 'outlined'
                              }"/>
            </dx-form-item>
          </dx-form-group-item>
        </dx-form>
    </load-component>
  </div>

</template>
<script setup lang="ts">
import { ref, watch } from 'vue';

import { DxButton } from 'devextreme-vue/button';
import {
  DxToolbar,
  DxItem as DxToolbarItem,
} from 'devextreme-vue/toolbar';

import {
  DxForm,
  DxItem as DxFormItem,
  DxGroupItem as DxFormGroupItem,
  DxColCountByScreen,
} from 'devextreme-vue/form';
import { DxTextBox } from 'devextreme-vue/text-box';
import { DxSelectBox } from 'devextreme-vue';
import LoadComponent from '@/components/load-component.vue';
import { Contact, contactStatusList } from '@/types/contact';
import UserPhoto from '@/components/user-photo.vue';
import ContactStatus from '@/components/contact-status.vue';
import FormTextbox from '@/components/form-textbox.vue';

const emptyContact = { state: { stateShort: '' } } as Contact;

const props = withDefaults(defineProps<{
  isLoading: boolean,
  contactData: Contact | null
}>(), {
  isLoading: true,
  contactData: null,
});

const isEditing = ref(false);
const contactData = ref(emptyContact);

let contactDataSaved = emptyContact;
const zipCodeValidator = { type: 'pattern', pattern: /^\d{5}$/, message: 'Zip is invalid' };

watch(
  () => props.contactData,
  (contactDataNew: Contact| null) => {
    contactData.value = contactDataNew || emptyContact;
  },
);

function startEdit() {
  contactDataSaved = { ...contactData.value };
  isEditing.value = true;
}

function saveEdit() {
  isEditing.value = false;
}

function cancelEdit() {
  contactData.value = contactDataSaved;
  isEditing.value = false;
}
</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

#contact-form {
  min-height: 300px;

  .form-title {
    font-size: 16px;
  }

  .dx-toolbar {
    margin-bottom: $toolbar-margin-bottom;
  }
}

.plain-styled-form {
  .form-item-button {
    margin-left: 10px;
    margin-top: 5px;
  }
}

.info {
  position: relative;
  padding-bottom: 30px;

  contact-status {
    position: absolute;
    margin-top: 20px;
  }
}

.status-editor-field {
  .contact-status {
    position: absolute;
    bottom: 0;
    font-size: 13px;
    padding-left: calc(#{$filled-texteditor-input-horizontal-padding} + 2px);
  }
}
</style>
