// packages/angular/src/app/components/utils/revenue-analysis-card/revenue-analysis-card.component.ts
import { Component, Input } from '@angular/core';
import { CardAnalyticsComponent } from '../../library/card-analytics/card-analytics.component';
import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';
import { DxBulletModule } from 'devextreme-angular/ui/bullet';
import { SalesByState } from 'src/app/types/analytics';

@Component({
  selector: 'revenue-analysis-card',
  templateUrl: './revenue-analysis-card.component.html',
  styleUrls: ['./revenue-analysis-card.component.scss'],
  imports: [
    CardAnalyticsComponent,
    DxDataGridModule,
    DxBulletModule,
  ],
})
export class RevenueAnalysisCardComponent {
  @Input() data: SalesByState;
}

<card-analytics titleText="Revenue Analysis" contentClass="sales-by-state grid">
  <dx-data-grid
    [dataSource]="data ?? undefined"
    [height]="290"
    [loadPanel]="{ enabled: false }"
  >
    <dxi-data-grid-column caption="State" dataField="stateName"> </dxi-data-grid-column>

    <dxi-data-grid-column
      alignment="left"
      caption="Sales"
      dataField="total"
      dataType="number"
      format="currency"
      sortOrder="desc"
      [hidingPriority]="2"
    >
    </dxi-data-grid-column>

    <dxi-data-grid-column
      alignment="left"
      caption="% Sold"
      dataField="percentage"
      name="percentN"
      format="percent"
      [hidingPriority]="1"
    >
    </dxi-data-grid-column>

    <dxi-data-grid-column
      alignment="left"
      caption="Percentage"
      dataField="percentage"
      name="percentB"
      cellTemplate="salesBullet"
      cssClass="sales-bullet"
      [width]="200"
    >
    </dxi-data-grid-column>

    <div *dxTemplate="let cellInfo of 'salesBullet'">
      <dx-bullet
        [showTarget]="false"
        [showZeroLevel]="false"
        [value]="cellInfo.data.percentage * 100"
        [startScaleValue]="0"
        [endScaleValue]="100"
      >
        <dxo-bullet-tooltip [enabled]="false"></dxo-bullet-tooltip>
        <dxo-bullet-size [width]="200" [height]="20"></dxo-bullet-size>
      </dx-bullet>
    </div>
  </dx-data-grid>
</card-analytics>

// packages/react/src/components/revenue-analysis-card/RevenueAnalysisCard.tsx
import React from 'react';
import Bullet, { Size, Tooltip } from 'devextreme-react/bullet';
import DataGrid, { Column } from 'devextreme-react/data-grid';
import { CardAnalytics } from '../card-analytics/CardAnalytics';
import { SaleByState } from '../../types/analytics';

export const RevenueAnalysisCard = ({ datasource }: { datasource: SaleByState[] }) => (
  <CardAnalytics title='Revenue Analysis' contentClass='sales-by-state grid'>
    <DataGrid dataSource={datasource} height={290}>
      <Column caption='State' dataField='stateName' />
      <Column alignment='left' caption='Sales' dataField='total' dataType='number' format='currency' sortOrder='desc' hidingPriority={2} />
      <Column alignment='left' caption='% Sold' dataField='percentage' name='percentN' format='percent' hidingPriority={1} />
      <Column
        alignment='left'
        caption='Percentage'
        dataField='percentage'
        cssClass='sales-bullet'
        name='percentB'
        cellRender={(cellInfo) => (
          <Bullet showTarget={false} showZeroLevel={false} value={cellInfo.data.percentage * 100} startScaleValue={0} endScaleValue={100}>
            <Tooltip enabled={false} />
            <Size width={200} height={20} />
          </Bullet>
        )}
        width={200}
      />
    </DataGrid>
  </CardAnalytics>
);
