// packages/react/src/components/utils/chat-empty-view/ChatEmptyView.tsx
import './ChatEmptyView.scss';

import React from 'react';

export type ChatEmptyViewTexts = {
  message: string;
  prompt: string;
};

type ChatEmptyViewProps = {
  texts: ChatEmptyViewTexts;
  onPromptClick: (messageText: string) => void;
};

const EMPTY_VIEW_PROMPTS = [
  {
    id: 'trends',
    title: '🎯 Trends',
    description: 'Identify trends in your business',
    messageText: 'Identify trends in the business shown in this dashboard.',
  },
  {
    id: 'predictions',
    title: '📊 Predictions',
    description: 'Predict which deals are at risk of closing',
    messageText: 'Predict which deals are at risk of closing based on this dashboard.',
  },
];

export const ChatEmptyView = ({ texts, onPromptClick }: ChatEmptyViewProps) => {
  return (
    <div
      className='chat-empty-view'
      aria-label={`${texts.message}. ${texts.prompt}`}
    >
      <div className='chat-empty-view__header'>
        <div className='chat-empty-view__title'>Ask AI Assistant</div>
      </div>

      <div className='chat-empty-view__prompts'>
        {EMPTY_VIEW_PROMPTS.map((prompt) => (
          <button
            key={prompt.id}
            type='button'
            className='chat-empty-view__prompt'
            onClick={() => onPromptClick(prompt.messageText)}
            aria-label={`${prompt.title}. ${prompt.description}`}
          >
            <span className='chat-empty-view__prompt-content'>
              <span className='chat-empty-view__prompt-title'>{prompt.title}</span>
              <span className='chat-empty-view__prompt-description'>
                {prompt.description}
              </span>
            </span>
          </button>
        ))}
      </div>
    </div>
  );
};

// packages/angular/src/app/components/utils/chat-empty-view/chat-empty-view.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

export type ChatEmptyViewTexts = {
  message: string;
  prompt: string;
};

const EMPTY_VIEW_PROMPTS = [
  {
    id: 'trends',
    title: '🎯 Trends',
    description: 'Identify trends in your business',
    messageText: 'Identify trends in the business shown in this dashboard.',
  },
  {
    id: 'predictions',
    title: '📊 Predictions',
    description: 'Predict which deals are at risk of closing',
    messageText: 'Predict which deals are at risk of closing based on this dashboard.',
  },
];

@Component({
  selector: 'chat-empty-view',
  templateUrl: './chat-empty-view.component.html',
  styleUrls: ['./chat-empty-view.component.scss'],
})
export class ChatEmptyViewComponent {
  @Input() texts: ChatEmptyViewTexts = {
    message: '',
    prompt: '',
  };

  @Output() promptClick = new EventEmitter<string>();

  prompts = EMPTY_VIEW_PROMPTS;
}

<div
  class="chat-empty-view"
  [attr.aria-label]="texts.message + '. ' + texts.prompt"
>
  <div class="chat-empty-view__header">
    <div class="chat-empty-view__title">Ask AI Assistant</div>
  </div>

  <div class="chat-empty-view__prompts">
    @for (prompt of prompts; track prompt.id) {
    <button
      type="button"
      class="chat-empty-view__prompt"
      [attr.aria-label]="prompt.title + '. ' + prompt.description"
      (click)="promptClick.emit(prompt.messageText)"
    >
      <span class="chat-empty-view__prompt-content">
        <span class="chat-empty-view__prompt-title">{{ prompt.title }}</span>
        <span class="chat-empty-view__prompt-description">
          {{ prompt.description }}
        </span>
      </span>
    </button>
    }
  </div>
</div>
