// packages/vue/src/components/revenue-snapshot-by-states-card.vue
<template>
  <card-analytics
    title="Revenue Snapshot by States"
    content-class="sales-by-state"
  >
    <dx-pie-chart
      :data-source="props.data"
      type="doughnut"
      :diameter="0.8"
      :inner-radius="0.6"
    >
      <dx-pie-series
        argument-field="stateName"
        value-field="total"
      >
        <dx-pie-label
          background-color="none"
          :radial-offset="-20"
          :visible="true"
          :customize-text="customizeSaleText"
        >
          <dx-pie-font
            color="#757575"
            :size="15"
          />
        </dx-pie-label>
      </dx-pie-series>

      <dx-pie-legend>
        <dx-pie-margin :top="70" />
      </dx-pie-legend>

      <dx-pie-size :height="270" />
    </dx-pie-chart>
  </card-analytics>
</template>

<script setup lang="ts">
import {
  DxPieChart,
  DxLabel as DxPieLabel,
  DxSeries as DxPieSeries,
  DxFont as DxPieFont,
  DxMargin as DxPieMargin,
  DxLegend as DxPieLegend,
  DxSize as DxPieSize,
} from 'devextreme-vue/pie-chart';
import { Sales } from '@/types/analytics';
import CardAnalytics from '@/components/card-analytics.vue';

const props = defineProps<{
  data: Sales
}>();

const customizeSaleText = (arg: { percentText: string }) => arg.percentText;
</script>

<style scoped>

</style>

// packages/angular/src/app/components/utils/revenue-snapshot-by-states-card/revenue-snapshot-by-states-card.component.ts
import { Component, Input } from '@angular/core';
import { CardAnalyticsComponent } from '../../library/card-analytics/card-analytics.component';
import { DxPieChartModule } from 'devextreme-angular/ui/pie-chart';
import { SalesByState } from 'src/app/types/analytics';

@Component({
  selector: 'revenue-snapshot-by-states-card',
  templateUrl: './revenue-snapshot-by-states-card.component.html',
  imports: [
    CardAnalyticsComponent,
    DxPieChartModule,
  ],
})
export class RevenueSnapshotByStatesCardComponent {
  @Input() data!: SalesByState | null;

  customizeSaleText(arg: { percentText: string }) {
    return arg.percentText;
  }
}


<card-analytics
  titleText="Revenue Snapshot by States"
  contentClass="sales-by-state"
>
  <dx-pie-chart
    [dataSource]="data"
    type="doughnut"
    [diameter]="0.8"
    [innerRadius]="0.6"
  >
    <dxi-pie-chart-series argumentField="stateName" valueField="total">
      <dxo-pie-chart-label
        backgroundColor="none"
        [radialOffset]="-20"
        [visible]="true"
        [customizeText]="customizeSaleText"
      >
        <dxo-pie-chart-font color="#757575" [size]="15"></dxo-pie-chart-font>
      </dxo-pie-chart-label>
    </dxi-pie-chart-series>

    <dxo-pie-chart-legend>
      <dxo-pie-chart-margin [top]="70"></dxo-pie-chart-margin>
    </dxo-pie-chart-legend>

    <dxo-pie-chart-size [height]="270"> </dxo-pie-chart-size>
  </dx-pie-chart>
</card-analytics>
