// packages/react/src/components/library/card-activities/CardActivities.tsx
import React from 'react';

import List from 'devextreme-react/list';
import { CardMenu } from '../card-menu/CardMenu';

import { formatDate } from 'devextreme/localization';

import classNames from 'classnames';

import { Activities, Activity } from '../../../types/card-activities';
import { withLoadPanel } from '../../../utils/withLoadPanel';

import './CardActivities.scss';

const activityMenuItems = [
  { text: 'View details' },
  { text: 'Delete' },
];

const listItemRender = (item: Activity) => {
  return (
    <div className='activity'>
      <div className='name'>{item.name}</div>
      <div className='date by'>
        <span>{formatDate(new Date(item.date), 'MM/dd/yyyy')}</span>
        <span className='by-span'>by</span>
        <span>{item.manager}</span>
      </div>
      <CardMenu items={activityMenuItems} />
    </div>
  );
};

const ActivitiesList = ({ activities }) => {
  return (
    <List className='activities-list' dataSource={activities} scrollingEnabled={false} itemRender={listItemRender} />
  );
};

const ActivitiesWithLoadPanel = withLoadPanel(ActivitiesList);

export const CardActivities = ({ activities, isLoading }: { activities?: Activities, isLoading?: boolean }) => (
  <div className={classNames({ 'card-activities': true, load: !activities })}>
    <ActivitiesWithLoadPanel
      activities={activities}
      hasData={!!activities}
      loading={isLoading}
      panelProps={{
        container: '.card-activities',
        position: { of: '.card-activities' }
      }}
    />
  </div>
);

// packages/angular/src/app/components/card-activities/card-activities.component.ts
import { CommonModule } from '@angular/common';
import {
  Component, NgModule, Input, SimpleChanges, OnInit, OnChanges,
} from '@angular/core';
import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxListModule } from 'devextreme-angular/ui/list';
import { DxLoadPanelModule } from 'devextreme-angular/ui/load-panel';
import { CardMenuModule } from '../card-menu/card-menu.component';
import { Activity } from 'src/app/types/activities';

@Component({
  selector: 'card-activities',
  templateUrl: './card-activities.component.html',
  styleUrls: ['./card-activities.component.scss'],
})
export class CardActivitiesComponent implements OnInit, OnChanges {
  @Input() activities: Activity[];

  @Input() showBy? = false;

  isLoading = true;

  activityMenuItems: Array<{ text: string }> = [
    { text: 'View details' },
    { text: 'Delete' },
  ];

  ngOnInit() {
    this.isLoading = !this.activities;
  }

  ngOnChanges(changes: SimpleChanges) {
    this.isLoading = !changes.activities.currentValue;
  }
}

@NgModule({
  imports: [
    DxListModule,
    DxButtonModule,
    DxLoadPanelModule,
    CardMenuModule,

    CommonModule,
  ],
  declarations: [CardActivitiesComponent],
  exports: [CardActivitiesComponent],
})
export class CardActivitiesModule { }

<div id="activities-list" [ngClass]="activities ? 'load' : null">
  <dx-list
    *ngIf="activities"
    class="activities-list"
    [items]="activities"
    [scrollingEnabled]="false"
  >
    <div *dxTemplate="let item of 'item'">
      <div class="activity">
        <div class="name">{{ item.name }}</div>
        <div class="date" [ngClass]="{ by: showBy }">
          <span>{{ item.date | date: "MM/dd/yyyy" }}</span>
          <span *ngIf="showBy">by</span>
          <span>{{ item.manager }}</span>
        </div>
        <card-menu
          [items]="activityMenuItems"
          >
        </card-menu>
      </div>
    </div>
  </dx-list>

  <dx-load-panel
    container="#activities-list"
    [position]="{ of: '#activities-list' }"
    [visible]="!activities || isLoading"
    [showPane]="false"
  ></dx-load-panel>
</div>
