// packages/vue/src/components/utils/revenue-total-ticker.vue
<template>
  <ticker-card
    title="Revenue Total"
    icon="dataarea"
    :data="props.data"
    :percentage="-14.7"
  />
</template>

<script setup lang="ts">
import TickerCard from '@/components/library/ticker-card.vue';
import { Sales } from '../../types/analytics';

const props = withDefaults(defineProps<{
  data: Sales | null
}>(), {
  data: () => [],
});
</script>

// packages/react/src/components/utils/revenue-total-ticker/RevenueTotalTicker.tsx
import React from 'react';

import { TickerCard } from '../../library/ticker-card/TickerCard';
import { TickerProps } from '../../../types/analytics';
import { formatCurrency } from '../../../utils/format-currency';

export const RevenueTotalTicker = ({ value }: TickerProps) =>
  <TickerCard
    title='Revenue Total'
    icon='dataarea'
    value={value}
    formatValue={formatCurrency}
    percentage={-14.7}
  />;
