// packages/react/src/components/card-tasks/CardTasks.tsx
import React, { useState, useCallback } from 'react';

import DataGrid, { Selection, RowDragging, Column } from 'devextreme-react/data-grid';

import { RowDraggingReorderEvent } from 'devextreme/ui/data_grid';

import { withLoadPanel } from '../../utils/withLoadPanel';

import { Task } from '../../types/task';

import './CardTasks.scss';

const Grid = ({ tasks }: { tasks: Task[] }) => {
  const [gridData, setGridData] = useState(tasks);

  const onReorder = useCallback((e: RowDraggingReorderEvent) => {
    const visibleRows = e.component.getVisibleRows();
    const toIndex = gridData.indexOf(visibleRows[e.toIndex].data);
    const fromIndex = gridData.indexOf(e.itemData);

    setGridData([
      ...gridData.slice(0, fromIndex),
      ...gridData.slice(fromIndex + 1, toIndex + 1),
      e.itemData,
      ...gridData.slice(toIndex + 1)
    ]);
  }, [gridData]);

  return (
    <DataGrid
      className='tasks-grid'
      dataSource={gridData}
      columnAutoWidth
    >
      <Selection mode='multiple' />

      <RowDragging
        allowReordering
        onReorder={onReorder}
        showDragIcons
      />

      <Column
        dataField='text'
        caption='Subject'
        hidingPriority={3}
      />
      <Column
        dataField='date'
        dataType='date'
        caption='Due Date'
        hidingPriority={1}
      />
      <Column
        caption='Assigned To'
        dataField='manager'
        hidingPriority={0}
      />
    </DataGrid>
  );
};

const GridWithLoadPanel = withLoadPanel(Grid);

export const CardTasks = ({ tasks, isLoading }: { tasks?: Task[], isLoading: boolean }) => {
  return (
    <div className='card-tasks'>
      <GridWithLoadPanel
        tasks={tasks?.filter((item) => !!item.status && !!item.priority)}
        hasData={!!tasks}
        loading={isLoading}
        panelProps={{
          container: '.card-tasks',
          position: { of: '.card-tasks' }
        }}
      />
    </div>
  );
};

// packages/angular/src/app/components/card-tasks/card-tasks.component.ts
import {
  Component, Input, NgModule, OnChanges, SimpleChanges, ViewChild,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxDataGridComponent,
  DxDataGridModule,
  DxLoadPanelModule,
} from 'devextreme-angular';
import { RowDraggingReorderEvent } from 'devextreme/ui/data_grid';
import { Task } from '../../types/task';

@Component({
  selector: 'card-tasks',
  templateUrl: './card-tasks.component.html',
  styleUrls: ['./card-tasks.component.scss'],
})
export class CardTasksComponent implements OnChanges {
  @ViewChild('dataGrid', { static: false }) component: DxDataGridComponent;

  @Input() tasks: Task[];

  @Input() isLoading: boolean = false;

  currentTasks: Task[];

  constructor() {
    this.onReorder = this.onReorder.bind(this);
  }

  ngOnChanges(changes: SimpleChanges) {
    if(changes.tasks?.currentValue) {
      this.currentTasks = changes.tasks.currentValue.filter((item) => !!item.status && !!item.priority);
    }
  }

  onReorder(e: RowDraggingReorderEvent) {
    const visibleRows = e.component.getVisibleRows();
    const toIndex = this.currentTasks.indexOf(visibleRows[e.toIndex].data);
    const fromIndex = this.currentTasks.indexOf(e.itemData);

    this.currentTasks.splice(fromIndex, 1);
    this.currentTasks.splice(toIndex, 0, e.itemData);
  }
}

@NgModule({
  imports: [DxDataGridModule, DxLoadPanelModule, CommonModule],
  declarations: [CardTasksComponent],
  exports: [CardTasksComponent],
})
export class CardTasksModule { }

<div id="card-tasks">
  <dx-data-grid
    *ngIf="currentTasks"
    #dataGrid
    [dataSource]="currentTasks"
    [columnAutoWidth]="true"
  >
    <dxo-selection mode="multiple"></dxo-selection>

    <dxo-row-dragging
      [allowReordering]="true"
      [onReorder]="onReorder"
      [showDragIcons]="true"
    ></dxo-row-dragging>

    <dxi-column
      dataField="text"
      caption="Subject"
      [hidingPriority]="3"
    ></dxi-column>
    <dxi-column
      dataField="date"
      dataType="date"
      caption="Due Date"
      [hidingPriority]="1"
    ></dxi-column>
    <dxi-column
      caption="Assigned To"
      dataField="manager"
      [hidingPriority]="0"
    ></dxi-column>
  </dx-data-grid>

  <dx-load-panel
    [visible]="!currentTasks || isLoading"
    [showPane]="false"
    container="#card-tasks"
    [position]="{ of: '#card-tasks' }"
  ></dx-load-panel>
</div>
