// packages/vue/src/components/theme-switcher.vue
<template>
  <dx-button
    class="theme-button"
    :icon="`icons/${theme === 'dark' ? 'sun' : 'moon'}.svg`"
    @click="onClickButton"
  />
</template>

<script setup lang="ts">
import { DxButton } from 'devextreme-vue/button';
import { ref } from 'vue';
import { currentTheme as currentVizTheme, refreshTheme } from 'devextreme/viz/themes';

const storageKey = 'themeViewer';
const themeMarker = 'theme-';

function getCurrentTheme(): 'dark' | 'light' {
  return window.localStorage[storageKey] || 'light';
}

function getThemeStyleSheets() {
  return [...document.styleSheets]
    .filter((styleSheet) => styleSheet?.href?.includes(themeMarker));
}

function switchTheme(themeName?: string) {
  themeName = themeName || getCurrentTheme();

  const enabledStyleSheet: CSSStyleSheet[] = [];
  getThemeStyleSheets().forEach((styleSheet) => {
    if (styleSheet?.href?.includes(`${themeMarker}${themeName}`)) {
      enabledStyleSheet.push(styleSheet);
    } else {
      styleSheet.disabled = true;
    }
  });

  enabledStyleSheet.forEach((styleSheet) => {
    styleSheet.disabled = false;
  });

  window.localStorage[storageKey] = themeName;
  currentVizTheme(currentVizTheme().replace(/\.[a-z]+\.compact$/, `.${themeName}.compact`));
  refreshTheme();
}

switchTheme();

const theme = ref(getCurrentTheme());

function onClickButton() {
  theme.value = theme.value === 'dark' ? 'light' : 'dark';
  switchTheme(theme.value);
}
</script>

<style scoped lang="scss">
</style>

// packages/react/src/components/theme-switcher/ThemeSwitcher.tsx
import React, { useEffect, useState } from 'react';
import Button from 'devextreme-react/button';
import { currentTheme as currentVizTheme, refreshTheme } from 'devextreme/viz/themes';
import './ThemeSwitcher.scss';

type Theme = 'dark'| 'light';

const stylesSheetsByThemes = {};
const storageKey = 'themeViewer';

function getCurrentTheme(): Theme {
  return window.localStorage[storageKey] || 'light';
}

async function getThemeStyleSheets(themeName: Theme) {
  const themePrefix = 'app-theme-';

  if (stylesSheetsByThemes[themeName]) {
    return stylesSheetsByThemes[themeName];
  }
  const themeCssSelector = `:root, .${themePrefix + themeName}`;
  const themeCssSelectorRegExp = new RegExp(themeCssSelector);

  const themeStyleSheets = [...document.styleSheets as unknown as CSSStyleSheet[]]
    .filter(({ rules })=> !![...rules as unknown as any[]]
      .find((rule) => rule.selectorText?.startsWith(themeCssSelector)));

  themeStyleSheets.forEach((styleSheet) => {
    [...styleSheet.cssRules as unknown as CSSStyleRule[]].forEach((rule) => {

      if (rule.selectorText?.startsWith(themeCssSelector)) {
        rule.selectorText = rule.selectorText.replace(themeCssSelectorRegExp, '');
      }
    });
  });

  stylesSheetsByThemes[themeName] = themeStyleSheets;

  return themeStyleSheets;
}

export async function switchTheme(themeName?: Theme) {
  const previousTheme = themeName == 'dark' ? 'light' : 'dark';

  themeName = themeName || getCurrentTheme();

  const stylesSheets = await getThemeStyleSheets(themeName);

  stylesSheets.forEach((stylesSheet) => stylesSheet.disabled = false);

  const previousStylesSheets = await getThemeStyleSheets(previousTheme);

  previousStylesSheets.forEach((stylesSheet) => stylesSheet.disabled = true);

  window.localStorage[storageKey] = themeName;

  currentVizTheme(`material.${themeName}`);
  refreshTheme();
}

export const ThemeSwitcher = () => {
  const [theme, setTheme] = useState(getCurrentTheme());

  const onClickButton = () => {
    setTheme(theme === 'dark' ? 'light' : 'dark');
  };

  useEffect(() => {
    switchTheme(theme);
  }, [theme]);

  return <div>
    <Button className='theme-button'
      icon={`icons/${theme !== 'dark' ? 'moon' : 'sun'}.svg`}
      onClick={onClickButton} />
  </div>;
};
