// packages/angular/src/app/shared/components/planning-kanban/planning-kanban.component.ts
import { Component, OnInit, NgModule, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxScrollViewModule,
  DxSortableModule,
  DxButtonModule,
} from 'devextreme-angular';
import DataSource from 'devextreme/data/data_source';
import { Status, statusList } from 'src/app/shared/types/statuses';
import { TaskType } from 'src/app/shared/types/TaskType';

@Component({
  selector: 'planning-kanban',
  templateUrl: './planning-kanban.component.html',
  styleUrls: ['./planning-kanban.component.scss']
})
export class PlanningKanbanComponent implements OnInit {
  @Input() dataSource: DataSource;

  kanbanDataSource: Array<{
    status: Status,
    tasks: Array<TaskType>
  }> = [];

  constructor() {
  }

  onListReorder = (e) => {
    const list = this.kanbanDataSource.splice(e.fromIndex, 1)[0];
    this.kanbanDataSource.splice(e.toIndex, 0, list);
  }

  getTaskByStatus = (status: Status): Array<TaskType> => this.dataSource.items().filter(item => item.status === status);

  getFormatDate = (date: Date) => `${date.getDay()}/${date.getMonth()}/${date.getFullYear()}`

  getFirstLetterName = (name: string) => name.split(' ').map(l => l[0]).join('');

  onTaskDragStart(e) {
    e.itemData = e.fromData[e.fromIndex];
  }

  onTaskDrop(e) {
    e.fromData.splice(e.fromIndex, 1);
    e.toData.splice(e.toIndex, 0, e.itemData);
  }

  ngOnInit() {
    this.dataSource.load();

    for(const status of statusList) {
      this.kanbanDataSource.push({
        status: <Status>status,
        tasks: this.getTaskByStatus(<Status>status)
      });
    }
  }
}

@NgModule({
  imports: [
    DxScrollViewModule,
    DxSortableModule,
    DxButtonModule,

    CommonModule
  ],
  providers: [],
  exports: [PlanningKanbanComponent],
  declarations: [PlanningKanbanComponent]
})
export class PlanningKanbanModule { }

<div id="kanban">
  <dx-scroll-view
    class="scrollable-board"
    direction="horizontal"
    showScrollbar="always"
  >
    <dx-sortable
      class="sortable-lists"
      itemOrientation="horizontal"
      handle=".list-title"
      (onReorder)="onListReorder($event)"
    >
      <div class="list" *ngFor="let dataItem of kanbanDataSource;">
        <div class="list-title dx-theme-text-color">
          <span>{{ dataItem.status }}</span>
          <span class="more dx-icon-more"></span>
        </div>
        <dx-scroll-view
          class="scrollable-list"
          direction="vertical"
          showScrollbar="always"
        >
          <dx-sortable
            class="sortable-cards"
            group="cardsGroup"
            [data]="dataItem.tasks"
            (onDragStart)="onTaskDragStart($event)"
            (onReorder)="onTaskDrop($event)"
            (onAdd)="onTaskDrop($event)"
          >
            <div
              class="card dx-card dx-theme-text-color dx-theme-background-color"
              *ngFor="let task of dataItem.tasks"
            >
              <div class="card-wrapper" [ngClass]="'priority-' + task.priority.toLowerCase()">
                <div class="card-priority"></div>
                <span class="edit dx-icon-edit"></span>
                <div class="card-content">
                  <div class="card-subject dx-theme-text-color">{{ task.text }}</div>
                  <div class="card-data">
                    <span class="priority">{{ task.priority }}</span>
                    <span class="date dx-theme-text-color">{{ task.dueDate | date: 'MM/dd/yyyy' }}</span>
                  </div>
                  <div class="card-assignee">
                    <span class="company dx-theme-text-color">{{ task.company }}</span>
                    <div class="circle" [attr.data-letters]="getFirstLetterName(task.owner)"></div>
                  </div>
                </div>
              </div>
            </div>
          </dx-sortable>
          <div class="add-task">
            <dx-button
              icon="plus"
              text="Add Task"
              stylingMode="text"
            ></dx-button>
          </div>
        </dx-scroll-view>
      </div>
    </dx-sortable>
  </dx-scroll-view>
</div>

// packages/react/src/components/plannin-kanban/PlanningKanban.tsx
import React, { useState, useEffect, useCallback } from 'react';
import ScrollView from 'devextreme-react/scroll-view';
import Sortable from 'devextreme-react/sortable';
import LoadPanel from 'devextreme-react/load-panel';
import { PlanningProps, Task } from '../../shared/types/task';
import { STATUS_ITEMS } from '../../shared/constants';
import { DragStartEvent, ReorderEvent } from 'devextreme/ui/sortable';
import { List } from './list/List';
import './PlanningKanban.scss';

const reorder = (items: any[], item: Object, fromIndex: number, toIndex: number) => {
  let result = items;
  if (fromIndex >= 0) {
    result = [...result.slice(0, fromIndex), ...result.slice(fromIndex + 1)];
  }

  if (toIndex >= 0) {
    result = [...result.slice(0, toIndex), item, ...result.slice(toIndex)];
  }

  return result;
};
export const PlanningKanban = ({ dataSource }: PlanningProps) => {
  const [loading, setLoading] = useState(true);
  const [lists, setLists] = useState<Task[][]>([]);
  const [statuses, setStatuses] = useState(STATUS_ITEMS);
  useEffect(() => {
    if (dataSource.length !== 0) {
      setLoading(false);
      const initialLists: Task[][] = [];
      STATUS_ITEMS.forEach((status) => {
        initialLists.push(dataSource.filter((task) => task.status === status));
      });
      setLists(initialLists);
    }
  }, [dataSource]);
  const onListReorder = useCallback(
    ({ fromIndex, toIndex }: ReorderEvent) => {
      setLists(reorder(lists, lists[fromIndex], fromIndex, toIndex));
      setStatuses(reorder(statuses, statuses[fromIndex], fromIndex, toIndex));
    },
    [lists, statuses]
  );

  const onTaskDragStart = useCallback(
    (e: DragStartEvent) => {
      e.itemData = lists[e.fromData][e.fromIndex];
    },
    [lists]
  );

  const onTaskDrop = useCallback(
    (e: ReorderEvent) => {
      const updatedList = [...lists];
      e.itemData.status = statuses[e.toData];
      updatedList[e.fromData] = reorder(updatedList[e.fromData], e.itemData, e.fromIndex, -1);
      updatedList[e.toData] = reorder(updatedList[e.toData], e.itemData, -1, e.toIndex);

      setLists(updatedList);
    },
    [lists, statuses]
  );

  return loading ? (
    <LoadPanel container='.content' visible position={{ of: '.content' }} />
  ) : (
    <div id='kanban'>
      <ScrollView className='scrollable-board' direction='horizontal' showScrollbar='always'>
        <Sortable className='sortable-lists' itemOrientation='horizontal' handle='.list-title' onReorder={onListReorder}>
          {lists.map((tasks, listIndex) => {
            const status = statuses[listIndex];
            return <List key={status} title={status} index={listIndex} tasks={tasks} onTaskDragStart={onTaskDragStart} onTaskDrop={onTaskDrop} />;
          })}
        </Sortable>
      </ScrollView>
    </div>
  );
};
