// packages/angular/src/app/components/utils/toolbar-analytics/toolbar-analytics.component.ts
import { Component, Input, Output, EventEmitter, inject } from '@angular/core';
import { CommonModule } from '@angular/common';

import { DxButtonComponent } from "devextreme-angular";
import { DxTabsModule } from 'devextreme-angular/ui/tabs';
import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';

import { type DxTabsTypes } from 'devextreme-angular/ui/tabs';

import { ScreenService } from 'src/app/services';
import { Dates, PanelItem } from 'src/app/types/resource';

@Component({
    selector: 'toolbar-analytics',
    templateUrl: './toolbar-analytics.component.html',
    styleUrls: ['./toolbar-analytics.component.scss'],
    imports: [
      CommonModule,
      DxButtonComponent,
      DxTabsModule,
      DxToolbarModule
    ],
})

export class ToolbarAnalyticsComponent {
  @Input() selectedItems: Array<number>;

  @Input() titleText: string;

  @Input() panelItems: Array<PanelItem>;

  @Output() selectionChanged = new EventEmitter<Dates>();

  protected screen = inject(ScreenService);

  selectionChange(e: DxTabsTypes.SelectionChangedEvent) {
    const dates = e.addedItems[0].value.split('/');

    this.selectionChanged.emit({ startDate: dates[0], endDate: dates[1] });
  }
}

<dx-toolbar class="theme-dependent">
  <dxi-toolbar-item location="before">
    <span class="toolbar-header">{{ titleText }}</span>
  </dxi-toolbar-item>

  @if (panelItems) {
    <dxi-toolbar-item location="before">
      <dx-tabs
        secondary="secondary"
        keyExpr="key"
        [width]="(screen.xSmallScreenChanged | async) ? 150 : 'auto'"
        [showNavButtons]="false"
        [scrollByContent]="true"
        [selectedItemKeys]="selectedItems"
        [items]="panelItems"
        (onSelectionChanged)="selectionChange($event)"
      ></dx-tabs>
    </dxi-toolbar-item>
  }

  <dxi-toolbar-item location="after" locateInMenu="auto">
    <dx-button
      class="add-card"
      icon="plus"
      text="Add Card"
      type="default"
      stylingMode="contained"
    ></dx-button>
  </dxi-toolbar-item>

  <dxi-toolbar-item
    location="after"
    locateInMenu="auto"
    widget="dxButton"
    showText="inMenu"
    [options]="{
      text: 'Refresh',
      icon: 'refresh',
      stylingMode: 'text'
    }"
  ></dxi-toolbar-item>

  <dxi-toolbar-item location="after" locateInMenu="auto">
    <div class="separator"></div>
  </dxi-toolbar-item>

  <dxi-toolbar-item
    location="after"
    locateInMenu="auto"
    widget="dxButton"
    showText="inMenu"
    [options]="{
      icon: 'export',
      text: 'Export',
      stylingMode: 'text'
    }"
  ></dxi-toolbar-item>
</dx-toolbar>

// packages/react/src/components/utils/toolbar-analytics/ToolbarAnalytics.tsx
import React, { ReactNode } from 'react';
import Button from 'devextreme-react/button';
import Toolbar, { Item } from 'devextreme-react/toolbar';
import './ToolbarAnalytics.scss';

type ToolbarAnalyticsProps = {
  title: string;
  additionalToolbarContent?: ReactNode;
};

export const ToolbarAnalytics = ({
  title,
  additionalToolbarContent,
  children,
}: React.PropsWithChildren<ToolbarAnalyticsProps>) => {
  return (
    <div className='view-wrapper view-wrapper-dashboard'>
      <Toolbar className='theme-dependent'>
        <Item location='before'>
          <span className='toolbar-header'>{title}</span>
        </Item>
        {additionalToolbarContent}
        <Item location='after' locateInMenu='auto'>
          <Button
            className='add-card'
            icon='plus'
            text='Add Card'
            type='default'
            stylingMode='contained'
          />
        </Item>
        <Item
          location='after'
          locateInMenu='auto'
          widget='dxButton'
          showText='inMenu'
        >
          <Button
            text='Refresh'
            icon='refresh'
            stylingMode='text'
          />
        </Item>
        <Item location='after' locateInMenu='auto'>
          <div className='separator' />
        </Item>
        <Item
          location='after'
          locateInMenu='auto'
          widget='dxButton'
          showText='inMenu'
        >
          <Button
            icon='export'
            text='Export'
            stylingMode='text'
          />
        </Item>
      </Toolbar>
      {children}
    </div>
  );
};
