// packages/vue/src/components/utils/revenue-card.vue
<template>
  <card-analytics
    title="Revenue"
    content-class="sales"
  >
    <dx-chart
      v-if="props.data"
      :data-source="props.data"
    >
      <dx-series value-field="total" />
      <dx-common-series-settings
        argument-field="date"
        type="splinearea"
        :color="seriesColor"
      >
        <dx-border :visible="true" />
      </dx-common-series-settings>
      <dx-argument-axis argument-type="datetime" />
      <dx-value-axis>
        <dx-chart-label>
          <dx-chart-format
            type="currency"
            currency="USD"
          />
        </dx-chart-label>
      </dx-value-axis>
      <dx-legend :visible="false" />
      <dx-size :height="270" />
    </dx-chart>
  </card-analytics>
</template>

<script setup lang="ts">
import {
  DxChart,
  DxSeries,
  DxCommonSeriesSettings,
  DxBorder,
  DxSize,
  DxLegend,
  DxArgumentAxis,
  DxValueAxis,
  DxLabel as DxChartLabel,
  DxFormat as DxChartFormat,
} from 'devextreme-vue/chart';

import { Sales } from '@/types/analytics';
import CardAnalytics from '@/components/library/card-analytics.vue';
import { ChartsColor, registerGradient } from 'devextreme/common/charts';

const props = defineProps<{
  data: Sales
}>();

const seriesColor: ChartsColor = {
  base: '#115EA3',
  fillId: registerGradient('linear', {
    rotationAngle: 90,
    colors: [{
      offset: '20%',
      color: '#1F74BD',
    }, {
      offset: '90%',
      color: '#93BCE1',
    }],
  }),
};
</script>

<style scoped>

</style>

// packages/react/src/components/utils/revenue-card/RevenueCard.tsx
import React from 'react';
import Chart, { ArgumentAxis, Border, CommonSeriesSettings, Format, Label, Legend, Series, Size, ValueAxis } from 'devextreme-react/chart';
import { ChartsColor, registerGradient } from 'devextreme/common/charts';
import { CardAnalytics } from '../../library/card-analytics/CardAnalytics';
import { Sale } from '../../../types/analytics';

const seriesColor: ChartsColor = {
  base: '#115EA3',
  fillId: registerGradient('linear', {
    rotationAngle: 90,
    colors: [{
      offset: '20%',
      color: '#1F74BD',
    }, {
      offset: '90%',
      color: '#93BCE1',
    }],
  }),
};

export const RevenueCard = ({ datasource }: { datasource: Sale[] }) => (
  <CardAnalytics title='Revenue' contentClass='sales'>
    <Chart dataSource={datasource}>
      <Series valueField='total' />
      <CommonSeriesSettings argumentField='date' type='splinearea' color={seriesColor}>
        <Border visible />
      </CommonSeriesSettings>
      <ArgumentAxis argumentType='datetime' />
      <ValueAxis>
        <Label>
          <Format type='currency' currency='USD' />
        </Label>
      </ValueAxis>
      <Legend visible={false} />
      <Size height={270} />
    </Chart>
  </CardAnalytics>
);
