// packages/react/src/components/library/task-list-kanban/TaskListKanban.tsx
import React, { useState, useEffect, useCallback } from 'react';

import ScrollView from 'devextreme-react/scroll-view';
import Sortable from 'devextreme-react/sortable';
import Button from 'devextreme-react/button';

import { DragStartEvent, ReorderEvent } from 'devextreme/ui/sortable';

import { CardMenu } from '../card-menu/CardMenu';
import { TaskKanbanCard } from '../task-kanban-card/TaskKanbanCard';

import { PlanningProps, Task } from '../../../types/task';

import { STATUS_ITEMS } from '../../../shared/constants';

import './TaskListKanban.scss';

const boardMenuItems = [
  { text: 'Add card' },
  { text: 'Copy list' },
  { text: 'Move list' },
];

const reorder = <T, >(items: T[], item: T, fromIndex: number, toIndex: number) => {
  let result = items;
  if (fromIndex >= 0) {
    result = [...result.slice(0, fromIndex), ...result.slice(fromIndex + 1)];
  }

  if (toIndex >= 0) {
    result = [...result.slice(0, toIndex), item, ...result.slice(toIndex)];
  }

  return result;
};

const TaskList = ({
  title,
  index,
  tasks,
  onTaskDragStart,
  onTaskDrop,
  changePopupVisibility,
}: {
  title: string,
  index: number,
  tasks: Task[],
  onTaskDragStart: (e: DragStartEvent) => void,
  onTaskDrop: (e: ReorderEvent) => void,
  changePopupVisibility?: () => void,
}) => {

  return (
    <div className='list'>
      <div className='list-title dx-theme-text-color'>
        <span>{title}</span>
        <CardMenu items={boardMenuItems} />
      </div>
      <ScrollView className='scrollable-list' direction='vertical' showScrollbar='always'>
        <Sortable className='sortable-cards' group='cardsGroup' data={index} onDragStart={onTaskDragStart} onReorder={onTaskDrop} onAdd={onTaskDrop}>
          {tasks.map((task) => (
            <TaskKanbanCard key={task.id} task={task} />
          ))}
        </Sortable>
        <div className='add-task'>
          <Button icon='plus' text='Add Task' stylingMode='text' onClick={changePopupVisibility} width='100%' />
        </div>
      </ScrollView>
    </div>
  );
};

export const TaskListKanban = React.forwardRef<Sortable, PlanningProps>(({ dataSource, changePopupVisibility }, ref) => {
  const [lists, setLists] = useState<Task[][]>([]);
  const [statuses, setStatuses] = useState(STATUS_ITEMS);
  useEffect(() => {
    const initialLists: Task[][] = [];
    STATUS_ITEMS.forEach((status) => {
      initialLists.push(dataSource.filter((task) => task.status === status));
    });
    setLists(initialLists);
  }, [dataSource]);
  const onListReorder = useCallback(
    ({ fromIndex, toIndex }: ReorderEvent) => {
      setLists(reorder(lists, lists[fromIndex], fromIndex, toIndex));
      setStatuses(reorder(statuses, statuses[fromIndex], fromIndex, toIndex));
    },
    [lists, statuses]
  );

  const onTaskDragStart = useCallback(
    (e: DragStartEvent) => {
      e.itemData = lists[e.fromData][e.fromIndex];
    },
    [lists]
  );

  const onTaskDrop = useCallback(
    (e: ReorderEvent) => {
      const updatedList = [...lists];
      e.itemData.status = statuses[e.toData];
      updatedList[e.fromData] = reorder(updatedList[e.fromData], e.itemData, e.fromIndex, -1);
      updatedList[e.toData] = reorder(updatedList[e.toData], e.itemData, -1, e.toIndex);

      setLists(updatedList);
    },
    [lists, statuses]
  );

  return (
    <div id='kanban' className='kanban'>
      <ScrollView direction='both' showScrollbar='always'>
        <Sortable ref={ref} itemOrientation='horizontal' handle='.list-title' onReorder={onListReorder}>
          {lists.map((tasks, listIndex) => {
            const status = statuses[listIndex];
            return <TaskList key={status} title={status} index={listIndex} tasks={tasks} onTaskDragStart={onTaskDragStart} onTaskDrop={onTaskDrop} changePopupVisibility={changePopupVisibility} />;
          })}
        </Sortable>
      </ScrollView>
    </div>
  );
});

// packages/angular/src/app/pages/planning-task-list/task-list-kanban/task-list-kanban.component.ts
import {
  Component, OnInit, NgModule, Input, SimpleChanges, OnChanges,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxLoadPanelModule } from 'devextreme-angular/ui/load-panel';
import { DxScrollViewModule } from 'devextreme-angular/ui/scroll-view';
import { DxSortableModule } from 'devextreme-angular/ui/sortable';
import { DxMenuModule } from 'devextreme-angular/ui/menu';
import notify from 'devextreme/ui/notify';
import { DragStartEvent, ReorderEvent, AddEvent } from 'devextreme/ui/sortable';
import { Task } from 'src/app/shared/types/task';
import { TaskStatus, taskStatusList } from 'src/app/shared/types/task';
import { TaskKanbanCardModule } from './task-kanban-card/task-kanban-card.component';

type Board = {
  name: TaskStatus
  cards: Task[]
};

@Component({
  selector: 'task-list-kanban',
  templateUrl: './task-list-kanban.component.html',
  styleUrls: ['./task-list-kanban.component.scss'],
})
export class TaskListKanbanComponent implements OnInit, OnChanges {
  @Input() dataSource: Task[];

  kanbanDataSource: Board[] = [];

  isLoading = true;

  statuses = taskStatusList;

  boardMenuItems: Array<{ icon: string, items: Array<{ text: string }> }> = [{ 
    icon: 'more',
    items: [
      { text: 'Add card...' },
      { text: 'Copy list..' },
      { text: 'Move list..' },
    ]}
  ];

  fillOutBoard = (cards: Task[]): Board[] => {
    const result: Board[] = [];
    for (const status of this.statuses) {
      const value = cards.filter((item) => item.status === status);

      result.push(<Board>{ name: status, cards: value });
    }

    return result;
  };

  constructor() {
    this.kanbanDataSource = this.fillOutBoard([]);
  }

  ngOnInit() {
    this.kanbanDataSource = this.fillOutBoard(this.dataSource);
  }

  ngOnChanges(changes: SimpleChanges) {
    this.isLoading = changes.dataSource.currentValue === undefined;
  }

  getCardsByStatus = (status: TaskStatus): Task[] => {
    const cards: Task[] = this.dataSource
      .filter((task) => task.status === status);

    return cards;
  };

  onListReorder = (e: ReorderEvent) => {
    const { fromIndex, toIndex } = e;
    const list = this.kanbanDataSource.splice(fromIndex, 1)[0];
    this.kanbanDataSource.splice(toIndex, 0, list);
  };

  onTaskDragStart(e: DragStartEvent) {
    const { fromData, fromIndex } = e;
    e.itemData = fromData.cards[fromIndex];
  }

  onTaskDrop(e: ReorderEvent | AddEvent) {
    const {
      fromData, toData, fromIndex, toIndex, itemData,
    } = e;

    itemData.status = toData.name;

    fromData.cards.splice(fromIndex, 1);
    toData.cards.splice(toIndex, 0, itemData);
  }

  notify = (text: string) => {
    notify(text);
  };
}

@NgModule({
  imports: [
    DxButtonModule,
    DxLoadPanelModule,
    DxScrollViewModule,
    DxSortableModule,
    DxMenuModule,

    TaskKanbanCardModule,

    CommonModule,
  ],
  providers: [],
  exports: [TaskListKanbanComponent],
  declarations: [TaskListKanbanComponent],
})
export class TaskListKanbanModule { }

<dx-scroll-view
  *ngIf="!isLoading"
  class="scrollable-board"
  direction="horizontal"
  showScrollbar="always"
>
  <dx-sortable
    class="sortable-lists"
    itemOrientation="horizontal"
    handle=".list-title"
    (onReorder)="onListReorder($event)"
  >
    <div class="list" *ngFor="let board of kanbanDataSource">
      <div class="list-title dx-theme-text-color">
        <span>{{ board.name }}</span>
        <dx-menu
          [items]="boardMenuItems"
        >       
        </dx-menu>
      </div>
      <dx-scroll-view
        class="scrollable-list"
        direction="vertical"
        showScrollbar="always"
      >
        <dx-sortable
          class="sortable-cards"
          group="cardsGroup"
          [data]="board"
          (onDragStart)="onTaskDragStart($event)"
          (onReorder)="onTaskDrop($event)"
          (onAdd)="onTaskDrop($event)"
        >
          <ng-container *ngFor="let task of board.cards">
            <task-kanban-card class="dx-card" [task]="task"></task-kanban-card>
          </ng-container>
        </dx-sortable>

        <div class="add-task">
          <dx-button
            icon="plus"
            text="Add Task"
            stylingMode="text"
            (onClick)="notify('Add task event')"
          ></dx-button>
        </div>
      </dx-scroll-view>
    </div>
  </dx-sortable>
</dx-scroll-view>

<dx-load-panel
  [(visible)]="isLoading"
  [showPane]="false"
  container=".content"
  [position]="{ of: '.content' }"
></dx-load-panel>
