// packages/angular/src/app/components/library/create-account-form/create-account-form.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, Input, signal } from '@angular/core';
import { Router, RouterModule } from '@angular/router';

import { LoginOauthComponent } from 'src/app/components/library/login-oauth/login-oauth.component';
import { ValidationCallbackData } from 'devextreme-angular/common';
import { DxFormModule } from 'devextreme-angular/ui/form';
import { DxLoadIndicatorModule } from 'devextreme-angular/ui/load-indicator';
import notify from 'devextreme/ui/notify';
import { AuthService, defaultUser } from 'src/app/services';

type CreateAccountFormData = {
  email: string;
  password: string;
  confirmedPassword: string;
};

@Component({
  selector: 'app-create-account-form',
  templateUrl: './create-account-form.component.html',
  styleUrls: ['./create-account-form.component.scss'],
  imports: [
    CommonModule,
    RouterModule,
    LoginOauthComponent,
    DxFormModule,
    DxLoadIndicatorModule,
  ]
})
export class CreateAccountFormComponent {
  @Input() redirectLink = '/auth/sign-in';

  @Input() buttonLink = '/auth/sign-in';

  private authService = inject(AuthService);

  private router = inject(Router);

  loading = signal(false);

  formData = signal<CreateAccountFormData>({
    email: defaultUser.email ?? '',
    password: 'password',
    confirmedPassword: 'password',
  });

  async onSubmit(e: Event) {
    e.preventDefault();
    const { email, password } = this.formData();
    this.loading.set(true);

    const result = await this.authService.createAccount(email, password);
    this.loading.set(false);

    if (result.isOk) {
      this.router.navigate([this.buttonLink]);
    } else {
      notify(result.message, 'error', 2000);
    }
  }

  confirmPassword = (e: ValidationCallbackData) => e.value === this.formData().password;
}

<form class="create-account-form auth-form" (submit)="onSubmit($event)">
  <dx-form
    labelLocation="top"
    [formData]="formData()"
    [showColonAfterLabel]="true"
    [disabled]="loading()"
  >
    <dxi-item
      dataField="email"
      editorType="dxTextBox"
      [editorOptions]="{
        placeholder: 'Email',
        stylingMode: 'filled',
        mode: 'email'
      }"
    >
      <dxi-validation-rule
        type="required"
        message="Email is required"
      ></dxi-validation-rule>
      <dxi-validation-rule
        type="email"
        message="Email is invalid"
      ></dxi-validation-rule>
      <dxo-label text="Email"></dxo-label>
    </dxi-item>

    <dxi-item
      dataField="password"
      editorType="dxTextBox"
      [editorOptions]="{
        stylingMode: 'filled',
        mode: 'password'
      }"
    >
      <dxi-validation-rule
        type="required"
        message="Password is required"
      ></dxi-validation-rule>
      <dxo-label text="Password"></dxo-label>
    </dxi-item>

    <dxi-item
      dataField="confirmedPassword"
      editorType="dxTextBox"
      [editorOptions]="{
        stylingMode: 'filled',
        mode: 'password'
      }"
    >
      <dxi-validation-rule
        type="required"
        message="Password is required"
      ></dxi-validation-rule>
      <dxi-validation-rule
        type="custom"
        message="Passwords do not match"
        [validationCallback]="confirmPassword"
      >
      </dxi-validation-rule>
      <dxo-label text="Confirm Password"></dxo-label>
    </dxi-item>

    <dxi-item>
      <div class="policy-info">
        By creating an account, you agree to the
        <a [routerLink]="redirectLink">Terms of Service</a> and
        <a [routerLink]="redirectLink">Privacy Policy</a>
      </div>
    </dxi-item>

    <dxi-item itemType="button">
      <dxo-button-options
        width="100%"
        type="default"
        [useSubmitBehavior]="true"
        [template]="'createAccountTemplate'"
      >
      </dxo-button-options>
    </dxi-item>

    <ng-container *dxTemplate="let item of 'createAccountTemplate'">
      <span class="dx-button-text">
        @if (loading()) {
          <dx-load-indicator
            width="24px"
            height="24px"
            [visible]="true"
          ></dx-load-indicator>
        } @else {
          Register
        }
      </span>
    </ng-container>
  </dx-form>
  <div class="login-link">
    Have an account? <a [routerLink]="redirectLink">Sign In</a>
  </div>
  <app-login-oauth></app-login-oauth>
</form>

// packages/react/src/components/library/create-account-form/CreateAccountForm.tsx
import React, { useState, useRef, useCallback } from 'react';

import { Link, useNavigate } from 'react-router-dom';

import { LoginOauth } from '../login-oauth/LoginOauth';

import Form, {
  Item,
  Label,
  ButtonItem,
  ButtonOptions,
  RequiredRule,
  CustomRule,
  EmailRule,
} from 'devextreme-react/form';
import LoadIndicator from 'devextreme-react/load-indicator';
import notify from 'devextreme/ui/notify';

import { createAccount } from '../../../api/auth';

import './CreateAccountForm.scss';

export const CreateAccountForm = ({
  redirectLink = '/sign-in',
  buttonLink,
}) => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const formData = useRef({ email: '', password: '' });

  const onSubmit = useCallback(
    async(e) => {
      e.preventDefault();
      const { email, password } = formData.current;
      setLoading(true);

      const result = await createAccount(email, password);
      setLoading(false);

      if (result.isOk) {
        navigate(buttonLink);
      } else {
        notify(result.message, 'error', 2000);
      }
    },
    [navigate]
  );

  const confirmPassword = useCallback(
    ({ value }) => value === formData.current.password,
    []
  );

  return (
    <form className='create-account-form' onSubmit={onSubmit}>
      <Form formData={formData.current} disabled={loading} labelLocation='top'>
        <Item
          dataField='email'
          editorType='dxTextBox'
          editorOptions={emailEditorOptions}
        >
          <RequiredRule message='Email is required' />
          <EmailRule message='Email is invalid' />
          <Label text='Email' />
        </Item>
        <Item
          dataField='password'
          editorType='dxTextBox'
          editorOptions={passwordEditorOptions}
        >
          <RequiredRule message='Password is required' />
          <Label text='Password' />
        </Item>
        <Item
          dataField='confirmedPassword'
          editorType='dxTextBox'
          editorOptions={confirmedPasswordEditorOptions}
        >
          <RequiredRule message='Password is required' />
          <CustomRule
            message='Passwords do not match'
            validationCallback={confirmPassword}
          />
          <Label text='Confirm Password' />
        </Item>
        <Item>
          <div className='policy-info'>
            By creating an account, you agree to the{' '}
            <Link to={redirectLink}>Terms of Service</Link> and{' '}
            <Link to={redirectLink}>Privacy Policy</Link>
          </div>
        </Item>
        <ButtonItem>
          <ButtonOptions width='100%' type='default' useSubmitBehavior>
            <span className='dx-button-text'>
              {loading ? (
                <LoadIndicator width='24px' height='24px' visible />
              ) : (
                'Register'
              )}
            </span>
          </ButtonOptions>
        </ButtonItem>
      </Form>

      <div className='login-link'>
        Have an account? <Link to={redirectLink}>Sign In</Link>
      </div>
      <LoginOauth />
    </form>
  );
};

const emailEditorOptions = {
  stylingMode: 'filled',
  mode: 'email',
  value: 'jheart@dx-email.com',
};
const passwordEditorOptions = {
  stylingMode: 'filled',
  mode: 'password',
  value: 'password',
};
const confirmedPasswordEditorOptions = {
  stylingMode: 'filled',
  mode: 'password',
  value: 'password',
};
