// packages/angular/src/app/shared/components/form-datebox/form-datebox.component.ts
import {
  Component, EventEmitter, Input, NgModule, Output, ViewChild,
} from '@angular/core';
import {
  DxCalendarModule,
  DxDropDownButtonModule,
  DxDropDownButtonComponent,
  DxDateBoxModule,
} from 'devextreme-angular';

import { ValueChangedEvent } from 'devextreme/ui/calendar';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'form-item-date',
  template: ` <dx-date-box [(value)]="value"
                           [readOnly]="!isEditing"
                           [label]="label"
                           [elementAttr]="{class: 'form-editor'}"
                           [inputAttr]="{class: 'form-editor-input'}"
                           stylingMode="filled"
                           placeholder="MM/dd/y"
                           displayFormat="MM/dd/y"
  ></dx-date-box>`,
})
export class FormDateboxComponent {
  @ViewChild(DxDropDownButtonComponent) dropDownButtonComponent: DxDropDownButtonComponent;

  @Input() isEditing = false;

  @Input() label = '';

  @Input() value!: string | Date | number;

  @Output() valueChange: EventEmitter<string | Date | number> = new EventEmitter();

  onValueChanged = (e: ValueChangedEvent) => {
    const { value } = e;

    this.value = value;
    this.valueChange.emit(this.value);

    this.dropDownButtonComponent.instance.close();
  };
}

@NgModule({
  imports: [
    DxCalendarModule,
    DxDropDownButtonModule,
    DxDateBoxModule,
    CommonModule,
  ],
  providers: [],
  exports: [FormDateboxComponent],
  declarations: [FormDateboxComponent],
})
export class FormItemDateModule { }

// packages/react/src/components/utils/form-datebox/FormDateBox.tsx
import DateBox from 'devextreme-react/date-box';

export const FormDateBox = ({
  value,
  readOnly,
  label,
  onValueChange,
}) => {
  return (
    <DateBox
      value={value}
      readOnly={readOnly}
      label={label}
      elementAttr={{ class: 'form-editor' }}
      inputAttr={{ class: 'form-editor-input' }}
      stylingMode='filled'
      valueChangeEvent='keyup input change'
      placeholder='MM/dd/y'
      displayFormat='MM/dd/y'
      onValueChange={onValueChange}
    />
  );
};
