// packages/react/src/components/side-panel/right-side-panel.tsx
import React, { } from 'react';
import classNames from 'classnames';
import Button from 'devextreme-react/button';
import { useScreenSize } from '../../utils/media-query';
import './right-side-panel.scss';

export const RightSidePanel = ({ isOpened, title, toggleOpen, children }) => {

  const { isLarge } = useScreenSize();
  return <>
    <div id='right-panel'>
      <div
        className={classNames({
          'right-sight-panel': true,
          'overlapping': !isLarge,
          'open': isOpened
        })}
      >
        <div className='side-panel-container'>
          <div className='side-panel-header'>
            {title &&
              <div className='side-panel-title'>
                <div className='side-panel-title-text'>
                  {{ title }}
                </div>
              </div>
            }
          </div>

          <div className='side-panel-content-wrapper'>
            {children}
          </div>
        </div>
      </div>
    </div>
    {!isOpened && isLarge && <Button
      className='open-button'
      icon={isOpened ? 'showpanel' : 'hidepanel'}
      onClick={toggleOpen} />
    }
  </>;
};

// packages/angular/src/app/components/library/right-side-panel/right-side-panel.component.ts
import {
  Component,
  NgModule,
  Output,
  Input,
  EventEmitter, HostBinding,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  DxButtonModule,
} from 'devextreme-angular';
import { ClickEvent as ButtonClickEvent } from 'devextreme/ui/button';
import {DataService, ScreenService} from 'src/app/services';

@Component({
  selector: 'right-side-panel',
  templateUrl: './right-side-panel.component.html',
  styleUrls: ['./right-side-panel.component.scss'],
  providers: [DataService],
})
export class RightSidePanelComponent {
  @Input() isOpened = false;

  @Input() title = '';

  @Output() openedChange = new EventEmitter<boolean>();

  @HostBinding('class.overlapping') get overlapping() { return !this.isLarge; };

  @HostBinding('class.open') get open() { return this.isOpened; };

  isLarge = this.screen.sizes['screen-large'];

  constructor(protected screen: ScreenService) {
    screen.screenChanged.subscribe(({isLarge, isXLarge}) => {
      this.isLarge = isLarge || isXLarge;
    });
  }


  toggleOpen = () => {
    this.isOpened = !this.isOpened;
    this.openedChange.emit(this.isOpened);
  };

  accordionTitleClick = (e: ButtonClickEvent) => {
    e.event.stopPropagation();
  };

}

@NgModule({
  imports: [
    DxButtonModule,
    CommonModule,
  ],
  declarations: [RightSidePanelComponent],
  exports: [RightSidePanelComponent],
})
export class RightSidePanelModule { }

<div class="right-side-panel">
  <div class="side-panel-container">
    <div class="side-panel-header">
      <div *ngIf="title" class="side-panel-title">
        <div class="side-panel-title-text">
          {{ title }}
        </div>
        </div>
      <dx-button class="open-button"
                 [icon]="(isOpened ? (isLarge ? 'showpanel': 'close'): 'hidepanel')"
                 (click)="toggleOpen()">
      </dx-button>
    </div>

    <div class="side-panel-content-wrapper">
      <ng-content></ng-content>
    </div>
  </div>
</div>
