// packages/vue/src/pages/crm-contact-list/components/contact-new-form.vue
<template>
  <dx-form
    class="plain-styled-form"
    label-mode="floating"
  >
    <dx-form-item item-type="group">
      <dx-col-count-by-screen
        :xs="1"
        :sm="1"
        :md="1"
        :lg="1"
      />
      <dx-form-item class="uploader">
        <div>
          <form-photo-uploader />
        </div>
      </dx-form-item>
    </dx-form-item>

    <dx-form-item item-type="group">
      <dx-col-count-by-screen
        :xs="1"
        :sm="1"
        :md="2"
        :lg="2"
      />
      <dx-form-item>
        <form-textbox
          label="First Name"
          v-model="contact.firstName"
          :is-editing="true"
        />
      </dx-form-item>
      <dx-form-item css-class="accent">
        <form-textbox
          label="Last Name"
          v-model="contact.lastName"
          :is-editing="true"
        />
      </dx-form-item>
      <dx-form-item css-class="accent">
        <form-textbox
          label="Company"
          v-model="contact.company"
          :is-editing="true"
          :validators="[]"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          label="Position"
          v-model="contact.position"
          :is-editing="true"
          :validators="[]"
        />
      </dx-form-item>
    </dx-form-item>

    <dx-form-item
      item-type="group"
      css-class="contact-fields-group"
    >
      <dx-col-count-by-screen
        :xs="1"
        :sm="1"
        :md="2"
        :lg="2"
      />

      <dx-form-item css-class="accent">
        <form-textbox
          label="Assigned to"
          v-model="contact.manager"
          :is-editing="true"
          :validators="[]"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model="contact.phone"
          :is-editing="true"
          icon="tel"
          mask="+1(000)000-0000"
          :validators="[]"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model="contact.email"
          :is-editing="true"
          icon="email"
        />
      </dx-form-item>
      <dx-form-item>
        <form-textbox
          v-model="contact.address"
          :is-editing="true"
          icon="home"
          :validators="[]"
        />
      </dx-form-item>
    </dx-form-item>
  </dx-form>
</template>

<script setup lang="ts">
import {
  DxForm,
  DxItem as DxFormItem,
  DxColCountByScreen,
} from 'devextreme-vue/form';
import { ref } from 'vue';
import { newContact } from '@/types/contact';
import FormTextbox from '@/components/form-textbox.vue';
import FormPhotoUploader from './form-photo-uploader.vue';

const props = defineProps<{
  validationGroup: string
}>();

const contact = ref(newContact);
</script>

// packages/react/src/pages/crm-contact-list/contact-new-form/contactNewForm.tsx

import React from 'react';

import Form, { Item as FormItem, ColCountByScreen } from 'devextreme-react/form';
import { newContact } from '../../../shared/types/crm-contact';
import { FormTextbox, FormPhotoUploader } from '../../../components';

export const ContactNewForm = () => {
  const validationGroup = 'contactNewValidationGroup';

  const updateField = (field: string) => (value) => {
    return { ...newContact, ...{ [field]: value } };
  };

  return (
    <Form
      labelMode='floating'
      className='plain-styled-form'
      validationGroup={validationGroup}
    >
      <FormItem itemType='group'>
        <ColCountByScreen xs={1} sm={1} md={1} lg={1}></ColCountByScreen>
        <FormItem>
          <FormPhotoUploader />
        </FormItem>
      </FormItem>

      <FormItem itemType='group'>
        <ColCountByScreen xs={1} sm={1} md={2} lg={2}></ColCountByScreen>
        <FormItem>
          <FormTextbox
            label='First Name'
            value={newContact.firstName}
            isEditing={false}
            onValueChange={updateField('firstName')}
            // validationGroup={validationGroup}
          ></FormTextbox>
        </FormItem>
        <FormItem>
          <FormTextbox
            label='Last Name'
            value={newContact.lastName}
            isEditing={false}
            onValueChange={updateField('lastName')}
            // validationGroup={validationGroup}
          ></FormTextbox>
        </FormItem>
      </FormItem>

      <FormItem itemType='group'>
        <ColCountByScreen xs={1} sm={1} md={2} lg={2}></ColCountByScreen>
        <FormItem>
          <FormTextbox
            label='Company'
            value={newContact.company}
            isEditing={false}
            onValueChange={updateField('company')}
            // validationGroup={validationGroup}
          ></FormTextbox>
        </FormItem>
        <FormItem>
          <FormTextbox
            label='Position'
            value={newContact.position}
            isEditing={false}
            onValueChange={updateField('position')}
            // validationGroup={validationGroup}
          ></FormTextbox>
        </FormItem>
      </FormItem>

      <FormItem itemType='group' cssClass='contact-fields-group'>
        <ColCountByScreen xs={1} sm={1} md={2} lg={2}></ColCountByScreen>
        <FormItem>
          <FormTextbox
            value={newContact.manager}
            label='Assigned to'
            isEditing={false}
            onValueChange={updateField('manager')}
            // validationGroup={validationGroup}
          ></FormTextbox>
        </FormItem>
        <FormItem>
          <FormTextbox
            value={newContact.phone}
            isEditing={false}
            onValueChange={updateField('phone')}
            icon='tel'
            mask='+1(000)000-0000'
            // validationGroup={validationGroup}
          ></FormTextbox>
        </FormItem>
        <FormItem>
          <FormTextbox
            value={newContact.email}
            onValueChange={updateField('email')}
            isEditing={false}
            icon='email'
            //  validationGroup={validationGroup}
          ></FormTextbox>
        </FormItem>
        <FormItem>
          <FormTextbox
            value={newContact.address}
            isEditing={false}
            onValueChange={updateField('address')}
            icon='home'
            // validationGroup={validationGroup}
          ></FormTextbox>
        </FormItem>
      </FormItem>
    </Form>
  );
};
