// packages/react/src/components/library/card-auth/CardAuth.tsx
import React from 'react';

import type { SingleCardProps } from '../../../types';

import './CardAuth.scss';

export const CardAuth = ({ title, description, children }: React.PropsWithChildren<SingleCardProps>) => {
  return (
    <div className='auth-card'>
      <div className='dx-card content'>
        <div className='header'>
          <div className='title'>{ title }</div>
          <div className='description'>{ description }</div>
        </div>
        {children}
      </div>
    </div>
  );
};

// packages/angular/src/app/components/card-auth/card-auth.component.ts
import { CommonModule } from '@angular/common';
import { Component, NgModule, Input } from '@angular/core';

@Component({
  selector: 'app-card-auth',
  templateUrl: './card-auth.component.html',
  styleUrls: ['./card-auth.component.scss'],
})
export class CardAuthComponent {
  @Input()
  title!: string;

  @Input()
  description!: string;
}

@NgModule({
  imports: [
    CommonModule,
  ],
  declarations: [CardAuthComponent],
  exports: [CardAuthComponent],
})
export class CardAuthModule { }

<div class="auth-card">
  <div class="dx-card content">
    <div class="header">
      <div class="title">{{ title }}</div>
      <div class="description">{{ description }}</div>
    </div>
    <ng-content></ng-content>
  </div>
</div>
