// packages/vue/src/components/utils/agenda-list-item.vue
<template>
  <div class="agenda-list-item">
    <div class="time">
      <div class="start">
        {{ startTime }}
      </div>
      <div class="duration">
        {{ duration }}
      </div>
    </div>
    <div class="description">
      <div class="description-title">
        {{ appointment.text }}
      </div>
      <div class="description-resource">
        {{ resources[(appointment.calendarId as any) || '']?.text }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Duration } from 'luxon';

const props = withDefaults(defineProps<{
  appointment: {startDate: Date, endDate?: Date, text?: string, calendarId?: string},
  resources: Record<string, any>,
}>(), {
  items: () => ({}),
  resources: () => ({}),
});

const startTime = computed(() => props.appointment.startDate.toLocaleTimeString(undefined, {
  hour: 'numeric',
  minute: 'numeric',
  hour12: false,
}));

const duration = computed(() => {
  const { startDate, endDate } = props.appointment;
  if (!endDate) return '';
  return Duration.fromMillis(endDate.getTime() - startDate.getTime())
    .rescale()
    .toFormat("h'h' m'm'");
});

</script>

<style scoped lang="scss">
@use "@/variables.scss" as *;

.agenda-list-item {
  display: flex;
  flex-direction: row;
  align-items: flex-start;
  gap: 32px;

  .time {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    width: 36px;

    @include subtext();

    .duration {
      @include subtext(0.7);
    }
  }

  .description {
    overflow: hidden;

    .description-title {
      @include h2-header-text();

      overflow: hidden;
      text-overflow: ellipsis;
    }

    .description-resource {
      @include description-text(0.7);
    }
  }
}
</style>

// packages/react/src/components/agenda/agenda-list-item.tsx
import './agenda-list-item.scss';
import React from 'react';
import { Duration } from 'luxon';

const getFormatedDuration = ({ startDate, endDate }) => {
  return Duration.fromMillis(endDate - startDate)
    .rescale()
    .toFormat("h'h' m'm'");
};

const TimeContent = ({ appointment }) => {
  const start = appointment.startDate.toLocaleTimeString(undefined, {
    hour: 'numeric',
    minute: 'numeric',
    hour12: false
  });
  return <div className='time'>
    <div className='start'>{start}</div>
    <div className='duration'>{getFormatedDuration(appointment)}</div>
  </div>;
};

export const AgendaListItem = ({ item, resources }) => {
  return <div className='agenda-list-item'>
    <div className='time'>
      <TimeContent appointment={item} />
    </div>
    <div className='description'>
      <div className='description-title'>
        {item.text}
      </div>
      <div className='description-resource'>
        {resources[item.calendarId]?.text}
      </div>
    </div>
  </div>;
};
