// packages/angular/src/app/components/utils/sales-performance-card/sales-performance-card.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
} from '@angular/core';
import { CardAnalyticsComponent } from '../../library/card-analytics/card-analytics.component';
import { DxChartModule } from 'devextreme-angular/ui/chart';
import { DxDropDownButtonModule } from 'devextreme-angular/ui/drop-down-button';
import { Sale } from 'src/app/types/analytics';
import { ChartVisualRange } from 'src/app/types/chart-visual-range';
import { DxDropDownButtonTypes } from 'devextreme-angular/ui/drop-down-button';

@Component({
  selector: 'sales-performance-card',
  templateUrl: './sales-performance-card.component.html',
  styleUrls: ['./sales-performance-card.component.scss'],
  imports: [
    CardAnalyticsComponent,
    DxChartModule,
    DxDropDownButtonModule,
  ],
})
export class SalesPerformanceCardComponent {
  @Input() groupByPeriods!: string[];

  @Input() salesByDateAndCategory!: Sale[] | null;

  @Input() visualRange: ChartVisualRange = {};

  @Output() performancePeriodChanged = new EventEmitter<DxDropDownButtonTypes.SelectionChangedEvent>();

  customiseToolip({ seriesName }: { seriesName: string }) {
    return { text: seriesName };
  }

  onDropDownSelectionChange(event: DxDropDownButtonTypes.SelectionChangedEvent) {
    this.performancePeriodChanged.emit(event);
  }
}

<card-analytics titleText="Sales Performance">
  <div filter class="sales-filter">
    <dx-drop-down-button
      stylingMode="text"
      [useSelectMode]="true"
      [items]="groupByPeriods"
      [selectedItemKey]="groupByPeriods[1]"
      (onSelectionChanged)="onDropDownSelectionChange($event)"
    >
    </dx-drop-down-button>
  </div>

  <dx-chart [dataSource]="salesByDateAndCategory">
    <dxo-chart-argument-axis [visualRange]="visualRange"> </dxo-chart-argument-axis>
    <dxo-chart-tooltip
      [enabled]="true"
      [customizeTooltip]="customiseToolip"
    ></dxo-chart-tooltip>
    <dxo-chart-series-template nameField="category"> </dxo-chart-series-template>

    <dxo-chart-common-series-settings
      argumentField="date"
      valueField="total"
      hoverMode="includePoints"
    >
      <dxo-chart-point hoverMode="allArgumentPoints"></dxo-chart-point>
    </dxo-chart-common-series-settings>

    <dxo-chart-argument-axis argumentType="datetime" [valueMarginsEnabled]="false">
    </dxo-chart-argument-axis>

    <dxo-chart-legend [visible]="false"></dxo-chart-legend>

    <dxo-chart-size [height]="270"></dxo-chart-size>
  </dx-chart>
</card-analytics>

// packages/react/src/components/sales-performance-card/SalesPerformanceCard.tsx
import React from 'react';
import Chart, { ArgumentAxis, CommonSeriesSettings, Legend, Point, SeriesTemplate, Size, Tooltip } from 'devextreme-react/chart';
import DropDownButton from 'devextreme-react/drop-down-button';
import { SelectionChangedEvent } from 'devextreme/ui/drop_down_button';

import { CardAnalytics } from '../card-analytics/CardAnalytics';
import { Sale } from '../../types/analytics';

export const SalesPerformanceCard = ({ datasource, periods, selectedPeriod, onPeriodChanged, range }: {
  datasource: Sale[], periods: string[], selectedPeriod: string, onPeriodChanged: (e: SelectionChangedEvent) => void,
  range: Date[]
}) => (
  <CardAnalytics
    title='Sales Performance'
    contentClass='sales'
    additionalHeaderContent={
      <div className='sales-filter'>
        <DropDownButton stylingMode='text' useSelectMode items={periods} selectedItemKey={selectedPeriod} onSelectionChanged={onPeriodChanged} />
      </div>
    }
  >
    <Chart id='chart' dataSource={datasource}>
      <ArgumentAxis visualRange={range} argumentType='datetime' valueMarginsEnabled={false} />
      <Tooltip enabled customizeTooltip={({ seriesName }) => ({ text: seriesName })} />
      <SeriesTemplate nameField='category' />
      <CommonSeriesSettings argumentField='date' valueField='total' hoverMode='includePoints'>
        <Point hoverMode='allArgumentPoints' />
      </CommonSeriesSettings>
      <Legend visible={false} />
      <Size height={270} />
    </Chart>
  </CardAnalytics>
);
