// packages/react/src/components/utils/revenue-card/RevenueCard.tsx
import React from 'react';
import Chart, { ArgumentAxis, Border, CommonSeriesSettings, Format, Label, Legend, Series, Size, ValueAxis } from 'devextreme-react/chart';
import { ChartsColor, registerGradient } from 'devextreme/common/charts';
import { CardAnalytics } from '../../library/card-analytics/CardAnalytics';
import { Sale } from '../../../types/analytics';

const seriesColor: ChartsColor = {
  base: '#115EA3',
  fillId: registerGradient('linear', {
    rotationAngle: 90,
    colors: [{
      offset: '20%',
      color: '#1F74BD',
    }, {
      offset: '90%',
      color: '#93BCE1',
    }],
  }),
};

export const RevenueCard = ({ datasource }: { datasource: Sale[] }) => (
  <CardAnalytics title='Revenue' contentClass='sales'>
    <Chart dataSource={datasource}>
      <Series valueField='total' />
      <CommonSeriesSettings argumentField='date' type='splinearea' color={seriesColor}>
        <Border visible />
      </CommonSeriesSettings>
      <ArgumentAxis argumentType='datetime' />
      <ValueAxis>
        <Label>
          <Format type='currency' currency='USD' />
        </Label>
      </ValueAxis>
      <Legend visible={false} />
      <Size height={270} />
    </Chart>
  </CardAnalytics>
);

// packages/angular/src/app/components/utils/revenue-card/revenue-card.component.ts
import { Component, Input } from '@angular/core';
import { CardAnalyticsComponent } from '../../library/card-analytics/card-analytics.component';
import { DxChartModule } from 'devextreme-angular/ui/chart';
import { Sales } from 'src/app/types/analytics';
import { ChartsColor, registerGradient } from 'devextreme/common/charts';

@Component({
  selector: 'revenue-card',
  templateUrl: './revenue-card.component.html',
  imports: [
    CardAnalyticsComponent,
    DxChartModule,
  ],
})
export class RevenueCardComponent {
  @Input() data: Sales;

  seriesColor: ChartsColor = {
    base: '#115EA3',
    fillId: registerGradient('linear', {
      rotationAngle: 90,
      colors: [{
        offset: '20%',
        color: '#1F74BD',
      }, {
        offset: '90%',
        color: '#93BCE1',
      }],
    }),
  };
}


<card-analytics titleText="Revenue" contentClass="sales">
  <dx-chart [dataSource]="data">
    <dxi-chart-series valueField="total"></dxi-chart-series>
    <dxo-chart-common-series-settings
      argumentField="date"
      type="splinearea"
      [color]="seriesColor"
    >
      <dxo-chart-border [visible]="true"></dxo-chart-border>
    </dxo-chart-common-series-settings>
    <dxo-chart-argument-axis argumentType="datetime"></dxo-chart-argument-axis>
    <dxi-chart-value-axis>
      <dxo-chart-label>
        <dxo-chart-format type="currency" currency="USD"></dxo-chart-format>
      </dxo-chart-label>
    </dxi-chart-value-axis>
    <dxo-chart-legend [visible]="false"> </dxo-chart-legend>
    <dxo-chart-size [height]="270"></dxo-chart-size>
  </dx-chart>
</card-analytics>
