// packages/angular/src/app/components/utils/conversion-card/conversion-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CardAnalyticsComponent } from 'src/app/components/library/card-analytics/card-analytics.component';
import { DxFunnelModule } from 'devextreme-angular/ui/funnel';
import { SalesOrOpportunitiesByCategory } from 'src/app/types/analytics';

@Component({
  selector: 'conversion-card',
  templateUrl: 'conversion-card.component.html',
  imports: [
    CommonModule,
    CardAnalyticsComponent,
    DxFunnelModule,
  ],
})
export class ConversionCardComponent {
  @Input() data!: SalesOrOpportunitiesByCategory | null;

  customizeOppText(arg: { valueText: string }) {
    return `$${arg.valueText}`;
  }
}


<card-analytics
  titleText="Conversion Funnel (All Products)"
  contentClass="opportunities"
>
  <dx-funnel [dataSource]="data" argumentField="name" valueField="value">
    <dxo-funnel-label
      [visible]="true"
      position="inside"
      backgroundColor="none"
      [customizeText]="customizeOppText"
    >
      <dxo-funnel-format type="largeNumber" [precision]="1"> </dxo-funnel-format>
    </dxo-funnel-label>

    <dxo-funnel-legend [visible]="true">
      <dxo-funnel-margin [top]="70"></dxo-funnel-margin>
    </dxo-funnel-legend>

    <dxo-funnel-size [height]="270"></dxo-funnel-size>
  </dx-funnel>
</card-analytics>

// packages/react/src/components/utils/conversion-card/ConversionCard.tsx
import React from 'react';
import Funnel, {
  Format,
  Label,
  Legend,
  Margin,
  Size,
} from 'devextreme-react/funnel';
import { CardAnalytics } from '../../library/card-analytics/CardAnalytics';
import { SaleOrOpportunityByCategory } from '../../../types/analytics';

export const ConversionCard = ({
  datasource,
}: {
  datasource: SaleOrOpportunityByCategory[];
}) => (
  <CardAnalytics
    title='Conversion Funnel (All Products)'
    contentClass='conversion-funnel'
  >
    <Funnel dataSource={datasource} argumentField='name' valueField='value'>
      <Label
        visible
        position='inside'
        backgroundColor='none'
        customizeText={({ valueText }) => `$${valueText}`}
      >
        <Format type='largeNumber' precision={1} />
      </Label>
      <Legend visible>
        <Margin top={70} />
      </Legend>
      <Size height={270} />
    </Funnel>
  </CardAnalytics>
);
