// packages/vue/src/pages/reset-password-form.vue
<template>
  <CardAuth
    title="Reset Password"
    :description="desc"
  >
    <ResetPasswordForm
      signInLink="/sign-in-form"
      buttonLink="/reset-password-form"
    ></ResetPasswordForm>
  </CardAuth>
</template>

<script setup lang="ts">
import CardAuth from '@/components/card-auth.vue';
import ResetPasswordForm from '@/components/reset-password-form.vue';

const desc = 'Please enter the email address that you used to register, and we will send you a link to reset your password via Email.';
</script>

<style scoped lang="scss">
@use "@/variables" as *;

</style>

// packages/angular/src/app/pages/reset-password-form/reset-password-form.component.ts
import { Component } from '@angular/core';

import { CardAuthComponent, ResetPasswordFormComponent } from 'src/app/components';

@Component({
  selector: 'app-reset-password-form',
  templateUrl: './reset-password-form.component.html',
  styleUrls: ['./reset-password-form.component.scss'],
  imports: [
    CardAuthComponent,
    ResetPasswordFormComponent,
  ],
})
export class AppResetPasswordComponent {

  defaultLink = '/sign-in-form';

  buttonLink = '/reset-password-form';
}


<app-card-auth
  title="Reset Password"
  description="Please enter the email address that you used to register, and we will send you a link to reset your password via Email."
>
  <reset-password-form
    [signInLink]="defaultLink"
    [buttonLink]="buttonLink"
  ></reset-password-form>
</app-card-auth>
